npm/eslint-plugin-dev/lib/index.js

Merging `develop` into `7.0-release` at this commit is causing lint to crash:
https://github.com/cypress-io/cypress/pull/14690/commits/e657481ff28a45b055e4d0f0a6670564f23782ba
Lint: https://app.circleci.com/pipelines/github/cypress-io/cypress/18714/workflows/68faf81a-d57a-4944-acc8-97883dc334f8/jobs/677644
Relevant discussions:
* https://github.com/babel/babel-eslint/issues/530
* https://github.com/babel/babel-eslint/issues/799
Removing template string linting is a temporary fix, until we can devote time to migrate the deprecated `babel-eslint` to `@babel/eslint-parser` (#15745, needs work) or find another solution.

chore: ignore template string linting for now

---

cli/lib/exec/open.js
cli/lib/exec/run.js
cli/test/lib/cli_spec.js
npm/eslint-plugin-dev/lib/index.js
packages/server/lib/browsers/electron.js
packages/server/lib/browsers/index.js
packages/server/lib/cypress.js
packages/server/lib/modes/interactive-ct.js
packages/server/lib/modes/record.js
packages/server/lib/modes/run-ct.js
packages/server/lib/modes/run.js
packages/server/lib/open_project.js
packages/server/lib/util/args.js
yarn.lock

- Related to #15704
- Closes https://cypress-io.atlassian.net/browse/CT-403
By default the Component Test Runner will launch in Electron to improve UX and maintain consistency with the E2E Runner.
We did not support Electron in the Component Test Runner. This means that users would have needed to install Chrome on their CI machines, which isn't acceptable. Now, we support Electron, Chrome, and Firefox.
Additionally, we use Electron by default. This is a UX improvement so that there is only on system tray application.
Adding Electron support for Cypress CT revealed an issue with our logic when we destroy Electron BrowserWindows. We attempt to do so safely, but our safety checks don't prevent certain race conditions. I tried to refactor server/lib/browsers.js to make sure the instance …

feat: adding electron support for cypress component testing

---

appveyor.yml
packages/server/lib/browsers/electron.js
packages/server/lib/browsers/index.js
scripts/win-appveyor-build.js

- Closes #9164
- Fixed a segfault that occurred when exiting Cypress with Electron tests still running.
- destroying the BrowserWindows during process.exit seems to sporadically cause segfaults

fix: don't destroy browserwindow on process.exit

---

cli/types/cypress.d.ts
packages/driver/cypress/integration/commands/net_stubbing_spec.ts
packages/driver/cypress/integration/commands/task_spec.js
packages/driver/src/cypress/error_messages.js
packages/driver/src/cypress/error_utils.js
packages/server/__snapshots__/6_task_spec.js
packages/server/lib/task.js
packages/server/test/unit/task_spec.js

Just adding docsUrl to some existing errors.
Also updated error_messages to let docsUrl apply to an entire set of error messages, so you don't need to specify it on each error.

chore: add docsUrl to intercept, task errors

---

packages/server/lib/browsers/electron.js
packages/server/test/unit/browsers/electron_spec.js

N/A - Not yet released
https://github.com/cypress-io/cypress/pull/15686 causes the Electron browser window to always maximize on launch when headed. This is for the sake of video recording, but we don't want this behavior in interactive mode.
**Before**
**After**

fix: Restore previous electron window size in interactive mode

---

packages/server/lib/util/suppress_warnings.js
packages/server/test/e2e/0_max_listeners_spec.ts

- Closes 
- Fixed an issue introduced in 7.0.0 where certain Node.js warnings were incorrectly printed to `stderr` in production builds of Cypress.
fix for typo in #15723 

fix: only log process.emitWarning outside of production

---

packages/server/lib/environment.js

- Closes #15814
- Closes #350 - since ipc=host is no longer required
- Fixed an issue that could cause Cypress to crash when running in Docker unless running with `--ipc=host`.
- seems like Cypress crashes much more frequently in Electron with 7.0.0 and Electron 12
- root cause appears to be /dev/shm usage, since passing disable-dev-shm-usage fixes it
- we recently started passing this to Chrome by default, so it's ok to pass it to Electron renderer by default too
- see https://github.com/WPO-Foundation/wptagent/issues/327 …

fix: pass disable-dev-shm-usage flag to Electron

---

packages/server-ct/src/project-ct.ts
packages/server/lib/config.js

- Closes #15899 
Fixes the viewport 1000x660 being ignored for component testing. Fixes #15899

fix(component testing): default config values

---

packages/server/lib/browsers/electron.js
packages/server/lib/browsers/index.js

- Closes #15943
Fixed an issue where crashes in Cypress would cause a misleading "Unknown signal: true" error after the actual crash message.
- no users reported, but i have seen it a few times with random crashes

fix: don't pass invalid signal to subprocess.exit on crash

---

packages/driver/cypress/integration/commands/net_stubbing_spec.ts
packages/driver/cypress/plugins/server.js
packages/net-stubbing/lib/server/intercepted-request.ts
packages/net-stubbing/lib/server/middleware/request.ts
packages/net-stubbing/lib/server/middleware/response.ts

- Closes #15841
Fixed an issue introduced in 7.0.0 where requests with responses stubbed via `cy.intercept(routeMatcher, staticResponse)` would still be sent to the destination server.
Introduced in #15255 

fix: prevent stubbed cy.intercepts from reaching server

---

package.json
packages/driver/package.json
yarn.lock

- Closes 
Upgrade Typescript types for Lodash
I encountered a bug in the lodash types that required me to do type assertions, found a fix but when checking the Lodash types I recognized that it had already been fixed, so just upgrading the types here

chore: Upgrade lodash types

---

cli/types/cypress.d.ts

- Closes #15426 
the return type for Cookies.default() was incorrectly set to void.  It now match the implementation (returning the destination object)
This change allow to extends the existing default without using typescript tricks to get around the return type.

fix: return type of Cookies.default

---

npm/webpack-batteries-included-preprocessor/README.md
npm/webpack-batteries-included-preprocessor/index.js
npm/webpack-batteries-included-preprocessor/test/e2e/features.spec.js

- Closes #15767
N/A - this only affects the `@cypress/webpack-batteries-included-preprocessor` package
- Fixes an issue with `@cypress/webpack-batteries-included-preprocessor` where passing in webpackOptions (namely via the `defaultOptions`) and the typescript path would not added the needed typescript-related webpack options.
- Updates the README to note that passing in the `typescript` path is necessary to enable TypeScript support

fix(@cypress/webpack-batteries-included-preprocessor): Ensure typescript options are set if typescript path is provided

---

packages/driver/cypress/integration/cypress/log_spec.js
packages/driver/src/cy/snapshots.js
packages/driver/src/cypress/log.js

- Closes #15816
- Fixed an issue where hovering over a command log without a snapshot would cause the error `Cannot read property 'name' of null`
Snapshotting can fail for various reasons. In the issue this closes, it was because the snapshot happens before the page fully loads, but it can also fail if the page is cross-origin. We [catch such failures when creating the snapshot and return `null`](https://github.com/cypress-io/cypress/blob/e9457e2d09546cb6a5e78413367fcb32a5f056b3/packages/driver/src/cy/snapshots.js#L219-L221), but the log [adds that `null` value to the list of snapshots](https://github.com/cypress-io/cypress/blob/e9457e2d09546cb6a5e78413367fcb32a5f056b3/packages/driver/src/cypress/log.js#L331-L334). When the user hovers over the command and we try to display the snapshot, …

fix: Prevent null snapshots from being stored and causing errors

---

circle.yml

Follow up to #16115
The caching approach is broken in the mac workflow, so we'll just keep to the previous behavior until we find a workaround

chore: fix darwin ci workflow

---

cli/types/cypress.d.ts
cli/types/tests/cypress-tests.ts

`cy.then` will show correct type when collection of HTMLElement's is provided.
- Why was this change necessary? => When a collection of HTMLElement's is return from the previous cy.then, it is automatically wrapped with JQuery, but this behavior was not reflected in the function type.
- Any implementation details to explain? => Added new definition for the function.
Related issues / PRs:
https://github.com/cypress-io/cypress/issues/8440
https://github.com/cypress-io/cypress/issues/14875
https://github.com/cypress-io/cypress/pull/15624
N/A

fix: cy.then shows wrong type when collection of HTMLElement's is provided

---

packages/electron/package.json

Fixes #15853 
- Fixed an issue causing tests to run slowly after upgrading to 7.0.0, especially when run with constrained CPU resources.
- Downgradeded bundled Chrome version to 87.
Electron v12.0.0-beta.16 and above contain an unknown bug causing a major slowdown when video recording is enabled. For now maybe we can downgrade Electron to this last known good version, v12.0.0-beta.14

chore(deps): downgrade electron to v12.0.0-beta.14

---

packages/driver/cypress/fixtures/xhr-abort.html
packages/driver/cypress/integration/commands/net_stubbing_spec.ts

Looks like typicode's jsonplaceholder went down and broke this test. Luckily we host our own.

chore: fix failing "should handle aborted requests" test

---

packages/driver/cypress/integration/commands/net_stubbing_spec.ts
packages/driver/src/cy/net-stubbing/aliasing.ts

- Closes #15823
- Fixed an issue where reusing `cy.intercept` aliases did not work as expected.

fix: consider multiple routes when looking for aliases

---

packages/driver/cypress/integration/commands/net_stubbing_spec.ts
packages/driver/src/cy/net-stubbing/add-command.ts
packages/driver/src/cy/net-stubbing/events/before-request.ts
packages/driver/src/cy/net-stubbing/static-response-utils.ts
packages/net-stubbing/lib/external-types.ts

- Closes #16117
- Fixed an issue in 7.0 where users could get a misleading "must pass a handler as the 3rd argument" error when using `cy.intercept`.
- Improved types for `cy.intercept()`.

fix: properly detect `cy.intercept(url, routeMatcher, handler)` overload

---

packages/driver/cypress/integration/commands/actions/type_spec.js
packages/driver/src/cy/commands/actions/type.js
packages/driver/src/cy/keyboard.ts
packages/driver/src/dom/elements.ts

- Closes #15913
* `cy.type()` will not change the `value` attribute of button-like inputs(`button`, `submit`, `reset`, `image`, `radio`, `checkbox`).
- Why was this change necessary? => For those elements, `cy.type()` didn't reflect the browser behavior.
- Any implementation details to explain? => It does not update the input when it is button-like.
N/A
I tried to implement 'check on pressing space', but failed because simply changing cypress command doesn't work on Firefox.

fix: `cy.type()` should not change the value attr of button-like inputs.

---

packages/extension/gulpfile.ts
packages/extension/webpack.config.js

- Closes #15032
`Cypress.cookies.debug(true)` doesn't show cookie-related messages on the console window. 
- Why was this change necessary? => Fix regression.
* This happened because Chrome extensions cannot parse version name like "0.0.0-development". Cypress extension wasn't loaded and the `automation:push:request` message wasn't sent. 
* Chrome extensions doesn't allow "eval". I had to change the bundling policy of the webpack. 
N/A
As far as I know, there is no way to test correct message is shown on the console window. In the current project setup, we're testing the mocks. We suppose that the extension is loaded successfully. But this bug happened because the loading failed.

fix: Cypress.cookies.debug() regression

---

packages/driver/cypress/integration/commands/assertions_spec.js
packages/driver/src/cy/commands/asserting.js

- Closes #16006
Cypress now correctly shows all `.should('contain')` assertions when chained after `.should('be.visible')`.
- Why was this change necessary? => Cypress showed some messages like `should('contain')` twice and hid other assertions.
- Any implementation details to explain? => When `applyChainer` in `asserting.js` triggered `assert` in `chai_jquery.js` every time `memo[value]` is called. I limited it to be called once. 
```js
cy.get('#x')
.should('be.visible')
.should('contain', 'Something')
.should('contain', '+123')
```

fix: does not show more than one .should('contain') assertion when chained after .should('be.visible')

---

packages/driver/cypress/integration/commands/misc_spec.js
packages/driver/src/cy/commands/misc.js

- Closes #16068
`cy.log()` will show all the arguments, not the first 2.
- Why was this change necessary? => `cy.log` didn't behave as the document. 
- Any implementation details to explain? => Use `...` operator for the args.
**before:**
**after:**

fix: cy.log only shows the first 2 args.

---

circle.yml
packages/driver/cypress/integration/e2e/testConfigOverrides.spec.js

Per the team's discussion in retrospective, it's possible that the flake has been addressed since 2 years ago and these tests can be reenabled.
PR that originally disabled tests: https://github.com/cypress-io/cypress/pull/5326

chore: run driver, runner tests in electron

---

packages/driver/cypress/integration/commands/net_stubbing_spec.ts
packages/driver/cypress/plugins/server.js
packages/net-stubbing/lib/server/middleware/request.ts

- Closes #15898
- Closes #16223
- Cypress no longer crashes with an error when testing a binary file upload
We recursively merge request properties after running the request through middleware, but in the case of a binary request body, which is a buffer, lodash identifies it as an array and the merging turns it into an array of numbers. That causes the error when it hits `request`, because it loops through the array and tries to write numbers into the request, which are invalid. It needs to remain a buffer for `request` to properly write it.
This fixes it by not trying to recursively merge binary buffers but overwriting them entirely after middleware runs.
- N/A Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? …

fix: Ensure binary request body is not mutated by cy.intercept

---

packages/driver/cypress/integration/commands/net_stubbing_spec.ts
packages/driver/src/cy/net-stubbing/events/before-request.ts
packages/runner/cypress/fixtures/errors/intercept_spec.ts

- Partially addresses #9588
- Improved the way that requests stubbed with `cy.intercept()` are displayed in the command log.
Previously, all `cy.intercept()` requests would be prefixed with `(req)` in the command log.
Now, there are 3 possible display names:
* `(req)`, for spies (same as before)
* `(req stub)`, for staticresponse stubs (same as cy.route's `(xhr stub)`)
* `(req fn)`, for dynamic interception (since it's not always a stub) (no parallel with cy.route)
Additionally, the URL display has been improved. Now, the origin (`scheme://host:port`) will not be shown if it's a request to the current origin. For comparison, `cy.route` only ever displays the path, even on a different origin, which is kinda confusing. …

fix(ui): show req stub/fn when a handler is supplied

---

packages/reporter/cypress/fixtures/runnables_commands.json
packages/reporter/cypress/integration/commands_spec.ts
packages/reporter/src/commands/command.tsx
packages/reporter/src/commands/commands.scss

- Partially addresses #9588
- Improved the way that `cy.intercept()` and `cy.route()` requests with multiple aliases are displayed in the command log.
The aliases are now displayed in one line (ignore the lack of badge background, this is just a test):
But the list can still be expanded, in which case it's unjoined:

fix(ui): display duplicate aliases in command log

---

packages/driver/cypress/integration/commands/net_stubbing_spec.ts
packages/driver/src/cy/net-stubbing/add-command.ts
packages/net-stubbing/lib/external-types.ts
packages/net-stubbing/lib/internal-types.ts
packages/net-stubbing/lib/server/driver-events.ts
packages/net-stubbing/lib/server/intercepted-request.ts
packages/net-stubbing/lib/server/route-matching.ts
packages/net-stubbing/lib/server/types.ts
packages/net-stubbing/test/unit/intercepted-request-spec.ts

- Closes #8531
- Closes #4460
- Added a `times` option to `cy.intercept`'s `RouteMatcher`. `times` specifies the number of times that a particular `cy.intercept` should be applied.
New API:
```js
// this example will cause 1 request to `/temporary-error` to receive a network
// error. subsequent requests will not match this RouteMatcher.
cy.intercept('/temporary-error', { times: 1 }, { forceNetworkError: true })
```

feat(cy.intercept): add `times` option to `RouteMatcher`

---

packages/driver/cypress/integration/commands/net_stubbing_spec.ts
packages/net-stubbing/lib/server/util.ts

- Closes #15050
`cy.intercept()` adds `access-control-expose-headers` header for CORS requests. 
- Why was this change necessary? => This causes some unnecessary confusion for some use cases. 
- Any implementation details to explain? => When there is a custom header, we add `access-control-expose-headers` automatically to avoid confusion.
**Before:** If it's a CORS request, you need to remember to add `access-control-expose-headers` to get header information from `cy.intercept()`.
```js
cy
.intercept('/cors*', {
body: { success: true },
headers: {
'access-control-expose-headers': 'x-token', // This line is required
'x-token': 'token',
},
})
```
**After:** Cypress automatically handles it.
```js
cy
.intercept('/cors*', {
body: { success: true }, …
```

fix: cy.intercept adds access-control-expose-headers for cors requests

---

packages/driver/cypress/integration/commands/net_stubbing_spec.ts
packages/driver/src/cy/net-stubbing/add-command.ts
packages/net-stubbing/lib/external-types.ts

`cy.intercept` accepts a RegExp matcher for `url` now when route matcher options are passed to it as the second argument.
When upgrading to Cypress 7 I had to figure out how to add a delay to one of our requests. In Cypress 6 we were just adding such intercept before other intercepts but now they are matched in the reverse order.
So we had a code like this:
```js
cy.intercept(/localization/, () => delay(500))
cy.customVisitWithSetOfCommonInterceptsInIt('')
```
but since this request was done immediately on startup of our application we couldn't just reorder those commands - because `cy.visit` only resolves after the `load` event.
So I've figured out that `{ middleware: true }` can actually save me here and to my surprise this both didn't work and didn't typecheck correctly:
```diff …
```

feat(intercept): support regexp matcher with middleware intercepts

---

packages/driver/cypress/integration/commands/net_stubbing_spec.ts
packages/driver/src/cy/net-stubbing/wait-for-route.ts

- Closes #16451
- Fixed an issue where `cy.wait()` could yield the incorrect result when used with `cy.intercept()` and several simultaneous requests.
- `cy.wait('@intercept')` was originally supposed to "latch" - it must wait for the request, then wait for the response. 
- it may seem unnecessary now, but the design for this emerged for the requirement for `cy.wait('@alias.request/response')`, which was scrapped
- regardless, #14885 broke the latching by allowing a request already in the `Complete` state to set requestWaited and responseWaited in one fell swoop
- this meant that in a race condition, the request yielded might not match the one which was marked as `requestWaited: true` when the request phase was waited
- reverted the `requestWaited = true` change and all tests still pass …

fix(cy.intercept): always wait for request before waiting for response

---

packages/driver/cypress/integration/commands/net_stubbing_spec.ts
packages/driver/src/cy/net-stubbing/add-command.ts
packages/driver/src/cy/net-stubbing/route-matcher-log.ts
packages/reporter/src/routes/routes.tsx

- Closes #9403
- Improved the way that `cy.intercept` matchers are displayed in the command log when using RouteMatcher properties besides `url` and `method`.
Compared to #9403, now routes that use non-url properties are displayed in a better way
See unit tests for more examples of stringification:
https://github.com/cypress-io/cypress/blob/d85db41b8526ae2947c661a7edb07af43ec59582/packages/driver/cypress/integration/commands/net_stubbing_spec.ts#L3244-L3258 …

fix(ui): improve "Routes" display for cy.intercept

---

cli/lib/tasks/unzip.js
cli/package.json
cli/test/lib/tasks/unzip_spec.js
yarn.lock

- Closes #6896
Update extract-zip to 2.0.1 to fix dependency warning.
- Why was this change necessary? => Remove dependency warning.
- Any implementation details to explain? => Callback API is removed from [2.0.0](https://github.com/maxogden/extract-zip/releases/tag/v2.0.0). 
N/A
N/A

chore: update extract-zip to 2.0.1

---

packages/driver/cypress/integration/commands/request_spec.js
packages/driver/cypress/plugins/server.js
packages/driver/src/cy/commands/request.js
packages/server/lib/request.js
packages/server/package.json

- Closes #6178
`cy.request` can now send blob data.
- Why was this change necessary? => Blob data was ignored because it cannot be serialized with `JSON.stringify`. 
- Any implementation details to explain? => Blob is encoded into base64 in the client and decoded and encoded to Buffer in the server and send it.
N/A
`@cypress/request-promise` encodes `Buffer` into an object. Maybe this format might not be what users want.

fix: can send binary data with cy.request.

---

npm/cypress-schematic/src/schematics/cypress/index.ts

Refs #16514
- Angular schematic now adds `ng e2e` to scripts
New projects generated with Angular v12 do not have the `e2e` script.
This PR adds such a script (in addition to the existing `cy:run` and `cy:open`)
It is now possible to run `yarn e2e` out of the box.

feat: schematic adds ng e2e to scripts

---

cli/schema/cypress.schema.json
npm/react/plugins/babel/getBabelWebpackConfig.js
npm/react/plugins/babel/index.js

- Closes #16596
Allow wepback config in @cypress/react/plugins/babel to be configurable to support running within a monorepo.
If running Cypress within a monorepo, babel will not search upwards beyond the working directory to find the babel config, and will fail to transpile most code including JSX.
https://babeljs.io/docs/en/config-files#monorepos
Usage:
```js
// plugins/index.js
module.exports = (on, config) => {
if (config.testingType === 'component') {
require('@cypress/react/plugins/babel')(on, config, {
setWebpackConfig: (webpackConfig) => {
webpackConfig.resolve.alias = {
'@my-monorepo/my-package': '../../my-package/src',
}
webpackConfig.module.rules.find(({ loader }) => loader === 'babel-loader').options = {
rootMode: 'upward',
}
return webpackConfig
},
});
}
return config
};
```

feat: custom webpack config for react/plugins/babel

---

packages/driver/cypress/integration/commands/request_spec.js
packages/driver/cypress/plugins/server.js
packages/driver/package.json
packages/driver/src/cy/commands/request.js

- Closes #1647
As `socket.io` ignores `FormData` body, Cypress driver couldn't send `FormData` with file. This PR fixes this behavior.
- Why was this change necessary? => Sending files is a valid behavior, but `cy.request()` doesn't support it. 
- Any implementation details to explain? => This PR encodes FormData to base64 string to bypass `socker.io`.
N/A

fix: can send FormData with File.

---

.github/PULL_REQUEST_TEMPLATE.md

So it doesn't automatically link everything to issue 1234 in ZenHub.

chore: update PR template [skip ci]

---

circle.yml
packages/driver/cypress/integration/commands/net_stubbing_spec.ts
packages/driver/package.json
packages/driver/src/cy/net-stubbing/add-command.ts
packages/driver/src/cypress/error_messages.js
yarn.lock

- Closes 
- Improved `cy.intercept()` argument validation. Invalid `hostname`s and extra arguments passed to `cy.intercept()` now result in an error.
- classifying this as a bug fix. though it may cause failures in existing tests, i'd consider it a bug if anyone is using these patterns, since it is certainly causing unexpected behavior
New errors
When an invalid number of arguments has been passed: 
When an invalid hostname is passed: …

fix: add more validation to cy.intercept()

---

npm/angular/package.json
npm/cypress-schematic/package.json

Set Angular schemantics rxjs version as approximately equivalent to version 6.6
Currently version 6.6.2 would be installed but angular projects relate to the latest rxjs 6.x release
The latest rxjs version will be installed

fix(angular): set rxjs versions > 6.6.0 as dependency

---

packages/socket/patches/socket.io-parser+4.0.4.patch
packages/socket/test/socket_spec.js

- Closes #16476 
Fixes flaky `hasBinary` infinite recursive call.
- Why was this change necessary? => In some CI platforms and Windows, infinite recursive `hasBinary` call crashes runner.
- Any implementation details to explain? => It seems that in some platforms and some cases, `Error` objects are cyclic. I removed the cyclic references.
N/A

fix: hasBinary flakiness

---

cli/types/cypress-npm-api.d.ts
cli/types/cypress.d.ts
cli/types/tests/plugins-config.ts

- Closes #16725
[`testingType` definition](https://docs.cypress.io/api/cypress-api/testing-type#Syntax) doesn't exist in `Cypress` interface.
- Why was this change necessary? => The definition doesn't exist. 
N/A

fix(types): add testingType definition

---

packages/server/lib/util/settings.js
packages/server/test/unit/util/settings_spec.js

Co-authored-by: Guillaume Viguier <guillaume.viguier-just@propulse-lab.com>
- Closes #6136
Thanks, @guillaumevp!
`--config-file` option can handle absolute paths.
- Why was this change necessary? => `--config-file` options couldn't handle absolute paths. 
- What is affected by this change? =>  N/A
N/A

fix: --config-file can now handle absolute paths.

---

cli/types/cypress.d.ts
cli/types/tests/kitchen-sink.ts

- Closes #9109 
Thanks, @dimazuien!
- `cy.request()` now accepts a generic in TypeScript for specifying the type of the request body
Make the type of response body of `cy.request` generic.
- Why was this change necessary? => Generic helps users write type-safer code.
N/A

feat(types): can specify the ResponseBody type of `cy.request`

---

cli/types/cypress.d.ts
cli/types/tests/cypress-tests.ts

- Closes #16669
When `any` type value is returned from the last function, then argument was wrapped with `JQuery`. It is a bad default. This PR fixes this issue.
- Why was this change necessary? => `then` wraps `any` with `JQuery` by default and it's a bad default. 
- Any implementation details to explain? => `any` matches any types. So, I broke the catch-all definition with premitives and object types. 
N/A

fix(types): when user returns `any` type, `then` doesn't wrap it with `JQuery`.

---

cli/package.json

Remove @cypress/listr-verbose-renderer which was previously vendored in #16855
The dep was vendored in #16855
No user facing changes

chore: Remove @cypress/listr-verbose-renderer

---

packages/driver/cypress/integration/commands/net_stubbing_spec.ts
patches/istextorbinary+5.12.0.patch

- Closes #16292
The algorithm that `istextorbinary` uses doesn't care about the multibyte utf8 characters. This PR fixes this problem. 
- Why was this change necessary? => `istextorbinary` often fails to detect strings when there are multibyte utf8 characters like Cyrillic, CJK, emoji, etc.
- Any implementation details to explain? => I created a patch for the changes I made at https://github.com/bevry/istextorbinary/pull/214
**Before:** Returns `ArrayBuffer`.
**After:** Returns `string`.

fix: false negatives on multibyte utf8 characters.

---

npm/webpack-batteries-included-preprocessor/babel.config.json
npm/webpack-batteries-included-preprocessor/index.js
npm/webpack-batteries-included-preprocessor/test/fixtures/.babelrc

- Closes #8364
- Spec files now properly compile when there is a `.babelrc` or `babel.config.json` present in the project
This disables loading `.babelrc` and `babel.config.json` in the default preprocessor. Since the default preprocessor can't anticipate per-user config, it's best for it to use its own config alone. Users that need custom configuration can utilize the preprocessor plugin API.
Preprocessing no longer fails when a project has a `.babelrc` or `babel.config.json` present. Users no longer need to add an empty `.babelrc` to the `cypress` directory as a workaround.
- N/A Have API changes been updated in the [`type …

fix(webpack-batteries-included-preprocessor): Disable loading babel config files

---

packages/driver/cypress/integration/commands/net_stubbing_spec.ts
packages/driver/src/cy/net-stubbing/events/before-request.ts
packages/driver/src/cypress/error_messages.js
packages/net-stubbing/lib/external-types.ts

- Closes #16327
`cy.intercept` provides req.query.
- Why was this change necessary? => When there's query on url, it's convenient to have parsed query string. 
- Any implementation details to explain? => I added `query`, `url` getter and setter to `req` object.
**Before:** `req.query` => `undefined`.
**After:** `req.query` => `{ a: 'b' }`

feat: cy.intercept provides req.query.

---

packages/server/lib/saved_state.js

n/a 
- unreleased bug uncovered in https://github.com/cypress-io/cypress/pull/15826
- apparently, removing a saved state key that still exists for users will cause cypress to run it through normalizeAndAllowSet again, causing the warning: 
- followup for proper fix: https://github.com/cypress-io/cypress/issues/17087

chore: add showedOnBoardingModal back to allowed state keys

---

cli/types/cypress.d.ts
cli/types/tests/cypress-tests.ts

- close #17066 
The types for `.contains()` now correctly allow for `includeShadowDom` option.

fix(types): Add includeShadowDom as valid option for .contains()

---

packages/driver/cypress/integration/commands/actions/focus_spec.js
packages/driver/src/cy/focused.js

Closes https://github.com/cypress-io/cypress/issues/15294
Calls to `.focus()` with options are now passing the options down the line instead of dropping them.
As can be seen in the implementation of the focus interceptors: https://github.com/cypress-io/cypress/blob/b222dc08a415ff2a9d05345915b75fec71072512/packages/driver/src/cypress/cy.js#L307-L309
`FocusOptions` as defined in the [`HTMLElement.focus()` specs](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOrForeignElement/focus) are supported. Unfortunately, they are dropped right after in the `interceptFocus` method, preventing them to actually reach any native code.
Cypress was not correctly handling call to focus with options like `{ preventScroll: true }`

fix: Better handle `preventScroll` options when passed to  `element.focus()`

---

packages/driver/cypress/integration/commands/net_stubbing_spec.ts
packages/driver/cypress/integration/commands/traversals_spec.js

We tell Cypress we're in "open" mode for runner tests, so the retries config was incorrect. Fixes tests causing increased flake in CI lately.

chore: fix retry flaky tests in net_stubbing_spec

---

npm/cypress-schematic/src/schematics/ng-add/files/cypress/plugins/index.ts

Running `ng add @cypress/schematic --defaults --skip-confirmation` in a new Angular 12 application results in a broken setup for cypress,
as the plugin file does not have any export.
When running `ng e2e`, Cypress complains with:
```
The plugins file is missing or invalid.
Your `pluginsFile` is set to `/Users/ced-pro/Code/angular/angular-cli-diff/ponyracer/cypress/plugins/index.js`, but either the file is missing, it contains a syntax error, or threw an error when required. The `pluginsFile` must be a `.js`, `.ts`, or `.coffee` file.
Or you might have renamed the extension of your `pluginsFile`. If that's the case, restart the test runner.
Please fix this, or set `pluginsFile` to `false` if a plugins file is not necessary for your project.
```
This commit reverts the changes to the plugin …

fix: plugin file in angular schematics

---

npm/cypress-schematic/src/schematics/ng-add/files/cypress.json

The fix in #17141 was not enough as `cypress.json` references `plugins/index.js` whereas it generates `plugins/index.ts`

fix: plugin file referenced by cypress config in angular schematics

---

packages/driver/cypress/integration/commands/querying_spec.js
packages/driver/cypress/integration/issues/1119_spec.js
packages/driver/src/cy/commands/querying.js

- Closes https://github.com/cypress-io/cypress/issues/1119
`cy.contains(0)` now logs correctly
This change fixes the issue in which 0 was not logged in the cypress console when used in the contains command
This was caused by the use of `_.compact` which removes all falsy values from the "message" array:  https://github.com/cypress-io/cypress/blob/ba8bfd27f1ac218fa3e322425039da834ba7b787/packages/driver/src/cy/commands/querying.js#L523        
My solution was to convert the falsy number `0` to t he truthy string `"0"`, another solution I considered was replacing `_.compact` with `_.without` and only filter out falsy values except from `0`, but I thought that just converting the `0` to `"0"` was a cleaner solution, but if you disagree please let me know and I can go with the `_.without` one …

fix: convert 0 to string in contains command

---

circle.yml

Skips restoring the `node_modules` when restoring the binary for binary tests. This both improves CI time and helps avoid issues where the node resolution would incorrectly resolve a module from a parent `node_modules`.

chore: don't restore node_modules for binary tests

---

scripts/binary/util/packages.js

CI Builds are failing due to incorrect patch for package dependencies. We should be working off of the root `yarn.lock` when installing in each package, until we land the changes in #17132

fix: copy yarn.lock to packages for deterministic builds

---

circle.yml
electron-builder.json
packages/server/package.json
yarn.lock

- Adds missing fsevents binaries
- Adds `fsevents` to optionalDependencies to ensure hoisting within package

chore: fix mac build

---

packages/driver/cypress/fixtures/request.html
packages/driver/cypress/integration/commands/net_stubbing_spec.ts
packages/net-stubbing/lib/server/intercepted-request.ts

- Closes #16821
The `times` option of the `cy.intercept`  works correctly with `req.continue`.
- Why was this change necessary? => `times` option should work correctly with `req.continue()`
- Any implementation details to explain? => Because of [`break outerLoop` here](https://github.com/cypress-io/cypress/blob/85a4cf69919707e936bee9a9aee22a53627d38bf/packages/net-stubbing/lib/server/intercepted-request.ts#L183), the `times` check code below wasn't executed. 
N/A
`times` also doesn't work with `req.reply`. I tried to fix it but it breaks the current tests and it would enlarge this PR. So, I decided to open [an issue about it](https://github.com/cypress-io/cypress/issues/17139) and tackle it later.

fix: `times` of `cy.intercept` doesn't work correctly with `req.continue`

---

packages/driver/cypress/integration/commands/connectors_spec.js
packages/driver/cypress/integration/issues/3871_spec.js
packages/driver/src/cy/commands/connectors.js

- Closes https://github.com/cypress-io/cypress/issues/3871
`cy.invoke` improved/fixed to work on nested objects 
users can now use `cy.invoke` and obtain the result they expected even when providing nested paths

fix: update subject when traversing object (for `cy.invoke`)

---

npm/vite-dev-server/src/makeCypressPlugin.ts

When adding a new spec file in vite-dev-server to run, the server is suppose to re-run the tests when making a change to it. 
Previously, it was only done with files existing at startup. Now, the list of files updates.
- open cypress open ct in vitejs. In this repo, the simplest is to do the following.
```node
cd npm/vite-dev-server
yarn cy:open
```
- Open one of the spec files in Cypress, open the same file in vscode
- Change the file in vscode
- It will re-run the current spec (expected)
- Now add a new spec file (a file named `npm/vite-dev-server/cypress/components/test.spec.js`)
- The file appears in Cypress
- Click on it to open it
- Now add a test in this new file and save
- BUG: The file should be re-run and is simply left alone
- FIXED: The file now re-runs

fix(vite): autorefresh new spec files

---

npm/react/src/mountHook.ts

- Closes #17236
Cypress React mount hook have correct types . Fixes #17236.
Improved types (example on `use-counter.spec.js`
**Before**
**After**

fix: improve React `mountHook` type

---

packages/driver/cypress/integration/commands/net_stubbing_spec.ts
packages/driver/src/cy/net-stubbing/events/response.ts
packages/driver/src/cy/net-stubbing/static-response-utils.ts
packages/net-stubbing/lib/server/util.ts
packages/net-stubbing/lib/util.ts

- Closes #17084
`res.send` of `cy.intercept` doesn't override json-related content types. 
- Why was this change necessary? => There are a lot of [json-related MIME types](https://www.iana.org/assignments/media-types/media-types.xhtml). But `res.send` only allows `application/json`. 
- Any implementation details to explain? => I checked to set `content-type` to `application/json` only when `content-type` doesn't have the text, `json`.
N/A

fix: `res.send` of `cy.intercept` doesn't override json-related content types. 

---

packages/server/test/e2e/5_stdout_spec.js
packages/server/test/support/fixtures/projects/e2e/cypress/integration/stdout_passing_spec.js

- Closes 
N/A
cypress.io is throwing an unhandled exception due to an error in the cookielaw sdk, breaking some of our e2e tests. visit with adblocker disabled to see. this PR suppresses the error.

chore(tests): update e2e tests to not visit live sites

---

packages/driver/cypress/integration/commands/net_stubbing_spec.ts
packages/net-stubbing/lib/server/driver-events.ts
packages/net-stubbing/lib/server/intercepted-request.ts
packages/net-stubbing/lib/server/middleware/response.ts
packages/net-stubbing/lib/server/util.ts

- Closes #15188
`delay` now works correctly with the `statusCode: 204`.
- Why was this change necessary? => `delay` didn't work correctly with `statusCode: 204`. 
- Any implementation details to explain? => It was happening because of `setTimeout` inside the [`getBodyStream`](https://github.com/cypress-io/cypress/blob/20de3e585fad675cb4abbd9a4764fa1c95e11a2a/packages/net-stubbing/lib/server/util.ts#L198-L226). It is called after the delay [when response is not an empty body but it isn't when it's not](https://github.com/cypress-io/cypress/blob/20de3e585fad675cb4abbd9a4764fa1c95e11a2a/packages/net-stubbing/lib/server/middleware/response.ts#L48-L54). I fixed this by changing `getBodyStream` as `async`.
N/A

fix: cy.intercept delay works correctly with 204 No Content

---

packages/network/test/unit/client_certificates_spec.ts

Skips flaky test:
```
1) lib/client-certificates loads cert files detects invalid PEM key passphrase:
AssertionError: expected [Function: act] to throw error including 'Cannot decrypt PEM key with supplied passphrase (check the passphrase file content and that it doesn\'t have unexpected whitespace at the end)' but got 'Failed to load client certificates for clientCertificates[0]: Cannot parse PEM key: Only 8, 16, 24, or 32 bits supported: 352.  For more debug details run Cypress with DEBUG=cypress:server:client-certificates*'
+ expected - actual
-Failed to load client certificates for clientCertificates[0]: Cannot parse PEM key: Only 8, 16, 24, or 32 bits supported: 352.  For more debug details run Cypress with DEBUG=cypress:server:client-certificates*
+Cannot decrypt PEM key with …
```

chore(tests): skip flaky "detects invalid PEM key passphrase" test

---

packages/server/lib/reporter.js
packages/server/test/unit/reporter_spec.js

- Closes #17378
- Cypress no longer throws the error "cannot read property split of undefined" in certain circumstances

fix: Handle cases where attempt error stack is undefined/falsy

---

packages/driver/cypress/integration/cypress/proxy-logging-spec.ts
packages/driver/src/cypress/proxy-logging.ts

- Closes 
n/a - pre-release fix for #16730 
Occasionally it's possible for a request to not have a pre-request sent by the browser, in which case we wait 500ms before continuing the request. If the request is cy.intercepted, before this PR, it would fail. This could cause flake because requests can miss pre-requests for legitimate reasons. This PR creates a dummy log in such an event instead of erroring. This fixes the failures here: https://app.circleci.com/pipelines/github/cypress-io/cypress-test-example-repos/8257/workflows/84ef6df2-c864-4c27-9d52-8729f9b6981d/jobs/195214/parallel-runs/12?filterBy=FAILED
- [na] Have API changes been updated in the …

fix: create dummy request logs for intercepts w/o pre-requests

---

packages/driver/cypress/integration/commands/net_stubbing_spec.ts
packages/net-stubbing/lib/server/intercepted-request.ts

- Closes #17139
`times` option of `cy.intercept` works with `req.reply`
- Why was this change necessary? => `times` option of `cy.intercept` doesn't work with `req.reply`. It's not an expected behavior.
- Any implementation details to explain? => I've left a long comment about the implementation decision in the code.
N/A

fix: `times` option of `cy.intercept` doesn't work with `req.reply`

---

packages/driver/cypress/integration/commands/waiting_spec.js

Fixing type for `callback` merged in - https://github.com/cypress-io/cypress/pull/17561/files

chore(tests): typo for callback

---

packages/https-proxy/lib/ca.js
packages/https-proxy/lib/server.js
packages/https-proxy/test/integration/proxy_spec.js

- Closes #8705 
- Fixed an issue that could cause intermittent OpenSSL errors when the local CA cert cache becomes corrupted.
- the first error from `addContext` is caught, and causes the existing certs for that hostname to be deleted, before trying one more time to generate certs.
- was not able to come up with an e2e test for this, only a unit test that i believe captures the issue
- [na] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/s …

fix(https-proxy): add error handling when using cached cert

---

npm/vite-dev-server/src/makeCypressPlugin.ts

In vite-dev-server 2.0.7, when updating (saving) a component, the linked spec file was not re-running.
This error happened because vite-dev-server prevented circular references the wrong way. 
It added files to `analyzedDependencies` before they were analyzed.
With this PR the dependencies are added to the list after they are analyzed.

fix: repair re-run of vite-dev-server issues

---

packages/server/lib/modes/interactive-e2e.js
packages/server/test/unit/modes/interactive_spec.js

- Closes #17766
- Cypress no longer causes a SIGSEGV error on Mac when closing the test runner
Using `process.exit()` doesn't allow time for other handlers and cleanup to run, causing the SIGSEGV error. [`app.quit()`](https://www.electronjs.org/docs/api/app#appquit) "guarantees that all beforeunload and unload event handlers are correctly executed."

fix: Use app.quit instead of process.exit to prevent crash on close

---

cli/types/cypress.d.ts

- Closes https://github.com/cypress-io/cypress/issues/17695
Fixes the missing `Timeoutable` typings on `cy.document()`
Fixes the

fix: Add Timeoutable to cy.document function typing

---

npm/vite-dev-server/package.json

- Closes #17648
Publish the root types of vite-dev-server since they were forgotten prior to this PR

fix: publish the types for vite-dev-server

---

packages/driver/cypress/integration/commands/assertions_spec.js
packages/driver/src/cy/chai.js

- Closes #17357
Do not allow image markdown in assertions and command log
- Why was this change necessary? => Image markdowns are interpreted in command log and it makes it hard for us to understand the assertion message.
- Any implementation details to explain? => By escaping markdowns.
Before:
After:

fix: do not allow image markdown in assertions and command log

---

cli/types/cypress.d.ts

Add Timeoutable option to `title` method
- Closes #17780

fix(types): Update title method options type

---

packages/driver/cypress/integration/commands/actions/type_spec.js
packages/driver/src/cy/keyboard.ts
packages/driver/src/cypress/cy.js

- Closes https://github.com/cypress-io/cypress/issues/17583
[.type()](https://docs.cypress.io/api/commands/type) now fires the `beforeInput` event during typing in Firefox. _Note: Chromium support was added in [5.5.0](https://docs.cypress.io/guides/references/changelog#5-5-0)_ Addresses #17583.
Support for the `beforeinput` event was previously added for Chromium but at that time Firefox did not support it. However, Firefox added support for `beforeinput` in version 87. This PR updates the related browser checks to include both Chromium and Firefox. The `beforeInput event` tests in type_spec.js now pass for both Chrome and Firefox.
Users can now test the `type()` command on inputs that rely on the `beforeinput` event in Firefox.
- [N/A] Have API changes been updated in the [`type …

feat: add firefox `beforeinput` event support

---

packages/driver/cypress/integration/cypress/cypress_spec.js
packages/server-ct/src/routes-ct.ts
packages/server/lib/routes.ts
packages/server/lib/server-base.ts

- Closes #17664
`Cypress.testingType` should be one of `'e2e'` or `'component'`. But it was `undefined` in `e2e` tests.
- Why was this change necessary? => `Cypress.testingType` wasn't working as defined.
- Any implementation details to explain? => `testingType` value wasn't passed from the server to the client.
N/A

fix: `Cypress.testingType` should not be `undefined`.

---

cli/types/cypress.d.ts
cli/types/tests/cypress-tests.ts
packages/driver/cypress/integration/commands/location_spec.js
packages/driver/src/cy/commands/location.js

- Closes #17399
`cy.url()` will decode URL when `decode` option is given.
- Why was this change necessary? => Encoded non-ascii url components are hard to read. This helps users read and test URL eaiser.
I was thinking what is the best solution for this problem. 
First option was to just leave the [existing workaround](https://github.com/cypress-io/cypress/issues/17399#issuecomment-899263020) at [cy.url doc](https://docs.cypress.io/api/commands/url#Examples). But I felt the solution is less Cypress-ish. 
So I decided to add an option. 
**Before:**
```js
it('t', () => {
cy.visit('https://mozilla.org/?x=шеллы')
cy.url().then((url) => {
expect(decodeURI(url)).to.contain('шеллы')
})
})
```
**After:**
```js
it('t', () => { …
```

feat: add `decode` option to `cy.url`

---

packages/resolve-dist/README.md
packages/static/README.md
packages/ts/README.md
packages/web-config/README.md

In an effort to help onboard new developers, every package should have a readme explaining:
- The purpose of the package
- If applicable, how to install, develop, build, watch, test, etc in the package

docs: Add readmes to packages that are missing Readmes

---

packages/reporter/cypress/support/index.ts

- Closes #17897 
N/A - Only affects internal tests
Tooltips are covered by the cypress tests themselves and are inconsistent in their rendering, so we're better off excluding them from percy snapshots. This is what we do in the desktop-gui as well.
N/A

chore: Don't include tooltips in reporter percy snapshots

---

packages/driver/cypress/integration/e2e/multidomain_spec.ts
packages/driver/src/cy/listeners.ts
packages/driver/src/cy/multidomain/index.ts
packages/driver/src/cypress/cy.ts
packages/driver/src/multidomain/index.js

- Closes #17945 
N/A - WIP multidomain work
The bridge iframe created for a given domain is re-used for multiple tests. Needed to do proper teardown between tests, removing event listeners, etc, and then re-setup them up when the new test starts.

chore: Fix running multiple multidomain tests

---

packages/socket/patches/socket.io-parser+4.0.4.patch
packages/socket/test/socket_spec.js

- Related with [#16641 comments](https://github.com/cypress-io/cypress/pull/16641#discussion_r699651415)
N/A
- Why was this change necessary? => The patched `hasBinary` should work like the original
[The original `hasBinary`](https://github.com/socketio/socket.io-parser/blob/75530b4dcdced9138d51a0b7b782c8f89cdf3899/lib/is-binary.ts#L33-L66) detects binary data inside `toJSON()` functions. 
But the patched version doesn't do that because we don't have the `toJSON` argument. The `obj.toJSON &&  typeof obj.toJSON === "function" && arguments.length === 1` in the code is always false because `arguments.length` is *always* `true`.
This PR solves this problem.
I guess there are none of them. Even if binary objects are In `toJSON()`, it will be converted to `string` eventually when encoding them. …

chore: make `hasBinary` of `socket.io-parser` work more like the original

---

packages/server/lib/open_project.ts

- Closes #18129 
- Fixed an issue where Cypress could crash with a `TypeError: openProject(...) is not a function` error when connecting to Cypress Cloud.
- tryToCall was accidentally double-wrapped in a27793ddda4f07ee4a967f3b5580d4045f6bdf02
- let's unwrap it a little
- [no] Have tests been added/updated?

fix(open_project): remove unnecessary fn wrapping from tryToCalls

---

packages/server/lib/errors.js
packages/server/lib/open_project.ts
packages/server/test/unit/open_project_spec.js

- Closes #18094 
- Added a deprecation notice for Windows 32-bit users that support will be removed in a future release.
warning for users on 32-bit windows:
warning for users on 64-bit windows:
same warning in runmode:

fix: add deprecation notice for win 32-bit

---

packages/driver/cypress/integration/e2e/multidomain_rerun_spec.ts
packages/driver/src/cy/multidomain/index.ts
packages/runner-shared/src/event-manager.js
packages/runner/src/iframe/iframes.jsx

- Closes #18043 
N/A - Multidomain WIP
Issue was caused by the secondary domain bridge iframe not existing and not being re-created on rerun.
Previously kept state in the driver for which domains were visited and had their bridge iframes already loaded (so they're not needlessly re-created between tests), but the iframes get cleared out between test runs, so it's better to let the runner, which controls the iframes, essentially keep that state instead.
- N/A Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypr …

chore: Fix rerunning multidomain tests

---

autobarrel.json
package.json
packages/data-context/README.md
packages/data-context/index.js
packages/data-context/package.json
packages/data-context/src/DataActions.ts
packages/data-context/src/DataContext.ts
packages/data-context/src/actions/ProjectActions.ts
packages/data-context/src/actions/index.ts
packages/data-context/src/index.ts
packages/data-context/src/sources/AppDataSource.ts
packages/data-context/src/sources/ProjectDataSource.ts
packages/data-context/src/sources/index.ts
packages/data-context/src/util/cached.ts
packages/data-context/src/util/index.ts
packages/data-context/test/.mocharc.js
packages/data-context/test/integration/data-context.spec.ts
packages/data-context/test/unit/data-context.spec.ts
packages/data-context/tsconfig.json
scripts/gulp/gulpfile.ts
scripts/gulp/tasks/gulpMakePackage.ts
scripts/gulp/utils/nexusTypegenUtil.ts

- Adds `yarn gulp makePackage` to help consistently scaffold a new package in the repo
- Just a starting point, feel free to adjust as we continue to work with it
- Adds `@packages/data-context`, with some bare-bones class structure

feat: add gulp makePackage, begin to scaffold data-context

---

packages/frontend-shared/src/graphql/urqlClient.ts
packages/graphql/schemas/schema.graphql
packages/graphql/src/entities/Wizard.ts
packages/graphql/src/entities/WizardNpmPackage.ts
packages/launchpad/cypress.json
packages/launchpad/package.json
packages/launchpad/src/Main.vue
packages/launchpad/src/components/select/SelectFramework.vue
packages/launchpad/src/setup/ConfigFile.vue
packages/launchpad/src/setup/EnvironmentSetup.vue
packages/launchpad/src/setup/InitializeConfig.vue
packages/launchpad/src/setup/InstallDependencies.vue
packages/launchpad/src/setup/ManualInstall.vue
packages/launchpad/src/setup/PackagesList.vue
packages/launchpad/src/setup/TestingType.vue
packages/launchpad/src/setup/TestingTypeCards.vue
packages/launchpad/src/setup/Wizard.vue
packages/launchpad/src/setup/WizardLayout.vue
yarn.lock

- Closes https://cypress-io.atlassian.net/browse/UNIFY-368
[This PR](https://github.com/cypress-io/cypress/pull/17875) made many changes, one of which was changing from the default [document cache](https://formidable.com/open-source/urql/docs/basics/document-caching/) to [graph cache](https://formidable.com/open-source/urql/docs/graphcache/).
This introduced some bugs relating to reactivity due to Graphcache's more aggressive caching policy.
I fixed the bugs by ensuring the mutations return the correct fields to update the cache. I also made some other small fixes:
- do not re-initializing the plugins if they were already initialized
- added urql devtools support
- do not create the config file is "create this manually" is selected
- use `<script setup>` 
Here's an example of a few of the …

fix(launchpad): fix bugs introduced by urql/graphcache

---

npm/create-cypress-tests/package.json
npm/create-cypress-tests/scripts/copy-templates.js
npm/design-system/package.json
npm/react/package.json
npm/vue/package.json
yarn.lock

After following the CONTRIBUTING.md guide, there are still errors running certain packages while developing in the Cypress repo on a Windows machine.
1. Follow the CONTRIBUTING.md guide
2. Run `yarn` and install deps from the root directory of the project.
When running `yarn` from the root once installed `node` and `python` there are errors.
There are scripts running `yarn <node_modules/.bin/command> ...args` commands, and they will fail on windows since they resolve to `<node_modules/.bin/command>` instead `<node_modules/.bin/command.cmd>`.
For example, on `npm/vue` we got this error:
```shell
@packages/electron: Packaging app for platform win32 x64 using electron v13.2.0
cypress: exec babel index.js -o build/index.js
@cypress/vue: /usr/bin/bash: …
```

chore: fix initial installation on windows

---

packages/desktop-gui/cypress/fixtures/config.json
packages/desktop-gui/cypress/integration/settings_spec.js
packages/desktop-gui/cypress/integration/setup_project_spec.js
packages/desktop-gui/src/dashboard-projects/dashboard-projects-api.js
packages/desktop-gui/src/runs/project-not-setup.jsx
packages/desktop-gui/src/runs/setup-project.jsx
packages/server/lib/gui/events.js
packages/server/lib/project_static.ts
packages/server/test/unit/gui/events_spec.js
packages/server/test/unit/project_spec.js

- Closes #5747
When using a custom config file and setting up its connection to the dashboard, Cypress now writes the `projectId` in the custom config file instead of `cypress.json`.
Create a project with a `custom.json` file as the configuration
```
yarn install
yarn start --project=/path/to/the/project --config-file=custom.json
```
Then open the runs tab
Finally, connect the current project with the Cypress cloud

fix: set projectId in a custom config file

---

packages/data-context/src/actions/AppActions.ts
packages/data-context/src/actions/WizardActions.ts

- Chooses first browser in the list if we haven't chosen one yet
- Only 1 of CT / E2E can be setup at once, this is necessary because openProject tears down the previously opened project

fix: assign default chosen browser & plugin initialization

---

packages/driver/cypress/integration/e2e/uncaught_errors_spec.js
packages/driver/src/cypress/command_queue.ts

Don't reassign the error name if it already exists
Throwing custom errors from the tests, those defined like this:
```js
MyCustomError extends Error {
get name() { return 'MyCustomError' }
}
```
leads to failing Cypress with the error `TypeError: Cannot set property name of [object Object] which has only a getter`
Affected Cypress versions >= 8.3.0

fix: don't reassign the error name if it already exists

---

packages/driver/cypress/integration/commands/net_stubbing_spec.ts
packages/driver/cypress/integration/commands/xhr_spec.js
packages/driver/cypress/integration/cypress/proxy-logging-spec.ts
packages/driver/src/cypress/log.ts
packages/driver/src/cypress/proxy-logging.ts

- Closes #17656 
- Fixed a regression introduced in 8.2.0 where certain XMLHttpRequests would not display their response bodies in the DevTools Console when clicked, even though they did before.
- This approach is used elsewhere (ex. commands/querying.js) to propagate consoleProps updates to the console.

fix(proxy-logging): use constant consoleProps object

---

packages/driver/src/cypress/error_messages.ts

- Closes #18271
- Updated `cy.request()` error messages when conflicting `failOnStatusCode` and `retryOnStatusCodeFailure` options are passed.
Besides being slightly erroneous, I think that this error was confusing because it tried to clearly outline all of the possible permutations of the conflicting options. Case in point, it took a long time for someone to even read far enough to notice that the error had a typo.
I wrote a more concise error message that points to the exact issue.
- There is a test for this error, but the error text is not snapshotted so there is no need to update.	
- [na] Have API changes been …

fix(driver): improve status_code_flags_invalid error message

---

circle.yml

Fixes semantic [release tests failure](https://app.circleci.com/pipelines/github/cypress-io/cypress/23827/workflows/cefa80d2-1e6e-4ff2-89c9-305c7696a347) blocking `npm-release` step, by splitting into new job w/ correct context.

chore: fix semantic-release dry run

---

npm/vite-dev-server/src/startServer.ts

This PR fix and closes #18261 
- preserve `optimizedDeps.entries` configured on target project
- ~~transform windows absolute paths to relative~~
- transform windows paths to use `/` to match fast glob patterns
1. Follow the CONTRIBUTING.md guide
2. clone my branch, `yarn && yarn build --scope npm/vite-dev-server && cd npm/vite-dev-server && yarn link`.
3. clone the repo on #18261 , `yarn && yarn link "@cypress/vite-dev-server"`
4. edit `package.json` and change `"@cypress/vite-dev-server": "2.1.0"` with `"@cypress/vite-dev-server": "0.0.0-development"`
5.  run `yarn test:component:run`: the result should be the expected
6. if running `yarn test:component:run` from previous step again, delete `node_modules/.vite` directory before run it again
Once finished testing, unlink from …

fix(vite-dev-server): windows `supportFile` + preserve optimize entries

---

packages/driver/cypress/integration/commands/actions/select_spec.js
packages/driver/src/cy/commands/actions/select.ts

- Closes https://github.com/cypress-io/cypress/issues/4318
Users can use `cy.select([])` to clear any selected options in a multi-value select.
This follows the existing pattern that passing an array into `cy.select()` will unselect the other options. For example, `cy.select(['Foo', 'Bar', 'Baz')` then `cy.select(['Foo'])` will only select 'Foo' and unselect the other options.
Previously, an error would be thrown if an empty array was passed into `cy.select()`, but this change allows the existing pattern to be extended to include clearing all selected options with `cy.select([])`.

feat(driver): Unselect all selected options with cy.select([])

---

.husky/pre-commit
package.json
yarn.lock

chore: update husky dev dependency to v7

---

npm/cypress-schematic/package.json
npm/react/package.json
npm/vue/package.json

NA
[NPM announcement](https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/)
Our recent [semantic-release build](https://app.circleci.com/pipelines/github/cypress-io/cypress/25624/workflows/007c84af-acfc-465f-b65c-b415215ce259/jobs/967757) failed (though it still shows as green...). Some of our packages were pointing to an outdated registry (`http`). The default registry is `https` so removing it will point to the updated registry.
NA
NA

fix: remove outdated registry link

---

packages/data-context/src/DataContextShell.ts
packages/data-context/src/sources/HtmlDataSource.ts

Fix a bug where the specs of the previous project are shown due to caching.
How to reproduce:
1. Open a project using global mode
2. Go to __vite__ URL, specs tab
3. Go back to launchpad and choose another project
4. Go to __vite__ URL, spec tab
5. Specs from previous project are shown due to cached graphql client
Not sure if there's a better way (eg some way to bust the cache when we change to a project). If there is, please suggest it and I'll update the PR.

fix(app): do not cache graphql

---

circle.yml

Our percy finalize job waits for other jobs in circle to finish, like the desktop-gui tests. This  was timing out lately because the desktop-gui tests are now taking longer than 10 mins to finish (about 12) and CircleCI exits any job when it gets no signal after 10 mins. 
This PR parallelizes the desktop-gui tests at the number of machines recommended by our dashboard (7). 
This should make our tests run faster and the percy-finalize job should no longer exit from no signal.

chore: Increase paralleled machines for desktop-gui tests

---

packages/data-context/package.json
packages/frontend-shared/package.json
scripts/binary/build.js
yarn.lock

Creates & fixes a failing scenario for https://github.com/cypress-io/cypress/pull/18714#pullrequestreview-794193286

fix: issue w create-cypress-tests in binary build

---

npm/react/plugins/next/checkSWC.ts
npm/react/plugins/next/findNextWebpackConfig.js

`cypress/react/plugins/next` will throw if using Next.js 12 SWC optimizations without having `"nodeVersion": system` in cypress config
With Next.js v12, javascript/typescript is compiled with [SWC](https://github.com/swc-project/swc) by default. When compiling with Cypress, the build will fail unless `"nodeVersion": "system"` is configured due to how Cypress' version of node can't sign the swc package.
This is a stop-gap until `"node-version": "system"` becomes the default. https://github.com/cypress-io/cypress/issues/18684
Users that are using Next.js v12 with SCW optimizations that have not added `"nodeVersion": "system"` to their cypress config will have their build fail with a message telling the user how to fix the issue.
I tested this by creating a fresh `create-next-app` and using …

fix(@cypress/react): throw if using Next.js swc-loader without nodeVersion=system

---

CONTRIBUTING.md

We squash commits to develop (unless maintaining history of converting files). This information wasn’t expressed anywhere in our Contributing guide, so I’ve added it.

docs: Add instructions to squash commits to develop in Contributing

---

packages/frontend-shared/src/graphql/urqlExchangeNamedRoute.ts
packages/frontend-shared/vite.config.ts

Guard against issue @JessicaSachs was having

chore: Force single resolution for core modules, infinite loop guard

---

cli/schema/cypress.schema.json

- Closes #18684
This is a follow-up PR to #18732 where I missed updating the cypress.schema.json file with the updated values. This PR should have the same change log as the previous PR.
Thanks for spotting this @emilyrohrbough !
This change will not impact user experience.

feat: Node version schema update

---

npm/cypress-schematic/src/schematics/utility/index.ts
npm/vue/.npmrc
npm/webpack-preprocessor/.npmrc
scripts/unit/npm-release-spec.js

NA
Continuation of #18710. Missed a few outdated links.
[CI Build](https://app.circleci.com/pipelines/github/cypress-io/cypress/25779/workflows/fa61dfc5-8408-4528-80eb-e0bd233b4da6/jobs/968565) showing the `426 Upgrade required`. 
NA

fix: remove outdated npm registry links

---

packages/data-context/src/sources/GraphQLDataSource.ts
packages/data-context/src/util/index.ts
packages/data-context/src/util/urqlCacheKeys.ts
packages/frontend-shared/src/graphql/urqlClient.ts

These are located in data-context, because we use them in the both the server-side and client-side urql, since we cache & hydrate the page on load
We want to to keep the key definitions in sync between the server & client so we only define them once

fix: share urql cache keys between client & server

---

patches/winston+2.4.4.patch

- Closes 
n/a - not user facing since we hide warnings: https://github.com/cypress-io/cypress/blob/ab4ae0d48a992289346339d8e538e14944b16615/packages/server/lib/util/suppress_warnings.js#L37-L41
Fixes this warning:
```
(node:846252) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `Cypress --trace-warnings ...` to show where the warning was created)
```
See https://github.com/winstonjs/winston/issues/1882 …

chore: patch `winston` to suppress `padLevels` warning

---

packages/driver/cypress/integration/commands/xhr_spec.js
packages/driver/src/cypress/server.ts

- Closes #18858
N/A - this bug is only in develop, not released yet

chore: Bind this correctly when setting response headers with cy.route()

---

packages/app/cypress/e2e/integration/navigation.spec.ts
packages/data-context/src/sources/HtmlDataSource.ts
packages/driver/cypress.config.ts
packages/server/lib/project_utils.ts
packages/server/lib/routes.ts

It's time to say hello to the future. If you run `yarn dev` with `LAUNCHPAD=1`, we serve the unified runner. No more `__vite__` route.
This also fixes a bug where we did not correctly serve the statically build `packages/app`. So now you can do `cd packages/driver && LAUNCHPAD=1 yarn cypress:open` and it will work as expected (open mode with unified app, but not using a dev server - this is how things will work in production).
- pull this
- yarn dev
- launch any project that are set up with cypress.config.ts. Good ones are `app`, `launchpad`, `driver`
- observe CT and E2E are working (no need to navigate to `__vite__`; no such route exists on the front-end)

feat(app): remove __vite__ route and default to unified runner

---

circle.yml

This PR enables the 10.0-release branch to release dmgs and build + test against the kitchen sink.

chore: adding 10.0-release to the circle.yml build script

---

packages/driver/cypress/integration/cy/snapshot_css_spec.js
packages/driver/cypress/integration/cy/timeouts_spec.js
packages/driver/src/cy/aliases.ts
packages/driver/src/cy/assertions.ts
packages/driver/src/cy/chai.ts
packages/driver/src/cy/commands/window.ts
packages/driver/src/cy/ensures.ts
packages/driver/src/cy/focused.ts
packages/driver/src/cy/jquery.ts
packages/driver/src/cy/keyboard.ts
packages/driver/src/cy/location.ts
packages/driver/src/cy/mouse.ts
packages/driver/src/cy/net-stubbing/add-command.ts
packages/driver/src/cy/net-stubbing/events/before-request.ts
packages/driver/src/cy/retries.ts
packages/driver/src/cy/snapshots.ts
packages/driver/src/cy/snapshots_css.ts
packages/driver/src/cy/stability.ts
packages/driver/src/cy/testConfigOverrides.ts
packages/driver/src/cy/timeouts.ts
packages/driver/src/cy/timers.ts
packages/driver/src/cy/video-recorder.ts
packages/driver/src/cy/xhrs.ts
packages/driver/src/cypress.ts
packages/driver/src/cypress/command_queue.ts
packages/driver/src/cypress/cy.ts
packages/driver/src/cypress/error_utils.ts
packages/driver/src/cypress/log.ts

- Related with #18172
N/A
- Why was this change necessary? => `$Cy` class is dummy and all the definitions were done inside the `create` function and `_.extend`. We're moving the parts into it. 
* At first, I wanted to move everything in this PR, but decided not to. Because it's still really big (+1675/-1667). I decided to break the PR to 3 steps.
1. Handle outside functions (this PR).
2. Handle queue and the functions inside `_.extend` (next PR)
3. Remove `// @ts-nocheck` in `cy.ts` and other outside functions.
* I moved `create` out of `export default` because it requires one more indentation. 
* There are many functions in `$Cy` that are defined outside `cy.ts` and merged into it by `_.extend`. I solved the problem by creating interfaces for …

chore: refactor `create` into class `$Cy`

---

packages/desktop-gui/cypress/integration/settings_spec.js

No user facing changes
This flaky test is caused by checking `expect(this.ipc.getUserEditor).to.be.called` before the [hook](https://github.com/cypress-io/cypress/blob/develop/packages/desktop-gui/src/settings/file-preference.jsx#L47-L57) has had a chance to be run. I corrected it by piggybacking on the implicit wait used in cy get to get the `.loading-editors` class. We simply check for `expect(this.ipc.getUserEditor).to.be.called` after we've checked the class.

fix: flaky settings_spec test

---

packages/frontend-shared/src/gql-components/topnav/TopNav.vue

When opening the launchpad I get warnings on the homepage
```log
[Vue warn]: onUnmounted is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement. 
at <Anonymous gql= Object show-browsers=false > 
at <Anonymous key=0 gql= Object show-browsers=false  ... > 
at <Anonymous> 
at <Anonymous> 
at <App>
```
One cannot define a new computed inside of a computed property.
Don't use composables directly inside a computed.

fix: onUnmounted warning in topnav

---

package.json
packages/driver/cypress/integration/cy/snapshot_spec.js
packages/driver/src/cy/snapshots.ts
packages/driver/src/cy/testConfigOverrides.ts
packages/network/lib/client-certificates.ts
packages/proxy/lib/http/response-middleware.ts
packages/rewriter/lib/js.ts
packages/rewriter/lib/threads/worker.ts
packages/runner-shared/src/header/index.tsx
packages/server/lib/util/file-opener.ts
packages/web-config/package.json
patches/react-vtree+3.0.0-beta.1.patch
yarn.lock

- Closes 
N/A
- Why was this change necessary? => Fix some new type changes.
* As of 4.4.4, the default type of the thrown error is `unknown` from `any`. It caused some errors. For more info => https://github.com/microsoft/TypeScript/pull/41013
* I had to update `@types/jsdom` and `@types/filesystem` to avoid type conflicts. 
* Added a patch to `react-vtree`. It seems that some missing types are added to TypeScript. 
N/A
N/A

chore: Update TypeScript to 4.4.4

---

npm/vite-dev-server/tsconfig.json

- Closes #18973 
- vite-dev-server now works with node v12

fix: compile npm packages for node 12

---

packages/driver/cypress/fixtures/meta-redirect-timeout.html
packages/driver/cypress/plugins/server.js

- Closes 
Change is not user facing.
This test is failing due to issue #19039. Previously failed XHR calls can be matched up with subsequent XHR calls inappropriately. Specifically the `/timeout?ms=100` call is matching up with a previously failed instance of this. This pr avoids this issue by specifying a new `/retry-timeout` route. Since the route is unique to this test it doesn't have the possibility of having a previously failed pre-request. This is not fixing the root issue, just providing flaky test relief.

fix: flaky redirect test

---

packages/driver/cypress/fixtures/shadow-dom-button.html
packages/driver/cypress/integration/commands/actions/click_spec.js
packages/driver/src/cy/ensures.ts

- Closes #18008
- Shadow DOM elements are no longer falsely reported as hidden by their host
- Why was this change necessary? => When clicking an element inside a custom element, it shows the error message that it is covered by its custom element container. 
* I added a condition to bypass error when the element is inside a shadow root and covered by it.
* It fixes the "covering" problem. But it doesn't solve "event messages are not sent" problem (#17531). I added a new fixture for later tests. 
**Before:**
**After:**
No Error.

fix: the shadow root container element is ignored when clicking an element in it.

---

.github/PULL_REQUEST_TEMPLATE.md

- Closes 
n/a
TIL we actually tell people to delete the checkboxes, lol, whoops.

chore(contributing): clarify PULL_REQUEST_TEMPLATE

---

circle.yml

- Related to #17722
This change removes `test-binary-against-documentation-firefox` and disabled the `test-binary-against-documentation-firefox`  jobs in the linux-workflow. These run on the main branches (develop & master & release-*)
During this past few releases, these jobs have been failing consistently. We have discussed & opted to remove for the time being.
n/a
n/a
- [ n/a] Have tests been added/updated?
- [n/a ] Has the original issue or this PR been tagged with a release in ZenHub? 
- [ n/a] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [n/a ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ n/a] Have new …

chore: remove flaky ci jobs for main builds

---

.vscode/cspell.json
.vscode/extensions.json
.vscode/settings.json

1. Volar - Vue Language Service. Typescript support.
2. Code Spell Checker - Fix typos.
3. WindiCSS Intellisense - Sort utility classes. Truncate long classes.
4. i18n Ally - Preview and edit string constants defined in json files.
5. Iconify - Intellisense for Font Awesome and other icon libraries. Preview and render the icons inline.
6. Gremlins - Catch stylized quotes. This has caused bugs in the past.
1. Vetur - Previously recommended Vue Language Service. Conflicts with Volar.
Also adds options and defaults for the various plugins. Many of these plugins are not yet required in develop, but it'll be easiest if people are using the same set of plugins if they're toggling between Develop and 10.0-release.

feat: adding recommended VSCode plugins to workspace

---

packages/frontend-shared/cypress/e2e/support/e2eSupport.ts
packages/server/lib/project-base.ts
packages/types/src/server.ts

Added the missing `i` to fix the miss-spelling of Initialize.
n/a 
n/a
- [n/a ] Have tests been added/updated?

chore: fix typo in the spelling of skipPluginInitializeForTesting option

---

packages/driver/cypress/integration/commands/clock_spec.js
packages/driver/src/cy/commands/clock.ts

Previously overwriting `.clock` command crashed because it did not preserve this context. Now the following works:
```js
Cypress.Commands.overwrite('clock', (originalCommand, ...args) => {
return originalCommand(...args)
})
cy.clock()
```
This MR is vastly inspired from #9589
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? [Link](https://github.com/cypress-io/cypress-documentation/pull/4244)

fix: set the context when overwriting .clock command

---

packages/server/lib/plugins/index.js
packages/server/test/unit/plugins/index_spec.js
yarn.lock

- Closes #18914
When using the default configuratation of `"nodeVersion": "system"` with an installed system node >=17, cypress will now work properly rather than throw an error incorrectly pointing to the user's plugin file.
Previously, users could work around this by setting `NODE_OPTIONS=--openssl-legacy-provider`. We now apply this workaround by default when detecting system node version 17.
This error no longer occurs when attempting to run spec files. It incorrectly points to the user's plugin file as the cause, while this was actually a bug with Cypress' bundled webpack.

fix: Add support for system node 17

---

packages/data-context/src/sources/GitDataSource.ts

- Closes 
if the current project do not have git initialized, prevent throwing errors when getting the branch

fix: prevent error if project do not have git

---

packages/driver/cypress/fixtures/shadow-dom-type.html
packages/driver/cypress/integration/commands/actions/type_spec.js
packages/driver/src/cy/keyboard.ts

- Closes #17531
Typing events now correctly propagate out of the shadow DOM.
- Why was this change necessary? => By default, text events don't propagate out of shadow root. This behavior sometimes causes some unexpected failures.
- Any implementation details to explain? => I followed the convention of `cy.click()` fixed at #3030. 
**Before:** Text events don't propagate out of shadow root boundary. 
**After:** They do. …

fix: text events propagate out of shadow root.

---

packages/reporter/src/hooks/hooks.scss
packages/reporter/src/lib/open-file-in-ide.tsx

The "Open in IDE" button should have a pointer cursor.
- Closes [#20c6mwc](https://app.clickup.com/t/20c6mwc)

fix(unify): cursor for Open in IDE button

---

packages/server/lib/project_utils.ts

Fix for preserving the currently selected spec when switching browsers. The backend redirects the browser when switching types and thus requires the exact route that the frontend uses for running a spec.

fix: preserve runnable spec on browser change

---

packages/https-proxy/lib/server.js
packages/https-proxy/test/integration/proxy_spec.js
packages/https-proxy/test/unit/server_spec.js

- Closes #9220 
The Cypress App will no longer crash when proxying an ill formed request. For example, if the application under test has a resource of "http: //localhost/asset.js" (notice the extraneous space) the Cypress App will no longer crash. Instead, a debug message will be logged and the asset will fail to load.
The goal here is to treat these ill-formed requests just like any other requests that are problematic (e.g. not found resources).  Thus, we don't attempt to stop the tests outright, but instead just fail the individual request.
Before:
Terminal:
After:
Terminal:
Browser Console:
Network: …

fix: Do not crash when a ill formed URL request is proxied

---

packages/app/src/runner/SpecRunner.vue
packages/app/src/runner/index.ts
packages/app/src/specs/InlineSpecList.vue
packages/app/src/specs/SpecsList.vue
packages/launchpad/cypress/e2e/integration/onboarding-flow.spec.ts

- Closes https://cypress-io.atlassian.net/browse/UNIFY-649 
In the unified runner, the AUT was not yet set up to scale down based on the space available so that the application or component being tested remains fully visible when the area is smaller than the Cypress viewport in use for the test.
This also removes a little bit of unused code from SpecRunner.vue and fixes a minor spacing issue.
https://user-images.githubusercontent.com/8340719/145082494-2ce40d6d-1eef-4f50-b579-ce07a34d41ba.mov
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? …

feat(unify): scale the AUT

---

packages/server/lib/browsers/chrome.ts
packages/server/lib/browsers/cri-client.ts
packages/server/test/unit/browsers/chrome_spec.js

- Closes  https://github.com/cypress-io/cypress/issues/18827
Fixed an issue where Chromium-family browsers would stay open after closing `cypress open`.
* If chrome is open, and electron is closed, the chrome process is not being killed
* This was broken before because process.on('exit') handlers have to be synchronous, and this was async

fix: close chrome when closing electron

---

packages/driver/cypress/integration/cy/skipping_async_spec.js
packages/driver/cypress/integration/cy/skipping_sync_spec.js
packages/driver/src/cypress/command_queue.ts
packages/driver/src/cypress/cy.ts

- Closes #17660 
- Closes #14867 
Skipped tests will no longer trigger the fail event or cause screenshots to be generated.
When a test is skipped, mocha triggers a ["sync skip; aborting execution" error](https://github.com/mochajs/mocha/blob/ac43029d6a86150a48ccd59e50e89ca10c72a9c0/lib/runnable.js#L143). In investigating #17660, it was determined that #14867 had the same root cause. The main difference is that #17660 deals with synchronous tests and #14867 deals with asynchronous tests. In both cases, the fix is to update the failure handling to check if the test is pending (mocha's indicator that the test was skipped) and not fail in that scenario.
#17660 Before:
#17660 After:
#14866 Before:
#14866 After: …

fix: Do not screenshot or trigger the failed event when tests are skipped

---

packages/server/lib/project-base.ts
packages/server/lib/util/settings.ts
packages/server/test/unit/util/settings_spec.js

The `_write` called within the `settings.read` is only needed if we're renaming config options that have been gone for years. Removing this as the config upgrade will have an entirely new flow.

refactor: remove unused legacy 'rewriteRules'

---

system-tests/lib/fixtures.ts
system-tests/package.json

N/A - affects internal tests only
Presumably since #18574, server unit tests fail on MacOS, because fixture projects are scaffolded using `os.tmpdir()`, [which is the symlinked temp directory and not the real one](https://github.com/nodejs/node/issues/11422). This causes a false positive in the [config logic](https://github.com/cypress-io/cypress/blob/32d59024fbffe9d30a93ee12599f7c8646725d2c/packages/server/lib/config.ts#L439), causing the support file not to be found and the following error to be thrown: 
This fix uses the `temp-dir` package instead of `os.tmpdir()` so that the correct temp directory is used and not the symlinked one.

chore: Fix server unit tests running on mac by using actual tmp dir

---

npm/vite-dev-server/src/startServer.ts
scripts/gulp/gulpConstants.ts

To work more easily with dashboard integration, we should be able to change the target of the remote server.
- This enables it using the `CYPRESS_INTERNAL_ENV=development` environment variable set
- This PR also fixes the conflict between vite-dev-server default port and the dashboards

build: allow work with local dashboard

---

.vscode/terminals.json
packages/app/src/runner/SpecRunnerContainer.vue
packages/app/src/runner/event-manager.ts
packages/app/src/runner/index.ts
packages/app/src/runner/injectBundle.ts
packages/app/src/runner/reporter.ts
packages/reporter/src/main.tsx
packages/runner-ct/package.json
packages/runner-ct/src/index.js
packages/runner-ct/src/main-lite.tsx
packages/runner-ct/webpack.config.ts
yarn.lock

Some small but important tweaks to the lifecycle of the runner:
- fixes potential race condition 
- ensure reporter and event manager are torn down correctly
- adds conditional to `runner-ct` bundle to make injected bundle slightly smaller
These will also be useful for when we implement "cypress in cypress", aka e2e testing open mode in open mode, which is what sparked this PR.
Testing: just make sure open mode still works as expected. I added some notes explaining what's going on, happy to do a sync if anyone wants more details on this.

fix(app): correctly teardown reporter and event manager

---

npm/vite-dev-server/src/makeCypressPlugin.ts
npm/vite-dev-server/src/startServer.ts

If the port was taken by say a docker engine that did not respond to `localhost` but only to `127.0.0.1` vite-dev-server would still use that port and fail.
Once this fix is in, we check this port properly.

fix: check the port is avail on all local hosts

---

packages/driver/cypress/integration/commands/net_stubbing_spec.ts
packages/driver/cypress/integration/cy/net-stubbing/static-response-utils-spec.ts
packages/driver/src/cy/net-stubbing/static-response-utils.ts
packages/net-stubbing/lib/external-types.ts
packages/net-stubbing/lib/internal-types.ts
packages/server/lib/fixture.js
packages/server/test/unit/fixture_spec.js

- Closes #19330
- Closes #19344
This issue was introduced in Cypress 9.0.0. by #18534 which made changes such that
- when null is passed as the encoding to `cy.readFile()` or `cy.fixture()`, the file is treated as binary and read as a Buffer.
- when null passed as the encoding to `cy.writeFile()` allows direct writing of buffers.
- If the encoding is unspecified, the default remains ‘utf8’, matching the current behavior.
Before this changes, when a fixture path was specified in cy.intercept() without an encoding value, the encoding would assume to be null and the file extension would be used to determine the encoding type and eventually fallback be read a a Buffer.
#18534 unintentionally introduced a non-passive change such that when a fixture path was specified in cy.intercept() without …

fix(cy.intercept): allow fixtures to define null encoding when used in static response

---

circle.yml
scripts/test-unique-npm-and-binary.js

Trigger downstream tests for windows binary. The `test-binary-and-npm-against-other-projects` step triggers a new commit to [cypress-test-example-repos](https://github.com/cypress-io/cypress-test-example-repos) to test the project against the Cypress binary once it's been uploaded to the cdn.
For more info see: https://github.com/cypress-io/cypress/blob/develop/guides/testing-other-projects.md. 
n/a
n/a
n/a
- [n/a] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/ty …

chore: trigger downstream project tests for windows workflow

---

yarn.lock

n/a
Addresses normalize-url vulnerabilities:
* https://snyk.io/vuln/npm:normalize-url@4.5.0
* https://snyk.io/vuln/npm:normalize-url@5.3.0
n/a

chore(deps): update dependency normalize-url to 4.5.1, 5.3.1 [security]

---

cli/types/cypress.d.ts

- Closes #19363 
n/a
I only added the public method that's documented, although there are other methods available.  
I'm not positive I did this right.  😬  And I didn't see any type tests to modify.  Is the return type of `Promise<void>` correct? 
Typescript types for `Cypress.session` should now be available.
- [na] Have new configuration options been …

chore: add types for Cypress.session.clearAllSavedSessions

---

cli/lib/tasks/verify.js
cli/test/lib/tasks/verify_spec.js

- Closes #19476 
- CYPRESS_VERIFY_TIMEOUT is now used as an integer rather than a string
This change allows the CYPRESS_VERIFY_TIMEOUT environment variable to work appropriately when set by the user. The test cases were also updated to be more strict in their assertions.

fix: Use CYPRESS_VERIFY_TIMEOUT as integer

---

packages/app/src/navigation/SwitchTestingTypeModal.vue
packages/data-context/src/actions/ProjectActions.ts
packages/graphql/src/schemaTypes/objectTypes/gql-Mutation.ts

- Closes [UNIFY-868](https://cypress-io.atlassian.net/browse/UNIFY-868)
Switching testing types works
With some recent changes, switching testing types broke. Previously, when choosing "Switching Testing Types", the Launchpad would take you to the "Choose Testing Type". Now, it takes you to the browser launch page, causing the testing type to not change. This is fixed by setting the testing type with a mutation on the frontend.
Another issue was that the open project was never being recreated, so even if you could switch it would still show you the wrong specs and nothing could execute. This is fixed by closing the active project whenever you choose to reconfigure.
A consequence of this fix is that the browser is closed immediately when reconfiguring, but this was a bug anyway so 2 birds …

fix: make switching testing types work

---

packages/server/lib/plugins/index.js
packages/server/test/unit/plugins/index_spec.js

- Closes #19320
* Improved the heuristic for detecting whether `--openssl-legacy-provider` is needed
Node 17+ can still be built against OpenSSL version 1 with `--shared-openssl` build parameter. In this case the option `--openssl-legacy-provider` does not work (and is not needed). We cannot assume that all versions of Node 17 are built with OpenSSL 3.
Native Node v17 as built by Arch Linux and Homebrew now works with Cypress again (after being broken in 9.1.1).
- [na] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.sche …

fix: Improve heuristic for --openssl-legacy-provider (#19320)

---

packages/server/README.md
packages/server/lib/modes/run.js
packages/server/test/unit/modes/run_spec.js
yarn.lock

- Closes #19485
Cypress remains open when the `--no-exit` option is used.
See https://github.com/cypress-io/cypress/issues/19485#issuecomment-1004263526
> This was introduced by #18896. By adding 'exit' to the default config we elevated the exit key from being in the root options object (options.exit) to being nested in the config object (options.config.exit), preventing us from reading it in run.js. A fix could would be reading from reading the 'exit' option from config.exit instead of options.exit in the above file.
Before:
After:
- [n/a] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/typ …

fix: retrieve 'exit' from config instead of options

---

packages/data-context/src/DataContext.ts
packages/data-context/src/data/ProjectConfigIpc.ts
packages/data-context/src/data/ProjectLifecycleManager.ts
packages/server/lib/modes/run.js
packages/server/lib/open_project.ts
system-tests/__snapshots__/plugins_spec.js
system-tests/projects/plugins-root-async-error/cypress.config.js
system-tests/test/plugins_spec.js

I also fixed some more here skipped ones here https://github.com/cypress-io/cypress/commit/424ae9ac2462c008138e49a5800f4d201c3c932f, not sure how I managed to push to 10.0-release (protected branch) but I accidentally did.
All the tests that were temporarily skipped before xmas are now green again.

chore: fix temporarily skipped specs on 10.0-release

---

cli/types/cypress.d.ts
packages/app/cypress.config.ts
packages/data-context/src/data/ProjectLifecycleManager.ts
packages/types/src/config.ts

closes [UNIFY-872](https://cypress-io.atlassian.net/browse/UNIFY-872)
In `cypress.config.ts` devServer are meant to be used as simply as this.
This for now fails to compile because of a type badly implemented. Probably the result of a bad merge.
```js
import { defineConfig } from 'cypress'
import { devServer } from '@cypress/vite-dev-server'
export default defineConfig({
component: {
devServer
}
})
```

fix: dev-server types

---

npm/react/plugins/next/checkSWC.ts

- Closes [UNIFY-877](https://cypress-io.atlassian.net/browse/UNIFY-877)
Remove "nodeVersion": "system" requirement for Next.js v12 applications now that "nodeVersion": "system" is the default for users using Cypress >= 9.0.0
Next.js uses SWC to compile js and wasn't working with our plugin due to "nodeVersion": "bundled" (which was the default prior to Cypress 9.0.0) causing Rust to not be able to run. Since "nodeVersion": "system", this PR changes how we check the nodeVersion so as to remove the requirement of having this property set for the application to compile if a user is using Cypress >= 9.0.0.
How it works:
- If using Next.js >= 12 and Cypress < 9: Users need to set "nodeVersion": "system"
- If using Next.js >= 12 and Cypress >= 9: Works with no change, errors if "nodeVersion": …

fix: check resolvedNodePath for Next.js 12 guard

---

cli/package.json
yarn.lock

Close #19624
By pinning a dependency to 1.4.0 see https://github.com/cli-table/cli-table3/pull/251/files https://github.com/Marak/colors.js/issues/285
Upgrade `cli-table3` to avoid problems with `colors.js` "bad" version
A non-working version of colors.js was uploaded and published by their owner. First-level dependencies are working through it.
No change.

fix: update cli-table dependency to fix broken colors.js

---

packages/proxy/lib/http/request-middleware.ts

Getting a bunch of `MaxListenersExceededWarning` in the network layer without this

fix: remove close handler when req stream ends

---

npm/vue/README.md

- Closes n/a
Updated the links in the readme to point to correct urls
n/a
n/a

fix: Vue README links in Global Components section

---

cli/scripts/clean.js
cli/scripts/post-install.js

Attempting to fix 
`Error: cp: cannot create directory 'types': No such file or directory`
https://app.circleci.com/pipelines/github/cypress-io/cypress/29561/workflows/a263d7d8-5dda-4992-8b10-342f6ae8fa8e/jobs/1138989

fix: flake in shelljs scripts during postinstall

---

packages/driver/cypress/integration/dom/coordinates_spec.ts
packages/driver/cypress/integration/e2e/multi_domain_spec.ts
packages/driver/src/dom/coordinates.ts
packages/driver/src/multi-domain/index.ts

- Closes #19689 
N/A - going into multi-domain feature branch
Fixes the following issues:
- Certain command errors wouldn't propagate correctly because the stubbed runnable was missing the `isPending` method
- Querying for nested elements resulted in a cross-origin when they were checked for visibility because we try to access `parent.frameElement`, which is cross-origin when the AUT is on a secondary domain
- N/A Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/c …

chore: Fix a couple multi-domain bugs

---

packages/driver/cypress/e2e/commands/commands.cy.js
packages/driver/cypress/integration/commands/actions/mount_spec.js
packages/driver/src/cy/commands/actions/index.ts
packages/driver/src/cy/commands/actions/mount.ts
packages/driver/src/cypress/commands.ts
packages/driver/src/cypress/error_messages.ts

Using `cy.mount()` will provide a detailed error message with a link for writing a custom mount command.
- Users may import the `mount` function from their appropriate library of choice or author their own custom command. The documentation will show (and perhaps encourage) the use of `cy.mount()`.
- Calling `cy.mount()` before it has been overridden will now provide an error message and behave like `cy.hover()`
- the cypress 'on' link has been created to bring users to the right place, we just need that content which is WIP.  
- …

feat: add cy.mount() runner error

---

circle.yml

Percy builds created in parallel test runs are grouped together using a PERCY_PARALLEL_NONCE environment variable.
Right now we use CIRCLE_WORKFLOW_ID as the nonce. This causes a problem during "rerun from failed" in Circle CI. "Rerun from failed" creates a new workflow ID for the failed jobs, meaning that our earlier Percy builds become disconnected and percy build:finalize only applies to the snapshots taken during the last run that took place - the rerun that caused any outstanding required jobs to pass.
This PR changes the nonce we provide from CIRCLE_WORKFLOW_ID to CIRCLE_SHA1, the commit sha for the commit being built in CI. Using the commit sha for the nonce allows us to rerun flaky tests, and have the finalized Percy build include everything from that commit.
Merging this to …

chore: use commit sha for percy nonce to unite reruns

---

cli/types/cypress.d.ts
packages/driver/cypress/integration/commands/actions/selectFile_spec.js
packages/driver/package.json
packages/driver/src/cy/commands/actions/selectFile.ts

- Closes #19751 
`.selectFile()` automatically infers the mime type of files based on their extension, and allows users to set it explicitly using the `mimeType` property on files.
In addition, users can specify the file contents with any `TypedArray` instance. Previously only instances of `Cypress.Buffer` were supported. 
Example:
```
cy.get('input[type=file]').selectFile({
contents: Uint8Array.from('567'),
mimeType: 'text/plain',
})
```

feat: Add mimeType support; Improve TypedArray support

---

packages/server/lib/util/args.js
packages/server/test/unit/util/args_spec.js

- Closes #19783 
Corrects glob pattern matching for CLI parameter spec when glob contains a range. Fixes #19783 
When we detect range brackets within the glob, but no commas, we do not need to do any further parsing and can use the value directly. However, this branch of logic was returning a string and not the expected array, and an exception is thrown as a result. 
This change corrects that and adds additional tests for coverage.
- [n/a] Have new configuration options been added to the …

fix: Correctly parse single --spec globs containing a range

---

packages/app/src/runner/ResizablePanels.vue
packages/app/src/runner/SpecRunnerRunMode.vue
packages/app/src/runner/useRunnerStyle.ts

- Closes https://cypress-io.atlassian.net/browse/UNIFY-962
The width of the runner's AUT area is now correct in Run Mode. No more white area on the right hand side.
To account for the left nav in open mode, there are a few places we apply a 64px offset in calculations. This PR checks for run mode and avoids doing that if we're not in run mode, since we don't render the nav there.
A longer term solution will be to drive this kind of thing with detecting and measuring the nav bar element itself, but we are about to get right into some related stuff as the AUT header comes together, so let's do that then.
- [na] Has a PR for …

fix: aut width in run mode

---

packages/app/src/pages/Specs/Runner.vue
packages/app/src/runner/unifiedRunner.ts

Two small fixes:
1. Wrapper div in Runner.vue so there is a HTML root element for the transition. Navigation to other pages from Spec Runner works normally now.
1. Testing navigating from a spec, to the rest of the app, and then to another spec, I saw an event manager error and the new spec would not load. On the 2nd visit to the Spec Runner, we were trying to get the eventManager before it was initialized. Resetting the value of the `initialized` ref when we unmount the runner component fixes that, because the container component uses `v-if="initialized"` to decide when to render the runner itself, so if it stays true, we render too early on subsequent visits.

fix: transition eventManager errors

---

packages/driver/cypress/integration/commands/actions/selectFile_spec.js
packages/driver/src/cy/commands/actions/selectFile.ts
packages/driver/src/cy/commands/aliasing.ts
packages/driver/src/cy/commands/files.ts
packages/driver/src/cy/commands/fixtures.ts

- Closes #19803 
`selectFile()` now retains the filename of files ready from disk when working with aliases.
```js
cy.fixture('example.json', { encoding: null }).as('exampleFile')
cy.get('input[type="file"]').selectFile('@exampleFile')
```
The input will have a filename of 'example.json', with the mimeType inferred from that. The filename and mimetype can still be specified manually.

feat: Retain fileName when working with aliased fixtures and files

---

npm/design-system/src/components/Nav/LeftNav.cy.tsx
npm/design-system/src/components/fileTree/FileTree.cy.tsx
npm/design-system/src/core/icon/Icon.cy.tsx

When building 10.0-release a few warnings appear about types in the design-system:
```
@cypress/design-system: $ rimraf dist && rollup -c rollup.config.js
@cypress/design-system: src/index.ts → ./dist...
@cypress/design-system: Info: === tsc-alias starting ===
@cypress/design-system: Info: 9 files were affected!
@cypress/design-system: (!) Plugin typescript: @rollup/plugin-typescript TS2531: Object is possibly 'null'.
@cypress/design-system: src/components/fileTree/FileTree.cy.tsx: (20:17)
@cypress/design-system: 20   const after = win.getComputedStyle($els[0], 'after')
@cypress/design-system:                    ~~~
@cypress/design-system: (!) Plugin typescript: @rollup/plugin-typescript TS2367: This condition will always return 'false' since the types 'NavClick' and 'number | undefined' …
```

chore: remove design system warnings

---

packages/driver/cypress/integration/e2e/multi-domain/commands/multi_domain_spies_stubs_clocks.spec.ts
packages/driver/src/multi-domain/index.ts
yarn.lock

- Closes #19846
n/a
The following error thrown when accessing `cy.clock()` or `cy.tick()`:
```
TypeError: Cannot set properties of undefined (setting 'clock')
at Object.clock (webpack:///../driver/src/cy/commands/clock.ts?:170:17)
```
The [`state('ctx')`](https://github.com/cypress-io/cypress/blob/1f70b21bc4427ff99d20d8b67d201d98d71021fe/packages/driver/src/cy/commands/clock.ts#L48) object was not set in the secondary domain which caused the error. In the primary domain the `state('ctx')` is set to the [`runnable.ctx`](https://github.com/cypress-io/cypress/blob/1f70b21bc4427ff99d20d8b67d201d98d71021fe/packages/driver/src/cypress/cy.ts#L845) when the runnable is set. Thus, in the secondary domain, I'm setting the `state('ctx')` to the `runnable.ctx` when the `state('runnable')` is set. …

chore(multi-domain): add clock support in multi-domain

---

packages/app/cypress.config.ts

- Closes 
- Currently `app` e2e tests must be run via the `cypress:*` commands in `packages/app`, or else you get a cryptic error `cy.task('__internal_withCtx') timed out after waiting 10000ms.`
- This PR guards against that with a better error:
- [na] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress …

chore(contributing): guard against footgun when using Cypress in Cypress

---

npm/vite-dev-server/README.md
npm/webpack-preprocessor/README.md

docs: update @cypress/webpack-preprocessor links 

---

packages/driver/cypress/fixtures/multi-domain.html
packages/driver/cypress/integration/e2e/multi-domain/multi_domain_uncaught_errors_spec.ts
packages/driver/src/cy/multi-domain/util.ts
packages/driver/src/multi-domain/cypress.ts

- Closes  #19709
N/A
Extends off of #19805 to implement `uncaught:exception`s or application error events in `switchToDomain`.
When uncaught exceptions or errors occur in the secondary domain (SD), we want to fail the current command and test in the primary domain (PD) as long as the `switchToDomain` callback context is still 'open'. If a user wishes to bypass `uncaught:exception`s in the SD, a `cy.on('uncaught:exception')` handler can be defined in the `switchToDomain` callback and `false` can be returned just as described in the [docs](https://docs.cypress.io/api/events/catalog-of-events#Uncaught-Exceptions). However,  `uncaught:exception` events outside the `switchToDomain` context will NOT be called with errors occurring in the SD.  This is mainly due to difficulties serializing …

feat: implement uncaught:exception and error in spec bridge

---

system-tests/lib/performance-reporter.js

Minor fix, currently missing `branch` / `commitSha` in the logged metrics

fix: correct reference branch / commitSha in performance-reporter

---

cli/types/cypress.d.ts
npm/react/plugins/babel/index.d.ts
npm/react/plugins/craco/index.d.ts
npm/react/plugins/load-webpack/index.d.ts
npm/react/plugins/next/index.d.ts
npm/react/plugins/react-scripts/index.d.ts

I noticed a few things while working on https://cypress-io.atlassian.net/browse/UDX-5.
Please LMK if these changes are going to cause any issues!
Changed in afea2166d8ce8ef456a6e505b38e23140b2a0128
- Removed `Promise` methods from code completion suggestions using a [TypeScript 2.8+ compatible `Awaited` polyfill](https://stackoverflow.com/a/49889856/142339) which I named `AwaitedLike` due to a naming conflict with the [TypeScript 4.5 bulit-in `Awaited` type](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-5.html#the-awaited-type-and-promise-improvements)
Before
After
Changed in 3a9100ad6b6d23853ab1f2351e85c04efaea4fba
- Replaced `legacyDevServer` with an appropriate name for each of the react-scripts plugins
- Also removed an unnecessary type definition
Before …

fix(unify): improve dev server config ergonomics

---

packages/driver/cypress/fixtures/type-enter.html
packages/driver/cypress/integration/commands/actions/type_spec.js
packages/driver/src/cy/commands/actions/type.ts
packages/driver/src/cy/keyboard.ts

- Closes #19541
Send click event with `cy.type('{enter}')` on some button-like elements(`<button>` element, `button`, `reset`, `image`, `submit` input elements)
- Why was this change necessary? => Cypress doesn't reflect the browser behavior.
- Any implementation details to explain? => Click event is programatically sent on Chrome only. Firefox automatically sends click events. 
**Before:** click event is not sent. 
**After:** click event is sent. 
- [na] Have API changes been updated in …

fix: send click event with `cy.type('{enter}')`.

---

packages/electron/package.json
yarn.lock

https://github.com/cypress-io/cypress/pull/19067 Made it easy to run cypress in dev mode (yarn start) on a m1 computer. Due to the upgrade of electron-packager, it appears all processes related to cypress including Cypress.app and node run on "Apple" rather than "Intel" according to the osx activity manager.  
The above change was introduced for the unreleased cypress 10.x , so this PR simply backports that change to cypress 9.x to allow the currently released version of cypress to run natively on M1 computers.

build: allow unified to run cypress on Apple Silicon (arm64) (backport #19067 to 9.x)

---

packages/server/lib/video_capture.ts

Speeds up video recording on low-resourced machines (such as most CI docker containers).
ffmpeg is now limited to a single thread on machines with 2 or fewer CPUs, reducing resource contention with the main cypress project. Also adjusted ffmpeg probes to reduce buffering, especially impactful on short videos.
No change. Video output remains unchanged in quality and filesize.
For Cypress' driver integration tests, this appears to save about 20 seconds for each container, from
to 
Exact time saved depends on branch, test, load, and the phase of the moon, but seems to be generally improved.
- [N/A] Have tests been added/updated? Existing tests cover video recording functionality.
- [N/A] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? …

fix: Adjust ffmpeg CLI args for performance

---

packages/driver/cypress/integration/e2e/multi-domain/multi_domain_uncaught_errors_spec.ts
packages/driver/src/cy/multi-domain/commands_manager.ts
packages/driver/src/multi-domain/cypress.ts
packages/driver/src/multi-domain/domain_fn.ts
packages/driver/src/multi-domain/errors.ts
packages/driver/src/multi-domain/spec_window_events.ts

- Closes #19858 
n/a
* Added window event listeners to spec bridge window on `error` and `unhandledrejection`
* Moved the error logic from the `onError` handler to it's own file to be shared with the spec bridge window handlers
* Updated the `onFail` handler to check if there is a current command and if not to just `reject`
Note, support for errors thrown after the `switchToDomain` call has ended are not currently supported. From other discussions, we are going to be looking into updating the commands and logs manager's to continue listening when the `switchToDomain` call ends. If this is done, then we shouldn't need to do anything additional for these errors.
**setTimeout error:**
**before:**
**after:**
**Promise rejection:**
**before:**
**after:**
- [n/a] Has the original issue (or this …

feat: (multi-domain) handle uncaught errors in the spec bridge

---

packages/driver/cypress/integration/commands/actions/selectFile_spec.js
packages/driver/src/cy/commands/actions/selectFile.ts

- Closes 
- Fixed an issue where files attached during `cy.selectFile` could have the wrong `File` prototype.
- fixes use cases where users are checking `instanceof File` to switch on behavior

fix(selectFile): use target window's File/DataTransfer classes

---

packages/data-context/README.md

- Closes https://cypress-io.atlassian.net/browse/UNIFY-1016
N/A
Explain interplay between `data`, `actions` and `sources` in `data-context` package. It's a work in progress; we should continue to update this as we go. I got this information [here](https://www.notion.so/cypressdx/TR-Unification-Development-0c9636f71d5748e6b8f0048f35114061), as well as my personal experience and looking at the patterns @tgriesser introduced.
I noticed a lot of our code doesn't actually adhere to these conventions, since they were not really set in stone when we started the unification project. Many Sources update `coreData` directly, not ideal. We should try to match these conventions as closely as possible.
One thing that does not have a clear practice is data that does not live in `coreData`. For example …

docs(data-context): explain concepts in data-context

---

packages/driver/src/cy/multi-domain/index.ts
packages/driver/src/multi-domain/communicator.ts
packages/driver/src/multi-domain/domain_fn.ts

n/a
Since we removed implicit preprocessing of errors before it is serialized with `postMessage` in #19936 , we need to explicitly preprocess errors in (for firefox) when errors are send back over to the primary domain. This should fix this [test](https://app.circleci.com/pipelines/github/cypress-io/cypress/31019/workflows/d99fccfd-d010-46e5-b510-ed96ea0e8aa0/jobs/1209163/tests#failed-test-0) as well as fix `done` being called with an error in the secondary domain. 
So the following code should result in the correct failure. ( NOTE: We currently do not have a test for this as it requires a 'cypress in cypress' type of test)

fix:  secondary domain error serialization in firefox

---

npm/react/plugins/utils/get-transpile-folders.js

- Closes [UNIFY-1060](https://cypress-io.atlassian.net/browse/UNIFY-1060)
Remove nullish coalescing operator in js files
`plugins/react-scripts` was failing on Node v12 due to the `??` operator. It's fine in typescript files since we transpile them, but not in javascript files.
`@cypress/react/plugins/react-scripts` works with node v12
I tested this by checkout out [cypress-component-testing-examples](https://github.com/cypress-io/cypress-component-testing-examples) and testing against `create-react-app` using nvm to switch to node v12. Running `npx cypress open-ct` throws:
```
The plugins file is missing or invalid.
Your `pluginsFile` is set to `/Users/zachjw/work/cypress-component-testing-examples/create-react-app/cypress/plugins/index.js`, but either the file is missing, it contains a …
```

fix: remove nullish coalescing in js files to support node 12

---

packages/launchpad/src/setup/ScaffoldLanguageSelect.vue

Fixes the e2e select language not having a highlight
Before:
After:

fix: e2e select language highlight

---

.github/semantic.yml
.github/workflows/semantic-pull-request.yml

- Closes 
- Switches from the semantic PR probot added in #7946 to the https://github.com/amannn/action-semantic-pull-request GitHub Action.
- Motivated by downtime on the probot, including the current multi-day outage
- Example of failure PR and output:
- https://github.com/flotwig/cypress-workflow-test/pull/4
- https://github.com/flotwig/cypress-workflow-test/runs/5112017104?check_suite_focus=true …

chore: set up semantic-pull-request GitHub Action

---

packages/example/bin/build.js
packages/example/package.json
yarn.lock

Seeing a bunch of failures here https://github.com/cypress-io/cypress/pull/20084 which are unrelated to the changes. For some reason, it's installing an older version of `cypress-kitchensink`. I don't know why. 
I tried using the latest commit (Feb 4). We were using second latest, Jan 5. With the latest one, it's working, at least locally, after a `yarn install`. Not sure if a circle caching issue, or what, but good to use the latest commit for the example project.
Also pushed this commit to #20084 to see if it fixes the problem there. We might just need to trick Circle into getting a new node_modules :thinking: 
Edit: this does not seem to fix #20084.

chore: use latest kitchensink in example

---

packages/app/src/main.scss
packages/app/src/runner/SpecRunnerOpenMode.vue
packages/app/src/runner/SpecRunnerRunMode.vue
packages/app/src/specs/InlineSpecListHeader.cy.tsx
packages/app/src/specs/InlineSpecListHeader.vue
packages/app/src/specs/InlineSpecListTree.vue
packages/app/src/specs/SpecsListHeader.cy.tsx
packages/app/src/specs/SpecsListHeader.vue
packages/frontend-shared/src/components/Card.vue
packages/frontend-shared/src/components/StandardModal.cy.tsx
packages/frontend-shared/src/components/StandardModal.vue
packages/frontend-shared/src/components/StatusBadge.vue
packages/frontend-shared/src/gql-components/HeaderBarContent.vue
packages/frontend-shared/src/gql-components/topnav/DocsMenuContent.vue
packages/frontend-shared/src/gql-components/topnav/TopNav.vue
packages/frontend-shared/src/locales/en-US.json
packages/frontend-shared/src/styles/shared.scss
packages/launchpad/src/Main.vue
packages/launchpad/src/global/GlobalProjectCard.vue
packages/launchpad/src/setup/CompareTestingCard.vue
packages/launchpad/src/setup/CompareTestingTypes.cy.tsx
packages/launchpad/src/setup/CompareTestingTypes.vue
packages/launchpad/src/setup/OpenBrowserList.vue

1. Font weights (should've been using medium, not semibold)
2. Removed outline for Projects link in Launchpad, used hocus-link-default
3. Fixed spacing in Card.vue (Testing Type cards)
4. Fixed spacing in Testing Type overlay
5. Added a hocus state for "Switch testing type"
6. Added dark scrollbars for "dark mode" parts of the UI
7. Fixed the SpecListHeader "Matches" text to use the proper i18n counters
8. Fixed the SpecListHeader "Matches" focus/hover states
9. Added various hardcoded strings into i18n
10. Removed scrollbars from Menu in GlobalProjectCard.vue
https://user-images.githubusercontent.com/2801156/153143645-f44ea454-db00-45d5-8195-ca353c84572e.mov

fix: various style issues in launchpad and app

---

packages/driver/cypress/fixtures/select-event-counter.html
packages/driver/cypress/integration/commands/actions/select_spec.js
packages/driver/src/cy/commands/actions/select.ts

- Closes #19494
`change`, `input` events are not fired when the same option is selected again. 
- Why was this change necessary? => When the same `<option>` is selected, `change`, `input` events are not be fired in browsers, but Cypress does. 
- Any implementation details to explain? => I cache the selected old values and check them.
**Before:** `cy.select` doesn't follow the browser behavior.
**After:** `cy.select` follows it.  …

fix: `change`, `input` events are not fired when the same option is selected again. 

---

npm/react/examples/react-scripts/cypress/plugins/index.js
npm/react/plugins/react-scripts/findReactScriptsWebpackConfig.js

- Closes https://cypress-io.atlassian.net/browse/UNIFY-1085
Correctly set default `webpackConfigPath` if the user passes an empty object of options to the react-script plugin.
@JessicaSachs discovered that in Cypress 10, if you use the default of
```ts
component: {
devServerConfig: {}
}
```
Then you will have a problem when setting up CT using our setup tool. This fixes it. The problem was if you pass an empty object, we would not set the default webpack config path correctly.

fix: set correct default when using react-scripts plugin

---

packages/server/lib/browsers/chrome.ts
packages/server/lib/browsers/electron.js
packages/server/test/unit/browsers/electron_spec.js

n/a
Due to some changes in how we transition tests made on #19915 we are seeing a race condition with electron where the cdp automation is not set up in time to handle the events that get triggered from running tests. This PR will ensure that we have CDP loaded before we navigate to the new url (incidentally this is how chrome already works).
- [na] Have new configuration options been added …

fix: reorder electron launching sequence to eliminate timing issue

---

packages/server/lib/modes/run.js

- Closes https://github.com/cypress-io/cypress/issues/20120
- Gray out the `system node` path in the terminal run header
**Before**
**After**

feat: gray out the path to system node in cypress run header

---

packages/app/src/runner/SpecRunnerHeader.cy.tsx
packages/driver/src/cy/commands/actions/type.ts

Backing out hot-fix for type changes in develop until those changes can land in develop first.

fix: Backing out driver change for type

---

packages/driver/cypress/fixtures/click-event-by-type.html
packages/driver/cypress/integration/commands/actions/type_spec.js
packages/driver/src/cy/commands/actions/type.ts

Same as #20067, not yet released
Buttons that call preventDefault on their keyUp events do not emit a click event when pressed with the Spacebar. This PR adds the defaultPrevented check to make sure we're not sending more events than we expect.
Came across this issue when Space was being used to toggle open a headless-ui Popover; you can see their logic here: https://github.com/tailwindlabs/headlessui/blob/main/packages/%40headlessui-vue/src/components/popover/popover.ts#L315-L320. The implementation in develop will emit the click event regardless of the prevention, causing the Popover to close and then immediately reopen (as it implements handlers for both).

fix: Update `.type(' ')` to not emit clicks when the keyup event has been prevented

---

packages/driver/cypress/integration/e2e/multi-domain/commands/multi_domain_screenshot.spec.ts
packages/driver/package.json
packages/driver/src/cy/commands/screenshot.ts
packages/driver/src/dom/animation.ts
packages/driver/src/dom/blackout.ts
packages/driver/src/dom/index.ts
packages/runner-ct/src/iframe/iframes.tsx
packages/runner-shared/src/dimensions.js
packages/runner-shared/src/dom.js
packages/runner-shared/src/iframe/aut-iframe.js
packages/runner/src/iframe/iframes.jsx

- Implements screenshot blackout support for #20060 
n/a
Blacking our screenshot elements in multi-domain was not previously working due to the element logic being executed in the primary domain which resulted in cross-domain failures. In order to resolve the cross-domain issue, the logic is moving to the `screenshot` command which has access to the secondary domain.
* Removed `beforeScreenshot` and `afterScreenshot` logic from `aut-iframe.js` to `screenshot.ts`
* listeners removed from `runner` and `runner-ct`
* Moved `add/removeBlackouts` and `add/removeCssAnimationDisabler` functions from `runner-shared/dom.js` to two new files `animation.ts` and `blackout.ts` in the `driver`.
* Moved the `getElementDimensions` function to its own file `dimensions.ts`.
Supports blacking out elements in …

feat: (multi-domain) add support for screenshot blackout

---

packages/driver/cypress/integration/cypress/error_utils_spec.ts
packages/driver/src/cypress/error_utils.ts

- Closes #19561
Fixes an issue where Cypress throws an error when reporting/wrapping errors with type `boolean` or `number`.
Cypress runner uses `wrapErr` to add and remove some props to error object. But it seems that some user modules/deps can throw/reject with type `bool` or `number`. But `wrapErr` covers only falsy values.
* Errors with type `boolean` or `number` will be considered as empty/invalid errors.

fix(driver): update wrapErr to ignore number and boolean values

---

circle.yml
packages/app/cypress/e2e/navigation.cy.ts
packages/app/cypress/e2e/settings.cy.ts
packages/frontend-shared/cypress/e2e/support/e2eSupport.ts
packages/launcher/lib/windows/index.ts
packages/launchpad/cypress/e2e/choose-a-browser.cy.ts

This PR fixes three tests on windows.
It also adds the possibility to add a timeout on `cy.scaffoldProject()`. This avoids flakes on windows when necessary but prevents the effects of a potential infinite loop.

test: fix some windows tests

---

packages/net-stubbing/lib/server/util.ts
packages/net-stubbing/test/unit/util-spec.ts

- Closes https://github.com/cypress-io/cypress/issues/20143
Http-Requests with content-type `multipart/form-data` will no longer stringified when they are intercepted
This change is necessary to guarantee that form-data requests which contain a binary file and a certain amount of plain text will not be serialized when they are intercepted. The serialization breaks binary files (like PDFs).

fix: treat form-data bodies as binary

---

packages/driver/cypress/integration/e2e/multi-domain/commands/multi_domain_misc.spec.ts
packages/driver/cypress/integration/e2e/multi-domain/commands/multi_domain_screenshot.spec.ts
packages/driver/src/multi-domain/cypress.ts
packages/runner/injection/main.js
packages/runner/injection/multi-domain.js
packages/server/test/support/fixtures/server/absolute_url_expected.html

- Closes #20060 
n/a
When taking a screenshot the timers need to be paused so the screenshot is not affected by any changes from the timer code. After the screenshot finishes, the timers are unpaused and allowed to run. The logic for pausing/unpausing the timers already exists in multi-domain but we weren't listening to the events. Updated `injection/multi-domain.js` to listen for the events and call the appropriate methods in `injection/timers.js`.
Timers are now paused when a screenshot is being taken and unpaused afterwards.
- …

feat: (multi-domain) add support for pausing timers during screenshots

---

packages/data-context/src/sources/FileDataSource.ts
packages/data-context/src/sources/migration/shouldShowSteps.ts

- Closes UNIFY-1009
None
Used `concat` instead of `isArray` to simplify the code

fix: refactor function getFilesByGlob to use concat instead of isArray

---

packages/server/lib/environment.js

n/a
Our cy.visit performance tests are locking up occasionally. When running locally in electron, I see the following message displayed:
```
[50160:0218/150228.534909:INFO:CONSOLE(7623)] "Throttling navigation to prevent the browser from hanging. See https://crbug.com/1038223. Command line switch --disable-ipc-flooding-protection can be used to bypass the protection", source: cypress:///../driver/node_modules/jquery/dist/jquery.js (7623)
```
Previously, we added the flag `--disable-ipc-flooding-protection` for [chrome](https://github.com/cypress-io/cypress/issues/5132). It looks like this is needed for electron as well. I tried adding it and running the tests through ci with no failures whereas previously it was failing fairly frequently. As mentioned …

chore: fix server performance flake

---

system-tests/lib/system-tests.ts
system-tests/test/deprecated_spec.ts

- Removes an incidental `systemTests.it.only` which would have prevented those CI groups from fully running.
- Throws an error in CI when `systemTests` are run exclusively
CC @jennifer-shehane and @ryanthemanuel and @tgriesser 
There was a PR merged in about a week ago (the PR that closes the browser tab) that inadvertently added this. That means that PR's into `10.0` that passed may not actually have been passing since the system test group that was set to run `deprecated_spec.ts`  were not running all the tests.
We should update our custom `eslint` plugin which disallows `it.only()` to account for this situation: `systemTests.it.only(...)`. Right now listing is not catching this problem and it could occur again in the future.

chore: remove system test it.only and prevent CI from ever running onlys

---

circle.yml

- Closes 
#20250 was merged with a bad assumption:
> Removed {{ arch }} from Circle cache keys - this is slightly different b/t docker and machine runners, and we need the machine runner to be able to run docker commands. This is fine because we use a workflow per arch and caches are scoped to a single workflow: [circleci.com/docs/2.0/caching/#writing-to-the-cache-in-workflows](https://circleci.com/docs/2.0/caching/#writing-to-the-cache-in-workflows)
In fact, this was a misreading of the docs, caches are shared across workflows. Merging #20250 broke the cache for darwin and windows by using the linux cache for all 3 workflows.
This PR avoids the mentioned `arch` issue by using the checksum of $PLATFORM instead. Unfortunately there's not a way to just put the literal $PLATFORM in the …

chore: fix cache keys to include PLATFORM

---

packages/frontend-shared/src/components/Card.cy.tsx
packages/frontend-shared/src/locales/en-US.json

- Closes https://cypress-io.atlassian.net/browse/UNIFY-1184
n/a
Fixed a typo in the description of E2E testing which said "each" twice.
Before:
After:

fix: Typo in E2E Description

---

packages/net-stubbing/lib/server/util.ts
packages/net-stubbing/test/unit/util-spec.ts

Reverts cypress-io/cypress#20144
Unreleased - not a user-facing change.
This is being reverted because it caused breakage in `cypress-example-recipes` that's indicative of real-world breakage for users of `cy.intercept()`: https://circleci.com/gh/cypress-io/cypress/1283292?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
The patch to `cypress-example-recipes` required for it to pass after #20144: https://github.com/cypress-io/cypress-example-recipes/pull/762/commits/149ad0ed5732052a3de108bfabb6dd6381c24f19
Discussion about how to fix the problem #20144 was meant to address can continue in the original issue, #20143

fix: revert "fix: treat form-data bodies as binary"

---

packages/data-context/src/DataContext.ts
packages/launchpad/cypress/e2e/migration.cy.ts
packages/launchpad/cypress/e2e/open-mode.cy.ts
packages/launchpad/cypress/e2e/project-setup.cy.ts
yarn.lock

- Closes UNIFY-1138
- Closes UNIFY-1130
The `ProjectLifecycleManager` should be self-contained in managing the config loading based on state changes, we shouldn't be calling `initializeConfig` it `initializeOpenMode` as we might not have a configured project.

fix: UNIFY-1138, UNIFY-1130 loading unconfigured project

---

circle.yml

- Closes 
- `/tmp` is a symlink on mac, causing this error when cache state is restored in darwin CI (only if there is a cache hit):
```
Error untarring cache: Error extracting tarball /var/folders/bl/wbxjgtzx7j5_mjsmfr3ynlc00000gp/T/cache486786390 : tmp/node_modules_installed: Cannot extract through symlink tmp/node_modules_installed tar: Error exit delayed from previous errors. : exit status 1
```
- This change was added in #20250 but actually does not appear to be necessary so we can revert it
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation …

chore: fix CI cache state for darwin

---

packages/driver/cypress/integration/e2e/multi-domain/multi_domain_spec.ts
packages/driver/cypress/integration/e2e/multi-domain/multi_domain_validation_specs.ts
packages/driver/src/cy/multi-domain/index.ts
packages/driver/src/cypress/cy.ts
packages/driver/src/cypress/runner.ts
packages/driver/src/multi-domain/communicator.ts
packages/runner-shared/src/event-manager.js
packages/runner/injection/multi-domain.js
packages/runner/src/iframe/iframes.jsx
packages/server/lib/html/multi-domain-iframe.html

- Closes #20199 
n/a
This PR introduces the concept of running multiple multi-domain command in a single test. To accomplish this, I have added logic to:
* Find an appropriate bridge when a multi-domain AUT is loaded
* Send bridge messages to a specific domain
* Send bridge messages to all domains
* Identify which domain sent a message to primary
What this does not fix:
* Setting readyForMultiDomain to false
* Anticipating a domain that never loads

chore: [Multi-domain]: Support multiple multi-domain commands in a single test

---

packages/driver/cypress/integration/cypress/error_utils_spec.ts
packages/driver/src/cypress.ts
packages/driver/src/cypress/error_utils.ts
packages/driver/src/cypress/log.ts
packages/driver/src/cypress/mocha.ts
packages/driver/src/cypress/runner.ts
packages/driver/src/cypress/screenshot.ts
packages/driver/src/cypress/script_utils.ts
packages/driver/src/cypress/source_map_utils.ts
packages/driver/src/cypress/stack_utils.ts
packages/driver/src/cypress/utils.ts
packages/driver/src/cypress/xml_http_request.ts
packages/driver/src/dom/jquery.ts
packages/driver/src/dom/window.ts
packages/driver/src/util/limited_map.ts
packages/driver/types/internal-types.d.ts
packages/errors/src/stackUtils.ts

- Related with #18715
- Next step of #19837
N/A. It's just removing `// @ts-nocheck` comments and defining types to avoid type errors. 
- Why was this change necessary? => To make pkg/driver files more type-safe.
N/A
- [na] Have new configuration options been added …

chore: remove pkg/driver //@ts-nocheck final

---

packages/app/src/runs/CloudConnectButton.vue

I merged https://github.com/cypress-io/cypress/pull/20332 without backmerging `10.0-release` first, where the eslint config was changed, which meant a linting error is now in 10.0-release. This fixes it. I'm sorry.

chore(app): fix linting

---

packages/icons/package.json

@elylucas here is the fix for the `Cannot find module './dist/icons'` error

fix: build icons in build-prod

---

npm/react/plugins/next/findNextWebpackConfig.js
npm/webpack-dev-server/src/browser.ts
npm/webpack-dev-server/src/makeWebpackConfig.ts

- Closes UNIFY-1133
In webpack 5 it seems that loaders called with the exact same query are not re-run. 
This creates a situation where the Cypress file watcher is updating the files but the new files are never pushed in the loader. It results in Cypress throwing a (No tests found) error since the spec exists but not in the AUT.
In this PR I disable caching and unsafe caching for the browser.js file.

fix: avoid nextjs unsafeCache and watchOptions

---

circle.yml

- https://discuss.circleci.com/t/coming-soon-gen2-macos-resources/41886/16
Updated and pushed to see build times were faster. Seems like they might just be!
[Reference Build Times](https://app.circleci.com/pipelines/github/cypress-io/cypress?branch=develop&filter=all) - Looked at jobs without installing node_modules
[Updated Build Times](https://app.circleci.com/pipelines/github/cypress-io/cypress?branch=faster-mac-builds&filter=all) - Neither build installed node_modules

chore: speed up mac build times in CI

---

circle.yml
guides/release-process.md
package.json
scripts/binary/move-binaries.ts
scripts/binary/s3-api.ts
scripts/binary/upload-build-artifact.js
scripts/binary/upload.js
scripts/binary/util/upload.js
yarn.lock

- Closes #20423
- update release scripts to use AWS credentials API instead of use custom env var. This allows one to login via the aws cli and have the ability to run the move binaries and upload to s3 scripts.
- updated CI env to use AWS envs instead of custom env var.
n/a
One less ENV to set during the release and less work to determine the AWS session token and aligns with AWS docs for providing credentials.
- [n/a] Have API changes been updated in the [`type …

chore: update release scripts to work with AWS SSO

---

packages/driver/cypress/integration/commands/net_stubbing_spec.ts
system-tests/test/screenshots_spec.js

n/a
This fixes a flake with screenshot system tests. Specifically, we are checking that image sizes are unique that are taken during the test (if the size is different, the image is likely different). Two images specifically will sporadically be identical images and this causes a flake. The two images in question are created by simulating an exception in both the beforeEach and afterEach hooks. Both exceptions will create an image and both will display the same state of the reporter since the images capture the state at the time of the exception and not when the exception itself is displayed. Before 10.0 we were still saved by the running timer for the overall test since it would keep track of the times out to the 100th of a second. In 10.0 that was switched to be to the nearest second so …

test: update screenshot system-tests flake so that it no longer compares images for uniqueness that represent the same state

---

packages/frontend-shared/src/components/Select.cy.tsx

In #20361 I removed some icons from the Select.cy.tsx spec and replaced them with empty divs. In this PR I'm adding them back after figuring out what the real issue was with why they weren't showing up.

fix: percy snapshotting for the Select.cy.tsx spec

---

packages/driver/cypress/integration/e2e/multi-domain/multi_domain_spec.ts
packages/driver/src/cy/multi-domain/util.ts
packages/driver/src/multi-domain/cypress.ts
packages/driver/src/multi-domain/domain_fn.ts
packages/driver/types/internal-types.d.ts

- Closes 
n/a
This enables commands run in switch to domain to be able to use the default timeout set outside of switch to domain.
The issue was that the runnable did not have a 'timeout' function. This was corrected by rehydrating the runnable into a test object.
Before: 
After:

chore: [Multi-Domain] enable commands in switchToDomain to use the default timeout

---

guides/README.md
guides/patch-package.md

- Closes #20400
n/a
- Documents best practices around using `patch-package` in the Cypress monorepo.

docs: document patch-package best practices

---

packages/server/lib/project-base.ts
packages/server/test/unit/project_spec.js

- Closes https://github.com/cypress-io/cypress/issues/20496
Fix regression that caused ANSI color chars to show up on Firefox warning message about `chromeWebSecurity`
This regression was introduced in Cypress version 9.5.0 as a result of this PR: https://github.com/cypress-io/cypress/pull/20072 where errors originating from the server (`@packages/errors`) were altered as part of a larger errors improvement.
To fix this regression, I simply stripped the ANSI chars from the warning message, since this config will display differently in 10.0 and will be deprecated with multi-domain anyway.
Before:
After:
- [n/a] Have API changes been updated in the [`type …

fix: error regression - unexpected ANSI color chars shown on Firefox warning message about chromeWebSecurity

---

packages/driver/cypress/integration/commands/navigation_spec.js
packages/driver/cypress/integration/e2e/multi-domain/commands/multi_domain_misc.spec.ts
packages/driver/cypress/integration/e2e/multi-domain/commands/multi_domain_navigation.spec.ts
packages/driver/cypress/integration/e2e/multi-domain/multi_domain_cypress_api.spec.ts
packages/driver/cypress/integration/e2e/multi-domain/multi_domain_events_spec.ts
packages/driver/cypress/integration/e2e/multi-domain/multi_domain_uncaught_errors_spec.ts
packages/driver/src/cy/commands/navigation.ts
packages/driver/src/cy/multi-domain/index.ts
packages/driver/src/cypress.ts
packages/driver/src/multi-domain/communicator.ts
packages/driver/src/multi-domain/cypress.ts
packages/driver/src/multi-domain/domain_fn.ts
packages/driver/src/multi-domain/events/misc.ts
packages/driver/src/multi-domain/events/screenshots.ts
packages/driver/types/internal-types.d.ts
packages/proxy/lib/http/request-middleware.ts
packages/proxy/lib/http/util/buffers.ts
packages/proxy/test/unit/http/helpers.ts
packages/proxy/test/unit/http/request-middleware.spec.ts
packages/runner/src/iframe/iframes.jsx
packages/server/lib/server-e2e.ts
packages/server/test/integration/server_spec.js

- Closes #19857
- Closes #20431
- Closes #19876
n/a
This change supports the following:
* Using `cy.visit()` within `switchToDomain` both as the first navigation to a new domain or navigating within the domain
* Note: relative urls are NOT currently supported
* Using `cy.go()` within `switchToDomain`
Details:
* Stability is sync'd in from primary domain to allow the command queue to proceed
* When requesting a change to the iframe src prop in the secondary, a message is sent to the primary to perform that actual change since the secondary does not have access to the `$autIframe`
* When resolving the url on the backend, the `isMultiDomain` value is passed along to:
* prevent the server from updating the remote state with the new origin
* inject `fullMultiDomain` for buffered multi-domain …

feat: (multi-domain) adding support for cy.visit in multi-domain

---

packages/driver/cypress/integration/cypress/log_spec.js
packages/driver/src/cy/commands/navigation.ts
packages/driver/src/cypress.ts
packages/driver/src/cypress/log.ts
packages/driver/src/cypress/runner.ts

- Related with [this comment](https://github.com/cypress-io/cypress/pull/20169#discussion_r813042620)
N/A. It's an internal refactoring
- Why was this change necessary? => Modernize the code.
- Any implementation details to explain? => Change the function/object to class.
As it's a refactoring, the code change is hard to read. So, I left this.
* I organized the code into 3 parts: `LogUtils`, `LogManager`, `Log`. 
* `LogUtils` are functions used in other files. They were exported with `export default`. I could remove them.
* `LogManager`: Inside `create` function, `logs` variable exists and it manages logs created. But it makes us create `fireChangeEvent` function inside `create` function and attach it to `Log`. So, I created `LogManager` class and …

chore: refactor log function to class

---

system-tests/projects/downloads/cypress/integration/downloads_spec.ts
system-tests/test/downloads_spec.ts

n/a
There was a [change](https://github.com/cypress-io/cypress/commit/2ee98938cd7b1c7b6cf368681c6f827682dabec2#diff-c1ed819829a1be91181002a07a7e3399f0c435939b724e49e4fd5d2d6f23befeR9-R29) made on the multi domain branch to fix a flake. The purpose of this change was to ensure that we are waiting for the download of the csv file before we check its contents.
Unfortunately, this left an additional flake. That flake was caused because we were downloading the same file multiple times in different tests and thus the second one actually gets placed at records(1).csv. In addition, the first file download doesn't have the fix that the second file download has so the file is not guaranteed to be downloaded. Therefore when the second test executes it's actually reading the location of the first …

test: fix system-tests-firefox downloads flake

---

packages/driver/cypress/fixtures/click-event-by-type.html
packages/driver/cypress/integration/commands/actions/type_events_spec.js
packages/driver/src/cy/commands/actions/type.ts

- Next step of #20191
- Final step of #19541
- Related with [this comment](https://github.com/cypress-io/cypress/pull/19726#issuecomment-1021238555)
Click events are fired correctly when focus is changed on event handlers. 
- Why was this change necessary? => When the focus is changed on event handlers, the newly focused object got the click event. This PR simulates this behavior. 
Click event emitting is a bit different between enter and space. 
* Click event is fired on the newly-focused element when enter is pressed. 
* Click event is not fired on any element when space is pressed.
Before this PR, Cypress behavior is the opposite (not firing on enter and firing on space). This PR fixes this issue. 
**Before:** Click event is not sent on enter …

fix: click event is fired correctly when focus has changed

---

packages/app/cypress/e2e/cypress-in-cypress-component.cy.ts
packages/app/cypress/e2e/cypress-in-cypress-e2e.cy.ts

NA
Recently added tests that visit the runner page directly were experiencing flake without waits. This PR adds the waits and links to an issue for figuring out why they are flaky.
NA

test: add waits to visits directly to runner

---

npm/webpack-dev-server/src/loader.ts
npm/webpack-dev-server/test/e2e.spec.ts
npm/webpack-dev-server/test/fixtures/foo bar.spec.js
system-tests/projects/webpack-dev-server/cypress/component/foo bar.spec.js

Use `decodeURI` so as to allow specs with `[]` and spaces to be loaded and executed.

fix: use decodeURI in loader and add tests

---

packages/driver/cypress/integration/e2e/multi-domain/commands/multi_domain_navigation.spec.ts
packages/driver/src/cy/commands/navigation.ts
packages/driver/src/cy/multi-domain/index.ts
packages/driver/src/cypress.ts
packages/driver/src/multi-domain/communicator.ts
packages/driver/src/multi-domain/cypress.ts
packages/driver/src/multi-domain/domain_fn.ts
packages/driver/src/multi-domain/events/logs.ts
packages/driver/src/multi-domain/events/misc.ts
packages/driver/src/multi-domain/events/screenshots.ts
packages/driver/src/multi-domain/events/test.ts
packages/driver/types/internal-types.d.ts
packages/runner-shared/src/event-manager.js

n/a
* Updated the `url:changed` event in the secondary to correctly serialize the url so it displays correctly in the AUT header (instead of `[object Object]`).
* When sending to the primary, we assume the `data` param is a key-value object but in this case, we were passing the url as a string. I updated the url to be passed as an object and updated the type of the `data` param to be `Cypres.ObjectLike` to prevent the issue in the future.
* Added `Cypress.isMultiDomain` and removed `Cypress.state('isMultiDomain')` and `__isMultiDomainCypress` so there is only one boolean to determine if `Cypress` is in multi-domain.
* Reverted the `about:blank` changes made in #20467 since we are requiring `experimentalSessionSupport` which visits `about:blank` between tests.
* Updated …

chore: (multi-domain) url:changed fix, revert about:blank, use Cypress.specBridgeCommunicator, Cypress.isMultiDomain

---

packages/data-context/src/codegen/code-generator.ts

Perf improvement/generally the pattern we should be following for loop iteration & promises, the `for / of` with an `await` in the body will execute in series, while the `Promise.all` loop executes in parallel.
Minor thing, but just a good idea to an eye out for these & replace anytime it won't affect the outcome.

refactor: remove for-of loop with await, replace with Promise.all + map

---

packages/driver/cypress/integration/e2e/multi-domain/multi_domain_uncaught_errors_spec.ts
packages/driver/src/cy/multi-domain/index.ts
packages/driver/src/cy/multi-domain/util.ts
packages/driver/src/cypress/error_messages.ts
packages/driver/src/multi-domain/communicator.ts
packages/driver/src/util/config.ts
packages/driver/src/util/serialization.ts
system-tests/__snapshots__/multi_domain_error_spec.ts.js
system-tests/projects/e2e/cypress/integration/multi_domain_error_spec.ts
system-tests/projects/e2e/multi_domain.html
system-tests/projects/e2e/multi_domain_secondary.html
system-tests/test/multi_domain_error_spec.ts

- Closes N/A
n/a
After the large refactor changes incorporated in #20247, `switchToDomain` error stack invocations were temporarily removed until we could safely reincorporate them. This PR addresses re adding those stack invocations, as well as condolidating the error/thrown preprocessing logic with the config preprocessing logic.
In `structuredClone`, Objects are serialized to literals while omitting prototype hierarchy values as well as omitting `get`, `set`, and other properties when cloning (see [here](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm#things_that_dont_work_with_structured_clone)). 
`Error`s, even though they are objects, are handled differently depending on the implementation of `structuredClone`. Firefox cannot serialize …

fix: standardize error and object serialization

---

packages/example/package.json
yarn.lock

Updates cypress-example-kitchensink to latest version, which has fewer external dependencies.
See
- https://github.com/cypress-io/cypress-example-kitchensink/pull/540
- https://github.com/cypress-io/cypress-example-kitchensink/issues/537
- https://github.com/cypress-io/cypress-example-kitchensink/issues/539
Tests using the kitchensink will no longer hang.
- [N/A] Have tests been added/updated?
- [N/A] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [N/A] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d. …

chore: Bump cypress-example-kitchensink to 1.15.3

---

packages/driver/cypress/integration/e2e/multi-domain/navigation_spec.ts
packages/driver/src/cy/multi-domain/index.ts
packages/driver/src/multi-domain/cypress.ts
packages/driver/src/multi-domain/domain_fn.ts
packages/runner-shared/src/event-manager.js

- Closes 
n/a
On further inspection, we should not get into a state where the AUT loads before the spec bridge is active due to our delaying logic. Given this we can remove some code trying to sync a load even that happened if the page loaded before the specbridge was active.

chore: [Multi-domain] Clean up stability code.

---

packages/driver/src/cypress.ts
packages/driver/src/multi-domain/communicator.ts
packages/driver/src/multi-domain/cypress.ts
packages/runner-shared/src/event-manager.js

- Closes N/A
N/A
When we reload tests, this errors tends to pop up anytime we edit tests that are dealing with errors in multi-domain. This is caused by multiple instances of the `primaryDomainCommunicator` being created, but rebinding the same `window.top.addEventListener('message')` on recreation. This leads to duplicate `message` events. This was introduced in #20520 when the `userInvocationStack` was added to the `primaryDomainCommunicator` instance [here](https://github.com/cypress-io/cypress/pull/20520/commits/525d3d043c2573b6a03c97074c0cc3efc1986588#diff-020c1583f496d3e76864f6520d8ac704ed5f608af74ded72518fa30c193107e9L49). The dangling `primaryDomainCommunicator` instance would NOT have the `userInvocationStack` set, which would fail to reify errors coming back from the other …

fix: make the primary domain communicator a singleton per cypress instance

---

packages/app/cypress/e2e/settings.cy.ts
packages/frontend-shared/src/composables/examples/UseMarkdownExample.cy.tsx
packages/frontend-shared/src/composables/useMarkdown.ts

- Closes UNIFY-1063
Some of the links in our markdown content are styled with inner `<code>` elements, which causes our link detection logic to fail. In these instances, the click target is the `<code>` element, not the link itself.
I updated the logic to search for parent links to prevent this. I also added component test coverage for the `useMarkdown` composable and e2e coverage for the links in Settings.

fix: Updating link detection in markdown content

---

packages/driver/cypress/integration/commands/files_spec.js
packages/driver/src/cy/commands/files.ts

- Closes #20683
When `null` encoding is used, and a file cannot be found, we are passing `null` to Buffer.from which is throwing `TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object`. This caused the command to bail instead of retrying and providing a meaningful error message to the users.
- Fixed an  issue in `cy.readFile()` where the command would not retry or provide a meaningful error message if `null` encoding was used and the file was not found. Fixed [#20683](https://github.com/cypress-io/cypress/issues/20683).
| before | after|
| --- | ---|
| <img width="400" alt="Screen Shot 2022-03-18 at 9 34 39 AM" src="https://user-images.githubusercontent.com/14099737/159022710-f02a0de8-7fcb-469f-89b9-3c92f8c81793.png"> | <img width="400" alt="Screen …

fix(driver): readFile - verify null contents to Buffer.from

---

circle.yml

n/a
In order to get the latest 10.0 changes on kitchen sink, we need to be pointing to the 10.0 pr.
n/a

chore: update kitchensink pr to point to 10.0.0 pr

---

packages/data-context/package.json
packages/frontend-shared/cypress/e2e/e2ePluginSetup.ts

- Fix "clean" script, noticed this was broken while pairing w/ @emilyrohrbough last week
- Scaffold `package.json` deps if they exist in a system-test directory in open-mode, as we do in regular system tests

chore: fix data-context clean script, scaffoldProjectNodeModule in open mode

---

packages/driver/cypress/integration/e2e/multi-domain/commands/multi_domain_log.spec.ts
packages/driver/cypress/integration/e2e/multi-domain/commands/multi_domain_misc.spec.ts
packages/driver/cypress/integration/e2e/multi-domain/multi_domain_yield_spec.ts
packages/driver/src/cy/multi-domain/index.ts
packages/driver/src/cypress/log.ts
packages/driver/src/multi-domain/domain_fn.ts
packages/runner-shared/src/event-manager.js

- Closes #20621
n/a
There were two things wrong that caused the disappearing logs when switching the top domain. 
1. The logs in the spec bridges always started at zero so we were getting duplicate log ids.
2. The logs in the switchToDomain were not getting attached to any commands in the primary domain. This lead to the commands getting lost when state was preserved and then rehydrated during a top domain switch event.
To resolve these problem, this PR passes the current log count into the secondary domain to reset its count on each `run:domain:fn` event. This may result in skipped number sequences per domain, but it will ensure unique id's across all domains, regardless of the situation. (Having a spec bridge that turns into top and back again comes to mind)
Secondly we attach the …

fix: [Multi-domain] Preserve switchToDomain command logs between top domain changes.

---

packages/server/lib/browsers/cdp_automation.ts
packages/server/lib/browsers/cri-client.ts
packages/server/test/unit/browsers/cri-client_spec.ts

N/A
This refactors `packages/server/lib/browsers/cri-client.ts` to use async/await instead of Bluebird promises. It's a precursor to work being done in this file related to reconnecting to the CDP. There are no functional changes in this PR.
- N/A Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/bl …

chore: Refactor cri-client to use async/await

---

circle.yml

- Closes 
- Moves the record key and Percy token to their own CircleCI contexts.

test: move record keys to contexts

---

cli/types/cypress.d.ts

Added the correct type for a cookie for the callback to preserve cookies. 
This type was set to `any`, but a correct type `Cookie` already exists.

fix(types): add correct type for preserve cookie callback

---

packages/driver/src/cy/commands/actions/type.ts
packages/driver/src/cypress.ts
packages/driver/src/cypress/browser.ts

- Closes #20562
`cy.type()` + `{enter}` or ` ` should work with Firefox 98+
- Why was this change necessary? => Some `click` event related behaviors of Firefox has been changed with 98. This breaks `cy.type()`.
Before Firefox 98, it automatically sent `click` event to all button-like elements. But after 98, it only does that with `<button>` element and does nothing with other button-like `<input>` elements. 
In addition, it does not change the state of `<input type="checkbox">` `<input type="radio">`. I fixed that, too. 
`cy.type()` works well with Firefox 98+
Currently Cypress CI uses Firefox 93. We couldn't detect this problem because of that. And the current CI cannot test this scenario. This should be tested manually.
- [na] Has a PR for …

fix: `cy.type()` + `{enter}` or ` ` should work with Firefox 98+

---

system-tests/projects/component-tests/cypress/support/component-index.html

NA
Adding a missing file that was causing some the dev-server for certain tests to throw errors. No tests are failing, but good to cleanup the logs and have the system tests structured as they should be.
No longer see 
```
ERROR in Entry module not found: Error: Can't resolve '/private/var/folders/8q/b_sy2fp93fs5k7mvkxn60g4r0000gn/T/cy-projects/component-tests/cypress/support/component-index.html' in '/private/var/folders/8q/b_sy2fp93fs5k7mvkxn60g4r0000gn/T/cy-projects/component-tests'
```
when running system tests that point to the `component-tests` project.

fix: add missing component-index.html

---

packages/driver/src/cy/commands/sessions.ts
packages/runner/cypress/integration/sessions.ui.spec.js

Fixes issue observed when cookies have not be set within a session and the user clicks the command log to view additional details. Discovered this issue when following along with the cy.session documentation examples in the docs pages.
**Error details**
**Observe issue & fix from updated tests:**
https://user-images.githubusercontent.com/14099737/162060904-5c153199-7ba1-40c6-afa0-c982ad454a7c.mov
Fixed an edge-case error observed in `cy.session` where an error is thrown when no cookies have been set for the session and the user clicks the session command log to view additional details in the dev tools console.
No error when clicking the session log.
- …

fix(session): error thrown by unset cookies when printing session details to dev tools console

---

circle.yml
cli/__snapshots__/install_spec.js
cli/lib/tasks/state.js
cli/test/lib/tasks/install_spec.js

- Partially addresses UNIFY-1449
- Decreased the length of the Cypress cache path when installing pre-releases. This should improve the experience for Windows users, where the max path length is 260 characters by default.
- Pre-release paths are getting ridiculously long since #20296 leading to issues like trying to unpack `C:\Users\Administrator\AppData\Local\Cypress\Cache\beta-10.0.0-10.0-release-404447e397190ebb0f8ce0bb270ea9a806ca78c6\Cypress\resources\app\node_modules\remark-mdx\node_modules\@babel\plugin-proposal-object-rest-spread\node_modules\@babel\helper-plugin-utils\lib` and failing on Windows because the path is too long (261 characters)
- ~~Removed `version` from the path altogether since it's not relevant in development.~~ Keeping `version` as a rough indicator of when the …

fix(cli): decrease the length of pre-release cache path

---

cli/lib/exec/spawn.js
cli/test/lib/exec/spawn_spec.js

- Closes #19299
Silences electron warnings about being unable to connect to dbus. These errors are normal and expected, and do not result in test failures. They are present when running electron inside docker containers 100% of the time.
Chromium (which Electron uses) always makes several attempts to connect to the system dbus. This works fine in most desktop environments, but in a docker container, there is no dbus service and Chromium emits several error lines, similar to these:
```
[1957:0406/160550.146820:ERROR:bus.cc(392)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[1957:0406/160550.147994:ERROR:bus.cc(392)] Failed to connect to the bus: Address does not contain a colon …
```

fix: silence dbus errors

---

packages/driver/src/cy/multi-domain/index.ts

- Closes 
n/a
Quick fix for an uncaught error.
In the event that the `run:origin:fn` event fails a secondary error was thrown because we weren't releasing the request.
I didn't add a test because it's hard to test a negative, This wasn't caught in our existing tests because it's a second error and we already handled the first error.

chore: [Multi-domain] Fix uncaught error

---

packages/driver/cypress/integration/cypress/command_spec.js
packages/driver/src/cypress/command.ts

While pulling in the[ logGroup changes into within in the 10.x branch,](https://github.com/cypress-io/cypress/pull/20980) I noticed two consistent command failures with the following error:
The test flow could be summarized like:
```js
cy.get('modal').as('modalAlias').within(() => {}) // within using log group
// do something 
cy.get('@modalAlias') // command replay is triggered which includes replaying the end-logGroup command
```
When a command is replayed, it's cloned and injected into the command queue. 
When the command is cloned, it pull sanitize the commands args list to pull forward an create a new command. Generally commands have args, but because the injected end-logGroup command did not have args passed, it was undefined and caused this error.
This check just ensures commands …

fix: add safety check for command.clone when cmd does not have args

---

packages/driver/cypress/integration/cy/navigation_spec.js
packages/driver/src/cy/navigation.ts

- Closes #19749
- Closes #20539 
n/a
This issue occurs during url state changes and Cypress attempts to test the current url, but the state is empty.
Cypress stops randomly throwing this error and failing tests:
`TypeError: Cannot read properties of undefined (reading 'undefined')` …

fix: empty state urls in navigation

---

packages/driver/cypress/integration/e2e/multi-domain/navigation_spec.ts
packages/driver/src/cypress/error_messages.ts

- Closes 
n/a
Added some updates to the error messages based on feedback
cross_origin_load_timed_out:
* added cy.origin docs url
* removed redundant page did not load message
cross_origin_command:
* removed colons
* added further explanation of likely causes.
When a page load times out when a cross origin request exists
When a command times out and the aut origin does not match the command origin

chore: [Multi-domain] Update error messages based on feedback.

---

circle.yml

N/A
Removes parallelism from a few jobs against remote repose that aren't benefitting from it

chore: remove parallelism from test-binary-against-repo jobs

---

cli/types/cypress.d.ts
packages/driver/cypress/integration/e2e/multi-domain/multi_domain_cypress_api.spec.ts
packages/driver/cypress/integration/e2e/multi-domain/multi_domain_spec.ts
packages/driver/cypress/integration/e2e/multi-domain/multi_domain_uncaught_errors_spec.ts
packages/driver/cypress/integration/e2e/multi-domain/multi_domain_validation_specs.ts
packages/driver/cypress/integration/e2e/multi-domain/navigation_spec.ts
packages/driver/src/cy/commands/navigation.ts
packages/driver/src/cypress/cy.ts
packages/driver/src/multi-domain/cypress.ts
packages/driver/src/multi-domain/domain_fn.ts
packages/driver/src/multi-domain/events/logs.ts
packages/driver/src/multi-domain/events/misc.ts
packages/web-config/webpack.config.base.ts
system-tests/test/multi_domain_error_spec.ts
system-tests/test/navigation_spec.ts

I audited all TODOs and FIXMEs added in the `feature-multidomain` branch and did the following:
- Removed it if no longer necessary
- Added context where necessary
- Added issue links to the comments that remain

chore: audit cross-origin related TODOs/FIXMEs

---

packages/data-context/src/actions/WizardActions.ts
packages/launchpad/src/setup/OpenBrowserList.vue
packages/scaffold-config/src/commandFile.ts
packages/scaffold-config/src/frameworks.ts
packages/scaffold-config/src/index.ts
packages/scaffold-config/src/supportFile.ts
packages/scaffold-config/test/unit/supportFile.spec.ts
system-tests/projects/component-tests/cypress/support/component-index.html
system-tests/projects/pristine/expected-cypress-js-component-create-react-app-v5/cypress/support/component.js
system-tests/projects/pristine/expected-cypress-ts-component-create-react-app-v5/cypress/support/component.ts

- Closes https://cypress-io.atlassian.net/browse/UNIFY-1387
**note**: forked from https://github.com/cypress-io/cypress/pull/20893
**note**: the generated file will be invalid until https://cypress-io.atlassian.net/browse/UNIFY-1386 lands, which bundles the mount commands in the binary.
Scaffold correct supportFile for component testing, including adding custom `mount` command and type definitions, if using TypeScript.
We register a convinient `cy.mount` command for CT when scaffolding a new project, or migrating an existing one.
Example for a project using React and TypeScript:
```ts
// ***********************************************************
// This example support/component.ts is processed and
// loaded automatically before your test files.
//
// This is a great place to put global …
```

feat: scaffold and register cy.mount command for CT

---

cli/types/cypress.d.ts
system-tests/project-fixtures/cra/cypress.config.ts
system-tests/project-fixtures/nuxtjs2/cypress.config.ts
system-tests/project-fixtures/vue-cli/cypress.config.ts

Fixes the types for the frameworks in the Cypress `d.ts`

fix: add possible frameworks to object API config

---

npm/vue/README.md
npm/vue2/README.md
npm/vue2/docs/manual-install.md

- Follow up to https://github.com/cypress-io/cypress/pull/21026
Updates @cypress/vue and @cypress/vue2 documentation to match the changes in the previous PR.
- [N/A] Have tests been added/updated?

fix: vue2 README and other docs

---

npm/webpack-dev-server-fresh/cypress.config.ts
npm/webpack-dev-server-fresh/cypress/e2e/create-react-app.cy.ts
npm/webpack-dev-server-fresh/cypress/e2e/nuxt.cy.ts
npm/webpack-dev-server-fresh/src/helpers/nuxtHandler.ts
npm/webpack-dev-server-fresh/test/handlers/nuxtHandler.spec.ts
system-tests/project-fixtures/nuxtjs2/cypress.config.ts

- Closes [UNIFY-1210](https://cypress-io.atlassian.net/browse/UNIFY-1210)
Remove asset size warnings from nuxt webpack-dev-server
The default nuxt webpack config has `webpack.performance` configured which causes an overlay in the browser if a bundle is too large. This is unnecessary for development/testing purposes so the `performance` object is now removed from the webpack configuration.
I enabled the tests for nuxt now that `cypress/vue2` has been merged. Had to add a webpack alias to the system test to get around a module resolution issue that is specific to system-tests. The system-tests for nuxt are slower than the rest as it takes longer for webpack to recompile the files so I bumped the `defaultCommandTimeout`.
Two tests, first showing the unwanted overlay and second after the …

fix: remove asset size warnings and enable nuxt e2e tests

---

cli/__snapshots__/errors_spec.js
cli/__snapshots__/unzip_spec.js
cli/lib/errors.js
cli/lib/tasks/unzip.js
cli/test/lib/tasks/unzip_spec.js

- Closes UNIFY-1449
- Improved the error message Cypress throws when max file length is exceeded on Windows platforms and added mitigation steps.
- This is pretty easy to check - the syscall is always `realpath` and the code is always `ENOENT` when this throws.
- Could have done an even more excessive check like in [155742b](https://github.com/cypress-io/cypress/pull/21047/commits/155742b0131fd5166d61820ef87c57a3fce3f650) but I think this is not necessary.
- Also opened a docs PR for the mitigation steps: https://github.com/cypress-io/cypress-documentation/pull/4437
- And an onlink PR: https://github.com/cypress-io/cypress-services/pull/4441
- [na] …

fix(cli): show additional mitigation steps for max path length error

---

packages/driver/src/cy/commands/actions/type.ts

- Closes #21033
cy.type('{enter}') submits the form correctly after Firefox 98.
- Why was this change necessary? => `Enter` event behavior change in Firefox 98 caused `cy.type('{enter}')` to not submit the `<form>`s.
`<form>` is submitted correctly with `cy.type('{enter}')`.
- [na] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema. …

fix: cy.type('{enter}') on <input> elements submits the form correctly after Firefox 98.

---

packages/desktop-gui/cypress/integration/settings_spec.js
packages/electron/package.json
yarn.lock

- Closes #21068
* Upgraded `electron` dependency from 15.3.5 to 15.5.1 to consume fixes related to [child_process.spawn slowness](https://github.com/electron/electron/pull/33406) in macOS Big Sur and later.

chore(deps): Bumping electron dependency to 15.5.1

---

npm/webpack-dev-server-fresh/src/helpers/sourceRelativeWebpackModules.ts

This fixes a CI-only bug that will occur in https://github.com/cypress-io/cypress/pull/21080 system tests.

fix: webpack integration tests for app w webpack-dev-server-fresh

---

circle.yml
cli/scripts/post-install.js
npm/webpack-dev-server-fresh/package.json
system-tests/package.json
yarn.lock

N/A
Fixes the windows CI failing at the `node_modules` step after #20951 - seemingly just because we added `rimraf` to dependencies. Don't have time to do a full diagnosis, but it seems the symlinking + hoisting + rimraf 
Adds a `linux-workflow-filters` if we want to skip the linux workflow on WIP branches

chore: fix windows node_modules install step

---

cli/types/cypress.d.ts
cli/types/tests/cypress-tests.ts

Reverts cypress-io/cypress#20377
This merge caused unintentional type check failures ( 92d94252ca90c10d65b4d8ce4a5b6bbebed87b18 ) because I didn't update the PR with `develop` before merging :grimacing: 
Failure: https://app.circleci.com/pipelines/github/cypress-io/cypress/36421/workflows/c59bf671-cfde-4305-83b3-d46fbc95c0fc/jobs/1458838
Once this merges I'll ask the original contributor to re-open a PR against develop.

fix: revert "fix: types for Cypress.Commands.add (#20376)"

---

packages/driver/cypress/integration/e2e/multi-domain/multi_domain_validation_specs.ts
packages/runner/injection/multi-domain.js
system-tests/__snapshots__/web_security_spec.js
system-tests/projects/e2e/cypress/integration/web_security_spec.js
system-tests/test/web_security_spec.js

- Closes 
n/a
If chromeWebSecurity is set to false we can't rely on a security error to identify the correct spec bridge.
This PR adds some check to verify we are on the correct origin policy for the spec bridge.

chore: [Multi-origin] Correctly find the spec bridge if chromeWebSecurity set to false.

---

packages/scaffold-config/src/supportFile.ts
packages/scaffold-config/test/unit/supportFile.spec.ts
system-tests/projects/pristine/expected-cypress-ts-component-create-react-app-v5/cypress/support/component.ts

Remove unused `MountReturn` import from scaffolded support file
`MountReturn` isn't an exported or defined type for `@cypress/vue` so it was throwing an error on project setup. We never used it anyway since we were scaffolding:
```
declare global {
namespace Cypress {
interface Chainable {
mount: typeof mount
}
}
}
```
Since we do `typeof mount`, the return type is derived from `mount`.
The `component.ts` file no longer has an invalid import.

fix: remove MountReturn from scaffolded ct support file

---

packages/scaffold-config/src/frameworks.ts

Use correct keys for ct frameworks based on [tech-brief](https://github.com/cypress-io/tech-briefs/tree/main/briefs/ct-architectural-improvements)
We have a mismatch of the keys the dev-servers expect vs what we scaffold.
We should be able to extract a type of webpack frameworks vs vite frameworks from the `WIZARD_FRAMEWORKS` but I'm no typescript wizard, so opted to fix it for now.
CT project setup will now scaffold a config with the proper framework key.

fix: ct project setup framework keys for next and nuxt

---

packages/server/lib/plugins/child/run_require_async_child.js

Remove relative import of vite from run `packages/server/lib/plugins/child/run_require_async_child.js`

fix: remove relative vite import

---

packages/driver/cypress/integration/commands/navigation_spec.js
packages/driver/cypress/integration/e2e/multi-domain/commands/multi_domain_navigation.spec.ts
packages/driver/src/cy/commands/navigation.ts
packages/driver/src/cy/multi-domain/index.ts
packages/driver/src/cypress/error_messages.ts
packages/driver/types/internal-types.d.ts
packages/proxy/lib/http/response-middleware.ts
packages/proxy/test/unit/http/response-middleware.spec.ts
packages/server/lib/experiments.ts
packages/server/lib/remote_states.ts
packages/server/lib/server-base.ts
packages/server/lib/server-e2e.ts
packages/server/lib/socket-base.ts
packages/server/test/integration/http_requests_spec.js
packages/server/test/integration/server_spec.js
packages/server/test/unit/remote_states.spec.ts
packages/server/test/unit/socket_spec.js
system-tests/__snapshots__/runnable_execution_spec.ts.js

n/a
* Added support for`cy.visit`'ing urls that redirect back to the primary domain
* The `cy.visit` for the redirect must be placed in the context of the origin of the final redirect
* The remote state is updated with the origin of the `cy.origin` command on the `bridge:ready` message instead of the `ready:for:origin` message
* Updated error message to instruct user to place the `cy.visit` in the correct context
* Renamed `ready:for:origin` to `cross:origin:release:html` …

chore: (cross-origin) add support for redirecting back to primary

---

packages/app/src/runner/selector-playground/SelectorPlayground.vue

- Closes [UNIFY-1425](https://cypress-io.atlassian.net/browse/UNIFY-1425)
There was a bug where a `ResizeObserver` error was being thrown when opening the SelectorPlayground. It is no longer thrown.
To fix it, we used `ch` and CSS to calculate width and offset instead of using JavaScript to measure the absolute pixel width.
There is no change to functionality, this bug has never released to the wild.
Shouldn't have changed. Only changed the implementation of the styles to prevent the error

fix: stop ResizeObserver error within the SelectorPlayground from throwing error

---

packages/driver/cypress/fixtures/dom.html
packages/driver/cypress/integration/commands/assertions_spec.js
packages/driver/cypress/integration/commands/querying/querying_spec.js
packages/driver/src/cy/chai.ts
packages/driver/src/cypress/utils.ts
packages/driver/src/dom/elements/find.ts
packages/driver/src/dom/elements/utils.ts
packages/driver/src/util/escape.ts

- Closes #19116
`cy.contains` and `should('contain')` handle backslash correctly.
- Why was this change necessary? => Using backslash in `cy.contains` and `should('contain')` doesn't work.
Using backslash breaks the Sizzle selectors below:
https://github.com/cypress-io/cypress/blob/b0fe8bf0dd90d302e51b8d75782edb3b19d5af3e/packages/driver/src/cy/chai.ts#L282
https://github.com/cypress-io/cypress/blob/b0fe8bf0dd90d302e51b8d75782edb3b19d5af3e/packages/driver/src/dom/elements/find.ts#L277
For example, strings like `<asdf\` escape the quotation marks and breaks the query.
So, I escaped the quotation marks. 
But I had to solve a few more problems like:
* redundant `escapeQuotes` functions. => create `utils/escape.ts` file and move them there.
* …

fix: `cy.contains` and `should('contain')` handle backslash correctly.

---

scripts/circle-env.js
scripts/unit/circle-env-spec.js

- Closes #21284 
n/a
- Change in #21211 didn't take into account contributor PRs.
- This PR ignores the env checking if `Environment` is empty (contributor PR)
- Example of this working: https://app.circleci.com/pipelines/github/cypress-io/cypress/37199/workflows/68edd3fc-5702-473e-bcfb-31a52b7d7857/jobs/1495506?invite=true#step-111-3 …

chore: fix circle-env for contributor PRs

---

packages/app/cypress/e2e/cypress-in-cypress-component.cy.ts
packages/app/cypress/e2e/cypress-in-cypress-e2e.cy.ts
packages/app/src/runner/event-manager.ts
packages/app/src/settings/project/RecordKey.vue
packages/server/lib/project-base.ts
packages/server/lib/server-base.ts
packages/server/lib/socket-base.ts

- Closes UNIFY-1651
In component testing, when the user moves away from the spec runner (for example to the Runs page) and then goes back to the spec runner, reruns due to webpack dev server recompilations will now properly reset the state of the reporter.
The steps to recreate this issue were:
1. Launch the app and run a component test
2. Click the runs tab
3. Go back to the spec list tab
4. Run the component test from step 1 again
5. Put your computer to sleep
6. Wake the computer
7. Modify the test in step 1
8. The test re-runs but the spec totals don't reset
What ends up happening in this flow is we [set up the websocket](https://github.com/cypress-io/cypress/blob/10.0-release/packages/app/src/runner/index.ts#L38-L44) and [on …

fix: moving away from runner and disconnecting websockets stops listening for changes to webpack build

---

packages/app/cypress/e2e/cypress-in-cypress-component.cy.ts

n/a
There was a mismerge in 10.0 that caused beforeEach's to not be run in cypress-in-cypress-component. This fixes that issue

chore: fix build due to mis merge

---

packages/app/cypress/e2e/settings.cy.ts
packages/frontend-shared/src/graphql/urqlClient.ts

- Closes UNIFY-1652
When logging out, the "Record Key" section, and any other stale cloud data will no longer be visible.
When logging out, we want to clear out any remote data that might have been cached on the client. We can do this by invalidating the `Query` field for the cache using [`cache.invalidate`](https://formidable.com/open-source/urql/docs/api/graphcache/#invalidate), on logout which will result in refetching all data with the latest info from the electron server.

fix: clear remote data by marking all query data as stale on logout

---

packages/driver/cypress/fixtures/dom.html
packages/driver/cypress/fixtures/form.html
packages/driver/cypress/integration/commands/actions/type_special_chars_spec.js
packages/driver/src/cy/commands/actions/type.ts

- Closes #21163 
Submit buttons can be outside of the form for implicit submission
Implicit submit wasn't working when the submit button wasn't nested within the form
Implicit submit with the enter key works when the submit button is outside of the form, but associated with a form attribute …

fix: Allow submit button to be outside of the form for implicit submission

---

circle.yml

- Related with #21304
- Closes #21318
N/A. It's an internal CI change. 
For some reason, a test in `settings_spec.js` of `desktop-gui` CI failed on all recent PRs of mine (#21286, #21285, #21197, #21283). So, I tested it with #21304 that it happens with an empty commit. 
I investigated this failure and learned that it's a flaky test and run 7 times ([5 passed, 2 failed](https://app.circleci.com/pipelines/github/cypress-io/cypress/37258/workflows/fa6c4589-3ccc-4dc6-9761-56419cd602a5/jobs/1498481/parallel-runs/0?filterBy=FAILED)). Because each container of desktop-gui is running all of the desktop-gui tests. 
It was the reason why `desktop-gui` is always super late to finish.
And it can cause unwanted flakiness.
N/A
* I distributed tests to the containers. Currently, each container runs 3 …

chore: Distribute tests to desktop-gui containers. Make `desktop-gui` tests faster!

---

packages/driver/cypress/integration/commands/assertions_spec.js

- Related with [this comment](https://github.com/cypress-io/cypress/pull/20704#discussion_r830722608)
N/A. It's an internal house keeping. This PR re-organizes tests that are organized in the wrong way.
- Why was this change necessary? => Tests are organized in the wrong way.
N/A
- [na] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.sc …

chore: Re-organize tests in assertions_spec.js

---

packages/driver/cypress/integration/cypress/proxy-logging_spec.ts
packages/driver/src/cypress/proxy-logging.ts

- Closes #21361 
XHR calls will now properly display the response body in the command log
When the proxy gets the close event for the response, we send the `response:received` event to the client. There is a race condition where this might reach the client before the XHR readystate has been updated on the client. If this happens, the xhr that gets attached to the log will not have a response body yet. To fix this, we will listen to the `onload` event of the xhr call if the xhr call hasn't completed and delay updating the proxy logging response until then.
n/a …

fix: ensure that proxy logs are updated after the xhr has actually completed

---

packages/scaffold-config/src/detect.ts

- Closes N/A
N/A
There's an incorrect check around `fs.existsSync` patched on `fs-extra` that tells us we can't use it. This is incorrect, we actually shouldn't be using `readFileSync`, as this is what opens a file descriptor. We can address that change in a separate PR.

fix: remove fs sync warning

---

packages/driver/cypress/integration/commands/files_spec.js

N/A
This test was asserting on the exact number of command retries that were occurring prior to the command timeout being reached. This exact count has the potential to be non-deterministic based on the execution time of the command within our defined timeout (overridden here to 50ms).
I updated the test to validate that *at least one* retry has occurred, which validates that the retry logic is being executing as we expect without relying on a consistent execution time.

test: Updating readFile error test assertions that rely on consistent execution time

---

packages/graphql/schemas/cloud.graphql
packages/graphql/schemas/schema.graphql
packages/graphql/test/stubCloudTypes.ts

n/a
Need to update subbed types now that cloud schema has changed
https://github.com/cypress-io/cypress-services/pull/4515
n/a

chore: update stubbed cloud types

---

packages/app/cypress/e2e/sidebar_navigation.cy.ts

- Closes https://cypress-io.atlassian.net/browse/UNIFY-1718
No changes.
The flaky test is checking that the mutation to store the width of the InlineSpecsList is called with a specific width value. 
To check the value, the test expects at a certain position of the right hand edge of the reporter, the reporter takes up the full space between the nav and the AUT. 
Previously, it used to click the "toggle specs list" button to close the specs list, before doing the test. Now that the specs list is closed by default, this test is in the weird situation of only passing when that click flakes, which is a known issue (see comment [here](https://github.com/cypress-io/cypress/blob/c110aa19412ca42c6f83fd87acca81729f955af9/packages/reporter/cypress/e2e/header.cy.ts#L44)), we often use `{ force: true …

test: remove flaky click from navigation spec

---

packages/config/package.json

- Closes N/A
As mentioned here, https://github.com/cypress-io/cypress/pull/21456#pullrequestreview-974482792, The `yarn clean` command was unintentionally deleting some of the test fixtures in the `config` package. I modified the glob pattern to not delete those.

fix: do not nuke babel fixtures

---

npm/react/plugins/next/findNextWebpackConfig.js

- Closes #19382
Add support for Next v12.1.6
The API for  [getNextJsBaseWebpackConfig](https://github.com/vercel/next.js/commit/0bf6655f1c9438591ca4cca8c34065ab164d9cc0) has changed in version 12.1.6 which was causing the resolved webpack config to not be the `client` webpack configuration. Small tweak passing in both options allows support for the new change and backwards compatibility.
CT testing works with latest version on Next
I have a clone of this PR targeting 10.0-release that has e2e tests covering this new version of Next.
https://github.com/cypress-io/cypress/pull/21515
- [na] Has a PR for user-facing changes been …

fix: add support for Next.js v12.1.6

---

packages/data-context/src/sources/MigrationDataSource.ts
packages/frontend-shared/cypress/e2e/e2ePluginSetup.ts
packages/graphql/src/schemaTypes/objectTypes/gql-Migration.ts
packages/launchpad/cypress/e2e/choose-a-browser.cy.ts
packages/launchpad/cypress/e2e/migration.cy.ts
packages/launchpad/cypress/e2e/open-mode.cy.ts
packages/launchpad/src/setup/TestingTypeCards.vue

- Closes UNIFY-1740
A bit of cleanup from flake seen in tests for #21560, in `migration.cy.ts` & `project-setup.cy.ts` also we don't want to be hitting the on link and returning for `videoEmbedHtml` unless we are currently migrating.

refactor: reduce flake in launchpad tests, return null for videoEmbedHtml if not needed

---

npm/webpack-dev-server/cypress/e2e/react.cy.ts
npm/webpack-dev-server/cypress/e2e/webpack-dev-server.cy.ts
npm/webpack-dev-server/package.json
npm/webpack-dev-server/src/CypressCTWebpackPlugin.ts
npm/webpack-dev-server/src/devServer.ts
npm/webpack-dev-server/test/devServer-e2e.spec.ts

- Closes UNIFY-1697
There is a race condition between our webpack compilation and our emission of the `dev-server:specs:changed` event. When a spec file is removed from the file system, we attempt to compile prior to updating our internal `files` property within the plugin, causing the loader to reference files that no longer exist.
I updated the `CypressCTWebpackPlugin` to filter out files in state that no longer exist on the file system during the beforeCompile phase. This prevents both the initial error from being presented at file removal time and allows the file to be immediately executed when re-created.
https://user-images.githubusercontent.com/1711637/169138230-2e4a3493-0726-4a1c-9eb1-2074fadc9aef.mov
- [n/a] Has the original issue (or this PR, if no issue exists) been tagged with …

fix: Ensuring spec file presence prior to webpack-dev-server compilation

---

packages/launchpad/src/setup/EnvironmentSetup.cy.tsx
packages/launchpad/src/setup/EnvironmentSetup.vue

- Closes https://cypress-io.atlassian.net/browse/UNIFY-1805
Sort the frameworks in a more structured manner on the select framework screen.
Put in alphabetical order.
Open to other ways to order the list, just threw this together since the current list is just in an arbitrary order.

chore: sort the frameworks select dropdown in a more logical way

---

circle.yml
packages/app/cypress/e2e/specs.cy.ts
packages/data-context/src/actions/ProjectActions.ts
packages/data-context/src/codegen/spec-options.ts
packages/data-context/test/unit/codegen/spec-options.spec.ts

- Closes UNIFY-1787
When we process the proposed file name for a new spec created in the app, we try to find a known spec file extension (`.cy`, `.spec`, `_spec`, etc.) within in. We do this so that if the file name as provided is found to be a duplicate, we can update the name without mangling this extension, which would in all likelihood result in the file not matching the spec pattern. 
As reported in the JIRA issue, the file name would be generated incorrectly if it didn't end with one of our expected spec extensions. This was due to our falling back to the _file_ extension in the absence of an expected spec extension, inadvertently doubling the file extension in the resulting file name. I corrected this by instead falling back to nothing and letting the file parsing continue like …

fix: Successfully create new specs files that do not have a known extension

---

CONTRIBUTING.md
guides/README.md
guides/debug-logs.md
packages/config/src/browser.ts
packages/data-context/src/data/ProjectConfigIpc.ts
packages/data-context/src/sources/CloudDataSource.ts
packages/data-context/src/sources/GitDataSource.ts
packages/data-context/src/sources/GraphQLDataSource.ts
packages/data-context/src/sources/ProjectDataSource.ts
packages/data-context/src/sources/VersionsDataSource.ts
packages/launcher/README.md
packages/launcher/lib/browsers.ts
packages/launcher/lib/darwin/index.ts
packages/launcher/lib/darwin/util.ts
packages/launcher/lib/detect.ts
packages/launcher/lib/linux/index.ts
packages/launcher/lib/log.ts
packages/launcher/lib/windows/index.ts
packages/server/lib/browsers/firefox.ts
packages/server/lib/util/editors.ts
packages/server/lib/util/file.js

If we want to consider this user-facing:
* Removed some verbose `DEBUG=cypress:*` lines and moved others to the `DEBUG=cypress-verbose:*` namespace.
- I noticed that we have added a lot of debug lines to our already-bloated `DEBUG` namespaces.
- With 10.0, there are going to be a lot of changes and potentially a lot of bug reports, so it's important that we take the opportunity to clean up `DEBUG` and make it easier to read and more useful before we start getting reports with `DEBUG` logs in them.
- This PR:
- Documents the way that `debug` namespaces are handled in `cypress`. Previously, the way we named debug namespaces was not documented.
- Removes or moves to `cypress-verbose` a lot of `debug` statements, some added in 10.0, some existing in 9.x
- Of note, `packages/launcher` is now …

chore: clean up `debug` statements in preparation for 10.0 release, add `debug` docs

---

packages/launchpad/cypress/e2e/choose-a-browser.cy.ts

na
Some improper stubbing in `choose-a-browser.cy.ts` was causing `open-mode.cy.ts` to fail if it happened to run first in CI.
https://app.circleci.com/pipelines/github/cypress-io/cypress/38605/workflows/16edf69c-4b38-4c59-977c-348ef7501456/jobs/1566814/parallel-runs/1
I tested this by lifting all the code from `choose-a-browser.cy.ts` and pasting it at the top of `open-mode.cy.ts`. The test was failing every time I did this.
https://user-images.githubusercontent.com/25158820/170370246-6a9f42a5-3efe-462a-b255-2987cbdb7c98.mov
na

test: fix flaky launchpad test

---

circle.yml
packages/reporter/cypress.config.ts
packages/reporter/cypress/support/component-index.html
packages/reporter/cypress/support/component.ts
packages/reporter/package.json
packages/reporter/src/hooks/hooks.cy.tsx
packages/reporter/src/hooks/hooks.scss
packages/reporter/src/runnables/runnables.scss
packages/reporter/src/test/test.cy.tsx
packages/ui-components/cypress/support/customPercyCommand.ts

- Closes https://cypress-io.atlassian.net/browse/UNIFY-1737
Hovering over test names now highlights the row to indicate clickability. Unifies styles for hovering over test name / hook name / command name.
Adds first component tests (primarily percy snapshots) to `packages/reporter`.
1. After checking out branch, use `yarn dev` to recompile reporter css, otherwise you won't see the updates.
2. `cypress open` any project.
3. Select any configured testing type, launch any browser, run any spec.
4. Mouse over the command list - notice rows highlight under the mouse.
Old behavior:
New behavior:
- [n/a] Has a PR for user-facing changes been opened in …

fix: Add hover states for test titles in reporter

---

packages/data-context/src/util/autoBindDebug.ts

- Closes N/A
N/A
Follow re: #21621, makes `cypress*` a bit more tolerable, by moving the `autoBindDebug` helper which is only meant for advanced race-condition debugging to `trace-cypress` debug namespace

chore: rename DEBUG cypress-trace -> trace-cypress

---

npm/cypress-schematic/package.json

Breaking change for `@cypress/schematic` to support scaffolding and building Cypress 10.x projects
na
I tested this by making the commits on master and running `node ./scripts/npm-release.js`. The output shows a breaking change for `@cypress/schematic`.
na

chore: enable @cypress/schematic for npm publishing

---

packages/data-context/src/actions/DevActions.ts
packages/data-context/src/data/ProjectConfigManager.ts
packages/data-context/src/sources/ProjectDataSource.ts
packages/data-context/src/sources/migration/codegen.ts
packages/data-context/test/unit/sources/ProjectDataSource.spec.ts

- Closes #22002
Consistently handle EPERM issues in chokidar watching

fix: #22002 choikdar ignore EPERM issues

---

packages/config/package.json
packages/config/src/ast-utils/addToCypressConfig.ts
packages/config/src/index.ts
packages/config/test/ast-utils/addToCypressConfig.spec.ts
packages/data-context/src/actions/WizardActions.ts
packages/data-context/src/sources/migration/codegen.ts
packages/launchpad/cypress.config.ts
packages/launchpad/cypress/e2e/scaffold-project.cy.ts
packages/launchpad/cypress/tasks/uninstallDependenciesInScaffoldedProject.ts

- Closes https://github.com/cypress-io/cypress/issues/21999
Cypress will generate a correct config file when using the directly downloaded version on a fresh project.
Previously, the config file would contain `const { defineConfig } = require("cypress");` or similar, even though cypress was not available from the project root. This is no longer the case; if the user can't `require('cypress')`, then we omit `defineConfig`.
1. Create an empty directory, `foobar`, or use an existing project without cypress configured.
2. `yarn cypress:open --project ../foobar`
3. Select e2e testing and continue through.
In 10.0.0, you get `Error: Cannot find module 'cypress'` after a few clicks. With this branch, you do not!
- [n/a] Has a PR for user-facing changes been opened in …

fix: Don't include defineConfig if cypress isn't available from project root

---

packages/app/src/runs/RunCard.vue

- Closes #21931
Visiting the Runs page will no longer cause list styles to look incorrect in the Spec Runner page and Header.
**Desired Behavior**
In this situation, Cypress should not show extra dots in the Runner UI that don’t belong there.
This is caused by styles leaking from this component: packages/app/src/runs/RunCard.vue and the fix is a one-line change, to add a `scoped` attribute to the `style` tag [here](https://github.com/cypress-io/cypress/blob/8d79472b7d569094c94836ecb6cd527ee5823111/packages/app/src/runs/RunCard.vue#L133).
Before checking out this branch:
1. Open the cypress app
1. Visit the Runs page
1. Visit the Specs List
1. Open a Spec
1. See bad styles
1. Refresh
1. See good styles
1. Visit the Runs page and then visit a spec again - the bad styles return as soon as …

fix: prevent RunCard styles from leaking outside of component

---

packages/app/src/runner/SpecRunnerHeaderOpenMode.vue
packages/app/src/runner/automation/AutomationMissing.vue
packages/frontend-shared/src/gql-components/HeaderBarContent.cy.tsx
packages/frontend-shared/src/gql-components/topnav/TopNavList.vue

- Closes #22032
Allow browsers list in top nav to be scrollable
We didn't have any scroll css on the browsers list in the top nav. This PR fixes this for all use cases of the `VerticalBrowserListItems.vue`.
I've added a test to verify it can scroll, and also added a missing percy snapshot for the unsupported browser tooltip
You can run the `renders with functional browser menu when show-browsers prop is true` from `HeaderBarContent.cy.tsx`. It has a long list of browsers and there is no scrolling on the element other than the full page scroll.
Before:
After: …

fix: top nav browsers list scroll

---

packages/frontend-shared/src/locales/en-US.json

- Closes #21798 
Capitalize the "C" of "cypress" in migration text.
- Why was this change necessary?
Brand consistency.
Before:
After:

fix: #21798 cypress should be capitalized in Step 3 of migration text

---

packages/data-context/src/sources/VersionsDataSource.ts
packages/data-context/test/unit/sources/VersionsDataSource.spec.ts

- Closes #22110 
The GUI will continue to run if getting machine-id fails.
The underlying npm package `node-machine-id` requires admin rights on Windows to get the machine id. This is causing the Cypress GUI to crash for Windows users that do not have administrator rights. The fix will allow for the failure as the ID is optional.
To test this it requires a Windows machine and a non-admin user. Perhaps also an extra setting to prevent the user from running `%windir%\System32\REG.exe`. Running Cypress without this change will cause the application to crash right after selecting the type of test to perform, and after the change the application will run as normal.
The GUI will continue to run if getting machine-id fails. …

fix: prevent Cypress from crashing when getting machine-id fails

---

packages/app/package.json
packages/launchpad/package.json

- Closes https://github.com/cypress-io/cypress/issues/21735
Do not ship unused source code in app.
Make binary slightly smaller by not including the source code for `app` and `launchpad` in the binary.
I am on linux.
1. `yarn binary-build`
2. Pick any option for version
3. Wait for build 
4. `ls /tmp/cypress-build/linux/build/linux-unpacked/resources/app/packages/launchpad`
5. Observe we only ship `dist` - not `src`
6. If you want to try it run `./tmp/cypress-build/linux/build/linux-unpacked/Cypress`
It hasn't.

chore: do not ship source for app and launchpad in binary

---

packages/app/src/specs/RowDirectory.vue
packages/app/src/specs/SpecItem.vue
packages/app/src/specs/SpecsList.vue
packages/app/src/specs/SpecsListRowItem.cy.tsx
packages/app/src/specs/SpecsListRowItem.vue

* Move click-sensitive row action wrapper to surround entire row
* Add styles to highlight spec icon on hocus to match Figma
* Small text highlight style change to match Figma
- Closes #21783 
* Entire row in Specs List will respond to clicks
* Styling updates to make current row in Specs List more obvious
[Figma design](https://www.figma.com/proto/PAOozuCxtfetqP8fUVvg0y/branch/xqSbhaPZdYYMax8LMOi8UP/Cypress-App?page-id=0%3A1&node-id=3799%3A60922&viewport=-7970%2C-3439%2C0.5&scaling=scale-down&starting-point-node-id=427%3A3959)
According to #21783 this was brought up a lot during v10 feedback testing. Current behavior only performs the row's action (toggle expansion for directories or navigate to spec for Spec rows) if you click directly on the row title item. This makes the entire row …

fix: Make spec row clickable across entire width

---

circle.yml

- Closes 
- Env checking added in #21211 began to fail on Windows-build jobs due to missing CIRCLE_INTERNAL_CONFIG: https://app.circleci.com/pipelines/github/cypress-io/cypress/39166/workflows/0c0a6261-bc78-4748-87aa-4512f2e66ea2/jobs/1597828
- I tried SSHing into a Circle Windows box but could not find another source for this info
- This PR disables the check on Windows
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/type …

chore: skip windows canary check

---

packages/app/src/specs/RunStatusDots.vue
packages/app/src/specs/SpecsList.vue
packages/frontend-shared/src/components/ResultCounts.vue
packages/frontend-shared/src/components/Tooltip.vue

Fixes styling issues in App-Cloud integration work:
1. Keep SpecList columns aligned with header columns when scrollable/non-scrollable
2. Remove hover coloration in tooltip
3. Align tooltip arrow
https://user-images.githubusercontent.com/11482842/172929975-7f57b1ef-e61e-4528-af03-99eb99294e54.mov

fix: styling fixes around for App-Cloud integration

---

packages/app/src/specs/LastUpdatedHeader.vue
packages/app/src/specs/RunStatusDots.vue
packages/app/src/specs/SpecHeaderCloudDataTooltip.vue
packages/app/src/specs/SpecsList.vue
packages/frontend-shared/src/components/Tooltip.vue
packages/frontend-shared/src/composables/useVirtualList.ts

* Fix watcher to prevent Specs Explorer from scrolling back to top when row data is updated
* Small fixes to reduce likelihood of Latest Runs tooltip from not cleaning up

fix: SpecsList scrolling performance fixes

---

cli/types/cypress.d.ts
npm/create-cypress-tests/package.json
npm/mount-utils/package.json
npm/react/package.json
npm/vite-dev-server/cypress/e2e/react.cy.ts
npm/vite-dev-server/cypress/e2e/vite-dev-server.cy.ts
npm/vite-dev-server/package.json
npm/vue/package.json
npm/vue2/package.json
npm/webpack-dev-server/CHANGELOG.md
npm/webpack-dev-server/cypress/e2e/create-react-app.cy.ts
npm/webpack-dev-server/cypress/e2e/next.cy.ts
npm/webpack-dev-server/cypress/e2e/nuxt.cy.ts
npm/webpack-dev-server/cypress/e2e/react.cy.ts
npm/webpack-dev-server/cypress/e2e/vue-cli.cy.ts
npm/webpack-dev-server/cypress/e2e/webpack-dev-server.cy.ts
npm/webpack-dev-server/package.json
npm/webpack-dev-server/src/helpers/nextHandler.ts
npm/webpack-dev-server/src/helpers/sourceRelativeWebpackModules.ts
system-tests/project-fixtures/react/cypress-vite-dev-server-function.config.ts
system-tests/project-fixtures/react/cypress-vite-port-in-use.config.ts
system-tests/project-fixtures/react/cypress-vite.config.ts
system-tests/project-fixtures/react/cypress-webpack-dev-server-function.config.ts
system-tests/project-fixtures/react/vite.config.js
system-tests/projects/vite2.9.1-react/package.json
system-tests/projects/vite2.9.1-react/yarn.lock
system-tests/projects/webpack5_wds4-react/package.json
system-tests/projects/webpack5_wds4-react/yarn.lock

- Closes https://github.com/cypress-io/cypress/issues/21944
Publish Cypress v10 compatible npm packages
Removes `"private": true` from the npm packages that we had disabled and fixes a few bugs in our implementation that would have caused issues. Notable changes:
- Replacing the require path for `@cypress/webpack-batteries-included-preprocessor` in webpack-dev-server from `__dirname` to `cypressBinaryRoot`. Relying on `__dirname` only works when sourcing from within the binary (or sourcing from the packages installed node_modules).
- Revert `find-up` to 5.0.0 as >6.0.0 is ESM only. We were relying on `local-pkg` to import it which uses `require`. Removed both packages.
- Restoed webpack-dev-server changelog that got removed in a previous merge
- Fixed types for when using the dev-server …

chore: prep npm packages for use with Cypress v10

---

packages/app/src/specs/SpecsList.cy.tsx
packages/frontend-shared/cypress/support/mock-graphql/mountFragment.ts

- Fixes component testing failures in `SpecsList.cy.tsx`

fix: Allow GQL variable definitions in `mountFragment`

---

packages/app/src/specs/SpecsList.vue
packages/app/src/specs/SpecsListRowItem.vue

- Closes 
Changes the Spec Explorer column sizes and adds padding to the rightmost column for Dashboard Integration data so the data is not flush with the scrollbar.

feat: Column width updates for latest runs and average duration work

---

packages/app/src/specs/AverageDuration.cy.tsx
packages/app/src/specs/LastUpdatedHeader.cy.tsx
packages/app/src/specs/RunStatusDots.vue
packages/app/src/specs/SpecHeaderCloudDataTooltip.cy.tsx
packages/app/src/specs/SpecHeaderCloudDataTooltip.vue
packages/app/src/specs/SpecListGitInfo.cy.tsx
packages/app/src/specs/SpecListGitInfo.vue
packages/app/src/specs/SpecRunSummary.cy.tsx
packages/app/src/specs/SpecRunSummary.vue
packages/app/src/specs/SpecsList.cy.tsx
packages/app/src/specs/SpecsList.vue
packages/frontend-shared/cypress/support/mock-graphql/clientTestUrqlClient.ts
packages/frontend-shared/src/components/ResultCounts.cy.tsx

* Adding component tests to cover new components and behaviors (more to come)
* Fix small issue disguising graphql resolver issues during component tests
* Styling fix for ACI latest runs tooltip so it points to the latest run dot

fix: Add component tests for ACI latest specs

---

packages/app/src/specs/DirectoryItem.vue
packages/app/src/specs/HighlightedText.vue
packages/app/src/specs/RowDirectory.vue
packages/app/src/specs/SpecFileItem.cy.tsx
packages/app/src/specs/SpecFileItem.vue
packages/app/src/specs/SpecItem.cy.tsx
packages/app/src/specs/SpecItem.vue

- Closes #21895
Spec directories and file names are now truncated if they exceed a certain width
In the spec list, directory paths and file names were wrapping to show the entire value rather than truncating when they overflowed max width. This lead to long file/dir names clogging up the UI and overflowing the set height for the row.
This change affects the spec lists for e2e and component testing. See the related issue for more details
- Open the spec list for an application (e2e or ct) and create a directory and/or spec file with a long name (shrink window width if necessary)
- Verify that when the file/dir name is longer than the width of the spec column in the table, the name is truncated
- Verify that you can view the full name of the file/dir by hovering over the truncated text …

fix: Truncate spec directories and file names instead of wrapping

---

packages/frontend-shared/src/locales/en-US.json

- Closes #21926
N/A
Make the text more generic, as to cover all the cases where we automatically change specs:
- rename
- move
- rename and move
Just open launchpad to any Cypress 9 project and have a look.
Improved language in migration UI to be more clear about intended and recommended behavior.
- [na] Have tests been added/updated? **It's just a json file, so no, there isn't any to update**

chore: make spec migration screen text more generic

---

circle.yml
cli/scripts/build.js

- Closes #22147
Fixed an issue causing a "nohoist config is ignored" warning when installing `cypress` with yarn.
Install latest prerelease comment on this branch on Linux, note there is no warning.

fix(cli): don't include workspaces.nohoist in public NPM package

---

packages/app/src/specs/SpecsListRowItem.vue

Increase rendering speed of items in spec-list
When quickly scrolling the spec list, there is a flash of un-rendered content due to the the virtual list having to re-render so many elements. This only became an issue with the recent ACI work that added more components to each row.
This fix defers the rendering of many of the columns such that the row + filename is given priority, leading to a more responsive feel to the table. It doesn't fix the issue entirely as fast scrolls can still cause a white flash, but it does improve the experience.
This PR __DOES NOT__ fix the scroll jank on Chrome. That is an issue in [Chrome v102](https://github.com/petyosi/react-virtuoso/issues/675) that has been fixed in v103. The scroll behavior works find in Firefox + Electron
Check out …

fix: make virtual-list loading more efficient

---

packages/app/cypress/e2e/settings.cy.ts
packages/app/cypress/e2e/specs_list_latest_runs.cy.ts
packages/app/src/specs/SpecHeaderCloudDataTooltip.vue
packages/frontend-shared/src/locales/en-US.json

feat: Update ACI tooltip copy

---

packages/app/cypress/e2e/specs_list_latest_runs.cy.ts
packages/app/src/specs/LastUpdatedHeader.vue
packages/app/src/specs/RunStatusDots.vue
packages/app/src/specs/SpecHeaderCloudDataTooltip.vue

* Average Runs data persistence
Update GQL query to work around issue that caused data to not hydrate properly when moving back from the Runs page
* Tooltip behavior
Minor tooltip tweaks to improve behavior when moving rapidly between SpecList headers
1. Load project with recorded run(s)
2. Open Specs List, observe latest runs data load
3. Navigate to the Cloud Runs page then back to Specs
4. Observe previously-loaded latest runs data is still present
* Without this fix, latest runs appear unloaded and do not trigger re-load
5. Move mouse rapidly between Specs List headers, it should no longer be possible to have multiple header tooltips remain open

fix: Address GQL runs data being lost after navigation

---

packages/driver/cypress/support/utils.js

No user facing changes
Many of the driver tests are watching `'log:changed'` events, then filtering the result with `findCrossOriginLogs`. While we'd expect this to be deterministic, in practice it doesn't seem to be, resulting in very flaky tests.
This PR `sort()`s the results, and removes this source of flake.

fix: Sort results in findCrossOriginLogs test helper to deterministic

---

npm/webpack-dev-server/test/.mocharc.js

No user facing changes.
The system tests in `sourceRelativeWebpackModules.spec.ts` have been extremely flaky the past few days, to the point where it's more "consistent failure" than it is "flake".
It seems to be simply a timeout issue - the 10s we've allocated aren't enough to successfully yarn install all the dependencies for `webpack5_wds4-react` and similar system test projects.
While I'd very much like to rewrite these tests so as not to take so long, there's no quick solution here and it would probably involve changing how we install system test dependencies entirely (or mocking them out not to actually install), something beyond the scope of my efforts at the moment.
Therefore, timeout increase. Green builds are super important.
- [n/a] Has the original issue (or this PR, if no …

fix: Increase timeout for npm-webpack-dev-server tests

---

packages/app/cypress/e2e/reporter_header.cy.ts
packages/app/cypress/e2e/runs.cy.ts
packages/app/cypress/e2e/specs_list_latest_runs.cy.ts
packages/app/cypress/e2e/subscriptions/createCloudOrgModal-subscription.cy.ts
packages/app/cypress/e2e/support/execute-spec.ts
packages/app/src/runs/RunsError.spec.tsx
packages/data-context/src/DataContext.ts
packages/data-context/src/actions/AuthActions.ts
packages/data-context/src/actions/DataEmitterActions.ts
packages/data-context/src/sources/CloudDataSource.ts
packages/data-context/src/sources/GraphQLDataSource.ts
packages/data-context/src/sources/RemotePollingDataSource.ts
packages/data-context/src/sources/RemoteRequestDataSource.ts
packages/data-context/src/util/DocumentNodeBuilder.ts
packages/data-context/test/unit/sources/CloudDataSource.spec.ts
packages/data-context/test/unit/util/DocumentNodeBuilder.spec.ts
packages/frontend-shared/cypress/e2e/e2ePluginSetup.ts
packages/frontend-shared/src/graphql/urqlClient.ts
packages/frontend-shared/src/graphql/urqlGlobalSubscriptions.ts
packages/graphql/schemas/schema.graphql
packages/graphql/src/schemaTypes/objectTypes/gql-Subscription.ts
packages/graphql/src/stitching/remoteSchemaWrapped.ts
packages/server/lib/saved_state.ts

Related to #21250
Correctly fixes tests failing due to the introduction of the new queries on the specs page, properly handles an infinite loop that was occurring when an incomplete response was sent back for a `stale` fetch result. This would cause an infinite re-fetch loop while the server was looking to fulfill the stale value. Instead, now if we detect this situation we clear the urql cache in both the electron process and the client.
Existing tests should be passing with only minor, expected modifications

fix: remove ctx.cloud.reset in tests, handle infinite loop in stale results

---

packages/app/src/specs/RunStatusDots.cy.tsx
packages/app/src/specs/RunStatusDots.vue
packages/app/src/specs/SpecRunSummary.cy.tsx
packages/app/src/specs/SpecRunSummary.vue
packages/app/src/specs/SpecsList.vue
packages/frontend-shared/cypress/support/mock-graphql/fakeCloudSpecRun.ts
packages/frontend-shared/src/assets/icons/queued-solid_x16.svg
packages/graphql/schemas/cloud.graphql
packages/graphql/schemas/schema.graphql
packages/graphql/test/stubCloudTypes.ts

* Update GQL schema
* Add handling for `UNCLAIMED` status
* Only show loading indicator in Latest Runs section on initial fetch
1. Open project and log in to cloud
2. Observe "latest run" data displays loading indicator on initial load of Specs Explorer
3. Start recording of project run in another terminal
4. Every 30 seconds app should poll for updated "latest run" data, observe that loading indicator is not shown during refetches
5. Mouse over the currently-running spec's "latest run" column, observe tooltip with "Queued" status
https://user-images.githubusercontent.com/11482842/175427837-387cd142-0926-4ce4-8647-fe8125e70d2f.mov
- [na] Has a PR for user-facing …

feat: Support "Queued" latest run status

---

packages/app/src/specs/SpecHeaderCloudDataTooltip.cy.tsx
packages/app/src/specs/SpecHeaderCloudDataTooltip.vue

* Fix state tracking so that button properly updates after requesting access
* Refactor improper cross-component GQL doc use
Implementation adapted from `RunsErrorRenderer.vue`
1. Open cypress app and log into dashboard
2. Open a project that is cloud-connected but that you do not have access to
3. Mouse over "latest runs" header, observe the "Request Access" button
4. Click button, observe button updates to "Request Sent"
5. Close and reopen tooltip, observe button still reports "Request Sent"
https://user-images.githubusercontent.com/11482842/175435214-77c19733-3a29-4642-9f85-c43a203cd973.mov …

fix: Update "Request Access" button state after requesting access (ACI)

---

packages/frontend-shared/src/gql-components/HeaderBarContent.vue
packages/launchpad/cypress/e2e/global-mode.cy.ts
system-tests/projects/todos/cypress/support/component-index.html

This PR addresses the consistently failing spec for the launchpad's global mode tests in Windows CI. See comments for details.
* Open up the launchpad, navigate to a project, and select a testing type
* Navigate back to the testing type selection
* Select a testing type again (the same one or different, doesn't matter)
* Inspect the project name link in the nav breadcrumbs and make sure there is no `role` attribute set on it (we want the implicit role on the `a` tag to take priority in this case)
- [n/a] Have API changes been …

test: Addressing launchpad test flake in Windows

---

circle.yml

N/A
With https://github.com/cypress-io/cypress/commit/9101a9066c44fa2bb5bcbca64351c30cb5457cae, we added a dependency on a new context to all the `run-new-ui-tests` jobs. Without this context set, we'd fall into the external contributor build logic, which seems like it might be the source of a few new failures we're seeing.
Gotta watch the build

chore: Adding record key context for internal ui jobs

---

circle.yml
packages/launchpad/cypress/e2e/global-mode.cy.ts

Changes include:
* Tweaked a test in global-mode.cy.ts to avoid clicking a link before it was enabled
* Updated the circle config to provide appropriate context vars to the windows ui (app/launchpad) builds. Shoutout to @ZachJW34 for noticing that I missed these earlier!
The app/launchpad tests in windows should be green now, I think this covers the recent flake we've seen. So PRs should be happier. The kitchensink build that executes in develop is still failing though.

test: Addressing yet more flaky windows tests

---

circle.yml
packages/data-context/test/unit/sources/WizardDataSource.spec.ts
packages/scaffold-config/src/dependencies.ts
packages/scaffold-config/src/frameworks.ts

- Closes #22371 
React DOM has been explicitly named as a required dependency for component testing in React applications
For component testing in applications that use React, we require both `react` and `react-dom` libraries, but only `react` is listed as a required dependency, so the wizard will allow users to continue without notifying them if their project doesn't have `react-dom` as a dependency, and then when they try to run a test, it will fail because `react-dom` is required.
This PR adds `react-dom` as a required dependency for React applications using Vite and ones created with Create React App so that users know to install `react-dom` in their project if it wasn't already installed.
Follow these steps with a Create React App app and a React app using Vite:
- Create a new …

fix: Require react-dom as a dependency for React projects

---

npm/cypress-schematic/sandbox12/angular.json
npm/cypress-schematic/sandbox12/package.json

na
There is an issue with @types/eslint causing the cypress-schematic tests to fail. Pinning the version resolves this for now.
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/61032
`yarn workspace @cypress/schematic launch:test12` now passes
na

fix: cypress-schematic ci issue with @types/eslint

---

cli/lib/exec/open.js
cli/lib/exec/spawn.js
cli/test/lib/exec/open_spec.js
cli/test/lib/exec/spawn_spec.js

- Closes #21615
Removes "Class WebSwapCGLLayer is implemented in both" terminal log when opening Cypress
This warning is benign (at least, it hasn't been confirmed to be causing any issues with Cypress) and confuses users who see this log in their terminal. We are now filtering this error.
Note that this is only an issue for Electron v18 and MacOS v12. I was on MacOS v11 and never saw this log until I updated.
Cypress open was forcing `stdio: 'inherit'` for the child process which bypasses all of our stdout filtering. I did not see any difference in terminal output after the removal of this option. We are piping all of the output of the child process so it makes sense that we wouldn't see any difference here. Since we are no longer forcing `stdio: 'inherit'`, we will now be filtering the …

fix: ignore WebSwapCGLLayer warning

---

packages/driver/src/cy/commands/screenshot.ts
packages/driver/src/dom/blackout.ts
system-tests/__snapshots__/screenshot_viewport_capture_spec.js
system-tests/projects/e2e/cypress/e2e/screenshot_viewport_capture.cy.js
system-tests/projects/e2e/cypress/e2e/screenshots.cy.js
system-tests/projects/e2e/cypress/fixtures/screenshot-blackout.html

- Closes #22173
Fixes a regression in 9.6 where absolute elements that are blacked out with `cy.screenshot` are positioned off the container element and not the body.
This PR attempts to fix a regression when screenshots were refactored for `cy.origin` in #20949 where element dimensions are calculated from the screenshotted element. This works in most cases, but causes some trouble with absolute elements. To fix this, since we no longer have access to the `AutIframe` class, is to reference the body to calculate dimensions for elements. 
See changes to the `screenshot_viewport_capture_spec.js`

fix: absolute positioning element blackouts in cy.screenshot

---

cli/types/cypress.d.ts
packages/server/lib/server-base.ts

Fix the hosts typing in cypress typings file
- Closes 
n/a

fix: for hosts typing in cypress.d.ts

---

packages/launchpad/cypress/e2e/config-files-error-handling.cy.ts

na
the `clears the error correctly after first 'try again' attempt` test has been flaky on CI. The problem was that, without waiting for the mutation to finish executing, elements could be grabbed and the test could proceed without the config processing finishing.
I ran this locally 100 times before and after the changes. Before, the test failed 15/100 times. After, no failures.

test: fix flaky config error test

---

npm/mount-utils/package.json
npm/vue/package.json
npm/vue2/package.json
scripts/sync-exported-npm-with-cli.js

To try this out, checkout the last commit of develop and run yarn install.
You should see the `cli/package.json` be modified without you asking.
1. In the generation script, take the missing `types` field into account
2. Fix the typings target of `vue` and `vue2` 
3. Add `types` field for `mount-utils`.

chore: avoid removing the types from vue, vue2 when yarn install

---

circle.yml

- For https://github.com/cypress-io/cypress-internal/issues/461
- Removes Windows from PRs and branch builds by default, cuz It's expensive, yo. And we don't need to do this as badly now that we aren't rapidly iterating on 10.0 pre-releases. We will be forced to reckon with Windows every 2 weeks like in the pre-10.0 days.

chore: only run Windows on main branches

---

packages/app/cypress/e2e/settings.cy.ts
packages/app/cypress/e2e/sidebar_navigation.cy.ts
packages/app/cypress/e2e/specs_list_e2e.cy.ts
packages/app/src/navigation/SidebarNavigation.cy.tsx
packages/app/src/navigation/SidebarNavigation.vue

- Closes 
Automatically collapse sidebar, and keep it collapsed, when window width is narrow to better utilize screen real estate.
1. Start with a window width >=1024px, make sure the sidebar is expanded.
2. Decrease the window width to become below 1024px, the sidebar should automatically collapse.
3. As long as window width is below 1024px, the sidebar should be collapsed with no option to be expanded.
4. Going back to a window width >=1024px should automatically expand the sidebar if it was expanded before.
5. Going back to a window width >=1024px should keep the sidebar collapsed if it was collapsed before.

feat: auto-collapse sidebar for window width < lg

---

packages/app/src/specs/LastUpdatedHeader.vue
packages/app/src/specs/SpecHeaderCloudDataTooltip.vue
packages/app/src/specs/SpecsList.cy.tsx

- Closes #22638 
* Add icons to help indicate that column headers provide more information on hover
N/A
1. Open a project in the app, navigate to the Specs Explorer
2. Validate that the "Last Updated", "Latest Runs", and "Average Duration" columns display a "question mark" icon
3. Validate that the tooltip for each column is triggered on hover of text *and* icon
4. Validate that columns do not overlap as viewport shrinks
* Note: This depends on behavior being introduced in #22393 to automatically collapse the sidebar
https://user-images.githubusercontent.com/11482842/179297441-a1948f2d-698d-46a2-97ce-83792bc312dc.mov
- [na] Have tests been added/updated? _Covered by percy_
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress …

feat: Add icons to headers that have tooltips

---

guides/release-process.md
scripts/binary/util/upload.js

N/A - internal only
1. Makes the following improvements to release-process.md:
- Moves the AWS SSO setup to prerequisites since it should only need to be done once
- Adds a step to test out the pre-release binary before moving it to beta or publishing to npm. This is the same as the later smoke test step after publishing to npm. It can help catch any issues that might invalidate the release after it's too late because it's taken up a version on npm.
- Adds a note that the merge from develop to master should be a merge commit and not a squash commit.
- Replaces the release-automation set-releases step with manual GitHub release creation since the release automation for it is broken.
2. Updates the binary upload script to use the list of valid platforms+arches when purging the cache. …

chore: Make improvements to release process doc and binary upload script

---

npm/cypress-schematic/README.md
npm/cypress-schematic/package.json
npm/cypress-schematic/src/builders/cypress/cypressBuilderOptions.ts
npm/cypress-schematic/src/builders/cypress/index.ts

Fixes #21555.
Users can now add custom options to `devServerTarget` in `angular.json` to specify `baseUrl`:
```json
"options": {
"host": "localhost",
"port": 4200
},
```

fix(cypress/schematic): run configuration does not work anymore without baseUrl 

---

npm/webpack-dev-server/src/createWebpackDevServer.ts

n/a
it always displayed:
`using webpack-dev-server v4` even when webpack-dev-server@3 is used.
This can be confusing while debugging.

fix: wrong version of webpack-dev-server displayed

---

cli/package.json
cli/scripts/post-build.js
cli/types/cypress.d.ts
npm/angular/package.json
npm/webpack-dev-server/cypress/e2e/angular.cy.ts
npm/webpack-dev-server/src/devServer.ts
npm/webpack-dev-server/src/helpers/sourceRelativeWebpackModules.ts
npm/webpack-dev-server/src/makeDefaultWebpackConfig.ts
npm/webpack-dev-server/test/handlers/angularHandler.spec.ts
packages/graphql/schemas/schema.graphql
packages/launchpad/cypress/e2e/scaffold-component-testing.cy.ts
packages/launchpad/src/utils/icons.ts
packages/scaffold-config/src/frameworks.ts
packages/scaffold-config/test/unit/detect.spec.ts

na
Product wants to push the delay of Angular CT to next release (GTM), so this PR disables all features of Angular CT. Will revert this after our next release.
You can point Angular at an angular cli application. There won't be any Angular detection. Even with a pre-setup application like `system-tests/projects/angular-cli-configured`, the dev-server will throw with `no matching framework`
na

chore: remove angular integration

---

packages/app/src/specs/RunStatusDots.cy.tsx
packages/app/src/specs/RunStatusDots.vue
packages/frontend-shared/src/assets/icons/queued-solid_x16.svg

- Closes #22601 
* Fix icon colors in "Latest Runs" section for queued/pending runs
Also updating the "queued" icon's SVG to support the `icon-light*` and `icon-dark*` style pattern if it gets used elsewhere
**Before**
Latest run icon for "Queued" status is lighter gray than dots
**After**
Latest run icon for "Queued" status is same gray color as dots

fix: Standardize colors for runs in queued status

---

circle.yml

[Contributor PRs](https://app.circleci.com/pipelines/github/cypress-io/cypress/41139/workflows/c92a406b-810e-4cb4-8e59-4a8dda45f6fb/jobs/1701067) are failing the `test-binary-against-kitchensink` job in CI due to an invalid curl for the node sourcing script. I added a fallback for branches matching external contributor branches to pull directly from develop.
There's probably a better way to go about this in general, but this is a quick fix for the PRs open now. 
N/A
I validated the script locally. This PR is green.
- [n/a] Has a PR for user-facing changes been opened in …

chore: updating run binary CI scripts to support external contributors

---

packages/app/src/components/FileMatchButton.cy.tsx
packages/app/src/components/FileMatchIndicator.cy.tsx
packages/frontend-shared/src/components/Alert.cy.tsx
packages/frontend-shared/src/components/Collapsible.cy.tsx
packages/frontend-shared/src/components/ListRowHeader.cy.tsx
packages/frontend-shared/src/warning/Warning.cy.tsx
packages/launchpad/src/components/code/FileRow.cy.tsx
packages/launchpad/src/warning/WarningList.cy.tsx

- Closes N/A
N/A
The content generated by faker was causing some visual regression failures as it changed in each test run. This PR adds a faker seed so that we now use consistent data when faker is called.
Load up the `FileRow` spec in the Launchpad project, rerun it a couple of times and you should see the same data each time. Comment out the `faker.seed(1)` and you should see that the data then changes each time you re-run the spec.
There are lots of other places we use faker, so I added the seed there as well, even though they are not currently covered by Percy snapshots that are flaky.
Being able to easily grab fake data when writing tests and have it change still seems very useful when developing components, so I'm not suggesting removing faker at this point -- but in CI I think we …

test: make content consistent in component tests that use faker

---

circle.yml
npm/angular/src/mount.ts
npm/webpack-dev-server/cypress/e2e/angular.cy.ts
system-tests/project-fixtures/angular/src/app/mount.cy.ts
system-tests/test/component_testing_spec.ts

- Closes #23096 
Teardown the previous component from the DOM before every test is run
This was pointed out by @brian-mann 
run the `angular.cy.ts` system test
Tests were setup to take a screenshot before each test...
Before:
https://user-images.githubusercontent.com/25158820/182721424-410b9e91-d26b-4c8e-aef6-f4f6582934f3.mov
After:
https://user-images.githubusercontent.com/25158820/182721441-ef4fde16-dbf9-49d3-a647-748d82fdcc88.mov
- [X ] Have tests been added/updated?
- [na ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

refactor(angular): handle mounting teardown before tests

---

circle.yml

More details at: https://github.com/cypress-io/cypress/pull/23113

chore: cherry-pick commit that fixes current yargs-parser type issue

---

npm/angular/package.json
npm/vue/cypress.config.ts
npm/vue/package.json
system-tests/lib/dep-installer/index.ts
system-tests/projects/component-tests/cypress.config.js
system-tests/projects/component-tests/cypressWithInvalidProjectId.config.js
system-tests/projects/component-tests/cypressWithoutProjectId.config.js
system-tests/projects/migration-e2e-plugins-modify-config/cypress/plugins/index.js
yarn.lock

na
Semantic release has been failing, possibly due to the [semantic-release bump](https://github.com/cypress-io/cypress/pull/22238) a few weeks ago. Hard to verify since we haven't had a passing `npm-release` job in a while. The problem was due to peer-deps from the `@cypress/code-coverage` package in `npm/vue`. Removing this allowed the `npm-release` job to move pass the error occurring in the `@semantic-release/npm prepare` plugin (I verified by sshing into the last master `npm-release` job and running `yarn npm-release`. The tokens were out of date so no packages were published).
We weren't verifying the results of `code-coverage` for the vue cypress tests, and it makes more sense in a system test anyway. In fact, we aren't even running the `npm/vue` cypress tests on CI right now. …

fix: remove dependency causing semantic-release to fail

---

npm/angular/package.json
npm/angular/rollup.config.js
npm/angular/src/mount.ts
npm/angular/tsconfig.json
npm/webpack-dev-server/cypress/e2e/angular.cy.ts
system-tests/project-fixtures/angular/src/app/components/button-output.component.ts
system-tests/project-fixtures/angular/src/app/components/projection.component.ts
system-tests/project-fixtures/angular/src/app/mount.cy.ts
system-tests/projects/angular-14/src/app/components/standalone.component.cy.ts
system-tests/projects/angular-14/src/app/components/standalone.component.ts
system-tests/test/component_testing_spec.ts

- Closes #22819 #23096 #23000 #22991 #23125 
Adds Angular Component Testing Support
Adds Angular Template Support
Adds Support for Angular Standalone Components
Fixes bug where previous component was not torn down before remounting the next component
You can run system tests for `angular-13` & `angular-14` & `component_testing_spec.ts`

feat: add template support, teardown & standalone

---

npm/cypress-schematic/src/e2e.spec.ts
scripts/npm-release.js

na
The `npm-release` job is broken due to peer-dependency issues. Before reverting the semantic-release dep (which has security implications), I'd like to try the `NPM_CONFIG_LEGACY_PEER_DEPS` option.
Link to latest master `npm-release` failure: https://app.circleci.com/pipelines/github/cypress-io/cypress/41450/workflows/e56453d4-5d77-4e96-8262-82517d9668aa/jobs/1716530
I have no good way to test this since semantic-release requires valid npm_tokens. The build is failing when running `npm version` but I can't reproduce this locally.
na …

fix: use legacy-peer-deps for semantic-release process

---

npm/react/src/createMount.ts
npm/react/src/mount.ts
npm/react/src/types.ts
npm/react18/src/index.ts
system-tests/__snapshots__/component_testing_spec.ts.js
system-tests/__snapshots__/vite_dev_server_fresh_spec.ts.js
system-tests/__snapshots__/webpack_dev_server_fresh_spec.ts.js
system-tests/project-fixtures/react/src/Unmount.cy.jsx

- Closes #23081
- Fixes issue in component testing when using React 18 mount
- Build `npm/react` and `npm/react18` projects
- Copy the `dist` folders from the projects and place them in a React project under their respective React folders in `node_modules/cypress`
- Run cypress in the React project

fix(react18): unmount component with react18 API

---

packages/proxy/lib/http/util/prerequests.ts
packages/proxy/test/unit/http/util/prerequests.spec.ts

- Closes 
- Fixed an issue introduced in 10.3.0 where network logs could be missing certain information or cause certain requests to be delayed by 500ms.
- Performance fixes in https://github.com/cypress-io/cypress/pull/22462 caused a couple of  unintended changes:
- Missing return statement on line 77 here causes a matched prerequest to be queued anyways: https://github.com/cypress-io/cypress/blob/8fb785a4664acf74ab9eacc243c09763e2730bf7/packages/proxy/lib/http/util/prerequests.ts#L69-L83
- More impactful, the `Record<string, ...>` data structure would clobber any duplicate `url+method` requests/pre-requests, which could manifest itself in incorrect pre-request data or unintended delays of requests by 500ms.
- Replaced this with a `StackMap` which supports duplicate keys and `.pop` by …

fix(proxy/prerequests): fix duplicate key behavior, fallthrough

---

scripts/npm-release.js

na
semantic-release v19 upgraded to npm v8 which supports workspaces. When running semantic-release, npm thinks that our lerna workspace is an npm workspace. When npm executes commands that modify the workspace, it will check the validity of the workspace. We don't want this to happen since we don't use npm and our links/peerDependencies make npm unhappy. We disable the workspace update via the NPM_CONFIG_WORKSPACES_UDPATE=false env variable.
I included this as a code comment for future reference
A bit tricky to test but I was able to run the plugin that was causing the `npm-release` job to fail locally. To do so, I modified `node_modules/semantic-release/lib/definitions/plugins.js` to change the `prepare` plugin to have `dryRun: true`. This allows the plugin to be executed during a …

fix: disable npm workspace update when running semantic-release

---

scripts/gulp/gulpfile.ts
scripts/gulp/tasks/gulpWebpack.ts

Removed a leftover runner-ct script that was throwing an error during `yarn watch`
Run `yarn watch` on latest develop to see the error in the terminal
Run` yarn watch` on my PR to see it _disappear_
na

chore: remove redundant runner-ct webpack script from watch

---

packages/app/src/runner/selector-playground/SelectorPlayground.cy.tsx
packages/app/src/specs/LastUpdatedHeader.cy.tsx
packages/app/src/specs/LastUpdatedHeader.vue
packages/app/src/specs/SpecHeaderCloudDataTooltip.cy.tsx
packages/app/src/specs/SpecHeaderCloudDataTooltip.vue
packages/frontend-shared/src/components/StandardModal.cy.tsx
packages/frontend-shared/src/components/Tooltip.cy.tsx
packages/frontend-shared/src/components/Tooltip.vue
packages/frontend-shared/src/gql-components/topnav/LoginModal.cy.tsx

- Closes #23115 
* Add delay to header tooltips so they don't pop open unless hovered on
Had to make two fixes here:
1. Add a "show-delay" to both header components and pass thru to base Tooltip
2. `floating-vue` by default keeps tooltip content in the DOM for 5 seconds after the tooltip closes before disposing of it. This caused the delay to be ignored if you moused back over the tooltip within that 5 second period. The disposal period is a global conflg for the library - I don't foresee any issues with reducing it to immediately dispose (it may actually clean up some of the weird tooltip behaviors we have currently) but let me know if you have concerns
1. Open a project in the app
2. From the specs list, move your mouse to the "New Spec" button (crossing over the "Average Duration" …

fix: Add delay to showing ACI header tooltips

---

guides/release-process.md

These changes will test the docker image prior to making the new cypress release available. This will also ensure the docker image gets released very near to the  npm package.
- Closes n/a
n/a
These changes will test the docker image prior to making the new cypress release available. This will also ensure the docker image gets released very near to the  npm package.

chore: Update release guide docker steps

---

npm/webpack-dev-server/src/helpers/createReactAppHandler.ts
npm/webpack-dev-server/src/helpers/nextHandler.ts
npm/webpack-dev-server/src/helpers/nuxtHandler.ts
npm/webpack-dev-server/src/helpers/vueCliHandler.ts
npm/webpack-dev-server/src/makeWebpackConfig.ts
npm/webpack-dev-server/test/makeWebpackConfig.spec.ts

- Closes #23224
Webpack entrypoints are no longer preserved for CT Webpack projects
Fixes a regression from https://github.com/cypress-io/cypress/pull/22314 where webpack entrypoints were being preserved. This is mostly a revert of the changes made to entrypoints in that PR. It made sense for frameworks as their was logic added for removing entrypoints that would cause problems in each handler, but users who pass in a custom webpack config (don't use a higher-order framework like Next or create-react-app) were facing issues with their entrypoint being included and executed.
Checkout the repo provided in the original issue: https://gitlab.com/souf/react-webpack-playground/-/tree/cypress-webpack-entry
Install Cypress and walk through CT setup.
Create a simple spec:
```js
// …
```

fix: remove webpack entrypoints from for ct webpack projects

---

packages/app/src/layouts/default.vue
packages/app/src/runs/CloudConnectButton.vue
packages/frontend-shared/src/gql-components/HeaderBarContent.cy.tsx
packages/frontend-shared/src/gql-components/HeaderBarContent.vue

Addressing Windows e2e failure introduced by #23295 
New GQL fields were added to existing queries in some base components which introduced delays/failures in e2e tests. Happened to get green CI for the original PR but [CI builds on develop surfaced issues on the Windows runs](https://app.circleci.com/pipelines/github/cypress-io/cypress/41828/workflows/b91a66aa-6ba1-4147-9ef9-435b0c991a4c/jobs/1734268).
GQL fields for cloud connect modals (some of which are remote query fields) were added to the app default layout which caused failures in `authChange-subscription.cy.ts`. Updating to run the query on-demand instead so it doesn't impact majority of e2e tests.
Also reverting how two components are resolving `projectId` to how Mark originally had them. There is some delay/instability …

fix: Address windows test failures introduced by gql query changes

---

package.json

chore: bumping version to 10.6.0

---

npm/cypress-schematic/src/builders/cypress/index.ts

- Closes https://github.com/cypress-io/cypress/issues/23345
Allow optional watch option for angular universal dev server 
It will now work with angular universal dev server 
- [ na] Have tests been added/updated?

fix: cypress-schematic add exception for nguniversal ssr dev server

---

circle.yml
scripts/verify-mocha-results.js

- Closes 
* Failures:
* https://app.circleci.com/pipelines/github/cypress-io/cypress/42216/workflows/aaa50b4c-1e68-4a27-a217-577dd369ec5b/jobs/1752157
* https://app.circleci.com/pipelines/github/cypress-io/cypress/41984/workflows/634ec702-5982-4928-952c-7aa452465061/jobs/1741529?invite=true#step-112-6
* Accursed `|| true` strikes again. This only ever worked in Docker Linux, so let's encode it and fix the `|| true`. …

chore: skip Circle env canary check unless in Docker

---

packages/network/lib/agent.ts
packages/network/test/unit/agent_spec.ts

- Closes #22217 
App no longer crashes on websocket upgrade request over https
A change was made on on #20107 to support `fetch` requests in the proxy. For that change, we needed to set `options.uri` in our `HttpsAgent.addRequest` method. It was assumed that this would cover the [existing logic](https://github.com/cypress-io/cypress/pull/20107/files#diff-0eefefc0f7a3eb51d155cb5b640d42389dd1ce4d220bd1aeca28bfa7ff3bf458L182-L185) to set `options.uri` as well, however, this didn't cover the case where we have a client certificate over https. This PR restores that functionality.
You can test this by uncommenting the code change and running the new test and see that there is a failure. You can also use the test project provided by @AtofStryker …

fix: app crashing on websocket upgrade request over https

---

npm/angular/package.json
npm/create-cypress-tests/package.json
npm/cypress-schematic/package.json
npm/mount-utils/package.json
npm/react/package.json
npm/react18/package.json
npm/vue/package.json
npm/vue2/package.json
npm/webpack-batteries-included-preprocessor/package.json
npm/webpack-preprocessor/examples/use-ts-loader/package.json
package.json
packages/driver/src/dom/elements/nativeProps.ts
packages/extension/package.json
packages/launcher/package.json
packages/network/package.json
packages/proxy/package.json
packages/scaffold-config/src/frameworks.ts
packages/server/package.json
packages/types/package.json
yarn.lock

n/a
Update to latest version of typescript. Had to bump `ts-loader` as `@packages/extension` was failing with the new version of TS.
Counting on CI here, everything worked well locally.
na

chore: update typescript

---

packages/app/src/navigation/KeyboardBindingsModal.vue
packages/app/src/runner/studio/StudioSaveModal.vue
packages/frontend-shared/src/components/StandardModal.cy.tsx
packages/frontend-shared/src/components/StandardModal.vue
packages/frontend-shared/src/components/StandardModalHeader.vue
packages/frontend-shared/src/gql-components/topnav/UpdateCypressModal.vue
packages/reporter/cypress/e2e/tests.cy.ts

Fixing some tests in `astone123/23337-studio-ui` and a small refactor to add a `noHelp` flag to the `StandardModal` component.

chore: fix some tests, minor refactor

---

circle.yml

n/a
the `npm-react` job was running with `parallelism = 8` but it wasn't splitting the files so it was duplicating the work across 8 machines. It only takes <5 minutes to run so I've removed it entirely.
Check out the latest develop [npm-react job](https://app.circleci.com/pipelines/github/cypress-io/cypress/42516/workflows/7f322812-ea51-462d-b0e1-27c4c3be36ed/jobs/1768390), then compare it to [this PR's build](https://app.circleci.com/pipelines/github/cypress-io/cypress/42532/workflows/64a667f9-982a-4620-8167-cdd4c2387fff/jobs/1768899).
na …

chore: remove react parallelism

---

npm/angular/package.json
npm/angular/src/mount.ts
npm/cypress-schematic/package.json
npm/cypress-schematic/src/ct.spec.ts
system-tests/projects/angular-14/package.json
system-tests/projects/angular-14/yarn.lock
yarn.lock

- Closes #23585
Fix Angular 14.2 mount compilation error
Angulars 14.2 update changed the API we relied on for tearing down the component between tests. Before 14.2, `tearDownTestingModule` was a static method on the `TestBed` class but was changed to be a method on the instance. Converting all `TestBed` references to the `getTestBed()` factory function gives us the proper instance of TestBed with the methods we need and reatins backwards compatibility.
Running the system tests in `system-tests/test/component_testing_spec.ts` is the best way to test. The `angular-14` project has had it's deps bumped. Without the changes to `mount` this test will fail.
https://user-images.githubusercontent.com/25158820/187244307-ef6d0a5b-a42c-423e-af5e-0795e6d08239.mov
- [na] Has a PR for user-facing …

fix: angular 14.2 mount compilation error

---

packages/server/lib/modes/run.ts
packages/server/lib/util/print-run.ts

- Closes 
- Makes `run.ts` easier to work on by factoring out all of the complicated display logic. Now `run.ts` is a measly ~1100 lines long, down from ~1700!
- Existing snapshot coverage should not change.

refactor: move console logging out of run.ts

---

packages/app/cypress/e2e/specs_list_latest_runs.cy.ts

Here's a way to test this from e2e to ensure the component appears in the right place on hover. @warrensplayer feel free to merge to your branch or just use this as an example.

test: add e2e test confirming login/connect button displays on hover

---

guides/release-process.md

- Closes 
N/A
Minor updates to release doc based on discrepancies I found during 10.7.0 release

chore: Update release process doc

---

packages/driver/cypress/e2e/commands/aliasing.cy.js
packages/driver/src/cypress/cy.ts

- Closes https://github.com/cypress-io/cypress/issues/23652
Fix: Mixing custom commands and aliases now works again. Fixes regression introduced between 10.4.0 and 10.5.0.
When a custom command invoked cypress commands, these 'internal' commands' return values are properly used as the subject for future commands, via the 'subjectLinks' internal Cypress state.
However, as of 10.5.0, aliases were not respecting these links, meaning they would end up with 'undefined' for a subject instead of the proper one (which would come from replaying the 'internal' commands).
See the test added by this PR for a more concrete example.
Added automated test demonstrating the issue. Also see the repro in https://github.com/cypress-io/cypress/issues/23652 for external validation.
- [n/a] Has a PR for …

fix: Aliases properly retry commands from inside custom commands

---

circle.yml
packages/launchpad/cypress/e2e/config-warning.cy.ts

- Closes N/A
Partially https://github.com/cypress-io/cypress/issues/23158 (one of the flaky tests)
N/A
Observe CI not failing and not flaky.

chore: fixing flaky tests

---

packages/app/cypress/e2e/runs.cy.ts
packages/app/cypress/e2e/subscriptions/createCloudOrgModal-subscription.cy.ts
packages/app/src/runs/modals/CloudConnectModals.spec.tsx
packages/app/src/runs/modals/CloudConnectModals.vue
packages/app/src/runs/modals/CreateCloudOrgModal.vue
packages/app/src/runs/modals/SelectCloudProjectModal.vue
packages/graphql/schemas/schema.graphql
packages/graphql/src/schemaTypes/objectTypes/gql-Mutation.ts

- Closes #23538 
* Fixes an issue where outdated organization and project information could be shown in dialogs to connect a project to the Cypress Dashboard.
* Adding a refetch when opening any of the Cloud Connect modals (Create/Select organization, Create/Select project) to reflect any org/project changes that have occurred outside the Cypress app since the user last logged in/opened the app
* Fixed an issue in the Select Project dialog that would continue to use old data in select menus after an updated `gql` prop was passed in
This procedure involves creating/deleting cloud data. We point to Prod for cloud data by default now, if you would be more comfortable testing against Staging you can do so by launching like so `CYPRESS_INTERNAL_ENV=staging yarn dev`
1. Open a project that is …

fix: Refetch latest cloud data when opening cloud connect modals

---

npm/vite-dev-server/package.json
npm/webpack-dev-server/package.json
npm/webpack-preprocessor/package.json
package.json
packages/data-context/src/data/ProjectConfigIpc.ts
packages/server/package.json
packages/ts/package.json
system-tests/scripts/bootstrap-docker-container.sh
system-tests/test-binary/node_versions_spec.ts
yarn.lock

- Closes https://github.com/cypress-io/cypress/issues/22795
- Closes https://github.com/cypress-io/cypress/issues/23393
Fix a bug where projects using Node.js 16.17+ and 18.6+ with `type: module` and `cypress.config.ts` were not working with Cypress.
Projects with `type: module` using TypeScript (with a `cypress.config.ts` file) broke recently due to Node.js changing something on their end. 
This is the exact PR to Node.js that broke everything: https://github.com/nodejs/node/pull/42623. It seems even the Node.js team wasn't fully across the scope of breakage that was introduced: https://github.com/nodejs/node/pull/42623#issuecomment-1223992512
Anyway, `ts-node` made some fixes in response to handle it. We use `ts-node` internally. I just updated the version of `ts-node` we ship to the …

fix: support type: module in Node.js 16.17.0+ and 18.6.0+

---

packages/launcher/lib/browsers.ts
packages/server/lib/browsers/firefox.ts
packages/server/test/unit/browsers/firefox_spec.ts

Follow up https://github.com/cypress-io/cypress/pull/23579/files#r963726642

chore: fix test and types in server

---

packages/server/lib/browsers/electron.ts
packages/server/test/unit/browsers/electron_spec.js

- Closes #23597
Additionally overrides the electron user agent via CDP if the [userAgent](https://docs.cypress.io/guides/references/configuration#Browser) config option is provided or `experimentalModifyObstructiveThirdPartyCode` is enabled.
It looks like the changes in #22958 did not fully override the electron user agent as expected (see #23597). In addition to setting the userAgent via the Electron's [webContents.session](https://www.electronjs.org/docs/latest/api/session#sessetuseragentuseragent-acceptlanguages) API, we now optimistically set the user agent via CDP, which resolves the issue entirely.

fix: additionally set electron user agent through CDP

---

packages/proxy/lib/http/request-middleware.ts
packages/proxy/test/unit/http/request-middleware.spec.ts

- Closes #23599
sets the `Sec-Fetch-Dest` request header to `document` in the case the AUT iframe is making a request. This is to better simulate top when the `experimentalModifyObstructiveThirdPartyCode` flag is enabled.
The goal of this change is to better simulate top from the AUT iframe by setting the `Sec-Fetch-Dest` [metadata header](https://developer.mozilla.org/en-US/docs/Glossary/Fetch_metadata_request_header) to `document` when the AUT iframe itself is making a request and the `Sec-Fetch-Dest` is `iframe`. This change it the proxy allows the AUT iframe to appear more like top. This should NOT effect nested iframes in the AUT and only impacts the AUT iframe, which we can safely assume would be top otherwise.

feat: add MaybeSimulateSecHeaders code to prevent 403 issues with google

---

packages/app/src/main.ts
packages/reporter/cypress/e2e/runnables.cy.ts
packages/reporter/src/lib/scroller.ts
packages/reporter/src/runnables/runnables.tsx

Some tweaks/fixes for https://github.com/cypress-io/cypress/pull/23053

chore: updates for marktnoonan/16098

---

npm/webpack-dev-server/src/helpers/angularHandler.ts
npm/webpack-dev-server/test/handlers/angularHandler.spec.ts

- Closes #23673
Change that allows passing in a default tsConfig flag in buildOptions to angularHandler
Allow users to pass in a specific tsconfig.json (e.g to avoid collisions with jest and similar)
N/A
N/A
As a quick note - I was wondering if I should add any tests for this, but seemed like such a small change it should not warrant one. However if it seems necessary, I can look into adding a test for it. …

fix: Use tsconfig from build if exists (closes #23673)
