README.md

Since the date has passed, let's assume it's soon? :)

Change the public beta date

---

CONTRIBUTING.md

Added instructions to allow edits from maintainers

---

circle.yml

use `working_directory: ...` option on CircleCI instead of `cd ... && cmd`

Working directory ci

---

appveyor.yml
circle.yml
package.json

Print platform and architecture without using `node -e ...` but with https://github.com/bahmutov/print-arch

Print arch

---

appveyor.yml
package.json
scripts/win-appveyor-build.js

Having multiple commands in Appveyor file is becoming a pain, especially with if statement for binary build

start moving appveyor build steps into shelljs file

---

packages/driver/src/cy/commands/connectors.coffee
packages/driver/src/cypress/error_messages.coffee
packages/driver/test/cypress/integration/commands/connectors_spec.coffee

Make cy.spread() work for get selections

---

packages/driver/src/cy/commands/actions/type.coffee
packages/driver/test/cypress/integration/commands/actions/type_spec.coffee

Allow typing space using .type(" ")

---

packages/desktop-gui/cypress/integration/update_banner_spec.coffee
packages/desktop-gui/src/update/updates.scss

Update spec list to extend to bottom of viewable area when updates banner exists

---

packages/server/lib/modes/record.coffee
packages/server/test/unit/modes/record_spec.coffee

it was annoying to me when it silently ignored my command

server: warn user if passed group id but not group flag

---

cli/__snapshots__/cli_spec.js
cli/lib/cli.js
cli/package.json
cli/test/lib/cli_spec.js

Server already accepts it, but the CLI was filtering it out
plus update to latest commander

cli: pass group and groupId flags, close #455

---

cli/lib/exec/run.js
cli/test/lib/exec/run_spec.js

Not just collect group option in the CLI, but put it into arguments list when spawning server.

Actually pass group id 455

---

appveyor.yml
circle.yml
package.json
scripts/binary/bump.coffee
scripts/binary/util/upload.coffee

- you can put env json file like `scripts/support/.aws_credentials.json` anywhere. The environment variable will be simply the base name without folder path
- renamed staging record key

Env file name

---

packages/launcher/package.json
packages/server/__snapshots__/record_spec.coffee
packages/server/lib/api.coffee
packages/server/lib/controllers/files.coffee
packages/server/lib/modes/headless.coffee
packages/server/lib/modes/record.coffee
packages/server/lib/project.coffee
packages/server/test/integration/cypress_spec.coffee
packages/server/test/unit/api_spec.coffee
packages/server/test/unit/modes/record_spec.coffee
packages/server/test/unit/project_spec.coffee
packages/ts/package.json

- send list of specs when creating build
A single failing test is random flaky test.

Send list of specs with record build 861

---

packages/driver/src/cy/commands/window.coffee
packages/driver/test/cypress/integration/commands/window_spec.coffee

Fix cy.viewport not changing viewport if only height changes

---

circle.yml

Better environment variable name on CircleCI

record test-tiny project on staging

---

packages/server/lib/plugins/index.coffee
packages/server/test/unit/plugins/index_spec.coffee

Fix 'reject is not defined' error

---

packages/server/lib/plugins/preprocessor.coffee
packages/server/lib/server.coffee
packages/server/lib/socket.coffee
packages/server/package.json
packages/server/test/unit/plugins/preprocessor_spec.coffee
packages/server/test/unit/socket_spec.coffee

Fix firing 'watched:file:changed' twice on change

---

cli/index.d.ts
packages/driver/src/cypress.coffee
packages/runner/src/lib/event-manager.js
packages/server/__snapshots__/config_spec.coffee
packages/server/lib/controllers/runner.coffee
packages/server/test/support/fixtures/projects/e2e/cypress/integration/config_passing_spec.coffee

Finally adding `platform` and `arch` constants for https://github.com/cypress-io/cypress/issues/824

Add platform arch 824

---

cli/__snapshots__/install_spec.js
cli/lib/tasks/install.js
cli/test/lib/tasks/install_spec.js
cli/test/support/normalize.js

Allow skipping binary download during install

---

packages/launcher/lib/browsers.ts
packages/launcher/lib/darwin/util.ts
packages/launcher/lib/linux/index.ts
packages/launcher/lib/types.ts
packages/launcher/lib/windows/index.ts
packages/launcher/package.json

instead of hardcoding aliases to browsers, need to make sure `--browser /usr/bin/chrome` works

Remove browser aliases 1023

---

packages/server/package.json

Upgrade browserify preprocessor to fix watch/re-run bug

---

cli/types/index.d.ts
cli/types/tests/cypress-tests.ts

fix: Unwrap subject returned by cy.then

---

packages/server/lib/gui/events.coffee
packages/server/test/unit/gui/events_spec.coffee
packages/server/test/unit/gui/windows_spec.coffee

- add more comprehensive tests around windows and events
- test that github callbacks work as expected

server: fixes #1093, ensure github login works

---

cli/schema/README.md
cli/schema/cypress.schema.json

Then I can make pull request to schemastore and point at the schema file in our repo, just like this example
```json
{
"name": ".angular-cli.json",
"description": "Angular CLI configuration file",
"fileMatch": [ ".angular-cli.json", "angular-cli.json" ],
"url": "https://raw.githubusercontent.com/angular/angular-cli/master/packages/@angular/cli/lib/config/schema.json"
}
```

add cypress.schema.json close #1109

---

cli/types/index.d.ts

All methods used in cypress-example-todomvc except for custom command have _nice_ IntelliSense with examples.

Doc ts better 1117

---

ISSUE_TEMPLATE.md

This encourages people to create reproducible examples using a fork of our project

add advice to issue template

---

package.json
packages/server/test/e2e/visit_spec.coffee
packages/server/test/e2e/web_security_spec.coffee
packages/server/test/integration/cypress_spec.coffee
packages/server/test/scripts/e2e.js

Nice separator for verbose e2e tests

Banner for server e2e tests

---

packages/server/lib/konfig.coffee
packages/server/test/unit/konfig_spec.coffee

if the key previously did not exist, delete it
closes #1223

return NODE_ENV to previous state after konfig()

---

packages/desktop-gui/src/runs/setup-project-modal.jsx

- with billing being released, this message is no longer needed.
- #close #827

remove message about private projects being 'free while in beta'

---

packages/desktop-gui/cypress/integration/setup_project_modal_spec.coffee
packages/desktop-gui/src/runs/setup-project-modal.jsx

Issue 1306

---

packages/driver/src/cypress/runner.coffee
packages/driver/src/cypress/utils.coffee
packages/driver/test/cypress/integration/cypress/utils_spec.coffee
packages/driver/test/cypress/integration/e2e/674_spec.coffee
packages/reporter/src/lib/err-model.js
packages/reporter/src/lib/err-model.spec.js
packages/reporter/src/test/test-model.js
packages/server/__snapshots__/issue_674_spec.coffee
packages/server/__snapshots__/reporters_spec.coffee
packages/server/lib/reporter.coffee
packages/server/test/e2e/issue_674_spec.coffee
packages/server/test/e2e/reporters_spec.coffee
packages/server/test/support/fixtures/projects/e2e/cypress/integration/issue_674_spec.coffee

- this prevents a situation where all test props were identical, but
we’re waiting for change event to occur

Issue 674 1338

---

packages/runner/src/header/header.jsx
packages/runner/src/header/header.spec.jsx

update viewport dropdown to show proper json formatting

---

package.json
packages/desktop-gui/cypress/fixtures/specs_windows.json
packages/desktop-gui/cypress/integration/specs_list_spec.coffee
packages/desktop-gui/src/specs/specs-store.js

Replacing "\\" with "/" for Windows tests to be rendered in folders

---

package.json
packages/driver/test/cypress/.eslintrc
packages/driver/test/cypress/fixtures/issue-1436.html
packages/driver/test/cypress/integration/issues/1436_spec.js
packages/runner/static/index.html
packages/server/lib/util/security.coffee
packages/server/test/unit/security_spec.coffee

Issue 1436

---

packages/server/lib/project.coffee
packages/server/lib/util/settings.coffee
packages/server/test/unit/project_spec.coffee

Watch cypress.env.json for changes

---

CONTRIBUTING.md

I try not to make opinionated/controversial changes. Please let me know if you disagree with any changes. Thanks!

Typography update: CONTRIBUTING.md

---

cli/package.json
cli/scripts/build.js

* Add keyword in package.json
* Also add keywords to the build script
closes #1508

Add keywords to help in searching cypress on npmjs.com

---

packages/driver/src/cy/commands/xhr.coffee
packages/runner/src/lib/event-manager.js
packages/server/lib/controllers/proxy.coffee
packages/server/lib/routes.coffee
packages/server/lib/server.coffee
packages/server/lib/socket.coffee
packages/server/lib/traffic_rules.coffee
packages/server/lib/util/traffic_rules.js

- work in progress for #687 
- collecting request route rules and passing them to the proxy layer where they are applied

WIP: network stubbing

---

packages/driver/src/cy/snapshots.coffee
packages/driver/test/cypress/integration/cy/snapshot_spec.coffee

Filter out non-screen stylesheets from snapshots

---

packages/server/lib/modes/run.coffee
packages/server/test/support/helpers/e2e.coffee

Issue 1592

---

packages/desktop-gui/cypress/integration/specs_list_spec.coffee
packages/desktop-gui/package.json
packages/desktop-gui/src/lib/local-data.js
packages/desktop-gui/src/projects/projects-api.js
packages/desktop-gui/src/specs/spec-model.js
packages/desktop-gui/src/specs/specs-list.jsx
packages/desktop-gui/src/specs/specs-store.js
packages/desktop-gui/src/specs/specs.scss

Fixes #1706 
Via local storage and per project
Decided against fuzzy filter

Desktop GUI filter improvements

---

packages/server/lib/util/ci_provider.coffee
packages/server/test/unit/ci_provider_spec.coffee

send Drone.io build number and url, close #1709

---

packages/driver/package.json

reference local coffee install in npm script

---

packages/server/lib/browsers/chrome.coffee

Add default chromium flag to disable device discovery notifications

---

packages/desktop-gui/cypress/fixtures/runs.json
packages/desktop-gui/cypress/integration/runs_list_spec.coffee
packages/desktop-gui/package.json
packages/desktop-gui/src/runs/runs-list-item.jsx
packages/desktop-gui/src/runs/runs-list.jsx

- also clean up some chaining in runs list spec
- close #1738

update clicking on 'run' to go to runs/buildNumber in Dashboard

---

cli/lib/exec/spawn.js
cli/lib/util.js
cli/test/lib/exec/spawn_spec.js
cli/test/lib/util_spec.js
packages/server/lib/util/tty.js
packages/server/test/integration/http_requests_spec.coffee
packages/server/test/integration/server_spec.coffee
packages/server/test/spec_helper.coffee
packages/server/test/unit/environment_spec.coffee
packages/server/test/unit/file_spec.coffee
packages/server/test/unit/tty_spec.coffee

- fixes #1745,
- fixes #1143 and fixes #1550
- fixes #1747
- fixes #1748

colors, piping, utf8 characters, stream overrides

---

cli/types/index.d.ts
cli/types/tests/kitchen-sink.ts
packages/driver/src/cypress/error_messages.coffee
packages/driver/test/cypress/integration/commands/screenshot_spec.coffee
packages/driver/test/cypress/integration/cypress/screenshot_spec.coffee
packages/server/__snapshots__/screenshot_fullpage_capture_spec.coffee
packages/server/__snapshots__/screenshots_spec.coffee
packages/server/lib/screenshots.coffee
packages/server/test/e2e/screenshot_fullpage_capture_spec.coffee
packages/server/test/e2e/screenshots_spec.coffee
packages/server/test/support/fixtures/projects/e2e/cypress/integration/screenshot_fullpage_capture_spec.coffee
packages/server/test/support/fixtures/projects/e2e/cypress/integration/screenshots_spec.coffee
packages/server/test/unit/screenshots_spec.coffee

Update typescript types for screenshots

---

packages/driver/src/cy/commands/screenshot.coffee
packages/driver/test/cypress/integration/commands/screenshot_spec.coffee

Pixel-check failure screenshots if test contains a cy.screenshot()

---

packages/server/__snapshots__/record_spec.coffee
packages/server/lib/screenshots.coffee
packages/server/test/support/fixtures/projects/e2e/cypress/integration/record_pass_spec.coffee
packages/server/test/support/fixtures/projects/e2e/scrollable.html

ensure that takenAt is not an array

---

cli/schema/cypress.schema.json
cli/types/index.d.ts
packages/server/lib/config.coffee
packages/server/lib/errors.coffee
packages/server/lib/modes/run.coffee
packages/server/lib/util/validation.coffee
packages/server/test/integration/cypress_spec.coffee
packages/server/test/unit/config_spec.coffee

validate cli + env var config, add breaking config changes

---

packages/server/lib/modes/run.coffee
packages/server/lib/video.coffee
packages/server/test/e2e/record_spec.coffee
packages/server/test/e2e/video_compression_spec.coffee
packages/server/test/support/fixtures/projects/e2e/cypress/integration/video_compression_spec.coffee
packages/server/test/support/helpers/e2e.coffee

video compression progress logs

---

cli/lib/exec/run.js
cli/test/lib/exec/run_spec.js
packages/desktop-gui/package.json
packages/server/lib/api.coffee
packages/server/lib/modes/record.coffee
packages/server/lib/util/args.coffee
packages/server/package.json
packages/server/test/e2e/record_spec.coffee
packages/server/test/unit/api_spec.coffee
packages/server/test/unit/modes/record_spec.coffee

rename planId -> groupId

---

packages/example/lib/example.js
packages/example/package.json
packages/server/lib/config.coffee
packages/server/lib/scaffold.coffee
packages/server/test/unit/config_spec.coffee
packages/server/test/unit/scaffold_spec.coffee

Make example scaffolding async

---

packages/server/lib/automation/index.coffee
packages/server/lib/browsers/electron.coffee
packages/server/lib/open_project.coffee
packages/server/lib/project.coffee
packages/server/test/unit/automation_spec.coffee
packages/server/test/unit/browsers/electron_spec.coffee
packages/server/test/unit/open_project_spec.coffee
packages/server/test/unit/project_spec.coffee

Unregister automation middleware when closing electron

---

cli/__snapshots__/install_spec.js
cli/__snapshots__/verify_spec.js
cli/lib/exec/run.js
cli/lib/exec/spawn.js
cli/lib/exec/versions.js
cli/lib/logger.js
cli/lib/tasks/install.js
cli/lib/tasks/state.js
cli/lib/tasks/verify.js
cli/lib/util.js
cli/test/lib/tasks/install_spec.js
cli/test/lib/tasks/verify_spec.js
cli/test/lib/util_spec.js
cli/test/spec_helper.js

close #1853 
close #817 
close #1399

env vars from configs, respect loglevel from npm

---

cli/types/index.d.ts
cli/types/tests/kitchen-sink.ts

- fixes #1831 
- implements Http method `PATCH` with a test which fixes #1778

Route typescript fix 1831

---

packages/server/__snapshots__/controllers_spec.coffee
packages/server/lib/controllers/spec.coffee
packages/server/test/e2e/browserify_babel_es2015_spec.coffee
packages/server/test/e2e/controllers_spec.coffee
packages/server/test/e2e/stdout_spec.coffee
packages/server/test/support/fixtures/projects/non-existent-spec/cypress.json
packages/server/test/support/fixtures/projects/non-existent-spec/cypress/plugins/index.js
packages/server/test/unit/spec_spec.coffee

Ensure errors from res.sendFile propagate and fail test run

---

cli/package.json
cli/types/index.d.ts
cli/types/minimatch.d.ts
cli/types/tests/kitchen-sink.ts

- close #1899 (types for `cy.clearLocalStorage`)
- close #1902 (types for `Cypress.minimatch`)

Ts definition for clear local storage 1899

---

cli/types/index.d.ts
cli/types/tests/kitchen-sink.ts

Ts server yields 1907

---

packages/server/lib/video_capture.coffee
packages/server/package.json

upgrade ffmpeg to v4, add more debug logs

---

cli/types/index.d.ts
packages/desktop-gui/cypress/integration/specs_list_spec.coffee
packages/desktop-gui/src/projects/projects-api.js
packages/desktop-gui/src/specs/specs-list.jsx
packages/server/lib/modes/run.coffee
packages/server/lib/open_project.coffee
packages/server/lib/server.coffee
packages/server/test/support/fixtures/projects/e2e/cypress/integration/config_passing_spec.coffee
packages/server/test/unit/modes/run_spec.coffee
packages/server/test/unit/open_project_spec.coffee

add browser.isHeadless + browser.isHeaded

---

packages/server/__snapshots__/js_error_handling_spec.coffee
packages/server/lib/controllers/proxy.coffee
packages/server/package.json
packages/server/test/e2e/js_error_handling_spec.coffee
packages/server/test/integration/http_requests_spec.coffee
packages/server/test/support/fixtures/projects/e2e/cypress/integration/js_error_handling_failing_spec.coffee

decode multi bytes correctly when stripping security from files

---

packages/reporter/src/commands/commands.scss

Fix reporter command shift when transitioning from pending

---

cli/__snapshots__/errors_spec.js
cli/__snapshots__/install_spec.js
cli/__snapshots__/verify_spec.js
cli/lib/errors.js
cli/lib/tasks/install.js
cli/lib/tasks/state.js
cli/lib/tasks/verify.js
cli/lib/util.js
cli/package.json
cli/test/lib/tasks/install_spec.js
cli/test/lib/tasks/state_spec.js
cli/test/lib/tasks/verify_spec.js

close #1984 improve error logging for `cypress verify`
close #1985 remove "skipping install" message to local users, keep in CI

Improve Error logging around Cypress verify

---

cli/__snapshots__/errors_spec.js
cli/__snapshots__/verify_spec.js
cli/lib/errors.js
cli/lib/tasks/verify.js
cli/test/lib/tasks/verify_spec.js

add more detailed error message for missing binary in ci

---

packages/server/lib/browsers/electron.coffee
packages/server/test/integration/cypress_spec.coffee
packages/server/test/unit/browsers/electron_spec.coffee

dont blow away the default electron options

---

cli/lib/exec/spawn.js
cli/test/lib/exec/spawn_spec.js

 catch EPIPE errors

---

packages/driver/src/cypress/cy.coffee
packages/driver/test/cypress/integration/issues/1854_spec.js

enable passing string arguments to timers

---

packages/server/lib/browsers/electron.coffee
packages/server/lib/gui/windows.coffee
packages/server/lib/modes/interactive.coffee
packages/server/lib/open_project.coffee
packages/server/lib/project.coffee
packages/server/lib/saved_state.coffee
packages/server/lib/util/file.coffee
packages/server/lib/util/saved_state.coffee
packages/server/test/integration/cypress_spec.coffee
packages/server/test/unit/file_spec.coffee
packages/server/test/unit/gui/windows_spec.coffee
packages/server/test/unit/saved_state_spec.coffee

- Fixes #2013
- Fixes #1912
- Fixes #1905
- Fixes #1890

state.json changes/improvements

---

cli/types/index.d.ts
cli/types/tests/kitchen-sink.ts

- closes #2007 
- a lot of work for #2009, just time boxed this

add cy.stub type for window alert and confirm

---

packages/server/lib/controllers/proxy.coffee
packages/server/lib/util/rewriter.coffee
packages/server/lib/util/security.coffee
packages/server/test/unit/security_spec.coffee

security stripping oversight

---

cli/__snapshots__/install_spec.js
cli/lib/errors.js

fix error typo

---

packages/desktop-gui/cypress/integration/runs_list_spec.coffee
packages/desktop-gui/src/lib/utils.js
packages/desktop-gui/src/runs/runs-list-item.jsx
packages/desktop-gui/src/runs/runs.scss

Issue 2060

---

packages/https-proxy/https.js
packages/https-proxy/index.js
packages/https-proxy/lib/proxy.coffee
packages/https-proxy/test/helpers/certs.coffee
packages/https-proxy/test/helpers/https_server.coffee
packages/server/__snapshots__/plugins_spec.coffee
packages/server/__snapshots__/stdout_spec.coffee
packages/server/__snapshots__/user_agent_spec.coffee
packages/server/__snapshots__/web_security_spec.coffee
packages/server/lib/browsers/chrome.coffee
packages/server/lib/project.coffee
packages/server/test/e2e/web_security_spec.coffee
packages/server/test/support/fixtures/projects/e2e/cypress/integration/web_security_spec.coffee
packages/server/test/support/helpers/e2e.coffee

enable disabling chromeWebSecurity in chrome 67

---

packages/example/package.json

update kitchen-sink example to 1.0.2 release

---

packages/driver/src/cy/commands/actions/type.coffee
packages/driver/src/dom/elements.coffee
packages/driver/src/dom/index.coffee
packages/driver/src/dom/selection.coffee
packages/driver/test/cypress/fixtures/dom.html
packages/driver/test/cypress/integration/commands/actions/type_spec.coffee
packages/driver/test/cypress/integration/cypress/cypress_spec.coffee

- add test for using type property
- add test for design mode
- deprecate `Cypress.dom.isType` in favor of `Cypress.dom.isInputType`, add deprecation warning

cy.type fixes

---

packages/reporter/src/commands/commands.scss

Fix failed command UI issue when pinned

---

CONTRIBUTING.md
packages/server/__snapshots__/7_record_spec.coffee.js
packages/server/lib/modes/record.coffee
packages/server/lib/modes/run.coffee
packages/server/test/e2e/7_record_spec.coffee

Fix beforeSpecRun is not a function error

---

packages/server/lib/saved_state.coffee

Whitelist autoScrollingEnabled in state.json

---

packages/server/package.json

Upgrade to latest browserify preprocessor

---

packages/runner/src/lib/dom.js
packages/server/test/e2e/4_screenshot_fullpage_capture_spec.coffee
packages/server/test/e2e/5_screenshot_viewport_capture_spec.coffee
packages/server/test/support/fixtures/projects/e2e/cypress/plugins/index.js

Fix screenshot blackout selector not working on multiple elements

---

packages/desktop-gui/package.json
packages/reporter/package.json
packages/runner/package.json
packages/runner/scripts/set-zunder-config.js
packages/runner/src/app/app.jsx
packages/runner/src/app/app.spec.jsx
packages/server/__snapshots__/4_return_value_spec.coffee.js

Update to zunder 6

---

circle.yml
packages/reporter/cypress.json
packages/reporter/scripts/build-dev.js
packages/reporter/scripts/build-prod.js
packages/reporter/scripts/set-zunder-config.js

Fix reporter Cypress tests and set up to run in CI

---

DEPLOY.md

Change formatting moving code block that is visualised outside the bullet point into the bullet point.

Move code in the bullet point

---

DEPLOY.md
packages/server/lib/modes/run.coffee
packages/server/test/e2e/7_record_spec.coffee

Add dashboard url to module api results

---

packages/driver/src/cy/commands/files.coffee
packages/driver/test/cypress/integration/commands/files_spec.coffee

- Fixes #2466 
- [Docs PR](https://github.com/cypress-io/cypress-documentation/pull/1117)
Should be part of 4.0.0

writeFile yields null

---

packages/driver/package.json
packages/driver/test/cypress/integration/commands/angular_spec.coffee

Upgrade Sinon to 7.1.1

---

package.json
packages/desktop-gui/package.json
packages/reporter/package.json
packages/runner/package.json

Upgrade deps to remove event-stream or fix at safe version

---

cli/package.json
package.json
packages/desktop-gui/package.json

Update lodash to 4.17.11

---

.gitignore
packages/desktop-gui/cypress/integration/specs_list_spec.coffee
packages/desktop-gui/src/specs/specs-list.jsx

Improve empty search results display

---

packages/extension/package.json
packages/socket/README.md

Remove obselete core-socket dep and update readme references

---

packages/launcher/lib/detect.ts
packages/launcher/package.json
packages/launcher/test/log.ts
packages/launcher/test/unit/detect_spec.ts
packages/launcher/test/unit/linux/spec.ts
packages/ts/tsconfig.json

Fix broken browser detection on Linux when 2 browsers have same version #

---

packages/driver/src/cy/commands/traversals.coffee
packages/driver/test/cypress/integration/commands/traversals_spec.coffee

Fix bug in traversals where passed function is treated as options object

---

packages/driver/package.json
packages/reporter/lib/test-setup.js
packages/reporter/package.json
packages/runner/lib/test-setup.js
packages/runner/package.json

Upgrade jsdom to 13.2.0

---

package.json
packages/server/package.json
packages/server/test/support/helpers/coverage.coffee

Hi there, vagrant is not necessary, isn't it?

Remove an unused package

---

packages/desktop-gui/cypress/integration/update_banner_spec.coffee
packages/desktop-gui/src/update/update-banner.jsx

On deskopGUI package,
1. Added a line to show 'yarn add' beneath the 'npm install' instructions 
2. Added a cy.get test for new yarn message
close #2871

closes #2871

---

circle.yml

Match the reporter cache key

---

circle.yml

Try v8 for reporter and runner caches

---

packages/server/lib/browsers/chrome.coffee
packages/server/test/unit/browsers/chrome_spec.coffee

Don't show "Restore Pages" prompt

---

packages/server/test/performance/proxy_performance.js

Store artifacts from perf tests

---

cli/lib/exec/spawn.js
cli/lib/tasks/download.js
cli/lib/util.js
cli/package.json
cli/test/lib/exec/spawn_spec.js
cli/test/lib/tasks/download_spec.js

Remove @cypress/get-windows-proxy from CLI

---

packages/server/lib/gui/menu.coffee
packages/server/test/unit/gui/menu_spec.coffee

Add Chromium Downloads to `Help` menu

---

cli/types/index.d.ts
cli/types/tests/cypress-tests.ts

Add missing `Date` to `cy.clock` typescript def

---

cli/types/index.d.ts
cli/types/tests/cypress-tests.ts
packages/driver/src/cypress/local_storage.coffee

Add typedefs for Cypress.LocalStorage.clear

---

cli/__snapshots__/errors_spec.js
cli/__snapshots__/verify_spec.js
cli/lib/errors.js
cli/lib/exec/spawn.js
cli/lib/exec/xvfb.js
cli/lib/tasks/verify.js
cli/lib/util.js
cli/test/lib/exec/spawn_spec.js
cli/test/lib/exec/xvfb_spec.js
cli/test/lib/tasks/verify_spec.js

As per X.Org, the proper capitalization is Xvfb https://www.x.org/releases/X11R7.7/doc/man/man1/Xvfb.1.xhtml

Fix mixed use of both XVFB and Xvfb to all be Xvfb

---

.vscode/terminals.json
packages/https-proxy/lib/server.coffee
packages/https-proxy/test/integration/proxy_spec.coffee
packages/https-proxy/test/spec_helper.coffee
packages/server/__snapshots__/8_network_error_handling_spec.coffee.js
packages/server/lib/request.coffee
packages/server/lib/util/ensure-url.ts
packages/server/test/e2e/8_network_error_handling_spec.coffee

Do not send requests for SNI server through upstream proxy

---

packages/server/lib/request.coffee
packages/server/test/unit/request_spec.coffee

Retry network requests on ENOTFOUND

---

packages/driver/src/cypress/log.coffee
packages/driver/test/cypress/integration/cypress/log_spec.js
packages/driver/test/cypress/support/defaults.coffee
packages/driver/test/unit_old/cypress/log_spec.coffee

Don't take snapshots when numTestsKeptInMemory is 0

---

packages/reporter/src/commands/commands.scss
packages/reporter/src/lib/variables.scss
packages/reporter/src/runnables/runnables.scss

Set min width for reporter contents

---

circle.yml
packages/server/test/performance/proxy_performance.js

Use percentiles to make proxy performance test not flaky

---

packages/server/__snapshots__/6_visit_spec.coffee.js
packages/server/test/support/fixtures/projects/e2e/cypress/integration/fast_visit_spec.coffee

One day this test will never flake...

Adjust 6_visit_spec fast_visit_spec to not flake on potential outliers

---

cli/__snapshots__/cli_spec.js
cli/lib/cli.js

Fixup usage information showing up as part of the help text.

fix(chore): fixup usage information

---

packages/server/__snapshots__/7_record_spec.coffee.js
packages/server/lib/errors.coffee
packages/server/lib/modes/record.coffee
packages/server/test/e2e/7_record_spec.coffee

Stop-gap for #4489
Also added response validation in `7_record_spec`:

Warn on createRun warning from dashboard if warning code is unknown

---

packages/desktop-gui/.eslintrc
packages/desktop-gui/cypress/integration/global_mode_spec.js
packages/desktop-gui/cypress/integration/project_mode_spec.js
packages/desktop-gui/cypress/integration/project_nav_spec.js
packages/desktop-gui/src/app/intro.scss
packages/desktop-gui/src/app/layout.jsx
packages/desktop-gui/src/app/nav.jsx
packages/desktop-gui/src/app/nav.scss
packages/desktop-gui/src/footer/_footer.scss
packages/desktop-gui/src/project-nav/browsers.jsx
packages/desktop-gui/src/project-nav/project-nav.jsx
packages/desktop-gui/src/project/project.jsx
packages/desktop-gui/src/project/project.scss
packages/desktop-gui/src/styles/components/_elements.scss
packages/desktop-gui/src/styles/components/_general.scss

Issue 869 desktop gui responsive nav

---

cli/types/index.d.ts
packages/driver/src/cy/commands/actions/type.coffee
packages/driver/src/cypress/keyboard.js
packages/driver/test/cypress/integration/commands/actions/type_spec.js

Add option to ignore special character sequences to cy.type

---

packages/server/lib/util/proxy.ts
packages/server/test/e2e/8_network_error_handling_spec.coffee
packages/server/test/unit/args_spec.coffee

Support NO_PROXY=<-loopback>, always have NO_PROXY=localhost otherwise

---

CONTRIBUTING.md

Instructions on submitting a blog previous said to just contact support - support suggested raising a PR and provided link to adding examples, updated instructions to include link to adding examples.

Update CONTRIBUTING.md to include more info on adding a blog

---

packages/driver/src/cy/commands/window.coffee
packages/driver/src/cypress/error_messages.coffee
packages/driver/test/cypress/integration/commands/window_spec.coffee

- Closes #5181
~~- [ ] Have the [type definitions](cli/types/index.d.ts) been updated with any user-facing API changes?~~
~~- [ ] Has the [cypress.schema.json](cli/schema/cypress.schema.json) been updated with any new configuration options?~~

#5181 - increasing max viewport width to 4000px

---

cli/lib/tasks/verify.js
cli/test/lib/tasks/verify_spec.js

add --no-sandbox to smoke test

---

README.md

Fixed broken License link in README
Current link goes to `/LICENSE.md`, which does not exist. File is just `/LICENSE/` so link was changed to reflect that.
Hasn't changed

Issue license readme update

---

package.json

Update package.json version to 3.5.0

---

packages/server/test/unit/ci_provider_spec.coffee

- Closes #5734
Fixes lint error.

Fix lint error.

---

packages/driver/src/cy/commands/request.coffee

Just a bit of cleanup for https://github.com/cypress-io/cypress/pull/5813

Clean up TypeError in `request.coffee`

---

packages/server/test/unit/open_project_spec.js

Fix open_project_spec

---

packages/driver/src/cypress.js
packages/driver/test/cypress/integration/commands/assertions_spec.js
packages/server/lib/util/app_data.js
packages/server/lib/util/args.js
packages/server/lib/util/ci_provider.js
packages/server/lib/util/coerce.js
packages/server/lib/util/file.js
packages/server/lib/util/fs.js
packages/server/lib/util/human_time.js
packages/server/lib/util/open.js
packages/server/lib/util/path_helpers.js
packages/server/lib/util/random.js
packages/server/lib/util/routes.js
packages/server/lib/util/saved_state.js
packages/server/lib/util/server_destroy.js
packages/server/lib/util/settings.js
packages/server/lib/util/shell.js
packages/server/lib/util/specs.js
packages/server/lib/util/status_code.js
packages/server/lib/util/stream_buffer.ts
packages/server/lib/util/system.js
packages/server/lib/util/terminal.js
packages/server/lib/util/validation.js

- Closes #5947
N/A
- Why was this change necessary?
Some files are not cleaned up after decaffeination.
- What is affected by this change?
N/A
- Any implementation details to explain?
N/A
N/A
- [NA] Have tests been added/updated?
- [NA] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [NA] Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?
- [NA] Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?

Fix hastily-done decaffs.

---

packages/server/lib/util/ci_provider.js
packages/server/test/unit/ci_provider_spec.coffee

- Collect `CI_JOB_NAME` env var from GitLab
- Useful for detecting retried jobs
- N/A

Collect GitLab CI_JOB_NAME env var

---

cli/__snapshots__/cli_spec.js
cli/lib/cli.js
packages/server/lib/browsers/chrome.ts
packages/server/lib/browsers/firefox.ts
packages/server/lib/browsers/types.ts
packages/server/lib/browsers/utils.ts
packages/server/lib/errors.coffee
packages/server/lib/modes/run.js
packages/server/test/e2e/2_headless_spec.ts

- Closes 
- adds headless + headless video recording

Firefox headless

---

cli/__snapshots__/cli_spec.js
cli/lib/cli.js

- Closes 
n/a
This got broken at some point, but was never released.

Fix cypress cache subcommands

---

package.json
packages/network/package.json
packages/server/package.json
yarn.lock

@Bkucera somehow these got out of line :open_mouth:

make `request` versions consistent

---

README.md

better support badge with cypress official color
N/A

better support badge

---

packages/driver/src/cy/commands/navigation.coffee

This fixes a regression introduced in #6459 
It's only in `develop` and hasn't been released, so it doesn't need to be in the changelog or have a tracking issue.

Fix options scope in navigation

---

packages/desktop-gui/cypress/integration/project_nav_spec.js
packages/desktop-gui/src/app/nav.scss

- Closes #7023
N/A - This is already covered by #7024 and just a continuation of that work.
#7024 fixed one CSS issue but created some more. See the gifs below.
Before:
After:
- N/A Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?

Fix Desktop GUI project nav CSS issues

---

packages/server/__snapshots__/3_plugins_spec.js

Fix failing e2e test

---

.github/PULL_REQUEST_TEMPLATE.md
packages/example/README.md

This is just fixing broken link I noticed while preparing another PR.

docs: fix broken CONTRIBUTING.md link

---

packages/server/test/support/fixtures/projects/webpack-preprocessor-awesome-typescript-loader/cypress/plugins/index.js
packages/server/test/support/fixtures/projects/webpack-preprocessor-awesome-typescript-loader/tsconfig.json

Explicitly specify types to avoid global conflicts

---

packages/server/test/e2e/2_cookies_spec.coffee

n/a
previously, all cookies e2e tests would run twice, once with forced
browser SameSite strictness, and once without.
this pushed the total chunk 2 e2e test time in firefox to ~12 minutes!
now, only 1 e2e test will run with forced SameSite strictness, which
will vastly improve the e2e test runtime.

chore(tests): only run 1 e2e test with forced SameSite support

---

DEPLOY.md

Improvements to the internal deploy doc, hopefully making it easier for future deployers (including myself 😀).

Improvements to deploy doc

---

packages/reporter/src/errors/errors.scss

- Closes #7499 
- Improved the design of the code frame file path
Before:
After:
- N/A Have API changes been updated in the [`type definitions`](cli/types/cypress.d.ts)?

Improve code frame file path design

---

packages/reporter/src/errors/errors.scss

- N/A - is pre-release version change
before: 
after:
- [na] Have API changes been updated in the [`type definitions`](cli/types/cypress.d.ts)?

fix: remove word breaks in error locations

---

packages/server/lib/errors.js
packages/server/lib/util/strip_indent.js
packages/server/lib/util/strip_indent.ts
packages/server/test/unit/util/strip_indent.ts

- Closes #7629
Clean up decaff result.
- Why was this change necessary? Readability
N/A
- [N/A] Have tests been added/updated?
- [N/A] Have API changes been updated in the [`type definitions`](cli/types/cypress.d.ts)?
- [N/A] Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?

chore: fix server/lib/errors.js readability.

---

packages/server/lib/modes/run.js

n/a
- just some extra cleanup
- minimizes diff from #7714 
n/a
- [na] Have API changes been updated in the [`type definitions`](../cli/types/cypress.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](../cli/schema/cypress.schema.json)?

chore: clean up postProcessRecording code

---

packages/reporter/cypress/integration/test_errors_spec.js
packages/reporter/cypress/support/utils.js
packages/reporter/src/collapsible/collapsible.tsx
packages/reporter/src/commands/commands.scss
packages/reporter/src/errors/errors.scss
packages/reporter/src/errors/test-error.tsx
packages/reporter/src/header/header.scss
packages/reporter/src/opener/file-opener.tsx
packages/reporter/src/runnables/runnable-header.tsx
packages/reporter/src/runnables/runnables.scss

- Closes #7732
Some minor UI updates and tweaks to improve the appearance and functionality of recently added enhancements.
See comment with screenshots below

Improvements to recently added UI updates

---

packages/server/package.json
yarn.lock

Fixes failing tests in Firefox >= 75.

Upgrade @benmalka/foxdriver to 0.4.1

---

DEPLOY.md

https://github.com/cypress-io/cypress/pull/8071#pullrequestreview-454136175

docs: NPM -> npm

---

packages/electron/package.json
yarn.lock

Latest version for 5.0.0 release
- Closes

fix(deps): electron@9.2.0

---

circle.yml
packages/server/package.json
scripts/binary/zip.js

n/a
- Should fix the issue with patches not getting applied to the built binary.

fix: add patches to package files

---

cli/types/cypress.d.ts

Fixes typos in type definitions
Fixes some typos in the Typescript definitions
```diff
- TestCptions
+ TestOptions
```
- [n/a] Has the original issue been tagged with a release in ZenHub? 

chore: Fixes type definitions

---

cli/schema/cypress.schema.json
cli/types/cypress.d.ts
packages/driver/cypress.json
packages/driver/cypress/integration/commands/net_stubbing_spec.ts
packages/driver/src/cy/commands/navigation.js
packages/driver/src/cy/commands/waiting.js
packages/driver/src/cy/net-stubbing/add-command.ts
packages/driver/src/cypress/error_messages.js
packages/server/lib/config.js
packages/server/lib/experiments.ts
packages/server/test/unit/config_spec.js

chore: rename experimental network stubbing

---

packages/net-stubbing/lib/server/intercept-request.ts

Addendum to https://github.com/cypress-io/cypress/commit/c37896089b23bd083c9fae5770ea638f87b0deb8 (https://github.com/cypress-io/cypress/pull/4176)

chore: fix typo

---

packages/reporter/src/commands/commands.scss

N/A - flipped progress bar from #8522 was never released

chore: flip progress bar on commands

---

.github/workflows/merge-master-into-develop.yml
.releaserc.json
lerna.json
package.json
patches/semantic-release-monorepo+7.0.3.patch
scripts/changed-packages.js
scripts/import.js
scripts/inject-npm-version.js
scripts/semantic-release.js
yarn.lock

Basics for getting the monorepo up and running!
* Adds external packages to lerna and yarn workspaces
* Import script for importing package with full commit history
* Semantic release for individual packages within the monorepo
* Automated semantic release deployment on CI

chore: set up monorepo

---

.github/workflows/merge-master-into-develop.yml
.releaserc.json
lerna.json
package.json
patches/semantic-release-monorepo+7.0.3.patch
scripts/changed-packages.js
scripts/import.js
scripts/inject-npm-version.js
scripts/semantic-release.js
yarn.lock

chore: merge branch 'develop'

---

packages/net-stubbing/lib/external-types.ts

- Closes #8694 
Improved types for the `cy.route2` `IncomingHttpRequest` object and request/response interceptor functions.

chore(types): update net-stubbing req object types

---

packages/net-stubbing/lib/external-types.ts

- Closes 
Improved `cy.route2` type docs.
- comments were updated in https://github.com/cypress-io/cypress-documentation/pull/3202
- this PR pulls those changes back into the actual types so they are consistent

fix(types): improve typedocs for cy.route2

---

packages/driver/cypress/integration/commands/navigation_spec.js
packages/driver/cypress/integration/commands/net_stubbing_spec.ts
packages/runner/cypress/integration/retries.ui.spec.js
packages/runner/cypress/integration/runner.ui.spec.js
packages/server/test/e2e/6_video_compression_spec.js
packages/server/test/e2e/7_record_spec.js

chore: adding retries to fix flaky specs

---

npm/webpack-preprocessor/README.md

docs: Fix typo in README

---

scripts/inject-npm-version.js

chore: better debug logs for semrel

---

packages/net-stubbing/lib/server/intercept-request.ts

- Closes no-issue
- Preparation for #8560.
N/A
- Why was this change necessary? => Refactoring before adding new code.
- What is affected by this change? => Make loop faster by adding short circuit.
N/A
- [N/A] Have tests been added/updated?

chore: Short circuit _doesRouteMatch().

---

.gitignore
npm/react/package.json
npm/vue/package.json
npm/webpack-preprocessor/package.json
scripts/npm-release.js

fix: adding build-prod tasks to all of the npm dependencies that need artifacts

---

appveyor.yml
circle.yml
scripts/win-appveyor-build.js

chore(ci): build v6.0-release branch like develop

---

packages/driver/src/cy/net-stubbing/events/response-received.ts

fix(net-stubbing): fix empty array stubs getting merged with real response

---

packages/example/package.json
yarn.lock

chore: Upgrade cypress-example-kitchensink to 1.13.0

---

packages/server-ct/example/plugins.js
packages/server-ct/index.js
packages/server-ct/src/project-ct.js
packages/server/lib/config.js

Here is a quick fix, tell me what you think

fix: when returning config in a plugin file, we get an error about missing browsers

---

packages/server-ct/src/server-ct.ts

Far from perfectly typed, but good enough for now

chore(component-testing): CT-140 start TS migration

---

packages/server-ct/index.js
packages/server-ct/src/project-ct.ts
packages/server-ct/src/server-ct.ts

Just move to TS, no change in behavior.

chore(component-testing): CT-141 update project-ct

---

CONTRIBUTING.md

- Closes #9740  
New contributors won't be redirected to broken links to issue templates

docs: links to issue template in contributing guideline

---

npm/react/package.json
yarn.lock

- Closes 
Updates dependencies used by @cypress/react to match latest version from cypress-react-unit-test instead of a regression

fix(deps): update dependencies in @cypress/react

---

packages/runner-ct/package.json
packages/runner-ct/src/.eslintrc.json
packages/runner-ct/src/lib/state.spec.ts
packages/runner-ct/src/lib/state.ts
packages/runner-ct/src/specs/make-spec-hierarchy.ts
packages/runner-ct/src/specs/spec-group.jsx
packages/runner-ct/src/specs/spec-item.jsx
packages/runner-ct/src/specs/specs-list.tsx
packages/runner-ct/test/.mocharc.js
packages/runner-ct/test/setup.js

Matches against the name of the spec, simple but useful. I got to learn some mobx. I also changed the files I edited to TypeScript. I wrote a unit test for now, I hope we can test this using Cypress itself soon.

feat: search input to filter specs

---

npm/react/package.json

- Closes #14305
Fixes an incorrect peerDependencyMeta in @cypress/react, which prevented it from being installed with Yarn 2.
I have not tried to verify the correctness of the package.json code surrounding this; I only know that this fixes the error upon installation.
This makes the package installable with Yarn 2.

fix: Correct typo in @types/react peerDependencyMeta entry

---

DEPLOY.md
scripts/binary/build.js

- Closes 
n/a
- IDK what this was, but it no longer exists and does not appear to be necessary

chore(docs): remove binary-build-linux references

---

npm/react/cypress/plugins/index.js
npm/react/cypress/support/index.js
npm/react/package.json
npm/react/src/hooks.ts
npm/react/src/mount.ts
npm/react/support/index.js
npm/vue/cypress/component/advanced/fetch-polyfill/Users.spec.js
npm/vue/cypress/component/advanced/mocking-axios/3-Users.spec.js
npm/vue/cypress/component/basic/code-coverage/Calculator-spec.js
npm/vue/cypress/component/basic/code-coverage/unit-spec.js
npm/vue/cypress/component/support.spec.js
npm/vue/cypress/plugins/index.js
npm/vue/package.json
npm/vue/src/index.ts
npm/webpack-dev-server/tsconfig.json

* Xdescribes broken features for Vue + React
* Swaps React to use the new component testing framework
* resolves broken webpack-dev-server transpilation

chore: Fixing react + vue component tests

---

.github/ISSUE_TEMPLATE/1-bug-report.md

- Closes 
Changed the issue template to suggest upgrading Cypress before opening a ticket.

chore: Suggest upgrading Cypress to latest version before opening a bug ticket

---

npm/webpack-batteries-included-preprocessor/index.js

- Closes #8864 
- Fixed an issue where the presence of a `browserslist` file would cause file preprocessing to error.
- N/A Have tests been added/updated? _Wasn't able to create an e2e test that failed before this fix, due to the way that e2e are different from production Cypress_

fix: ignore browserslist file

---

cli/lib/tasks/install.js
cli/test/lib/tasks/install_spec.js

- Closes #4595
- Fixed an issue that could cause failure when installing two Cypresses at the same time.

fix(cli): use per-pid filename for downloaded cypress zip

---

scripts/get-next-version.js

Restricts get-next-version to only consider code related to cli or TR packages.

chore: restrict get-next-version to packages and cli dirs

---

cli/package.json
package.json
packages/launcher/package.json
packages/server/lib/exec.js
packages/server/package.json
yarn.lock

N/A
Everyone who installs cypress gets an old version of ramda installed, resuling in multiple versions of the same package being installed
It hasn't

chore: update ramda to 0.27.1

---

packages/runner-ct/src/SpecList/components/SearchSpec.scss
packages/runner-ct/src/SpecList/components/SearchSpec.tsx

https://user-images.githubusercontent.com/5592465/108743833-da6ca300-74fe-11eb-984f-9383424eb23d.mov

feat: use search input type f/ find spec field

---

packages/runner-ct/src/app/RunnerCt.scss
packages/runner-ct/src/app/RunnerCt.tsx

- Closes: https://cypress-io.atlassian.net/browse/CT-309
Slight improved styling.
- The plugin area is small and hard to see/click. This change make the plugins area easier to expand by making the entire surface area clickable.
It has not changed.
None.

chore(component-testing): tweak styling for plugins

---

npm/vite-dev-server/cypress/components/Foo.tsx
npm/vite-dev-server/cypress/components/react-no-jsx.spec.jsx
npm/vite-dev-server/cypress/components/react-no-jsx.spec.ts
npm/vite-dev-server/cypress/components/react-no-jsx.spec.tsx

Add some additional tests to the vite-dev-server for React and jsx/tsx.

chore: add some tsx/jsx tests

---

packages/runner-ct/src/app/RunnerCt.tsx
packages/runner-ct/src/lib/state.ts

feat: resize speclist

---

npm/design-system/src/components/Nav/LeftNav.spec.tsx
npm/design-system/src/components/Nav/LeftNav.tsx
npm/design-system/src/components/Nav/types.ts
packages/runner-ct/src/app/RunnerCt.tsx
packages/server/lib/socket-base.ts

I also refactored the LeftNav to make it more type-safe.
Because runner-ct does not launch an electron process, I changed the code to just launch an external browser via child_process.

fix(runner-ct): open link in external browser

---

npm/design-system/package.json

build: fix watch mode

---

npm/react/cypress/component/viewport-spec.jsx

There was a bug in the build process that let this test failure slip by the PR status checks.

fix: removing test for previous undesireable behavior

---

npm/react/CHANGELOG.md

chore: update changelog with breaking changes

---

npm/webpack-dev-server/src/aut-runner.ts

fix: bring back cleanup

---

packages/electron/package.json

- Closes 
Updated Electron to 12.0.2.

chore(deps): electron@12.0.2

---

packages/server/lib/gui/windows.ts
yarn.lock

- Closes 
- https://github.com/cypress-io/cypress/pull/16113 probably introduced this 
- was never released, but fixes this error on desktop-gui launch:

fix: pass contextIsolation: true

---

npm/cypress-schematic/README.md
npm/cypress-schematic/src/schematics/cypress/files/cypress.json

- updated README with usage examples

fix: update schematic readme with examples

---

npm/cypress-schematic/README.md
npm/cypress-schematic/package.json
npm/cypress-schematic/src/schematics/cypress/index.ts

- add check to make sure e2e folder exists to avoid deletion error
- add link to plugins discussion and inspiration in README

fix: angular schematic readme update. add check to make sure e2e folder exists to avoid deletion error.

---

packages/launcher/__snapshots__/browsers_spec.ts.js
packages/launcher/__snapshots__/darwin_spec.ts.js
packages/launcher/__snapshots__/windows_spec.ts.js
packages/launcher/lib/browsers.ts
packages/launcher/lib/darwin/index.ts
packages/launcher/lib/windows/index.ts
packages/launcher/test/unit/windows_spec.ts
packages/ui-components/src/browser-icon.tsx
yarn.lock

- Closes #16376
- Cypress now detects and supports testing in [Chrome Beta](https://www.google.com/chrome/beta/)
We now detect and display Chrome Beta as an option.

feat: Add support for Chrome Beta

---

circle.yml

See https://github.com/cypress-io/cypress/pull/16289#issuecomment-843743407

chore: switch percy_finalize job to small

---

circle.yml
packages/server/__snapshots__/5_headless_spec.ts.js
packages/server/test/e2e/5_headless_spec.ts
packages/server/test/e2e/6_video_compression_spec.js
packages/server/test/support/helpers/e2e.ts
patches/snap-shot-it+7.9.3.patch
scripts/run-docker-local.sh

- Closes 
- enables us to use the Remote Protocol work that is available as of FF86
- for now we can ignore the video processing errors in e2e tests...
- skipping 6_video_compression spec in FF since video recording is broken

chore: use cypress/browsers:node14.16.0-chrome90-ff88

---

appveyor.yml
circle.yml
packages/runner-ct/package.json
packages/runner/package.json
packages/server/lib/open_project.ts
packages/server/lib/project-base.ts
scripts/binary/util/packages.js

- Closes #17944 
- Improved the file size of the Cypress binary
This keeps unnecessary source files from being included in the binary. It keeps the source files from `runner-ct` from being copied. It also prevents packages like the `driver`, `reporter`, and `ui-components` from having any files copied into the binary at all, since their files are bundled into the runner and desktop-gui at build-time.
The binary file size will be smaller, but probably not by a significant amount.
- …

chore: Prevent unnecessary files from being included in the binary

---

appveyor.yml
circle.yml
package.json
scripts/win-appveyor-build.js
yarn.lock

- Closes 
n/a
Fixes failures: https://ci.appveyor.com/project/cypress-io/cypress/builds/40745860
See https://github.com/bahmutov/make-empty-github-commit/pull/15 for details on why this broke our CI process.

chore: update make-empty-github-commit to fix test-other-projects

---

packages/launchpad/src/global/GlobalPage.vue
packages/launchpad/src/global/GlobalProjectCard.vue

Use a fragment to get better type definitions.

chore(laucnhpad): improve types using fragment

---

packages/data-context/src/actions/ProjectActions.ts
packages/data-context/src/data/coreDataShape.ts
packages/frontend-shared/cypress/support/mock-graphql/stubgql-Mutation.ts
packages/graphql/schemas/schema.graphql
packages/graphql/src/schemaTypes/objectTypes/gql-CurrentProject.ts
packages/graphql/src/schemaTypes/objectTypes/gql-Mutation.ts

Removes unused code in the launchpad / app

chore: remove dead code

---

packages/app/src/navigation/KeyboardBindingsModal.spec.tsx
packages/app/src/navigation/KeyboardBindingsModal.vue
packages/app/src/navigation/SidebarNavigation.vue
packages/frontend-shared/src/components/StandardModalHeader.vue
packages/frontend-shared/src/locales/en-US.json

- Closes https://cypress-io.atlassian.net/browse/UNIFY-554
https://user-images.githubusercontent.com/5592465/141024631-f4366dde-23a7-4bdc-a3d9-157e0216d5bd.mov
- When the help link of a modal is forced to empty, I hide the help link.

feat: setup keyboard shortcuts modal

---

packages/data-context/src/actions/FileActions.ts
packages/data-context/src/actions/ProjectActions.ts
packages/data-context/src/data/coreDataShape.ts
packages/data-context/src/sources/ProjectDataSource.ts
packages/frontend-shared/cypress/support/mock-graphql/stubgql-Mutation.ts
packages/graphql/schemas/schema.graphql
packages/graphql/src/schemaTypes/objectTypes/gql-Mutation.ts
packages/launchpad/cypress/e2e/integration/config-files-error-handling.spec.ts

feat: Create default config file

---

appveyor.yml

Update the yaml file with the new branch name

fix: 10.0 appveyor updateyaml

---

CONTRIBUTING.md

- Closes 
n/a
Fix a minor typo in CONTRIBUTING.md
n/a

docs: Fix a minor typo in CONTRIBUTING.md

---

.vscode/cspell.json
.vscode/extensions.json
.vscode/settings.json
CONTRIBUTING.md
circle.yml
cli/package.json
package.json
packages/app/src/specs/InlineSpecList.vue
packages/app/src/specs/InlineSpecListTree.spec.tsx
packages/app/src/specs/InlineSpecListTree.vue
packages/app/src/specs/SpecsList.spec.tsx
packages/app/src/specs/SpecsList.vue
packages/frontend-shared/cypress/support/mock-graphql/stubgql-Project.ts
packages/frontend-shared/src/composables/useVirtualList.ts
packages/frontend-shared/src/composables/useVirtualListNavigation.ts
packages/https-proxy/package.json
packages/network/package.json
packages/proxy/package.json
packages/server/package.json
system-tests/lib/system-tests.ts
system-tests/package.json
yarn.lock

chore: merging in from develop into 10.0-release

---

packages/app/src/specs/CustomPatternNoSpecContent.vue
packages/app/src/specs/NoSpecsPage.spec.tsx
packages/app/src/specs/NoSpecsPage.vue
packages/app/src/specs/SpecPatterns.spec.tsx
packages/app/src/specs/SpecPatterns.vue
packages/frontend-shared/cypress/e2e/support/e2eProjectDirs.ts
packages/frontend-shared/src/locales/en-US.json
packages/graphql/schemas/cloud.graphql
packages/graphql/schemas/schema.graphql

I want to use this spec pattern component in another component, so I moved it to a separate component.

refactor: extract spec pattern component

---

packages/data-context/src/sources/GitDataSource.ts
packages/graphql/src/schemaTypes/objectTypes/gql-CurrentProject.ts

- Closes 
Fix array length filled with null when there's an error getting the source control for some files

feat: Fix gitInfo dataLoader error handler

---

packages/app/cypress.config.ts
packages/frontend-shared/cypress.config.ts
packages/launchpad/cypress.config.ts

Avoid the project not found error.

build: connect to real project in staging

---

circle.yml

[#19037](https://github.com/cypress-io/cypress/pull/19037) has been merged. Clean up the branch name from the CircleCI configuration.
n/a
n/a

chore: Clean up CircleCI Configuraiton

---

README.md
npm/create-cypress-tests/src/component-testing/init-component-testing.ts
npm/cypress-schematic/README.md
npm/react/CHANGELOG.md
npm/react/examples/find-webpack/README.md
npm/vue/examples/vue-cli/README.md
packages/app/src/settings/project/Config.vue
packages/app/src/settings/project/ConfigLegend.vue
packages/app/src/settings/project/Experiments.vue
packages/app/src/settings/project/ProjectId.vue
packages/app/src/settings/project/RecordKey.vue
packages/app/src/settings/project/SpecPatterns.vue
packages/app/src/specs/generators/GeneratorSuccess.spec.tsx
packages/data-context/src/sources/WizardDataSource.ts
packages/frontend-shared/src/components/StandardModal.vue
packages/frontend-shared/src/gql-components/topnav/DocsMenuContent.vue
packages/launchpad/src/components/code/FileRow.vue
packages/launchpad/src/error/BaseError.spec.tsx
packages/launchpad/src/error/BaseError.vue

- Closes  [UNIFY-608](https://cypress-io.atlassian.net/jira/software/projects/UNIFY/boards/20?assignee=5ea883deddd45f0b94f5d98d&selectedIssue=UNIFY-608)

feat: update on-links

---

packages/app/src/navigation/SidebarNavigation.vue

fix: local component state is getting reset when the sidebar requeries.

---

packages/app/src/App.vue
packages/app/src/layouts/default.vue
packages/frontend-shared/src/gql-components/ExternalLink.vue
packages/frontend-shared/src/gql-components/HeaderBarContent.vue
packages/frontend-shared/src/gql-components/topnav/TopNav.vue

The vertical align of the header was off. Also fixed ExternalLinks so that they open (like real links do) when you do keyboard nav.

fix: external links, max width, and topnav alignment

---

packages/app/src/specs/DirectoryItem.vue
packages/app/src/specs/InlineSpecList.spec.tsx
packages/app/src/specs/InlineSpecList.vue
packages/app/src/specs/InlineSpecListHeader.spec.tsx
packages/app/src/specs/InlineSpecListHeader.vue
packages/app/src/specs/InlineSpecListTree.spec.tsx
packages/app/src/specs/InlineSpecListTree.vue
packages/app/src/specs/SpecFileItem.vue
packages/frontend-shared/src/composables/useCollapsibleTree.ts
packages/frontend-shared/src/composables/useVirtualListNavigation.ts

I'm going to switch onto the Specs List on the Index page in a moment, so I want to get this in here and then do the refactor to make it generic in another PR
https://user-images.githubusercontent.com/2801156/144541181-5251fb1e-cc39-429d-8974-3dd4d64fc85f.mov

feat(specs-list): improving focus management and keyboard handling of the specs list.

---

packages/launchpad/src/global/FileDropzone.vue

- Closes  [UNIFY-579](https://cypress-io.atlassian.net/jira/software/projects/UNIFY/boards/20?selectedIssue=UNIFY-579)

feat: Remove uploadName div

---

packages/frontend-shared/src/styles/shared.scss

- Closes [UNIFY-636](https://cypress-io.atlassian.net/browse/UNIFY-636)

fix: times new roman and gray background persisting from Runner page

---

packages/app/cypress/e2e/integration/settings.spec.ts
packages/data-context/src/actions/ProjectActions.ts
packages/frontend-shared/cypress/e2e/e2ePluginSetup.ts
packages/frontend-shared/cypress/e2e/support/e2eProjectDirs.ts
packages/graphql/schemas/cloud.graphql
packages/graphql/schemas/schema.graphql
packages/server/lib/server-e2e.ts
packages/server/test/performance/proxy_performance_spec.js
packages/server/test/spec_helper.js

#19308 was merged without all tests passing - this should fix the final failures

fix: CI Fixes related to #19308

---

packages/app/src/composables/usePreferences.ts
packages/app/src/store/runner-ui-store.ts

We can have type safety on the preference and argument like this

chore: types for unify-628

---

packages/app/src/settings/project/Config.vue
packages/app/src/settings/project/ConfigLegend.spec.tsx
packages/app/src/settings/project/ConfigLegend.vue
packages/app/src/specs/CustomPatternNoSpecContent.vue
packages/app/src/specs/DefaultSpecPatternNoContent.vue
packages/app/src/specs/NoSpecsPage.spec.tsx
packages/app/src/specs/SpecPatterns.vue
packages/data-context/src/data/ProjectConfigIpc.ts
packages/data-context/src/data/ProjectLifecycleManager.ts
packages/frontend-shared/src/gql-components/OpenConfigFileInIDE.vue
packages/launchpad/src/error/BaseError.spec.tsx
packages/launchpad/src/error/BaseError.vue
packages/server/lib/modes/run-ct.ts
packages/server/lib/modes/run.js
packages/server/lib/plugins/child/RunPlugins.js
packages/types/src/server.ts
system-tests/__snapshots__/config_spec.js

fix: fix refactor lifecycle run mode for CT

---

packages/electron/package.json
yarn.lock

- Closes #19365 
N/A
electron-packager is used in the postinstall process when doing local development on the cypress runner. The platform restrictions were updated in version 15.1.0 to allow for darwin/arm64, which is what the M1 macs are. Prior to this version, the postinstall process fails with
> The platform/arch combination darwin/arm64 is not currently supported by Electron Packager
Relevant change to electron-packager here: https://github.com/electron/electron-packager/commit/bd88cc01870bc24d2a95be43f368612d9c9605c7
N/A …

fix: Update electron-packager to support development on M1 Macs

---

guides/release-process.md

- Closes n/a
n/a
Updating the release-process guide to include a link to how to update the `cypress-docker-images` repo. I also made some minor formatting updates too.
n/a

chore: Update release-process document [skip ci]

---

CONTRIBUTING.md

docs: fix typo in CONTRIBUTING.md 

---

scripts/binary/meta.ts

Fix build path for electron-builder on arm64 linux
N/A
Not for users but for cypress developers: allow compiling the binary on arm64 linux
I have read the below but I think all of them are not applicable

chore: Fix build path for electron-builder on arm64 linux

---

packages/server/lib/plugins/child/browser_launch.js
packages/server/lib/plugins/child/run_plugins.js
packages/server/test/unit/plugins/child/run_plugins_spec.js
yarn.lock

- Related to #18914 & #19320
While investigating the above issues, it was asked why the OpenSSL error message wasn't up-front for consumers to reference.
Surface openSSL unhandled rejection errors that occur within plugin code to provide error message and stack trace for debugging.
**Previous behavior**
The error previously observed by consumers:
Error received by server when running DEBUG=cypress:* 
Further investigation shows our serialized error removed the error
**New behavior**
- [n/a] Have new configuration …

fix: surface openSSL unhandled rejection errors that occur within plugin code

---

packages/app/src/runner/ResizablePanels.vue

Adds a CSS class to fix the position of the snapshot pinning UI and its container element. This corrects the positioning of the UI on the screen and some side effects from having the container bleed over other elements.
- [na] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/sc …

fix(unify): correct location of snapshot pinning UI in runner

---

packages/runner/src/app/app.scss

- Closes https://github.com/cypress-io/cypress/issues/16788
I've cherry-picked https://github.com/cypress-io/cypress/pull/18649 as discussed in https://github.com/cypress-io/cypress/issues/16788#issuecomment-1009493900

fix: overflow clip to prevent selector header from disapearing (#18649)

---

packages/driver/cypress/integration/commands/commands_spec.js
packages/driver/src/cypress/commands.ts

See discussion in https://github.com/cypress-io/cypress/pull/19145#discussion_r779831860

feat: Allow Cypress.Commands.add on hover & mount

---

package.json
packages/app/package.json

N/A
This is a small fix for being able to run the dev task in the app packages to ensure that cypress in cypress works properly.
N/A

fix: dev task for running cypress in cypress in the app package

---

npm/angular/lib/index.ts
npm/create-cypress-tests/src/findPackageJson.ts
npm/cypress-schematic/src/builders/cypress/index.ts
npm/cypress-schematic/src/schematics/ng-generate/e2e/schema.ts
npm/cypress-schematic/src/schematics/utility/dependencies.ts
npm/cypress-schematic/src/schematics/utility/jsonFile.ts
npm/design-system/src/components/searchInput/SearchInput.tsx
npm/design-system/src/components/virtualizedTree/VirtualizedTree.tsx
npm/design-system/src/components/virtualizedTree/VirtualizedTreeChild.tsx
npm/design-system/src/components/virtualizedTree/types.ts
npm/design-system/src/core/input/InputBase.tsx
npm/design-system/src/core/surface/elevation/Elevation.stories.tsx
npm/design-system/src/core/surface/paddedBox/PaddedBox.stories.tsx
npm/eslint-plugin-dev/lib/index.js
npm/react/src/mount.ts
package.json
packages/driver/src/cy/keyboard.ts
packages/driver/src/cy/listeners.ts
packages/network/lib/agent.ts
packages/server/lib/socket-base.ts
yarn.lock

N/A - dev-only chore
This fixes the following ["error" message that pops up in VSCode](https://github.com/microsoft/vscode-eslint/issues/1149) any time you type `const` in a TypeScript file. 
It accomplishes this by switching to `@typescript-eslint/indent` for `.ts/.tsx`. It caught some issues with indentation in our TypeScript files (some had 3 space indentation?), which is why there are a number of file changes. Some of the changes are more innocuous/arbitrary, as it seems to behave a bit differently from the regular eslint indent rule.
- N/A Has a PR for user-facing changes been opened in …

chore: Use @typescript-eslint/indent instead of eslint's indent

---

cli/types/cypress-eventemitter.d.ts
packages/driver/cypress/fixtures/multi-domain.html
packages/driver/cypress/integration/e2e/multi-domain/commands/multi_domain_actions.spec.ts
packages/driver/cypress/integration/e2e/multi-domain/commands/multi_domain_misc.spec.ts

n/a
Added test for new `cy.selectFile()` command in multi-domain

chore: adding test for selectFile() in multi-domain

---

cli/types/cypress-eventemitter.d.ts
cli/types/cypress.d.ts
cli/types/tests/cypress-tests.ts
npm/angular/lib/index.ts
npm/create-cypress-tests/src/findPackageJson.ts
npm/cypress-schematic/src/builders/cypress/index.ts
npm/cypress-schematic/src/schematics/ng-generate/e2e/schema.ts
npm/cypress-schematic/src/schematics/utility/dependencies.ts
npm/cypress-schematic/src/schematics/utility/jsonFile.ts
npm/design-system/src/components/searchInput/SearchInput.tsx
npm/design-system/src/components/virtualizedTree/VirtualizedTree.tsx
npm/design-system/src/components/virtualizedTree/VirtualizedTreeChild.tsx
npm/design-system/src/components/virtualizedTree/types.ts
npm/design-system/src/core/input/InputBase.tsx
npm/design-system/src/core/surface/elevation/Elevation.stories.tsx
npm/design-system/src/core/surface/paddedBox/PaddedBox.stories.tsx
npm/eslint-plugin-dev/lib/index.js
npm/react/src/mount.ts
package.json
packages/driver/cypress/fixtures/multi-domain.html
packages/driver/cypress/integration/e2e/multi-domain/commands/multi_domain_actions.spec.ts
packages/driver/cypress/integration/e2e/multi-domain/commands/multi_domain_misc.spec.ts
packages/driver/cypress/integration/e2e/multi-domain/multi_domain_spec.ts
packages/driver/src/cy/keyboard.ts
packages/driver/src/cy/listeners.ts
packages/driver/src/cy/multi-domain/index.ts
packages/driver/src/cypress/error_messages.ts
packages/network/lib/agent.ts
packages/server/lib/socket-base.ts
yarn.lock

- Closes #19708 
n/a
* Updated the `switchToDomain` `data` argument to be an array
* The array can be of any type including mixed types
* If an array is not passed, an error is thrown notifying the user the `data` argument must be an array

chore: update switchToDomain 'data' argument to be an array

---

packages/app/cypress/e2e/index.cy.ts

Skip test that was enabled due to date being exceeded

chore: skip fixed-date test

---

packages/app/cypress/e2e/settings.cy.ts
packages/app/src/settings/project/ProjectSettings.vue
packages/app/src/settings/project/RecordKey.cy.tsx
packages/app/src/settings/project/RecordKey.vue

- Closes UNIFY-862
The manage keys button is now pointing to the current cloud project's settings page.

feat: wire up the manage record keys button

---

package.json
packages/data-context/package.json
packages/data-context/test/integration/data-context.spec.ts
packages/data-context/test/unit/test.spec.ts

- Closes 
- Seems like these aren't running in CI. They do pass locally.

test: run data-context unit tests in CI

---

guides/release-process.md

We need to add more guidance until https://github.com/cypress-io/cypress/issues/19771 can be investigated.

chore: Update release process guide with findings from 9.3.0 release

---

packages/app/cypress.config.ts
packages/launchpad/cypress/e2e/project-setup.cy.ts

Need some extra tabs now that the tabindex has been fixed for cards

fix(unify): Fixing launchpad project setup tests

---

system-tests/projects/migration-component-testing/README.md
system-tests/projects/migration-e2e-custom-integration/README.md
system-tests/projects/migration-e2e-custom-integration/cypress.json
system-tests/projects/migration-e2e-custom-test-files/README.md
system-tests/projects/migration-e2e-custom-test-files/cypress.json
system-tests/projects/migration-e2e-fully-custom/README.md
system-tests/projects/migration-e2e-fully-custom/cypress.json

Added a project to represent all the different projects we need to support in the migration workflow.
Related: https://cypress-io.atlassian.net/browse/UNIFY-979

chore: add test cases for migration

---

.github/ISSUE_TEMPLATE/1-bug-report.yml

https://youtu.be/NnriKHmj5T8
- Closes

chore: add link to the video how to report Cypress bug

---

packages/server/.gitignore
packages/server/package.json
system-tests/package.json
system-tests/test/network_error_handling_spec.js
yarn.lock

- Closes #20057 
- Looked at all the failing system-tests jobs to see what they all had in common. `network_error_handling_spec` was the spec all the failing jobs had in common.
- Used `wtfnode` to see what was preventing the process from exiting, ended up being the mitm proxy on 13371
- `mitmProxy.close` is broken, so switched to using the debugging proxy for the purposes of forcing TE: chunked: https://github.com/joeferner/node-http-mitm-proxy/issues/184
- Still not sure why this only affected contrib PRs or when it began affecting them.
- Check the PRs linked in #20057 to see the fix in action - I cherry-picked it to the 3 PRs mentioned there.
- [na] Has a PR …

test: fix network_error_handling_spec for external contributors

---

packages/app/src/main.scss
packages/app/src/navigation/SidebarTooltip.vue
packages/app/src/runner/SpecRunnerOpenMode.vue
packages/app/src/runner/SpecRunnerRunMode.vue
packages/app/src/specs/InlineSpecListHeader.cy.tsx
packages/app/src/specs/InlineSpecListHeader.vue
packages/app/src/specs/InlineSpecListTree.vue
packages/app/src/specs/SpecsListHeader.cy.tsx
packages/app/src/specs/SpecsListHeader.vue
packages/frontend-shared/src/components/Card.vue
packages/frontend-shared/src/components/StandardModal.cy.tsx
packages/frontend-shared/src/components/StandardModal.vue
packages/frontend-shared/src/components/StatusBadge.vue
packages/frontend-shared/src/gql-components/HeaderBarContent.vue
packages/frontend-shared/src/gql-components/topnav/DocsMenuContent.vue
packages/frontend-shared/src/gql-components/topnav/TopNav.vue
packages/frontend-shared/src/locales/en-US.json
packages/frontend-shared/src/styles/shared.scss
packages/launchpad/src/Main.vue
packages/launchpad/src/global/GlobalProjectCard.vue
packages/launchpad/src/setup/CompareTestingCard.vue
packages/launchpad/src/setup/CompareTestingTypes.cy.tsx
packages/launchpad/src/setup/CompareTestingTypes.vue
packages/launchpad/src/setup/OpenBrowserList.vue

fix: firefox tooltip styles were broken for wide text

---

circle.yml
packages/app/cypress/e2e/index.cy.ts
packages/app/src/specs/generators/EmptyGenerator.vue

na
Fixes failing app e2e tests
na

test: fix failing app integration tests

---

packages/app/cypress/e2e/specs_list_e2e.cy.ts

test: Update specs_list_e2e.cy.ts

---

packages/driver/cypress/integration/e2e/multi-domain/commands/multi_domain_misc.spec.ts

- Closes 
n/a
Quick PR to fix the command misc spec, seems they're not out of order in the feature branch

chore: [Multi-domain]: Fix misc test

---

packages/data-context/package.json
packages/data-context/test/unit/helper.ts
packages/data-context/test/unit/sources/migration/autoRename.spec.ts
packages/data-context/test/unit/sources/migration/shouldShowSteps.spec.ts
packages/data-context/test/unit/util/migration.spec.ts

- Closes 
n/a
Cleaning this up to reuse existing fixtures code.

test: clean up scaffoldMigrationProject

---

circle.yml

- Closes 
n/a
- This avoids the issues around using `choco install` when Chrome has updated, see: [gep13.co.uk/blog/chocolatey-error-hashes-do-not-match](https://www.gep13.co.uk/blog/chocolatey-error-hashes-do-not-match)
- [Relevant Slack convo](https://cypressio.slack.com/archives/C01TQQCQLJY/p1644364807665819?thread_ts=1644360498.326039&cid=C01TQQCQLJY)
- With `--ignore-checksums` off, someone would still have to compromise Google's https downloads server to hijack this install, so I think we should be safe.
- There appear to be some unrelated persistent failures in `windows-run-x-integration-tests-chrome` since merging of #20063. Shouldn't block this PR.
- [na] Has the original issue (or this PR, if no issue exists) been tagged with a release in …

chore: ignore checksums when installing Chrome in Windows CI

---

CONTRIBUTING.md
__snapshots__/bump-spec.js
circle.yml
scripts/binary/bump.js
scripts/unit/binary/bump-spec.js

- Closes #19954
n/a
- For UNIFY-998
- Removes test-example-repos. As outlined in [the Whimsical](https://whimsical.com/app-other-projects-ci-G7s7k8gd3nYKKm7PeZzrjQ) it is only adding coverage via `test-example-recipes`.
- Adds `test-example-recipes` coverage directly in test-binary jobs. …

test: replace cypress-test-example-repos coverage + remove bump

---

cli/lib/tasks/install.js
package.json
packages/driver/cypress/e2e/commands/net_stubbing.cy.ts
packages/launcher/package.json
packages/net-stubbing/lib/server/util.ts
packages/net-stubbing/test/unit/util-spec.ts
packages/network/lib/connect.ts
packages/network/test/unit/connect_spec.ts
yarn.lock

chore: merge develop into 10.0-release

---

circle.yml

n/a
Fairly clean merge. Only a couple of branch name conflicts in circle.yml
n/a

chore: merge develop to 10.0-release

---

circle.yml
scripts/get-next-version.js

- Closes 
- This CI step is silently failing to check out the release branch: 
- This PR updates it to correctly check out the release branch, and also fail if `next-version.js` fails.
- Successful run: https://app.circleci.com/pipelines/github/cypress-io/cypress/32437/workflows/02ceb7f8-dee8-4eb6-8c30-992571115b06/jobs/1275105
- [na] Have new …

chore: fix "cannot find module" in clone-repo-and-checkout-release-branch

---

packages/app/src/settings/SettingsSection.cy.tsx
packages/frontend-shared/src/locales/en-US.json
packages/graphql/schemas/schema.graphql
packages/graphql/src/schemaTypes/interfaceTypes/gql-ProjectLike.ts
packages/graphql/src/schemaTypes/objectTypes/gql-CurrentProject.ts
packages/graphql/src/schemaTypes/objectTypes/gql-Mutation.ts
scripts/gulp/gulpfile.ts

- Closes UNIFY-860
Find/Replace of all references to Cypress Cloud in the codebase

chore: UNIFY-860 remove all references to Cypress Cloud

---

circle.yml
packages/launchpad/cypress/e2e/choose-a-browser.cy.ts

Launchpad has a test that is failing consistently in windows. This PR updates the test so that it passes.
Green build in windows shown here: https://app.circleci.com/pipelines/github/cypress-io/cypress/32823/workflows/32727651-b2f8-4a55-9fba-7452097be3a3/jobs/1292070

chore: fix launchpad's failing windows test

---

packages/launchpad/src/global/GlobalPage.vue

Slightly cleaner syntax for filtering against a specific type, targeting https://github.com/cypress-io/cypress/pull/20361/files.
Docs for this feature: https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards

chore: cleaner filtering with a user defined type guard

---

packages/data-context/src/DataContext.ts
packages/data-context/src/data/ProjectLifecycleManager.ts
packages/data-context/src/sources/BrowserDataSource.ts
packages/frontend-shared/cypress/e2e/support/e2eProjectDirs.ts
packages/graphql/src/schemaTypes/objectTypes/gql-ErrorWrapper.ts
packages/graphql/src/schemaTypes/objectTypes/gql-Query.ts
packages/launchpad/cypress/e2e/config-files-error-handling.cy.ts
packages/launchpad/src/error/ErrorCodeFrame.vue
system-tests/projects/config-with-import-error/cypress.config.js

- Closes 
It was showing node internal file instead of the user file

fix: show correct stack trace file name

---

packages/data-context/src/sources/migration/codegen.ts
system-tests/projects/migration-component-testing-customized/expected-cypress.config.js
system-tests/projects/migration-component-testing-defaults/expected-cypress.config.js
system-tests/projects/migration-component-testing/expected-cypress.config.js
system-tests/projects/migration-e2e-component-default-everything/expected-cypress.config.js
system-tests/projects/migration-e2e-component-default-test-files/expected-cypress.config.js
system-tests/projects/migration/expected-cypress.config.js

- Closes  [UNIFY-1207](https://cypress-io.atlassian.net/jira/software/projects/UNIFY/boards/20?assignee=5ea883deddd45f0b94f5d98d&selectedIssue=UNIFY-1207)

fix: remove mileading comment

---

packages/icons/package.json
packages/server/lib/modes/interactive-e2e.ts

- Closes 
n/a unreleased
- For Mac/Win, we ship a full iconset. Unfortunately we can't do that for Linux (see #20452 for an attempt and links to the issues for why we can't do this)
- Switching to a lower res icon fixes the jaggies that come from scaling down the 128px image.
- It's ok to use the circle icon since we aren't on Mac.
- Also updated `@packages/icons` unit tests to run in CI since they weren't before.
Before | After
--- | --- …

fix: use 64x64 icon on Linux

---

packages/app/src/runner/unifiedRunner.ts
packages/app/src/specs/generators/component/ComponentGeneratorStepOne.vue

- Closes 
Update GQL query to have the latest specs after creation - so, those can be displayed and ready to be run

fix: specs list cache up to date

---

packages/driver/cypress/e2e/cypress/log.cy.js
packages/driver/src/cy/commands/navigation.ts
packages/driver/src/cypress.ts
packages/driver/src/cypress/log.ts
packages/driver/src/cypress/runner.ts

merge develop into 10.0-release - no merge conflicts (lucky me!)

chore(unification): merge develop into 10.0-release

---

cli/schema/cypress.schema.json
cli/types/cypress.d.ts
npm/angular/README.md
npm/create-cypress-tests/__snapshots__/init-component-testing.test.ts.js
npm/create-cypress-tests/src/component-testing/init-component-testing.test.ts
npm/create-cypress-tests/src/component-testing/init-component-testing.ts
npm/react/examples/find-webpack/README.md
npm/vite-dev-server/cypress/new-signature/plugins.js
packages/config/__snapshots__/index_spec.js
packages/config/lib/options.ts
packages/data-context/src/sources/migration/codegen.ts
packages/errors/__snapshot-html__/TEST_FILES_DEPRECATION.html
packages/errors/src/errors.ts
packages/errors/test/unit/visualSnapshotErrors_spec.ts
packages/server/test/integration/cypress_spec.js
packages/types/src/config.ts
system-tests/__snapshots__/config_spec.js
system-tests/projects/invalid-root-level-config/invalid-testFiles-config.js
system-tests/projects/same-fixtures-integration-folders/cypress.config.js
system-tests/projects/unify-onboarding-with-config/cypress.config.js
system-tests/test/config_spec.js

- Closes  [UNIFY-1278](https://cypress-io.atlassian.net/browse/UNIFY-1278)
Removes reference to `testFiles` and throw an error if it's being used on the root level of the config file, explaining that it has been removed for `specPattern` and where to set it!

feat: remove testFiles reference

---

packages/driver/cypress/integration/e2e/multi-domain/multi_domain_uncaught_errors_spec.ts
packages/driver/src/cy/commands/navigation.ts

- Closes 
n/a
This is a simple PR to get the feature branch back to a good state in CI.

chore: [multi-domain] Fix build

---

npm/vue/docs/manual-install.md

This config value was removed in Cypress 7.0.0 - https://docs.cypress.io/guides/references/changelog#7-0-0. Remove from manual installations instructions.
n/a

chore(doc): clean up deprecated config reference

---

packages/driver/cypress/integration/e2e/multi-domain/commands/multi_domain_network_requests.spec.ts
packages/driver/src/cy/commands/request.ts

- Closes #20617
N/A
Looks like `cy.request()` works just fine without any further work, so I just needed to uncomment the test. Also added a test for request to the primary domain as well, since it shouldn't be tied to the secondary domain anyway.
- N/A Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.s …

chore: Verify cy.request() works in multi-domain callback

---

circle.yml

- Closes 
n/a
This enables binary build and additional testing for the multi-domain branch.
n/a

chore: [multi-domain] enable binary builds and more tests for the multi-domain branch

---

guides/release-process.md
scripts/prepare-release-artifacts.js

n/a
shelljs doesn't support running commands with exec that require interactive input: https://github.com/shelljs/shelljs/wiki/FAQ#running-interactive-programs-with-exec
This PR switches to use node's built in exec command and adds a bit more clarification to the release process.
n/a …

chore: update release documentation and fix interactive release scripts

---

packages/driver/src/cy/multi-domain/index.ts

- Closes 
n/a
Simple PR to ensure that event listeners are properly cleaned up in the event that a promise is canceled by an external event (ie a on load time out).
n/a

chore: [multi-domain] clean up listeners when promise is canceled

---

scripts/gulp/tasks/gulpE2ETestScaffold.ts

N/A
A little dev quality-of-life improvement, currently at startup the gulp `e2eTestScaffoldWatch` script doesn't take into account empty directories, so when you switch branches you'll see artifacts like this: 
You will no longer see these empty directories when switching branches

chore: properly cleanup outdated system-test directories

---

packages/driver/cypress/integration/e2e/multi-domain/commands/multi_domain_navigation.spec.ts
packages/driver/src/cy/commands/navigation.ts
packages/driver/src/cypress/error_messages.ts
yarn.lock

- Closes n/a
n/a
* Updated `cannot_visit_different_origin` error message to account for `switchToDomain`
* Renamed `previousDomainVisited` to `previousUrlVisited` to better match other code
* Updated the type to make the actual usage
A more appropriate error message is displayed for cross-origin errors within `switchToDomain` …

chore: (multi-domain) update visit cross-origin error message

---

circle.yml

- Closes 
- Moves the record key and Percy token to their own CircleCI contexts.
- Cherry-pick of #20859 on to 10.0-release

test(unification): move record keys to contexts

---

npm/react/docs/recipes.md

docs: fix nextjs examples link in recipes.md

---

packages/driver/src/cy/commands/navigation.ts
packages/driver/src/cy/commands/request.ts
packages/driver/src/cy/multi-domain/index.ts
packages/driver/src/cy/stability.ts
packages/driver/src/cypress/command_queue.ts
packages/driver/src/cypress/cy.ts
packages/driver/src/cypress/error_messages.ts
packages/driver/src/multi-domain/events/socket.ts
packages/driver/types/internal-types.d.ts
packages/runner-shared/src/event-manager.js

- Closes 
n/a
This PR focuses on `multi-domain/index.ts` and `stability.ts`. Other files are included as well but the changes there are more ancillary than comprehensive. There will be more changes coming in future PRs.
Be kind, naming is hard. 😅

chore: [Multi-domain] Renaming variable and functions to reduce confusion between usage of origin, origin policy and domain Part 1

---

packages/driver/src/cy/commands/navigation.ts
packages/driver/src/cy/multi-domain/index.ts
packages/driver/src/cypress.ts
packages/driver/src/cypress/cy.ts
packages/driver/src/cypress/error_messages.ts
packages/driver/src/multi-domain/cypress.ts
packages/driver/src/multi-domain/domain_fn.ts
packages/driver/src/multi-domain/events/socket.ts
packages/driver/src/util/config.ts
packages/driver/types/internal-types.d.ts
packages/proxy/lib/http/response-middleware.ts
packages/proxy/test/unit/http/response-middleware.spec.ts
packages/runner-shared/src/event-manager.js
packages/runner/src/iframe/iframes.jsx
packages/server/lib/remote_states.ts
packages/server/lib/server-base.ts
packages/server/lib/socket-base.ts
packages/server/test/integration/http_requests_spec.js
packages/server/test/integration/server_spec.js
packages/server/test/unit/remote_states.spec.ts
packages/server/test/unit/socket_spec.js

- Closes 
n/a
This PR renames any previously added `domain` events to instead specify `origin`.
This pr also finishes the renaming in the following files
event-manager.js
multi-domain/index.ts
config.ts
socket.ts
iframes.jsx (except updating a src file that will happen during file renaming)
remote_states.ts (except isMultiDomain)
server-base.ts
socket-base.ts
Coming soon:
re-nameing isMultiDomain
domain_fn.ts
response-middleware.ts
file renaming (this will be last)
n/a, purely code renaming

chore: [Multi-domain] Rename domain events

---

packages/driver/cypress/integration/commands/navigation_spec.js
packages/driver/cypress/integration/e2e/multi-domain/commands/multi_domain_navigation.spec.ts
packages/driver/cypress/integration/e2e/multi-domain/navigation_spec.ts
packages/driver/src/cy/commands/navigation.ts
packages/driver/src/cypress/error_messages.ts
packages/driver/src/cypress/location.ts
system-tests/__snapshots__/runnable_execution_spec.ts.js

Closes #20974
n/a
* Updated the cross-origin error message to inform the user to use `cy.origin`
Experimental flag off:
Experimental flag on:

chore: (multi-domain) update cross-origin error

---

.github/CODEOWNERS

Adding myself to be specifically notified when things are added in the GraphQL/DataContext layer

chore: add @tgriesser to codeowners on packages

---

packages/frontend-shared/src/gql-components/StatusBadge.vue

Cleaning up a few unused styles and component

refactor: remove unused components/styles

---

npm/angular/cypress/plugins/webpack.config.ts

test: fix angular compile

---

circle.yml

- Closes 
n/a
Simple PR to clean up the circle.yml after the feature-mulitdomain branch has merged.

chore: remove feature-multidomain branch from circle.yml

---

packages/server/lib/project_static.ts

- n/a
n/a
[Git.io deprecation](https://github.blog/changelog/2022-04-25-git-io-deprecation/)
> Effective Friday, April 29, 2022 all links on git.io will stop redirecting. Please update any existing links that make use of the git.io URL service immediately.
n/a …

chore: replace git.io link with the original URL

---

packages/frontend-shared/src/gql-components/HeaderBarContent.vue

- Closes UNIFY-1633
- Closes UNIFY-1634
- Added a space between project name and branch name in header bar.
- Removed lowercasing on testing type name in header bar.
- Covered by Percy

fix: minor tweaks to shared header bar

---

packages/app/src/runs/CloudConnectButton.cy.tsx
packages/app/src/runs/RunsContainer.cy.tsx
packages/app/src/runs/modals/CloudConnectModals.spec.tsx
packages/app/src/runs/modals/CreateCloudOrgModal.vue
packages/app/src/runs/modals/SelectCloudProjectModal.cy.tsx

- Closes N/A
N/A
Removing some dead code that I came across while working on other tickets

chore: remove unused organizationControl graphql field

---

package.json

chore: release 9.6.1

---

npm/vite-dev-server/cypress/components/spec with whitespace.spec.ts
npm/vite-dev-server/src/makeCypressPlugin.ts
npm/vite-dev-server/src/resolveServerConfig.ts
packages/driver/src/cypress/script_utils.ts

- Closes https://github.com/lmiller1990/vue-3-cypress-vite/issues/1 (external repo)
Correctly handle spec files with white space in `@cypress/vite-dev-server`.
We were not doing `encodeURI` which made it impossible to load specs with white space for projects using `@cypress/vite-dev-server`. Some users reported it in an example repo I created for Vue and Vite. https://github.com/lmiller1990/vue-3-cypress-vite/issues/1

fix: handle specs with white space in vite-dev-server

---

packages/app/src/specs/SpecsList.cy.tsx
packages/frontend-shared/src/locales/en-US.json

- Closes [UNIFY-1757](https://cypress-io.atlassian.net/browse/UNIFY-1757)

fix: Change the capitalization of Component Specs

---

packages/driver/cypress/e2e/cypress/proxy-logging.cy.ts

- Related to UNIFY-1753
- Skips this test in Electron for now while work is done to isolate the root cause of the problem.

test(driver): skip failing proxy-logging test in Electron

---

packages/data-context/test/unit/data/ProjectLifecycleManager.spec.ts
packages/data-context/test/unit/helper.ts
packages/types/src/modeOptions.ts

Target https://github.com/cypress-io/cypress/pull/21538
- update `createTestDataContext` to receive `modeOptions`
- avoid using `ts-expect-error`

chore: improve test context method to avoid ts overrides

---

package.json

- Closes 
n/a
This pr simply bumps the current version of cypress.

chore: release 9.7.0

---

.github/PULL_REQUEST_TEMPLATE.md

- Closes 
- This came up from today's CT retro, that it's not always clear how to test the changes in PRs, especially for niche fixes or for newer contributors. Adding a section to the PR template where people can list steps to test will help with this.
- Super open to feedback on this, I feel like possibly this section could also be combined with the "How has the user experience changed?" section. …

docs: add "Steps to test" to PR template

---

circle.yml

- Closes 
- The [known_hosts monster](https://cypressio.slack.com/archives/CFKTGTXQS/p1649883291776519) is rearing its ugly head again in `develop`: https://app.circleci.com/pipelines/github/cypress-io/cypress/38651/workflows/63215ece-1018-49d6-bb8e-2731d16d76f0/jobs/1569406
- This is Ryan's old patch for this that seems to work fine.

chore: fix unit-tests-release job

---

packages/example/package.json
yarn.lock

- For [UNIFY-1043](https://cypress-io.atlassian.net/browse/UNIFY-1043)
n/a
- Pulls in the latest kitchensink for scaffolding in preparation for 10.0.0 release.
- During release, `example.cypress.io` will be re-deployed manually as part of the regular release process.

chore(deps): bump cypress-example-kitchensink to latest 10.0.0

---

packages/launchpad/src/main.ts

- Closes  [UNIFY-1738](https://cypress-io.atlassian.net/browse/UNIFY-1738)
The push fragment was being called correctly, and the subscription as well, what was going on was that the test may be fast enough that the resolved subscription was not being updated before the test completed making the Percy snapshots be flaky.
Making this change as the comment on the code says, may help the test to be consistent

fix: Cypress version loading constantly

---

packages/errors/__snapshot-html__/EXPERIMENTAL_STUDIO_REMOVED.html
packages/errors/src/errors.ts

- Closes https://github.com/cypress-io/cypress/issues/22008
We updated the error messaging when the `experimentalStudio` configuration is found.

fix: Update experimental studio error messaging to not indicate it will come back.

---

guides/release-process.md
scripts/binary/util/upload.js

- Closes 
- Some improvments from 10.0 release week
- Removes old repos from example repo list
- Consolidates 21+22
- Adds finger gun emoji
- Updates AWS_PROFILE docs to correlate with Infra docs
- Updates default profile name to prod

docs(guides): update release-process

---

packages/data-context/src/sources/VersionsDataSource.ts
packages/launchpad/cypress/e2e/open-mode.cy.ts
system-tests/projects/todos/cypress.config.js

- Closes #21880
N/A
Includes`x-framework` and `x-dev-server` headers when requesting the latest Cypress version.
Note: we only make this request in open mode.
There's no easy way to test this without modifying the code or monitoring your network traffic. You could do:
1. Pick a project (any, say launchpad or app) with component testing configured.
2. Add `console.log(manifestHeaders)` here: https://github.com/cypress-io/cypress/compare/lmiller1990/21880?expand=1#diff-f4439168518f09f406948b6f67428518c25a6ac04a9b766f86b2dfbe1964ac2eR1633. 
3. See if the `x-framework` and `x-dev-server` are correct.4. 
I also added a test that verifies this.

chore: add component testing metadata to manifest fetch request

---

packages/app/src/specs/AverageDuration.vue
packages/app/src/specs/LastUpdatedHeader.vue
packages/app/src/specs/SpecHeaderCloudDataTooltip.vue
packages/app/src/specs/SpecListGitInfo.vue
packages/app/src/specs/SpecsList.vue
packages/app/src/specs/SpecsListRowItem.vue
packages/frontend-shared/src/locales/en-US.json

feat: responsive ACI columns

---

packages/app/src/specs/LastUpdatedHeader.vue

- Closes 
Removes the z-index and background classes since we don't need these anymore due to the updated header content.

fix: fix Last updated header

---

package.json

updating version for 10.c.0 release

chore: updating version for 10.3.0

---

.github/CODEOWNERS

Removing myself from CODEOWNERS, and instead tagging the teams on directories I was previously added on
N/A

chore: Remove @tgriesser from CODEOWNERS

---

npm/webpack-dev-server/src/createWebpackDevServer.ts
npm/webpack-dev-server/src/helpers/sourceRelativeWebpackModules.ts
npm/webpack-dev-server/src/makeWebpackConfig.ts

Use the sourced Webpack to grab the `IgnorePlugin`

fix: use sourced webpack IgnorePlugin

---

packages/app/cypress/e2e/specs.cy.ts
packages/app/src/components/SpecPatterns.cy.tsx
packages/app/src/components/SpecPatterns.vue
packages/frontend-shared/src/locales/en-US.json

- Closes #21728 
- Display proper plural format for matches in the `Spec Patterns` section in `Project Settings`
NA
- Open a project that has 1 spec
- Navigate to Spec Patterns under Project Settings
- Match count should read `1 Match`
Before:
After:

fix: Correct pluralization in Spec Pattern

---

packages/server/__snapshots__/cypress_spec.js
packages/server/test/integration/cypress_spec.js
system-tests/lib/normalizeStdout.ts
system-tests/lib/system-tests.ts
system-tests/test/spec_isolation_spec.js

- Closes N/A
N/A
Test snapshot hard codes Cypress version, so it will always fail. Now it normalizes it correctly, so it won't fail as we release new Cypress versions.
Observe CI is passing.

chore: fix test by normalizing stdout

---

packages/server/lib/screenshots.js
packages/server/test/unit/screenshots_spec.js
system-tests/lib/system-tests.ts

Noticed this code can be cleaned up in @packages/server.
n/a

chore: remove dead server code

---

npm/vue/package.json
yarn.lock

- Closes N/A
N/A
Update `@vue/test-utils` dependency in `npm/vue` to the latest version.
If CI is green we are good to go.

chore: bump vue/test-utils version

---

circle.yml
system-tests/package.json

- Closes 
When running `yarn test {spec pattern}` in `system-tests` an error would occur. It looks like zsh may behave differently on m1 with how it treats cmd args.
Before Change:
- On m1, run yarn test visit
- Fails to run with `The "path" argument must be of type string. Received an instance of Array`
After Change:
- On m1 run yarn test visit
- Runs successfully

chore: Fix glob pattern

---

cli/package.json
cli/scripts/post-build.js
cli/types/cypress.d.ts
npm/angular/package.json
npm/webpack-dev-server/cypress/e2e/angular.cy.ts
npm/webpack-dev-server/src/devServer.ts
npm/webpack-dev-server/src/helpers/sourceRelativeWebpackModules.ts
npm/webpack-dev-server/src/makeDefaultWebpackConfig.ts
npm/webpack-dev-server/test/handlers/angularHandler.spec.ts
packages/graphql/schemas/schema.graphql
packages/launchpad/cypress/e2e/scaffold-component-testing.cy.ts
packages/launchpad/src/utils/icons.ts
packages/scaffold-config/src/frameworks.ts
packages/scaffold-config/test/unit/detect.spec.ts

Enable Angular CT support
Reverting the changes from ecad07e27b4745d5346858a667d5a991abacf7d9. Added the `feat` in the commit title to bump minor version in next release.
Code has been tested, but there are system tests you can run via `yarn workspace @cypress/webpack-dev-server cypress:open --e2e` and clicking on `angular.cy.ts`.
Angular CT support!

feat: enable Angular CT support

---

.github/ISSUE_TEMPLATE/4-flaky-test.yml

n/a
Adds an issue template for flaky internal tests. This is helpful for logging issues as part of the [proposal to Restore Confidence in CI](https://github.com/cypress-io/prod-eng-docs/blob/main/cypress-app/restore-confidence-in-ci.md)
n/a
n/a

chore: create flaky test template

---

packages/app/src/specs/CreateSpecModal.cy.tsx
packages/app/src/specs/generators/EmptyGenerator.vue

Potential improvement to spec for #21815.

chore: improve spec for #21815

---

npm/react/cypress/component/advanced/react-router-v6/README.md

- Closes N/A
Just a small thing I noticed in passing.

docs: update stale links in React example README

---

package.json

chore: update package.json version [skip ci]

---

packages/app/cypress/e2e/runs.cy.ts
packages/app/src/runs/modals/SelectCloudProjectModal.cy.tsx
packages/app/src/runs/modals/SelectCloudProjectModal.vue
packages/data-context/test/unit/sources/GraphQLDataSource.spec.ts
packages/graphql/test/stubCloudTypes.ts

- Closes #22936 
- Populate the project drop down when connecting a project if an organization only has one project 
https://user-images.githubusercontent.com/25568640/184048508-157d8c70-4443-43fa-977a-653923c355f4.mov
https://user-images.githubusercontent.com/25568640/184048522-572b37ef-1651-4763-afbb-580d64f51e24.mov

feat: Auto select project when an organization only has one project

---

package.json

chore: [skip ci] update version to 10.5.0

---

.github/workflows/add_to_triage_project.yml

- Closes n/a
n/a
The default GITHUB_TOKEN does not contain the necessary scopes to run the add-to-project action. Thus, I added a new token with the necessary scopes.
n/a

chore: add_to_triage_project github token

---

packages/app/cypress.config.ts
packages/app/cypress/e2e/spec.cy.ts
packages/app/cypress/e2e/studio.cy.ts
packages/app/cypress/e2e/studio/README.md
packages/app/cypress/e2e/studio/helper.ts
packages/app/cypress/e2e/studio/studio-cancel.cy.ts
packages/app/cypress/e2e/studio/studio-empty-spec.cy.ts
packages/app/cypress/e2e/studio/studio-kitchensink.cy.ts
packages/app/cypress/e2e/studio/studio-smoke.cy.ts
packages/app/src/runner/index.ts
packages/app/src/store/studio-store.ts
packages/frontend-shared/cypress/e2e/support/e2eSupport.ts
packages/graphql/schemas/cloud.graphql
packages/graphql/schemas/schema.graphql
packages/reporter/src/components/LaunchStudioIcon.tsx
packages/reporter/src/hooks/hooks.tsx
packages/reporter/src/runnables/runnable-and-suite.tsx
packages/reporter/src/runnables/runnables.tsx
packages/reporter/src/test/test.tsx
system-tests/projects/experimental-studio/cypress/e2e/index.html
system-tests/projects/experimental-studio/cypress/e2e/spec.cy.js

Adding some e2e tests for Cypress Studio in Cypress 10. This targets `feat/studio-cypress-10`.

test: studio e2e tests

---

circle.yml

- Closes 
- We recently rotated tokens and as part of that, noticed that the PERCY_TOKEN was in both `test-runner:percy` and main env. After removing it from main env percy-finalize started to fail open: https://app.circleci.com/pipelines/github/cypress-io/cypress/42503/workflows/3ee274a4-9f4e-4aaa-aa25-783973088d7b/jobs/1767086
- Adding this context should restore the Percy functionality.
- See here that PERCY_TOKEN is set: https://app.circleci.com/pipelines/github/cypress-io/cypress/42515/workflows/3ca0074a-28ad-459a-9c12-a08d4db1c9a8/jobs/1767748?invite=true#step-111-9

chore(percy): add percy context to finalize job

---

package.json

chore: bumping version to 10.7.0

---

circle.yml
packages/app/cypress/e2e/runner/pluginEvents.cy.ts

Thank you @flotwig for noticing I broke windows. OOPS 😅 
broken build: https://app.circleci.com/pipelines/github/cypress-io/cypress/42795/workflows/a549ce5a-eae5-48d6-ace6-060d274f02c3/jobs/1781183

chore: fix paths for windows

---

.github/workflows/triage_add_to_routed_project.yml
.github/workflows/triage_closed_issue_comment.yml

- Closes n/a
n/a
If an issue is closed using the "Close with comment" button, the GitHub Action to handle closed issues with a new comment is incorrectly run since the issue is closed prior to the action running. A new check is being added to verify the `closed_at` date/time is not equal to the comment `created_at` date/time.
n/a
n/a

chore: handle "Close with comment"

---

packages/app/cypress/e2e/runner/runner.ui.cy.ts
system-tests/projects/runner-e2e-specs/cypress/e2e/runner/disabled-command-log.runner.cy.js

This test runs here: https://github.com/cypress-io/cypress/blob/develop/packages/app/cypress/e2e/cypress-in-cypress-run-mode.cy.ts#L67

chore: remove skipped test - covered elsewhere

---

cli/types/cypress.d.ts
cli/types/tests/cypress-npm-api-test.ts

- Closes https://github.com/cypress-io/cypress/issues/22146
N/A
Fixes type definitions.
- Pick any `cypress.config.ts`
- add `modifyObstructiveCode`
- it should be detected via TS
Better types for the config file.

chore: fix types for modifyObstructiveCode

---

browser-versions.json
packages/app/package.json
packages/app/vite.config.mjs
yarn.lock

- Closes #23509
- Fix regression causing incompatibility with Chrome 70 and older
Try to run e2e tests (I used the kitchen sink app) using Chrome 70.
Prior to this change, nothing will render in the UI and tests will timeout.
After the fix, tests will run normally.
I can provide the chrome binary (macOS) if needed.
- na Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- na Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

fix: Add polyfill for Chrome V65+

---

packages/data-context/src/actions/EventCollectorActions.ts

- Closes 
N/A
Fixing name of debug logger, no functional impact

fix: Update name of debug logger
