packages/driver/src/cy/commands/actions/scroll.coffee, packages/driver/test/cypress/integration/commands/actions/scroll_spec.coffee
Addresses #725
The UI log for `scrollTo` was lacking context such as x, y or position. I added these to the log message by creating an array of message arguments that are then joined with `, `. If a user defines a position, we use the "friendly name" such as `center` or `bottom`. If a user defined x and y coordinates or scroll percentages then we will use that instead of `position`.
You can see the difference in the UI below.
Before:
[![https://gyazo.com/ec77f62ac1532a859363fd5ec9af9130](https://i.gyazo.com/ec77f62ac1532a859363fd5ec9af9130.png)](https://gyazo.com/ec77f62ac1532a859363fd5ec9af9130)
After:
[![https://gyazo.com/2c2ad7f336af101f673197a272e8eef8](https://i.gyazo.com/2c2ad7f336af101f673197a272e8eef8.png)](https://gyazo.com/2c2ad7f336af101f673197a272e8eef8)
I also added context …
=> Add context to UI log message such as x, y or position.

packages/server/lib/config.coffee, packages/server/lib/modes/headless.coffee, packages/server/lib/modes/record.coffee, packages/server/test/unit/config_spec.coffee, packages/server/test/unit/modes/headless_spec.coffee, packages/server/test/unit/modes/record_spec.coffee
Compressing and uploading a video to the dashboard is an expensive operation. If there have been no failures, we are not usually interested in the video as it will reveal nothing interesting, so it makes sense that we may want the video to only be compressed and uploaded if there have been any failures.
This PR adds a new `uploadVideoOnlyOnFailure` config setting that if set to true will disable compressing and uploading the video unless there have been some failures. It defaults to `false` to keep the current functionality.
Includes unit tests for the new functionality. I did not add any integration tests for the upload feature because I saw this comment in the code:
```
```
so it seems that there are no tests for this capability yet
=> Add option to upload video on tests passing. Addresses #460

packages/server/lib/util/args.coffee, packages/server/test/integration/cypress_spec.coffee, packages/server/test/unit/args_spec.coffee
Hello,
This is a fix for https://github.com/cypress-io/cypress/issues/620. Instead of splittings pairs on all occurrences of the `=` character, we split on the first one only. This makes it possible values to contain equal signs.
=> Fix parsing error in parseNestedValues

packages/driver/package.json, packages/driver/src/cypress/log.coffee, packages/driver/test/cypress/fixtures/zonejs.html, packages/driver/test/cypress/integration/e2e/zonejs_spec.coffee
zone js messing around with xsh requests, and creates circular dependencies, this causes stack overflow when cypress trying to stringily such objects, I just added additional stop word, to break this cycle
=> fixes stack overflow, for angular 4 apps

CONTRIBUTING.md, README.md, circle.yml, packages/coffee/package.json, packages/desktop-gui/package.json
- Move CI status within the TOC
- Add ‘driver’ to ‘Working in specific package’ section
- some minor link / wording fixes
- added wording around our labels.
- close #763 
- Add ‘why cypress’ video to readme
- Add a bunch of badges
- Add ‘install cypress’ section that refers to docs
- Add a nice logo at the top.
- close #768
=> #763 driver contributions

CONTRIBUTING.md
It looks to me like the repo was renamed and that these needed to be updated?
=> Renamed cypress-monorepo to cypress

cli/lib/exec/run.js, packages/server/lib/cypress.coffee, packages/server/test/integration/cypress_spec.coffee
when running in local mode using `scripts/start.js`, we are skipping CLI logic, so we cannot record runs.
=> server: read record key from environment variable, close #820

circle.yml, package.json, packages/ts/register.js, scripts/binary/build.coffee
No longer hardcode `CYPRESS_ENV=production` in the built binary application
=> Add ability to point built binary at staging, close #813

CODE_OF_CONDUCT.md, CONTRIBUTING.md
GitHub was sadly showing us as not having a code of conduct, although we have had one for a long time. They were only looking for CODE_OF_CONDUCT.md file.
- updated CoC to version 1.4 of Contributor covenant.
- updated link in Contributing doc to new CoC.
=> Moved code of conduct to main dir

packages/launcher/package.json, packages/ts/package.json, scripts/test-other-projects.js
Form different commit message to each test project to install specific binary and npm version without using environment variables. The test projects will install it using https://github.com/bahmutov/commit-message-install
=> build: commit to test projects using commit-message-install format

DEPLOY.md, appveyor.yml, package.json, scripts/binary/ask.coffee, scripts/binary/bump.coffee, scripts/binary/index.coffee, scripts/binary/util/upload.coffee
Getting error setting Buildkite variable
```
Error attempting to update the variable { NEXT_DEV_VERSION: '1.1.0' } for cypress-io/cypress on buildkite
error response data
{ message: 'Validation Failed',
errors: 
[ { field: 'env',
code: '"_aws_credentials_json" is not a valid environment variable name (only a-z, A-Z, 0-9 and underscores are allowed)',
value: [Object] } ] }
```
Possible solutions:
- only patch some variables and not all of them. Not sure if this is possible
- rename `_aws_credentials_json` to NOT start with `_`
=> Separate bump next version command

scripts/binary/bump.coffee, scripts/test-other-projects.js
We no longer need shared CI environment variables to pass NPM version and binary url. All happens via commit message.
=> Do not set env vars to kickoff

packages/server/lib/fixture.coffee, packages/server/package.json, packages/server/test/unit/fixture_spec.coffee
Stop formatting and saving fixtures. Let the users use their own favorite formatting tools.
=> Do not format fixture on run

packages/server/lib/controllers/proxy.coffee, packages/server/test/integration/http_requests_spec.coffee
Fixes #962 (verified locally on my use-case but might break some other things)
I can see that all proxy unit tests are commented out at the moment. 
Can definitely add some for this. Should I? 😃
=> Issue 962 - Skip invalid cookies instead of crashing

cli/index.d.ts, cli/package.json, cli/scripts/build.js, cli/scripts/start-build.js
- brings in `@types/cypress` definition file into NPM repo
- links definition file `index.d.ts` to `cypress` package by specifying it in the CLI package.json file as `"types": "index.d.ts"`
- updates definition bringing it up to date (well, work in progress)
- adds a lot more documentation from API docs to the JSdoc comments to make available to IntelliSense
=> Include typescript definitions 856

cli/index.d.ts
- Moved what was inside the `Core` interface to the `Cypress` interface
- Fixed some URLs
- Add definitions for `Cypress.Commands.add` (and remove the old ones)
Fix #1006
=> Typings: fix Cypress interface

packages/driver/src/cypress/error_messages.coffee, packages/driver/test/cypress/integration/e2e/uncaught_errors_spec.coffee, packages/server/__snapshots__/caught_uncaught_hook_errors_spec.coffee, packages/server/__snapshots__/commands_outside_of_test_spec.coffee, packages/server/__snapshots__/js_error_handling_spec.coffee, packages/server/__snapshots__/uncaught_spec_errors_spec.coffee, packages/server/__snapshots__/uncaught_support_file_spec.coffee
This is to change the tone/inflection of the message. The previous
message felt like it was bordering on aggressive.
Fixes #1025
=> De-emphasize a word in error message

package.json, scripts/binary/bump.coffee, scripts/binary/index.coffee, scripts/test-other-projects.js
Seems now that I have implemented this we still need more work inside `cypress-test-example-repos`. Because we do NOT plan to create branches in the `cypress-test-example-repos` itself - instead we are creating branches like `1.2.0` in the `cypress-example-recipes` that are tested by the code in `cypress-test-example-repos`.
So in addition to this (this only works if we use branches for direct breaking changes in the repos), we also need to update code here to look at the commit message, extract version, see if the repo we have cloned has a branch with this name, switch to that branch and do install, run the tests. etc.
Opened https://github.com/cypress-io/cypress-test-example-repos/issues/10 - this should very simple
=> build: make empty commit in next version branch first, close #1070

cli/types/index.d.ts
This adds the 4th item in #1040.
This change only adds auto-complete and help. Cypress supports strings for `cy.shoud` and `cy.and`. This PR adds a lot of happy-path assertions that help guide to what's available instead of just `should: (assertion: string, value?: any, matcher:? any): Chainable<Subject>`. If an assertion type isn't listed in the types, it will fall back to a simple string assertion. This does not actually add any type safety, just a nicer developer experience.
Here's a video of the auto-complete support in VS-Code with this change:
=> chore: Add extra chainer types for auto-complete

circle.yml, package.json, scripts/test-other-projects.js
Passing cypress SHA to the build jobs via commit messages
=> ci: pass commit into commit message to test projects

CONTRIBUTING.md, cli/lib/cli.js, cli/lib/exec/open.js, cli/lib/exec/run.js, cli/lib/exec/spawn.js, cli/test/lib/exec/open_spec.js, cli/test/lib/exec/run_spec.js, cli/test/lib/exec/spawn_spec.js, package.json, packages/server/package.json, packages/server/test/integration/cli_spec.coffee
- matches how we run in production better to keep parity and consistency
=> cli: fixes #838 start cypress in dev by routing through the CLI

cli/__snapshots__/errors_spec.js, cli/__snapshots__/verify_spec.js, cli/lib/errors.js
closes #1136 
Hopefully everything is okay here, this is my first PR so let me know if not!
=> Fix typos in CLI errors.js

package.json
Upgrade debug package to version 2.6.9 or greater due to vulnerability to regular expression denial of service (issue 1003).
=> Upgrade debug package to version 2.6.9 or greater

cli/types/index.d.ts, cli/types/tests/chainer-examples.ts, cli/types/tests/cypress-tests.ts, cli/types/tests/kitchen-sink.ts
Added a lot of documentation to chainer autocomplete interface. Below is a video of the experience:
Related to #1040
Addresses chainer documentation concern of #1117
Also fixed an issue with `.within` types when using options.
=> doc: should/and chainer autocomplete

cli/types/index.d.ts, cli/types/tests/actions.ts, cli/types/tslint.json
Fixes #1186
* Added support for `Cypress.on` and `cy.on`
* Added documentation for the various action events documented https://docs.cypress.io/api/events/catalog-of-events.html#App-Events
* Added dt tests for the action callbacks
=> feat: Add TypeScript support for Cypress action events

cli/package.json, cli/test/lib/cli_spec.js, cli/test/lib/tasks/download_spec.js, cli/test/lib/tasks/install_spec.js, cli/test/lib/tasks/unzip_spec.js, cli/test/lib/tasks/verify_spec.js, package.json
for example added to CLI to suites that have a log of text output that is confusing and hard to separate.
Just add to these suites
```js
describe('some verbose stuff', () => {
require('mocha-banner').register()
})
```
To get things like these
suites with short tests without much output are left alone (we do not require `mocha-banner` there)
=> Banner to separate test output

cli/types/index.d.ts, cli/types/tests/cypress-tests.ts
It is valid to return a wrapped `undefined`. Example: `cy.wrap(undefined)` or `Promise.resolve(undefined)` or even `cy.wrap(null)`.
As it is before this PR, returning a wrapped `undefined` or `null` would result in a double-wrapped type
Fixes #1219
=> fix: Incorrect type for 'then' returning a wrapped 'undefined'

packages/server/__snapshots__/domain_spec.coffee, packages/server/lib/util/cors.coffee, packages/server/test/e2e/domain_spec.coffee, packages/server/test/support/fixtures/projects/e2e/cypress/integration/domain_spec.coffee, packages/server/test/unit/cors_spec.coffee
Closes #451
Currently `parseDomain` returns an invalid response when passed a domain ending in `.localhost`. For example, `www.ourapp.localhost` returns:
```
domain: "loc"
subdomain: "www.ourapp"
tld: "local"
```
This PR adds `.localhost` to the `customTlds` list so that the domain is parsed correctly:
```
domain: "ourapp"
subdomain: "www"
tld: "localhost"
```
This PR closes #451
=> Allow .localhost tld to be parsed correctly

packages/server/__snapshots__/domain_spec.coffee, packages/server/lib/util/cors.coffee, packages/server/package.json, packages/server/test/e2e/domain_spec.coffee, packages/server/test/support/fixtures/projects/e2e/cypress/integration/domain_spec.coffee, packages/server/test/unit/cors_spec.coffee
- use the public suffix when parsing tld’s so that document.domain is
set correctly
=> server: fixes #802 and fixes #380 and fixes #402 and fixes #493 and fixes #1161

packages/driver/src/dom/elements.coffee, packages/driver/test/cypress/integration/commands/querying_spec.coffee
even if it’s a regex, this selector is still passed to sizzle and needs to be valid, which means quotes must be escaped
closes #1322
=> escape text before interpolating in getContainsSelector

packages/driver/src/cypress/runner.coffee, packages/server/__snapshots__/caught_uncaught_hook_errors_spec.coffee, packages/server/test/e2e/caught_uncaught_hook_errors_spec.coffee, packages/server/test/support/fixtures/projects/e2e/cypress/integration/hook_caught_error_failing_spec.coffee
- add e2e test around this behavior
- cleanup runner code for clarity
=> server, driver: fixes #1343, ensure we fire 'test:after:run' events for tests which failed due to a before hook and have sibling tests

circle.yml, cli/__snapshots__/build_spec.js, cli/scripts/build.js, cli/test/lib/build_spec.js, cli/test/lib/cypress_spec.js
uses `engines` property from CLI folder package.json file. 
Command on Node 6 for example is working now
```
npm_config_engine_strict=1 npm i https://cdn.cypress.io/beta/npm/2.0.4/circle-fix-engines-1373-a97a6f3fa6ce03acd79c5664e036da90c2e35ece-14625/cypress.tgz --ignore-scripts
```
and the installed package has the expected engines
```
"engines": {
"node": ">=4.0.0"
}
```
=> Fix engines 1373

.buildkite/pipeline.yml, appveyor.yml, circle.yml, package.json, scripts/check-node-version.js
=> ci: use Node 8.2.1 to build binary on Windows CI #1390

packages/driver/package.json, packages/driver/src/cypress.coffee, packages/driver/src/cypress/error_messages.coffee, packages/driver/src/cypress/selector_playground.coffee, packages/driver/test/cypress/integration/cypress/selector_playground_spec.coffee, packages/driver/test/unit_old/cypress/utils_spec.coffee, packages/runner/package.json, packages/runner/src/iframe/aut-iframe.js, packages/runner/src/lib/dom.js, packages/runner/src/selector-playground/selector-playground.scss
Fixes #1135
Adds the following API:
```javascript
Cypress.SelectorPlayground.defaults({
selectorPriority: ['data-cy', 'data-test', 'id', 'class', 'nth-child'],
onElement (el) {
// return your own selector here
},
})
```
Docs PR: https://github.com/cypress-io/cypress-documentation/pull/423
=> Add selector playground configuration methods

packages/driver/src/cy/commands/window.coffee, packages/driver/src/cypress/error_messages.coffee, packages/driver/test/cypress/integration/commands/window_spec.coffee
This PR fixes https://github.com/cypress-io/cypress/issues/1444.
Lowers the current minimum lower bound on `cy.viewport` from `200` to `20` pixels.
=> Lower minimum viewport bound

packages/reporter/src/runnables/runnables.scss
Hi 👋
Is there is a reason why text in UI is not selectable?
Me and my colleagues would find it very useful, mostly for searching for the specific tests in source code.
UX is not perfect, as selecting text also expands/collapses details, but worth IMO :)
=> Allow text selection in UI

packages/runner/src/header/header.jsx, packages/runner/src/header/header.scss, packages/runner/src/lib/variables.scss
Fixes #1569
Loading the Open Sans font can prevent errors from being visible in failure screenshots. This preloads the font by using it on an always present part of the UI.
=> Fix screenshot rendering issue

cli/lib/exec/xvfb.js, cli/package.json
Use latest `@cypress/xvfb`, pass longer timeout, more debug messages from XVFB module
=> cli: pass timeout 5 seconds for XVFB, close #1628

packages/reporter/src/commands/command-model.js, packages/reporter/src/commands/command.jsx, packages/reporter/src/commands/command.spec.jsx, packages/reporter/src/commands/commands.scss, packages/reporter/src/hooks/hook-model.js, packages/reporter/src/hooks/hook-model.spec.js, packages/reporter/src/test/test-model.spec.js, packages/runner/src/lib/shared.scss
Fixes #1580 
Duplicates can still be individually pinned and printed to console.
=> Collapse duplicate events in reporter

packages/reporter/src/runnables/runnables.scss
This is a minor visual glitch. 
I am super sensitive of animations which are out of center. They are driving me nuts. So this change fixes the running animation to be centered all the time without shifting one pixel off center.
The animation is used to mark the current running action. It is reproduceable on chrome and electron on each version currently in use with cypress.
before
after
=> [low priority] fix out of center running animation

cli/lib/cli.js, cli/lib/util.js, cli/test/lib/util_spec.js
- closes #1673 and allows easier tracking of options that can break Node execution (and thus Cypress run)
=> cli: print NODE_OPTIONS when DEBUG=cypress... is used, close #1673

packages/driver/src/cy/commands/screenshot.coffee, packages/driver/test/cypress/integration/commands/screenshot_spec.coffee, packages/server/lib/automation/screenshot.coffee, packages/server/lib/modes/run.coffee, packages/server/lib/screenshots.coffee, packages/server/test/unit/screenshots_spec.coffee
Fixes #1726 
Yielded object:
Console output:
=> Yield details object from cy.screenshot()

packages/driver/src/cy/commands/screenshot.coffee, packages/driver/src/cypress/screenshot.coffee, packages/driver/test/cypress/integration/commands/screenshot_spec.coffee, packages/driver/test/cypress/integration/cypress/screenshot_spec.coffee, packages/runner/src/lib/event-manager.js, packages/server/__snapshots__/screenshots_spec.coffee, packages/server/lib/automation/screenshot.coffee, packages/server/lib/cypress.coffee, packages/server/lib/screenshots.coffee, packages/server/lib/util/electron_app.coffee, packages/server/package.json, packages/server/test/e2e/screenshot_app_capture_spec.coffee, packages/server/test/e2e/screenshot_fullpage_capture_spec.coffee, packages/server/test/e2e/screenshots_spec.coffee, packages/server/test/support/fixtures/projects/e2e/cypress/integration/screenshot_app_capture_spec.coffee, packages/server/test/support/fixtures/projects/e2e/cypress/integration/screenshot_element_capture_spec.coffee, packages/server/test/support/fixtures/projects/e2e/cypress/integration/screenshot_fullpage_capture_spec.coffee, packages/server/test/support/fixtures/projects/e2e/cypress/integration/screenshots_spec.coffee, packages/server/test/support/fixtures/projects/e2e/cypress/plugins/index.js, packages/server/test/support/helpers/e2e.coffee, packages/server/test/unit/screenshots_spec.coffee
=> cy.screenshot bug fixes and enhancements

cli/lib/tasks/install.js, cli/test/lib/tasks/install_spec.js
closes #1813
`state.getBinaryPkgVersionAsync` was called with a wrong argument.
It should called with the path to the binary directory `/cache/Cypress/1.2.3/Cypress.app` instead of the cache install directory `/cache/Cypress/1.2.3`.
=> fix cli: global binary cache reuse

packages/driver/src/cy/snapshots.coffee, packages/driver/test/cypress/integration/cy/snapshot_spec.coffee
=> Fix for issue-1226 - preserve styles for empty style tags - css-in-js

cli/__snapshots__/cli_spec.js, cli/lib/cli.js, cli/lib/exec/run.js, cli/lib/tasks/cache.js, cli/package.json, cli/test/lib/cli_spec.js, cli/test/lib/exec/run_spec.js, cli/test/lib/tasks/cache_spec.js, cli/test/spec_helper.js
close #1856 `cypress cache <command>`
close #1871 `--no-exit`
=> cache commands, --no-exit

cli/types/index.d.ts, cli/types/tests/kitchen-sink.ts, cli/types/tsconfig.json
- adds `auth` object to `cy.visit`
- closes #1897
=> types for auth in cy.visit, close #1897

cli/package.json
- bump cachedir to 1.3.0 which adds FreeBSD support (see https://github.com/LinusU/node-cachedir/pull/7)
- close #1942
=> bump cachedir to 1.3.0

cli/__snapshots__/verify_spec.js, cli/lib/exec/spawn.js, cli/lib/exec/versions.js, cli/lib/tasks/install.js, cli/lib/tasks/state.js, cli/lib/tasks/verify.js, cli/test/lib/tasks/install_spec.js, cli/test/lib/tasks/state_spec.js
close #1960 
just making sure to use `path.resolve` on env vars so users can give relative paths
=> allow relative paths in CYPRESS_* env vars

packages/driver/src/cy/commands/xhr.coffee
=> Don’t truncate xhr urls in command log

packages/server/lib/project.coffee
Changes the logMemory function to use console.log rather than console.debug. 
When I run cypress with CYPRESS_MEMORY=1, I get a TypeError that console.debug is not defined. I am using node v9.8.0.
=> Replace console.debug with console.log for logMemory

packages/server/lib/socket.coffee, packages/server/test/unit/socket_spec.coffee
address  #712
- Fixes broken watch path on Windows when using any trans-piled code (ts, cucumber etc...)
- update related unit tests
=> Change hard-coded forward slash in watch path to platform specific path delimiter

packages/driver/src/cypress/commands.coffee, packages/driver/test/cypress/integration/cypress/cy_spec.coffee, packages/server/test/e2e/6_visit_spec.coffee, packages/server/test/support/fixtures/projects/e2e/cypress/integration/issue_2196_spec.coffee
=> Update state(‘current’) args when a command is overwritten

README.md
This change moves your CI badges into a list, making them easier to read and matching the style of your docs README:
https://github.com/cypress-io/cypress-documentation/blob/develop/readme.md
Thanks for the great documentation.
=> Style CI badges as list items

packages/driver/src/cypress/runner.coffee, packages/driver/test/cypress/integration/cypress/runner_spec.coffee
- Fixes #1157 
Would love any feedback on if/where to add tests, `runner_spec.coffee` didn't seem appropriate but might be a good place in the server?
=> Fix UI bug where test label was the contents of double quotes from test title

packages/server/__snapshots__/5_screenshots_spec.coffee.js, packages/server/lib/screenshots.coffee, packages/server/test/support/fixtures/projects/e2e/cypress/integration/screenshots_spec.coffee, packages/server/test/unit/screenshots_spec.coffee
- Fixes #2403 
Opted to set a max length of 242 for the original string so it's 255 with ` (failed).png`
=> Truncate file names for screenshots

cli/__snapshots__/download_spec.js, cli/lib/tasks/download.js, cli/test/lib/tasks/download_spec.js, cli/test/spec_helper.js
In a corporate environment it may be necessary to download cypress through a proxy host because `https://download.cypress.io` isn't directly accessible. While it is possible to host specific, previously downloaded binaries and passing `CYPRESS_INSTALL_BINARY` to the installation, this loses the flexibility to provide current versions for different operating systems without maintenance.
This PR introduces a `CYPRESS_DOWNLOAD_BASE_URL` env variable which allows to override the base url which is currently hardcoded to `https://download.cypress.io/`. For example, when installing the package with `CYPRESS_DOWNLOAD_BASE_URL=https://example.org/cypress` it will attempt to download from `https://example.org/cypress/desktop/0.20.2?platform=OS&arch=ARCH`.
A proxy like …
=> Introduce CYPRESS_DOWNLOAD_BASE_URL to specify a base download url

cli/package.json, cli/types/index.d.ts, cli/types/moment.d.ts, cli/types/tests/cypress-tests.ts
The `Cypress.moment` field isn't strongly typed currently, which means no nice completion/checks when using it from tests written in TypeScript. This adds the TS definition for that.
=> Add strong typed definition for Cypress.moment().

packages/driver/src/cy/commands/actions/type.coffee, packages/driver/src/dom/elements.coffee, packages/driver/test/cypress/fixtures/dom.html, packages/driver/test/cypress/integration/commands/actions/type_spec.coffee, packages/driver/test/cypress/integration/dom/elements_spec.coffee
- Fixes #2738 
Think directly setting this value might overstep something that's happening in type, but not entirely sure.
=> Add clear support for HTML 5 input types

packages/server/package.json
extend has a security vulnerabitlity and is used by request < 2.88
https://hackerone.com/reports/381185
https://github.com/cypress-io/cypress/pull/2485 failed testing as it bumps to a major version. 
This is just a minor version so it should not break things.
Fixes https://github.com/cypress-io/cypress/issues/2455 ?
=> Update request lib for security vulnerability in extend

cli/types/index.d.ts
Pretty self-explanatory. Cypress' wrap function resolve promises. Would help if types reflected that behavior.
=> Update types to support promises in wrap

cli/types/index.d.ts, packages/driver/src/cy/commands/waiting.coffee, packages/driver/test/cypress/integration/commands/waiting_spec.coffee
Address #2446 by adding two new options `requestTimeout` and `responseTimeout` to the XHR `cy.wait` command.
=> Allow separate request and response timeout overrides in cy.wait

packages/driver/src/cypress/server.coffee, packages/driver/test/cypress/integration/e2e/server_spec.coffee
Closes #2925
`fn.apply` shouldn't be called with `arguments` and no prior `this` value as this results in `arguments` being assigned as `this` for the function on which `.apply` is called...
=> Fix bailIfRecursive callback invocation

cli/package.json, cli/types/index.d.ts, cli/types/tests/cypress-tests.ts
Fixes #3075
The previous type definitions assumed `options` were an optional second parameter, but `options` is actually an optional primary parameter.
=> fix: Type definitions for .then

packages/desktop-gui/src/app/nav.jsx
Address issue #3091 
I added labels for "Support" and "Docs" to desktop-gui/src/app/nav.jsx. I also removed the Tooltip. I checked, and the changes show after running "npm run watch". 
If there is something else I should have done, please let me know. This is my first try at contributing to an open source project.
Thank you for your help and time.
=> added labels for support and docs

packages/reporter/src/lib/tooltip.scss
Small CSS fix for issue #2980 
Rule `word-wrap: break-word;` is used in `tooltip.scss` file as proposed in #2980
=> Fix tooltip styling

packages/driver/test/cypress/integration/issues/3253_spec.js, packages/runner/src/app/app.scss
- close #3253 
- changing the flex-direction does not affect scrolling or display behavior or older/newer browser versions
=> Fix bug where scrollbar would take up full width of test runner instead of only command log in Chrome 72+

packages/desktop-gui/cypress/fixtures/browsers.json, packages/desktop-gui/cypress/fixtures/config.json, packages/desktop-gui/src/lib/browser-model.js, packages/launcher/__snapshots__/browsers_spec.ts.js, packages/launcher/lib/browsers.ts, packages/launcher/lib/darwin/index.ts, packages/launcher/lib/detect.ts, packages/launcher/lib/launcher.ts, packages/launcher/lib/linux/index.ts, packages/launcher/lib/types.ts, packages/launcher/lib/windows/index.ts, packages/launcher/test/unit/browsers_spec.ts, packages/launcher/test/unit/detect_spec.ts, packages/launcher/test/unit/launcher_spec.coffee, packages/launcher/test/unit/linux/spec.ts, packages/server/lib/api.coffee, packages/server/lib/browsers/chrome.coffee, packages/server/lib/browsers/electron.coffee, packages/server/lib/browsers/index.coffee, packages/server/lib/browsers/utils.coffee, packages/server/lib/gui/events.coffee, packages/server/lib/modes/run.coffee, packages/server/lib/open_project.coffee, packages/server/test/integration/cypress_spec.coffee, packages/server/test/unit/browsers/browsers_spec.coffee, packages/server/test/unit/modes/run_spec.coffee
=> Represent browsers as objects internally

packages/desktop-gui/cypress/fixtures/browsers.json, packages/desktop-gui/cypress/fixtures/config.json, packages/desktop-gui/cypress/integration/project_nav_spec.coffee, packages/desktop-gui/src/lib/browser-model.js, packages/desktop-gui/src/projects/projects-api.js
This fixes the bug that was introduced in #3225 which means that browsers cannot be launched in open mode.
Also adds a test to `desktop-gui` to ensure a browser is always launched with the necessary properties.
=> Fix regression causing browsers not to be launched in open mode

packages/server/lib/config.coffee, packages/server/test/unit/config_spec.coffee
closes #3540 and #3545 
Tests:
```js
/// <reference types="Cypress" />
it('test url', function () {
cy.visit('/')
var baseUrl = Cypress.config('baseUrl')
//baseUrl = baseUrl + '/'    // bug in Cypress - add slash
cy.url().should('eq', Cypress.env('test_url'))
cy.url().should('eq', baseUrl)
})
it('test url - copy paste from @jennifer-shehane', function () {
cy.visit('/')
cy.url().should('eq', Cypress.config('baseUrl'))
})
```
=> Issue 3540: Fix baseUrl slash

cli/lib/util.js
Attempt to close [cypress-io#1243](https://github.com/cypress-io/cypress/issues/1243) (More like a temp fix)
I am currently running `npm install` inside docker and the log for cypress is ridiculous long. I hope this can reduce the log length to 100 instead of thousands.
However, I dont have any experiences in library development. Im not sure how I can test if this code actually works. All i know is that I didnt break any existing tests.
So if you know how to test this code, please let me know how or you can help me test it and let me know the result.
Thank you
=> Reduce the number of log printed when install cypress in docker

packages/driver/src/cy/chai.coffee, packages/driver/test/cypress/integration/commands/assertions_spec.coffee
- close #3549 
- obj.is and obj.find is not a function when used on regular el - needs
to be jQuery el
**Tests**
I can't figure out where the tests for these chai overrides are. Any help?
=> convert dom element to jQuery element in order to properly check contains assertion

cli/package.json
- Breaking change: Drop support for Node.js < 6.x]
- Use os.homedir() instead of os-homedir module (reduced dependency and
size)
=> Bump cachedir from 1.3.0 -> 2.1.0

packages/driver/src/cypress/keyboard.coffee, packages/driver/src/dom/selection.js, packages/driver/test/cypress/integration/commands/actions/type_spec.coffee
PR close https://github.com/cypress-io/cypress/issues/2033 by implementing handlers for `Home` and `End` in function `type`.
I am creating a PR for Downshift library in which I am implementing keyboard handling for Home and End in the context of a Dropdown (Home highlights first option, End the last one). PR is [here](https://github.com/paypal/downshift/pull/646). I meant to write end-to-end tests as well. Since the repo uses Cypress, I found that it did not support `{home}` and `{enter}` so I found this issue in your repo and am trying to fix it.
Work is still in progress, I still mean to write UTs and E2Es. However, I appreciate early feedback on the implementation as well, since this could be my first commit in this repository.
=> Add {home} and {end} to cy.type()

packages/extension/app/manifest.json, packages/extension/test/unit/extension_spec.coffee
Fixes #3673
Fixes #1239
This PR makes the extension have a static ID so it can be whitelisted.
The extension ID for Cypress is: `caljajdfkjjjdehjdoimjkkakekklcck`
=> Make extension have a static ID so it can be whitelisted

packages/server/lib/gui/windows.coffee, packages/server/test/unit/gui/windows_spec.coffee
- close #1251 
This removes the GitHub warning banner about an outdated browser in our Electron pop-up by replacing the user agent string of Electron with a new Chrome UA: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36"
I was only able to replicate the warning banner on Windows, and this fixes it there.
=> Spawn GitHub login with a new user agent to dismiss warning banner

packages/driver/src/cy/commands/navigation.coffee, packages/driver/test/cypress/integration/commands/navigation_spec.coffee
Fixes #3721 
Now shows valid `options` in the console log when the visit command is clicked, if options were passed.
=> Log options to cy.visit()

packages/server/lib/util/args.js, packages/server/test/integration/cypress_spec.coffee
Fixes #3742
* When parsing `--env` arguments containing variables with empty values (a valid pattern), Cypress crashed due to trying to `.split()` on an `undefined`.  For example, `cypress run --env="USERNAME=,PASSWORD="` would crash the application.
* This commit changes the regular expression used to parse environment variables to use a `.*` rather than a `.+`.  This will initialize environment variables that are supplied without values to an empty string.  Since empty strings are falsy in JavaScript, this should work fine with users defaulting to hardcoded values in the case that environment variables aren't supplied (the use case that I was trying to create when I encountered this bug)
Previous behavior:
```sh
"USERNAME=,PASSWORD=".split(',').map(pair => pair.split(/=(.+)/))
// …
```
=> Fix parsing environment variables with empty values

cli/types/index.d.ts, cli/types/tests/cypress-tests.ts
While docs say `trigger()` accepts arbitrary event properties in `options`, it is actually not allowed by TypeScript because `ObjectLike` is not intersected in type definition.
=> fix: trigger() accepts arbitrary event properties in options

cli/types/index.d.ts
Allow timeout on hash according to the documentation (https://docs.cypress.io/api/commands/hash.html#Arguments).
=> Allow timeout on hash

packages/driver/package.json, packages/server/package.json, packages/server/test/unit/cors_spec.coffee
Fixes #3717 
A regression in `parse-domain` since `2.1.0` is causing tests to fail for some users with public suffixes. This will add a unit test for the behavior that is broken to ensure we don't accidentally upgrade as well as reverts it back to `2.0.0`.
=> Downgrade parse-domain@2.1.7 -> 2.0.0

packages/driver/src/cypress/keyboard.coffee, packages/driver/test/cypress/integration/commands/actions/type_spec.coffee
close #3423 
I have make Cypress to be able to type some Javascript reserved words such as "hasOwnProperty" and "toString".  In addition, I've added some tests taken from the big naughty list of strings.
=> #3423 Enable Cyrpess to type strings containing reserved words

packages/server/lib/util/proxy.ts, packages/server/test/spec_helper.coffee, packages/server/test/unit/args_spec.coffee
This is the bug causing the failing AppVeyor build, basically the agent was always trying to use a proxy set to string `"undefined"` when no proxy is defined, making the request fail catastrophically every time.
Appveyor build: https://ci.appveyor.com/project/cypress-io/cypress-test-example-repos/builds/23690466
The issue causing the actual crash was that `socket.io` was somehow ACK'ing with a circular reference because of the error:
```
Mon, 08 Apr 2019 19:51:45 GMT socket.io-parser decoded 210["backend:request","http:request",{"url":"https://jsonplaceholder.cypress.io/users","method":"GET","gzip":true,"timeout":30000,"followRedirect":true}] as {"type":2,"nsp":"/","id":10,"data":["backend:request","http:request",{"url":"https://jsonplaceholder.cypress.io/users","method":"GET","gzip":true, …
```
=> Fix bug in proxy where HTTPS_PROXY became 'undefined'

packages/extension/app/newtab.html, packages/extension/app/popup.html, packages/runner/src/errors/automation-disconnected.jsx, packages/runner/src/errors/no-automation.jsx, packages/runner/src/header/header.jsx, packages/runner/src/iframe/visit-failure.js, packages/runner/src/selector-playground/selector-playground.jsx
- close #3951 
- Update urls to use most recent on.cypress.io links
- Update wording of newtab to say tests *may* fail due to focus, as
opposed to *will* fail (as was the case in the past)
=> Add rel="noopener" where appropriate, remove where not

cli/types/index.d.ts
This adds additional types for the `cy.visit()` changes from #3489 
Fixes #3989
=> Add missing fields to typescript definition for VisitOptions

packages/desktop-gui/src/app/nav.jsx, packages/desktop-gui/src/auth/login-form.jsx, packages/desktop-gui/src/runs/permission-message.jsx, packages/desktop-gui/src/settings/record-key.jsx, packages/reporter/src/commands/command.jsx, packages/runner/src/header/header.jsx
&nbsp; | Demo
------------ | -------------
❌ Before<br />✅ After | ![ezgif com-video-to-gif](https://user-images.githubusercontent.com/486954/56430388-e538ca00-62ce-11e9-9748-6f0eb249a69d.gif)
`fa-spinner` was not meant to spin smoothly but in steps.
I work a lot with Cypress and it's hurting my eyes and crushing my soul! 😱😵😖😭
Changed to the dedicated 8 step `fa-pulse` animation.
Nope. But it looks riskless 😅
=> Corrected spinner animation

packages/server/__snapshots__/2_browser_path_spec.coffee.js, packages/server/test/e2e/2_browser_path_spec.coffee
When I run `develop` with SNAPSHOT_UPDATE option, it prompts me of this change to the browser-path snapshot. @flotwig can you verify that this is the intended output for the snapshot?
=> Update snapshot for browser path not found

cli/types/index.d.ts, cli/types/tests/cypress-tests.ts, packages/driver/src/cypress.coffee, packages/driver/test/cypress/integration/cypress/cypress_spec.coffee
* Re-exposes `cy.isCy()` on `Cypress.isCy()`, since it doesn't return a chainer
* Adds types for `Cypress.isCy()`
* Documentation PR: cypress-io/cypress-documentation#1669
Closes #3822
=> Expose `cy.isCy` as `Cypress.isCy`, add typedefs

packages/driver/src/cy/commands/querying.coffee, packages/driver/src/cy/commands/waiting.coffee, packages/driver/src/cy/xhrs.coffee, packages/driver/test/cypress/integration/commands/agents_spec.coffee, packages/driver/test/cypress/integration/commands/aliasing_spec.coffee, packages/driver/test/cypress/integration/commands/querying_spec.coffee, packages/driver/test/cypress/integration/commands/waiting_spec.coffee, packages/driver/test/cypress/integration/commands/xhr_spec.coffee
I have removed the constraint that the aliases' names cannot contain dots. The issue is in querying.coffee, xhrs.coffee and waiting.coffee. The change is to use the dot as if it's an allowed character in the aliases' names.
Note that this PR is the continuation of https://github.com/cypress-io/cypress/pull/3929.
Addresses #3512
=> Enable aliases names to contain the dot character

cli/types/index.d.ts
Hi
The `cy.stub` TypeScript signature is wrong. I started from your [Add example to cy.stub() for stubbing window.prompt behavior](https://github.com/cypress-io/cypress-documentation/issues/193) but, with the same code, I get an error form TypeSctypt
```
Property 'returns' does not exist on type 'Agent<SinonStub<any[], any>>'.
```
see the screenshot of the code
In the above screenshot, I show you how everything works fine with the `log`, `as` and `withArgs` functions added by the `Agent` type.
The problem is that the `cy.stub` function returns a `Agent<sinon.SinonStub>` but the `Agent` itself doesn't extend the `sinon.SinonStub` type.
Since the code
```javascript
cy.stub(win, "prompt").returns("yes");
```
works perfectly in a standard JavaScript spec file, the error is in the TypeScript …
=> Fix the cy.stub type signature

cli/package.json, packages/server/__snapshots__/7_record_spec.coffee.js, packages/server/test/support/helpers/e2e.coffee
the issue was that sometimes artifacts finish uploading in a different order than the saved snapshot test
the solution is to sort the stdout lines so the order doesn't affect the snapshot 
- cleanse stdout of uploading multi results
=> fix flaky spec: server e2e snapshot spec 

packages/driver/package.json, packages/driver/src/cy/commands/navigation.coffee, packages/driver/src/cy/commands/request.coffee, packages/driver/src/cypress/error_messages.coffee, packages/driver/test/cypress/integration/commands/navigation_spec.coffee, packages/driver/test/cypress/integration/commands/request_spec.coffee, packages/driver/test/cypress/integration/cypress/cypress_spec.coffee, packages/extension/app/background.coffee, packages/extension/app/manifest.json, packages/extension/gulpfile.coffee, packages/extension/test/integration/background_spec.coffee, packages/extension/test/spec_helper.coffee, packages/network/test/support/servers.ts, packages/network/test/unit/agent_spec.ts, packages/runner/lib/test-setup.js, packages/runner/src/lib/event-manager.js, packages/server/lib/socket.coffee, packages/server/test/integration/websockets_spec.coffee, packages/server/test/unit/socket_spec.coffee, packages/socket/index.js, packages/socket/lib/browser.js, packages/socket/lib/client.js, packages/socket/lib/socket.js, packages/socket/package.json, packages/socket/patches/has-binary2+1.0.3.patch
* Fixes #4346 
* Fixes #1958
* Even with circular JSON support in the socket, `request` lib can't serialize a recursive body (of course), so we should warn the user that they're sending an invalid body
* ![image](https://user-images.githubusercontent.com/1151760/59373648-1c988580-8d18-11e9-9175-179b8e1a9edc.png)
Thought about using `flatted` (the successor to `circular-json`), but jsperf shows it performs 50% slower: https://jsperf.com/flatted-vs-circularjson
=> Allow circular structures to be sent over the websocket, make it an error to send circular request bodies

packages/server/lib/project.coffee, packages/server/test/integration/cypress_spec.coffee, packages/server/test/unit/project_spec.coffee
Fixes #4283 
Files are watched in 3 places:
- In `openProject`, `getSpecChanges` watches files to see if any are added or removed: https://github.com/cypress-io/cypress/blob/4bd3cf2c531bdbf1783493e8045c18f09dfc390b/packages/server/lib/open_project.coffee#L142-L153
- This is only called from gui/events for desktop-gui, so it does not run in `run` mode: https://github.com/cypress-io/cypress/blob/4bd3cf2c531bdbf1783493e8045c18f09dfc390b/packages/server/lib/gui/events.coffee#L234-L234
- In `project`, `cypress.json`, `cypress.env.json`, and the `pluginsFile` are watched
-  [x] `pluginsFile` is watched in run mode, so added a guard - normally watches all files in dependency tree outside of `node_modules`: https://github.com/cypress-io/cypress/blob/a389a51e45dc0bf708da304346079c3b6638caad/package …
=> Do not watch any files in run mode

packages/network/lib/agent.ts, packages/network/test/unit/agent_spec.ts
* Fixes #4303 
* NO_PROXY is now respected for HTTPS urls, as it should be
=> agent: Fix NO_PROXY not respected for HTTPS urls

packages/server/__snapshots__/6_visit_spec.coffee.js, packages/server/test/e2e/6_visit_spec.coffee, packages/server/test/support/fixtures/projects/e2e/cypress/integration/fast_visit_spec.coffee, packages/server/test/support/fixtures/projects/e2e/cypress/plugins/index.js
Now asserts that 90% of visits complete in less than 100ms, and 100% of visits complete in less than 250ms.
Also logs out a nice histogram to understand if a failure is just flake or if it represents a real speed change.
=> Fix flaky `fast_visit_spec`

packages/reporter/src/hooks/hook-model.js, packages/reporter/src/hooks/hook-model.spec.js
Fixes #4411
Brings total Command re-renders down to 407 from 80,000+
=> reporter: Cache aliasesWithDuplicates to prevent unnecessary re-renders, fixes UI slowdown

packages/desktop-gui/src/project-nav/browsers.jsx
Noticed this error when multiple copies of the same browser exist:
This PR changes the key to use `path` instead of `name` since `path` is always unique.
=> Use 'path' for key in browsers dropdown, fix desktop-gui duplicate key warning

packages/server/lib/controllers/xhrs.coffee, packages/server/package.json
I don’t see `getStream` being called anywhere in the code, this is the
only method that uses string-to-stream
Removes 33.2kB MINIFIED, 9.6kB MINIFIED + GZIPPED
=> remove string-to-stream dep (getStream isn't called anywhere)

packages/server/test/unit/plugins/child/run_plugins_spec.coffee, packages/server/test/unit/request_spec.coffee
Fixes #4481
Also increases the timeout on the 4x retry test for ECONNRESET, I could never get it to flake locally, only in CI, assuming it's just random slowdown. Bumping timeout from 100 to 250ms should fix this.
=> Fix `run_plugins_spec` test leaking into other tests, other flake in `request_spec`

packages/driver/src/cy/commands/agents.coffee, packages/driver/src/cy/commands/request.coffee, packages/driver/src/cy/commands/xhr.coffee, packages/driver/src/cypress/error_messages.coffee, packages/driver/src/cypress/server.coffee, packages/driver/src/cypress/utils.coffee, packages/driver/src/cypress/xml_http_request.coffee, packages/driver/test/cypress/integration/commands/xhr_spec.coffee
=> Warn when a percent-encoded URL is passed to cy.route

appveyor.yml
failed on second npm install for example here: https://ci.appveyor.com/project/cypress-io/cypress/builds/26026722/job/6k0c7uip7v2707pu
Maybe 3 times is the charm
=> NPM install up to 3 times on AppVeyor

packages/driver/src/cy/commands/actions/type.coffee, packages/driver/src/cypress/error_messages.coffee, packages/driver/test/cypress/fixtures/dom.html, packages/driver/test/cypress/integration/commands/actions/type_spec.js, packages/runner/src/lib/dom.js
- do not allow typing into readonly form controls as per https://www.w3.org/TR/2010/WD-html5-20101019/common-input-element-attributes.html#attr-input-readonly
- close #1246
=> Do not allow typing into readonly fields.

packages/web-config/webpack.config.base.ts
this fixes development mode of cypress visiting non-localhost domains, since `livereload` script was not hard-coding localhost
=> [internal] use localhost for webpack livereload plugin

packages/server/index.js, packages/server/package.json
- Closes #4763 
Manually verified fix works in Windows 10:
=> Fix DNS lookup for 'localhost' when offline on Windows

cli/types/index.d.ts, cli/types/tests/cypress-tests.ts
The `cy.once` function has not the corresponding types, I get the
> Property 'once' does not exist on type 'Chainable<undefined>'.ts(2339)
error while using it in a TS file (see the screenshot below).
I duplicated the `cy.on` signature an added the tests, let me know if I need to do something more 😊
Thank you guys 👋
=> Fix the cy.once typings

packages/desktop-gui/cypress/fixtures/specs.json, packages/desktop-gui/cypress/fixtures/specs_windows.json, packages/desktop-gui/cypress/integration/error_message_spec.js, packages/desktop-gui/cypress/integration/project_mode_spec.js, packages/desktop-gui/cypress/integration/specs_list_spec.js, packages/desktop-gui/cypress/integration/update_banner_spec.js, packages/desktop-gui/src/project/project.jsx, packages/desktop-gui/src/project/project.scss, packages/desktop-gui/src/specs/specs-list.jsx, packages/desktop-gui/src/specs/specs.scss, packages/desktop-gui/src/styles/components/_loading.scss, packages/desktop-gui/src/update/update-banner.jsx, packages/desktop-gui/src/update/updates.scss
- Closes #4888 
- Closes #4904
=> Desktop GUI layout issues/improvements

packages/https-proxy/lib/server.coffee, packages/https-proxy/test/unit/server_spec.coffee
Previously if Cypress received an erroneous HTTP CONNECT (for example, `CONNECT %7Balgolia_application_id%7D-dsn.algolia.net:443`), it would try to decode it via url.parse, receive an empty port, pass that empty port to `net.connect`, and then crash because `net.connect` requires a port and the rejection is unhandled.
This ensures that `net.connect` is always called with a port so that the request can cleanly error out in an expected way.
- Closes #3250
=> Do not crash on invalid HTTP CONNECT

cli/types/index.d.ts, cli/types/tests/chainer-examples.ts, cli/types/tests/cypress-tests.ts
Closes #4022
Provides strong typing for arguments and return type of `invoke` command. Also ensures `functionName` is the key of a function on the `Subject`.
Since typing becomes more strict, this is technically a breaking change, but isn't considered a big deal (see https://github.com/cypress-io/cypress/pull/4907#issuecomment-517582651)
=> Provide strong types for 'invoke' command (#4022)

packages/desktop-gui/cypress/integration/error_message_spec.js, packages/desktop-gui/src/styles/components/_alerts.scss
- Closes #4959 
No longer covers nav and footer when the error details are expanded:
Bonus: caps the height of the error details and scrolls them instead of the entire error message so 'Try Again' button stays visible (as long as desktop gui height is at a reasonable size):
=> Fix desktop-gui layout issues when there's a plugins file error

packages/server/lib/gui/auth.js, packages/server/test/unit/gui/auth_spec.js
shell.openExternal should've been converted to a Promise w/ Electron 5. Without this, Promise.fromCallback never resolves and `authCallback` is never set, leading to authentication failure.
=> Fix auth after Electron upgrade

packages/desktop-gui/cypress/integration/runs_list_spec.js, packages/desktop-gui/src/app/nav.scss, packages/desktop-gui/src/auth/login-form.jsx, packages/desktop-gui/src/auth/login-modal.jsx, packages/desktop-gui/src/auth/login.scss, packages/desktop-gui/src/project/project.scss, packages/desktop-gui/src/runs/setup-project-modal.jsx, packages/desktop-gui/src/specs/specs.scss
Scrolling some panes in the desktop-gui was broken after the Electron update, since Chromium changed how sizing of children of `display:flex` elements are handled.
This PR also adds the fallback error messages (Open this URL in your browser to continue login: ...) to the Runs List login, and updates the New Project Modal to use the existing LoginModal which has fallback error messages.
Runs & Configuration view both have this scrolling bug:
=> desktop-gui fixes: Fix scrolling after Electron upgrade, add auth fallback errors

packages/server/index.js, packages/server/lib/util/suppress_unauthorized_warning.ts, packages/server/test/unit/suppress_unauthorized_warning_spec.ts
- Closes #5248
Not user facing - suppresses a warning from Electron upgrade, which is unreleased
Manually verified that this technique works by doing the following:
```
➜ ~ NODE_TLS_REJECT_UNAUTHORIZED=0 node
Welcome to Node.js v12.4.0.
Type ".help" for more information.
> const originalEmitWarning = process.emitWarning
undefined
> 
> process.emitWarning = (warning, options) => {
...   if (warning && warning.includes && warning.includes('NODE_TLS_REJECT_UNAUTHORIZED')) {
.....     return
.....   }
... 
...   return originalEmitWarning.call(process, warning, options)
... }
[Function]
> tls.connect()
TLSSocket { ... }
> Thrown:
Error: connect ECONNREFUSED 127.0.0.1
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1054:14) { ... }
```
=> Suppress NODE_TLS_REJECT_UNAUTHORIZED warning

packages/driver/test/cypress/fixtures/dom.html, packages/driver/test/cypress/integration/e2e/domSnapshots.spec.js, packages/driver/test/cypress/support/utils.js, packages/runner/src/lib/dom.js
- fix #5239
- partially revert #1229 
- address #1215
- use jquery .width() and height() methods to calculate dimensions of elements for dom highlights
before:
after:
=> fix: switch back to using jquery width/height on element dimensions

packages/server/package.json
We were previously using this PR as the source for our `node-https-proxy-agent`: TooTallNate/node-https-proxy-agent#73 
But it got merged, and the author deleted his branch. So now we need to update this ref to point back to TooTallNate's repo (since he hasn't cut a release with these changes yet)
=> Update https-proxy-agent to point back to original repo

packages/driver/src/cypress.coffee, packages/reporter/cypress/integration/shortcuts_spec.js, packages/reporter/src/lib/shortcuts.js, packages/reporter/src/main.jsx
- Closes #5283
Fixes an issue where typing into the selector playground input could trigger keyboard shortcuts.
This does not need to be added to the changelog because the keyboard shortcut feature has not yet been released.
N/A
N/A
N/A
- N/A Has a PR to [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation) been submitted to document any user-facing changes? 
- N/A Have the [type definitions](cli/types/index.d.ts) been updated with any user-facing API changes?
- N/A Has the [cypress.schema.json](cli/schema/cypress.schema.json) been updated with any new configuration options?
=> Fix selector playground triggering keyboard shortcut

PULL_REQUEST_TEMPLATE.md, cli/lib/exec/spawn.js, cli/test/lib/exec/spawn_spec.js
- Closes #5241
Fixed a bug where Cypress would exit with an `ENOTCONN` error at the end of a test run if using Node 12.11.0 or greater on Windows.
~~Still trying to reproduce in my Windows VM, but a user in #5241 did say that this patch resolves the issue for them.~~
Was able to reproduce (only in `cypress run`) and confirmed that this patch does fix the issue for Node 12.11.0 and Windows 10.
=> Catch & ignore ENOTCONN errors when piping Cypress subprocess

packages/server/package.json
Not user facing
The fixes we need for our tests to run have been merged:
https://github.com/TooTallNate/node-https-proxy-agent/releases/tag/3.0.0
This dependency doesn't need to rely on a git hash now that the changes have been published to NPM.
=> Update https-proxy-agent to 3.0.0

packages/server/__snapshots__/scaffold_spec.coffee.js, packages/server/lib/scaffold/support/commands.js
- Closes #5360 
Fixes a grammatical mistake found in the scaffold command file
=> fix scaffold command grammatical error

cli/lib/exec/spawn.js, cli/test/lib/exec/spawn_spec.js
Not user facing
Tests were failing with Node 6: https://circleci.com/gh/cypress-io/cypress-test-node-versions/8271
Before this PR, only the `close` event could resolve the child process in the CLI. The `close` event is only emitted once all underlying stdio streams from the child process end.
With this PR, either the `close` event or the `exit` event can resolve the child process. `exit` is typically fired before `close`, but other than that has the same `(code, signal) => {}` callback signature.
N/A
=> Close CLI when exit event fires

cli/__snapshots__/spawn_spec.js, cli/lib/exec/spawn.js, cli/lib/util.js, cli/test/lib/exec/spawn_spec.js, cli/test/lib/util_spec.js, packages/electron/lib/electron.coffee, packages/server/__snapshots__/4_xhr_spec.coffee.js, packages/server/index.js, packages/server/lib/util/reset_node_options.ts, packages/server/test/e2e/4_xhr_spec.coffee, packages/server/test/support/fixtures/projects/e2e/cypress/integration/xhr_spec.coffee, packages/server/test/support/helpers/e2e.coffee
- Closes #5431 
Fixes a regression in 3.5.0 where the maximum size of an HTTP header or `cy.route()` stub body was limited to 8kb and requests would fail with HTTP error 431.
- Passes `--max-http-header-size=${1024 * 1024}` in `NODE_OPTIONS` environment var from CLI
- Passing it as a CLI arg (the way we thought it worked) does not seem to work with vanilla Electron binary or with built Cypress binary, so this is the only way
- By ordering it before the user-supplied NODE_OPTIONS, the user can still override this via NODE_OPTIONS if they choose
- Makes 4_xhr_spec e2e test go through CLI so it can run a test with this max http header size set
- User's original NODE_OPTIONS are backed up and restored once Electron successfully launches so that `node` processes launched by Cypress on behalf …
=> Always pass NODE_OPTIONS with max-http-header-size

circle.yml
Part 2 of #5512 
N/A
- Adds default NEXT_DEV_VERSION to build-npm-package so external PRs can build
- Only run Mac jobs in develop
- They are really slow due to Circle's limited macOS executor pool, oftentimes way longer than the Linux jobs
- Doesn't offer any additional benefit to build binary + package on mac on each commit, since we already do the same on Linux on each commit
N/A
=> Use a default NEXT_DEV_VERSION to build NPM package; only run Mac in dev

packages/server/__snapshots__/2_cdp_spec.ts.js, packages/server/__snapshots__/protocol_spec.ts.js, packages/server/lib/browsers/protocol.js, packages/server/lib/errors.coffee, packages/server/test/unit/browsers/protocol_spec.ts
- Partially addresses #5445
Increased the timeout when connecting to the Chrome DevTools Protocol from 5 seconds to 20 seconds. Added logging for when the connection is taking longer than 5 seconds to help with debugging.
- see https://github.com/cypress-io/cypress/issues/5445#issuecomment-547310305
- increasing this timeout is reasonable, if their CPU/memory is seriously constrained, Chrome could take a long time to launch
=> Increase CDP timeout to 20 seconds; add logs after 5 seconds

packages/server/lib/util/stream_buffer.js, packages/server/lib/util/stream_buffer.ts, packages/server/test/unit/stream_buffer_spec.js
- Closes #5585
Fixed an issue where Cypress would crash with `TypeError: Cannot read property 'length' of null` on some network requests.
- It's possible for a stray read/write to occur after the buffer has been deleted from memory, causing the bug seen in #5585 This PR adds tests that the buffer is not null to catch these.
=> Catch stray reads/writes on destroyed stream_buffers

packages/desktop-gui/cypress/integration/setup_project_modal_spec.js, packages/desktop-gui/src/app/nav.jsx, packages/desktop-gui/src/auth/auth-store.js, packages/desktop-gui/src/auth/login-modal.jsx, packages/desktop-gui/src/runs/project-not-setup.jsx, packages/desktop-gui/src/runs/runs-list.jsx, packages/desktop-gui/src/runs/setup-project-modal.jsx, packages/desktop-gui/src/settings/record-key.jsx
- Closes #5631 
Fixed a bug where Cypress would appear frozen after cancelling user login while in the "Runs" tab.
- Previously, there were 2 overlapping modals, even once the auth closed, the "setup project" was still open
- This PR makes it so that if the auth is closed without the user logging in, the "setup project" modal will never open
=> Properly close login modal during project setup

packages/server/test/unit/request_spec.coffee
- Closes 
N/A
* this fixes those annoying server-unit-tests that fail occasionally
* makes it so that a failure in these 3 tests will only fail the test, not crash the process
* increased timeout to reduce flake
N/A
=> Fix flaky request retrying unit tests

packages/server/__snapshots__/4_request_spec.coffee.js, packages/server/lib/request.coffee, packages/server/test/e2e/4_request_spec.coffee, packages/server/test/support/fixtures/projects/e2e/cypress/integration/request_spec.coffee
- Closes #5654
- Fixed a regression introduced in v3.6.1 where `cy.request` with `followRedirect: false` would fail if a Set-Cookie header was present on the response. Fixes #5654 
* was a simple error, currentUrl was undefined but could still end up being used in this edge case
N/A
=> Fix bug where cy.request does not work with followRedirect: false and Set-Cookie

cli/types/index.d.ts, cli/types/tests/cypress-tests.ts, packages/driver/src/cy/commands/connectors.coffee, packages/driver/src/cypress/error_messages.coffee, packages/driver/test/cypress/integration/commands/connectors_spec.coffee
- Closes #5754 
- `cy.its()` and `cy.invoke()` now support a number for the first argument.
=> Extend cy.its and cy.invoke to accept a number as 1st arg

packages/driver/src/cy/keyboard.ts, packages/driver/src/cypress/cy.coffee, packages/driver/src/dom/elements.ts, packages/driver/src/dom/selection.ts, packages/driver/test/cypress/integration/commands/actions/type_spec.js
- Closes #5703
- fixes issue with `.type` not respecting previous selection in non-selectionRange input element (email, number) (only way to change selection is with `.select()`)
- fixes issue with `.type` not respecting previous selection if current value of the input is same as key
- code from firefox branch was pulled in, causing the large amount of files changed. This will help reduce changes needed for firefox as well
before (incorrect): text is appended to the current selection
after (correct): text replaces current selection
before (incorrect): ignores current key, next character replaces selection 
after (correct): text replaces current selection, next character is typed after
=> fix type when previous selection in input in some cases

packages/driver/src/cy/keyboard.ts, packages/driver/src/cypress/cy.coffee, packages/driver/src/dom/elements.ts, packages/driver/src/dom/selection.ts, packages/driver/test/cypress/integration/commands/actions/type_spec.js
Reverts cypress-io/cypress#5809
This change broke the `piechopper` and `realworld` example projects
=> Revert "fix type when previous selection in input in some cases"

cli/lib/tasks/unzip.js, cli/test/lib/tasks/unzip_spec.js
- Fixes #3803 on Linux
- Cypress will attempt to use the `unzip` binary during `cypress install` before trying the slower, Node.js-based unzipping method.
- time spent unzipping (unzipMs):
- with node.js unzipping: 25667ms
- with `unzip`: 5320ms
- will definitely help people with slow CI
- technically, `unzip` could work on macOS or windows, but it's probably not going to exist on either so I'm not sure we should even attempt it
`cypress install` is much faster
- not sure how to test - existing `ditto` stuff doesn't have a test
- I have written a test for a situation when `unzip` is unavailable, but had to skip it - it was causing weird `verify_spec` failures
=> cli: unnzip Cypress using `unzip` utility on Linux

packages/driver/src/cy/keyboard.ts, packages/driver/src/cypress/cy.coffee, packages/driver/src/dom/elements.ts, packages/driver/src/dom/selection.ts, packages/driver/test/cypress/integration/commands/actions/type_spec.js
- retry of reverted PR #5809 with bugfix for regression caught in develop + more tests
- Closes #5703
- fixes issue with `.type` not respecting previous selection in non-selectionRange input element (email, number) (only way to change selection is with `.select()`)
- fixes issue with `.type` not respecting previous selection if current value of the input is same as key
- code from firefox branch was pulled in, causing the large amount of files changed. This will help reduce changes needed for firefox as well
before (incorrect): text is appended to the current selection
after (correct): text replaces current selection
before (incorrect): ignores current key, next character replaces selection 
after (correct): text replaces current selection, next character is typed after
=> try 2: fix type when previous selection in input in some cases

packages/server/lib/browsers/cdp_automation.ts, packages/server/package.json, packages/server/test/unit/browsers/cdp_automation_spec.coffee, packages/server/tsconfig.json
- Closes #5656
- previously, we were using `tough.cookieMatch` to filter cookies: https://github.com/cypress-io/cypress/blob/d56c551b0bb77a838da8de15bff137f1d96f9d47/packages/server/lib/browsers/cdp_automation.ts#L23-L37
- however, this is *incorrect*
- Cypress was designed around the internal 'cookie filter' having the same structure as the filter for WebExtensions cookies.getAll: https://developer.chrome.com/extensions/cookies#method-getAll
- the WebExtensions filter uses `domain` like this: "Restricts the retrieved cookies to those whose domains match or are subdomains of this one."
- we were using tough.domainMatch, which matches like an actual browser, instead
=> Fix CDP cookie matching algorithm

packages/server/lib/open_project.js, packages/server/test/unit/open_project_spec.js
- Fixes #5933 
- Fixed a bug where the specs list in interactive mode would not refresh when files are changed on disk.
=> fix desktop gui specs not being watched for file changes

packages/driver/package.json, packages/driver/src/cy/commands/cookies.js, packages/driver/src/cypress/error_messages.coffee, packages/driver/test/cypress/integration/commands/cookies_spec.coffee
- Closes #5642
- The strict cookie validation added in 3.5.0 for `cy.setCookie`, `cy.clearCookie`, and `cy.getCookie` has been removed. 
- added error wrapping for the automation errors, since they are more likely now
Users will now get the browser's error message and won't be subject to the overly strict strict-cookie-parser rules
=> Remove strict cookie validation from cookie commands

packages/launcher/package.json, packages/server/__snapshots__/2_headless_spec.ts.js, packages/server/lib/browsers/chrome.js, packages/server/lib/browsers/chrome.ts, packages/server/lib/browsers/electron.coffee, packages/server/test/e2e/2_headless_spec.ts, packages/server/test/support/fixtures/projects/e2e/cypress/integration/headless_spec.js, packages/server/test/support/fixtures/projects/e2e/cypress/plugins/index.js, packages/server/test/unit/browsers/chrome_spec.coffee
- Closes #5949
- Fixed a bug where `cypress run --headless` would not run Chrome-family browsers headlessly.
- mis-merged a decaffeinated version of `chrome.js` and tests didn't catch it :/
|    | chrome |
| --- | --- |
| headless | 800x600 |
| headed | 1050x1004 |
=> Fix `cypress run --headless`

DEPLOY.md
The `[][]` style is for reference links, but this link is supposed to use inline syntax `[]()`.
=> docs: fix markdown syntax for link

cli/types/index.d.ts, cli/types/tests/cypress-tests.ts
- Closes 
The type definitions for `cy.location()` have been improved.
```ts
cy.location('path') // type error
cy.location('pathname') // ✅
```
=> TypeScript: strict parameter type for `location`

cli/package.json, cli/types/cypress-npm-api.d.ts, cli/types/index.d.ts, cli/types/tests/cypress-npm-api-test.ts, cli/types/tests/kitchen-sink.ts
- Closes #5228
- Closes #6087
* EventEmitter2 types like `removeListener`, `removeAllListeners` are added to `Cypress` and `cy`.
* Missing `runUrl` is added to type.
* #5228: Unlike `on` or `once`, `removeListener` and `removeAllListeners` are [documented here](https://docs.cypress.io/api/events/catalog-of-events.html#Binding-to-Events). But their types didn't exist in `index.d.ts`. 
* #6087: [`runUrl` is documented](https://docs.cypress.io/guides/guides/module-api.html#cypress-run). But type is missing. 
N/A
* #5228: Added `eventemitter2` to `cli` and used `import()` in `index.d.ts`. 
* #6087: N/A
**Before:**
**After:**
- [NA] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [NA] Have API changes been …
=> Added missing EventEmitter2 type to Cypress and cy + missing runUrl to Cypress.run() result.

packages/reporter/src/commands/commands.scss
- Closes #5625 
Messages from `cy.log()` are now truncated at 50 lines the Command Log instead of the 1 line.
Before:
After:
Truncates the log to 50 lines and shows ellipsis to indicate truncation.
Clicking to log to console will log full `cy.log()` content. 
none.
=> Truncate cy.log() in Command Log to 50 lines instead of 1

packages/driver/src/cy/assertions.js, packages/driver/test/cypress/integration/commands/assertions_spec.js
- Closes #4981
Now, `should()` and `and()` with function argument can be chained. 
Sometimes, we want to organize our assertions by chaining `should()`s but we couldn't. 
N/A
N/A
Now code like below works.
```js
cy.wrap('ab')
.should((subject) => {
expect(subject).to.be.a('string')
expect(subject).to.contain('a')
})
.should((subject) => {
expect(subject).to.contain('b')
expect(subject).to.have.length(2)
})
.and((subject) => {
expect(subject).to.eq('ab')
expect(subject).not.to.contain('c')
})
```
- [NA] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [NA] Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?
- [NA] Have new configuration options been added to the …
=> should() chaining

packages/server/lib/browsers/protocol.js, packages/server/package.json, packages/server/test/unit/browsers/protocol_spec.ts
- Closes #6053 
- retries `CRI.List` if the `about:blank` page cannot be found, maybe the browser is starting
The CI runs should stop failing due to Cypress not being able to find the tab to control.
I did experiments with closing and opening Chrome Canary with lots of tabs and extensions and could get into situations where the initial `CRI.List` call returns no targets, but the next call returns full list of tabs. Adding retries seems like a solution we need to try.
No changes, unless the user is running Cypress with debug logs `DEBUG=cypress:server:protocol`. In that case they should see several calls 
```
cypress:server:protocol CRI.List on port 56428 +317ms
cypress:server:protocol CRI List { numTargets: 1, targets: [ { description: '', devtoolsFrontendUrl: …
```
=> retry CRI.List when connecting to the browser

packages/reporter/src/commands/commands.scss
- Closes #6145
log entries are truncated at 50 lines.
So this:
becomes:
=> show 50 lines of the logmessage of cy.get, too

packages/server/lib/util/ci_provider.js, packages/server/test/unit/ci_provider_spec.coffee
Enables and extends Bamboo + Git variables for use with CI/CD flows
Closes #4895 
We now collect more environment variables for Bamboo CI when recording for the Dashboard.
Cypress will now listen for the following Bamboo Variables:
ex: bamboo_VAR
- buildNumber
- buildResultsUrl
- planRepository_repositoryUrl
- planKey
- buildKey
- agentId
Also getting variables with underscores due to how Bamboo exports bash shell variables explained below.
>Bamboo variables are exported as bash shell variables. All full stops (periods) are converted to underscores. For example, the variable bamboo.my.variable is $bamboo_my_variable in bash. https://confluence.atlassian.com/bamboo/bamboo-variables-289277087.html#Bamboovariables-Systemvariables
When using Bamboo and recording runs for the Dashboard, the …
=> Update Bamboo variables for CI

cli/lib/exec/spawn.js, cli/lib/exec/xvfb.js
- Closes #6184
Fixes `cypress verify` crash on some systems caused by not defined `-screen`. 
`cypress verify` crashes in a docker image with this environment: 
```console
root@6c2f9da07ecd:/app# uname -a 
Linux 6c2f9da07ecd 4.9.184-linuxkit #1 SMP Tue Jul 2 22:58:16 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
root@6c2f9da07ecd:/app# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
root@6c2f9da07ecd:/app# apt list xvfb 
Listing... Done
xvfb/bionic-updates,now 2:1.19.6-1ubuntu4.3 amd64 [installed]
N: There are 2 additional versions. Please use the '-a' switch to see them.
root@6c2f9da07ecd:/app# node -v 
v10.14.2
root@6c2f9da07ecd:/app# ./node_modules/.bin/cypress -v 
Cypress package version: 3.8.2
Cypress binary …
```
=> fix: set explicit screen when spawning own xvfb

packages/driver/src/cy/keyboard.ts, packages/driver/test/cypress/integration/commands/actions/type_spec.js
- Closes #6116 
Fixed a regression in 3.5.0 so that `cy.type(force: true)` now types characters for readonly inputs.
**Before**
**After**
- [ X] Have tests been added/updated?
=> fix(type): type chars for readonly inputs if force: true

packages/driver/README.md, packages/driver/src/cy/commands/connectors.coffee, packages/driver/test/cypress/integration/commands/connectors_spec.coffee
- Closes #6216 
`its()` now supports 0 as a value for indexes or object keys
Many times a developer will intuitively reach for the first item in an array for tests or checks
(or for anything if I'm honest), and until now trying to reach that property using `.its(0)` threw an error.
Now developers world-wide would be able to check the first index of their array in a cypress environment. Well, I'm sure you could still have done it with `.its("0")` but just isn't as cool.
The tests check for edge cases, other than that I didn't do anything unexpected
this didn't work, now it does, it's the intuitive thing to do, so it's pretty chill
```javascript
cy.wrap(["cake","hamburger"]).its(0).should("eq","cake");
```
Is there anything to add to cypress-documentation? This now works as planned, I …
=> Issue #6216 -- have .its() receive the number 0 as parameter

packages/server/__snapshots__/process_profiler_spec.ts.js, packages/server/index.js, packages/server/lib/browsers/electron.coffee, packages/server/lib/browsers/index.js, packages/server/lib/cypress.js, packages/server/lib/modes/run.js, packages/server/lib/plugins/index.coffee, packages/server/lib/project.js, packages/server/lib/util/electron-app.js, packages/server/lib/util/process_profiler.ts, packages/server/lib/video_capture.js, packages/server/package.json, packages/server/test/integration/cypress_spec.js, packages/server/test/unit/browsers/browsers_spec.coffee, packages/server/test/unit/browsers/electron_spec.coffee, packages/server/test/unit/plugins/index_spec.coffee, packages/server/test/unit/util/process_profiler_spec.ts
- Closes #6169
- Added debug information about the memory & CPU usage of Cypress, which can be accessed by enabling the `cypress:server:util:process_profiler` debug stream.
looks like this (processes are grouped based on heuristics):
users can also choose to dump out ALL process information at every interval by using `cypress-verbose:server:util:process_profiler`, but this would be a looooot of data
users can also set `CYPRESS_PROCESS_PROFILER_INTERVAL` to the number of milliseconds between invocations
see above
=> Add process profiler for debugging

packages/driver/package.json, packages/driver/patches/sinon+8.1.1.patch, packages/driver/test/cypress/integration/commands/agents_spec.coffee
- Closes #6129 
Technically this is part of the sinon.js changelog... but...
- Constructors can now be spied upon with `cy.spy`.
=> Add test for cy.spy, cy.stub.callThroughWithNew on constructors

packages/server/__snapshots__/browsers_spec.coffee.js, packages/server/lib/browsers/index.js, packages/server/lib/errors.coffee, packages/server/test/unit/browsers/browsers_spec.coffee
- Closes 
- n/a - part of earlier --browser changes
n/a
`--browser canary` will not work in 4.x
=> Remove `--browser canary` backwards-compatibility

packages/launcher/lib/darwin/index.ts
Closes #6357
correct path for detecting Chromium on MacOS
- cypress crashes as described on #6357 
- Tests can't run
=> fix path typo for chromium mac

packages/launcher/lib/darwin/index.ts
Correct detection logic for Edge & Firefox Nightly on MacOSX
- Closes #6354
- Closes #6345
=> Correct detection logic for Edge & Firefox Nightly

packages/launcher/__snapshots__/spec.ts.js, packages/launcher/lib/detect.ts, packages/launcher/lib/windows/index.ts, packages/launcher/test/unit/windows/spec.ts
- Closes #6355 
- Added 64-bit Firefox paths to Windows browser detection. 64-bit Firefox will now be detected correctly on Windows.
=> Detect 64-bit Firefox on Windows

cli/types/index.d.ts
- Closes #6359
Update Cypress.Screenshot JSDoc link in cli/types/index.d.ts
Previous JSDoc with broken link
```
/**
* @see https://on.cypress.io/api/screenshot-api
*/
Screenshot: {
defaults(options: Partial<ScreenshotDefaultsOptions>): void
}
```
Updated JSDoc with working link
```
/**
* @see https://on.cypress.io/screenshot-api
*/
Screenshot: {
defaults(options: Partial<ScreenshotDefaultsOptions>): void
}
```
=> Fix broken Screenshot link in cli/types/index.d.ts

packages/server/lib/browsers/firefox.ts, packages/server/lib/browsers/utils.ts, packages/server/test/e2e/4_before_browser_launch_spec.ts, packages/server/test/unit/browsers/firefox_spec.ts
- Closes #6380 
- Fixed an issue where Cypress could fail to launch Firefox if another instance of Firefox is running.
- Fixed an issue where users could receive a "launched older version" error when launching Firefox Stable after launching Firefox Developer Edition or Firefox Nightly, or launching Firefox Developer edition after launching Firefox Nightly.
- prevents firefox from trying to connect to other running instances of FF
- puppeteer passes it: https://github.com/puppeteer/puppeteer/blob/8b49dc62a62282543ead43541316e23d3450ff3c/lib/Launcher.js#L488
- [na] Have …
=> Pass -no-remote when launching firefox

packages/server/package.json, packages/server/test/support/fixtures/projects/e2e/cypress/integration/browserify_babel_es2015_passing_spec.coffee, yarn.lock
- Closes #6403
Update `@cypress/browserify-preprocessor` to `2.1.4`, fixing a regression involving non-top-level requires in tests.
- N/A Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?
=> Upgrade browserify preprocessor to 2.1.4

packages/desktop-gui/cypress/integration/error_message_spec.js, packages/desktop-gui/cypress/integration/settings_spec.js, packages/desktop-gui/src/lib/ipc.js, packages/desktop-gui/src/project/error-message.jsx, packages/desktop-gui/src/project/project-model.js, packages/server/lib/gui/events.coffee, packages/server/test/unit/gui/events_spec.coffee
- Closes #6416
- selecting "copy to clipboard" will copy a markdown-formatted version of the error to the clipboard
- error titles can be specified to override the default "An unexpected error occurred"
- currently browser launch errors and plugin errors have custom titles
All project-level errors pretty much look like this:
**Examples of browser launch errors**
**Example of plugin error**
=> Update project error UI

packages/driver/src/cypress/server.coffee, packages/driver/test/cypress/integration/commands/xhr_spec.coffee
- Closes https://github.com/cypress-io/cypress/issues/5864
Fix deep call stacks for XHRs
Cypress wraps xhr callbacks with an override.  However, in the current code, every time a callback getter is called, we replace the original memoized callback with the wrapper. Every time the getter is called, another wrapper is added, which in extreme cases (e.g. iterating over chunks of a long request body and calling `onreadystatechange` for each chunk) can cause "Maximum call stack size exceeded" errors.
This change resolves the issue by not overwriting the memoized callback in the getter. The setter will still correctly memoize the new callback.
N/A
N/A
=> [driver] Fix xhr ballooning callback stack depth.

cli/types/index.d.ts, cli/types/tests/chainer-examples.ts
- Closes #2027
Fix the type of `cy.$$`.
- Why was this change necessary?
`cy.$$` and `Cypress.$` are different. But they use the same type. 
- What is affected by this change?
N/A
- Any implementation details to explain?
Copied related type from `jQuery.d.ts`.
Using jQuery utility functions with `cy.$$` like `cy.$$.escapeSelector` now fails.
- [NA] Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?
=> Fix the type of $$.

packages/proxy/lib/http/util/security.ts, packages/proxy/test/unit/http/util/security.spec.ts
- Improve fix for issue #1436 - #1437
Added support for running cypress tests on Jira plugins even when Jira scripts were not minified.
Issue #1436 was still occurring when running jira in none-minified mode, which was making impossible to run cypress test on jira plugins.
The fix just add an additional regular expression to catch also the case where the Jira getParentWindow is not minified.
No change.
=> fix(proxy): added support for jira getParent function even when not minified

appveyor.yml, circle.yml
This will cause CI to fail if the yarn.lock is out of date.
https://yarnpkg.com/cli/install
> If the --immutable option is set, Yarn will abort with an error exit code if anything in the install artifacts (yarn.lock, .pnp.js, ...) was to be modified.
=> Pass `--immutable` to `yarn` in CI

packages/server/lib/browsers/electron.js
- Closes #6662
- Fixed a bug where taking screenshots in Electron with Cypress debug logs enabled would fail.
truncated data object for logging was accidentally being returned instead of the original object
=> Fix taking screenshots in Electron with debug logs enabled

packages/network/lib/agent.ts, packages/server/lib/request.coffee, packages/server/test/performance/proxy_performance_spec.js
- Closes #6659
- Fixed a regression introduced in v3.8.3 where HTTPS requests could experience slowdown.
- in #5446, we set the TLS minimum version to TLSv1
- however, this also caused slowdowns in the proxy, which are visible in the `server-performance-spec`s if you look before and after this got merged
- all *intercepted (not passthru) HTTPS* connections were affected
- this PR makes it so that minVersion is set to TLSv1 only if the initial connection failed with a TLS version mismatch error
- this PR also fixes the `proxy_performance_spec`
- previously, the heuristics it was using were way too loose, and also easy to misunderstand
- now, it's as simple as "our proxy should never be more than 3x as slow as regular Chrome, under any conditions"
- 4.5x for the case where our proxy goes …
=> Fix proxy slowdown with intercepted HTTPS requests

packages/server/test/e2e/3_plugins_spec.js
This skips a currently flaky e2e test. It needs more time put into an actual fix, so I think it's best just to skip it for now, so it doesn't keep failing and getting in the way of other work.
=> Skip flaky e2e test for now

circle.yml
n/a
- fixes the install comments on `develop` - previously, darwin builds would say "[Circle has built](https://circleci.com/gh/cypress-io/cypress/281921) the `linux x64` version of the Test Runner."
- this PR makes it so they say `darwin x64` by using the `mac` executor
=> Fix `darwin` install comment

packages/desktop-gui/cypress/integration/ipc_bus_spec.js, packages/desktop-gui/src/lib/ipc-bus.js, packages/server/index.js, packages/server/lib/gui/events.coffee, packages/server/lib/modes/interactive.js, packages/server/lib/util/electron-app.js, packages/server/test/unit/gui/events_spec.coffee
- Closes #6750 
- Fixed a regression in 4.2.0 where Electron deprecation warnings were printed to `stderr` in `open` mode.
- now, objects sent via IPC in `open` mode are cloned to exclude functions and elements, to make the Structured Clone Algorithm usable: https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm
- previously, `allowRendererProcessReuse` was only set in `run` mode, now it's set in `open` mode too to get rid of the warning
- now we set `noDeprecation` when the env is `production`, so no deprecation warnings will be printed in built binaries …
=> Fix deprecation warnings from Electron 8 upgrade

packages/driver/src/dom/transform.ts, packages/driver/test/cypress/fixtures/dangling-element.html, packages/driver/test/cypress/integration/dom/visibility_spec.ts
- Closes #6745
`vue-fragment` made `isVisible` fail. It is fixed in this PR.
Because of the manipulation of `parentNode` by `vue-fragment`. Dangling elements are created and they return empty string. [Because `getComputedStyle()` returns empty strings when the element is not in the DOM tree.](https://bugs.chromium.org/p/chromium/issues/detail?id=558165)
N/A
Created a test file that replicate the behavior. They're done in these 3 steps.
**Step 1. Create new DOM tree**
**Step 2. Add paragraph to parent and set parentNode to container**
**Step 3. Remove container and set parentNode to parent**
Because of the Step 3, container is not in the DOM tree, but it's the parent of paragraph. So, it can be accessed and the bug occurred. 
`cy.get()` works even if `vue-fragment` is used. 
- [NA] Has a …
=> Ignore dangling node in DOM tree.

cli/package.json, yarn.lock
Reference: #6793
Versions of extract-zip before `1.6.8` depended on a vulnerable version of `minimist` via `mkdirp`:
https://github.com/maxogden/extract-zip/pull/85#issuecomment-603563097
Minimist vulnerability: https://app.snyk.io/vuln/SNYK-JS-MINIMIST-559764
Less security vulnerabilities.
=> Upgrade extract-zip to address vulnerability

packages/server/package.json, yarn.lock
We are already using 4.0.0, but this changes it to be via npm, not via a commit hash.
=> tough-cookie@4.0.0

packages/server/package.json, yarn.lock
- Closes #6458 
- Fixed an issue where Cypress could crash with a "This socket has been ended by the other party" error when testing applications that make use of websockets.
- see https://github.com/http-party/node-http-proxy/issues/1432 for details
=> Fix 'This socket has been ended by the other party'

packages/server/__snapshots__/2_cookies_spec.coffee.js, packages/server/lib/request.coffee, packages/server/test/e2e/2_cookies_spec.coffee, packages/server/test/support/fixtures/projects/e2e/cypress/integration/cookies_spec_baseurl.coffee
- Closes #6890
- Fixed an issue where invalid `Set-Cookie` values could cause requests to fail with a "cannot read property key of undefined" error. Now, invalid `Set-Cookie` values will be ignored.
- previously, this error was hidden behind the "Parse Error: Invalid header character", which was fixed in #5988 
- some users who were experiencing that error before 4.3.0 are now seeing this error
- correct way forward is to ignore the invalid values: https://github.com/cypress-io/cypress/issues/6890#issuecomment-609913483
- [na] Have new configuration options been added …
=> Ignore invalid Set-Cookie values

circle.yml
As a first step towards #6848 this PR re-enables `dtslint` in our CI flow. 
- This re-enables dtslint tests after they were paused earlier in #6819 due to failures with `ts@next`.
=> Bring back dtslint

packages/driver/src/cy/chai.js, packages/driver/src/cy/commands/navigation.coffee, packages/driver/src/cy/errors.coffee, packages/driver/src/cypress/error_utils.js, packages/driver/src/cypress/runner.js, packages/driver/test/cypress/integration/cypress/error_utils_spec.js, packages/server/__snapshots__/1_commands_outside_of_test_spec.coffee.js, packages/server/__snapshots__/6_uncaught_spec_errors_spec.coffee.js, packages/server/__snapshots__/6_uncaught_support_file_spec.coffee.js, packages/server/__snapshots__/7_record_spec.coffee.js
- Closes #6964 
- Closes #6969 
- Uncaught errors now display their stack trace
- Assertion errors now include a stack trace that includes the calling code
Uncaught error - stdout before:
Uncaught error - stdout after:
Assertion error - stdout before:
Assertion error - stdout after:
- N/A Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?
=> Don’t remove stack from uncaught errors

packages/desktop-gui/cypress/integration/project_nav_spec.js, packages/desktop-gui/src/lib/browser-model.js, packages/launcher/__snapshots__/browsers_spec.ts.js, packages/launcher/__snapshots__/darwin_spec.ts.js, packages/launcher/__snapshots__/windows_spec.ts.js, packages/launcher/lib/browsers.ts, packages/launcher/lib/detect.ts, packages/launcher/lib/linux/index.ts, packages/launcher/lib/types.ts, packages/launcher/lib/utils.ts, packages/launcher/test/fixtures.ts, packages/launcher/test/unit/darwin_spec.ts, packages/launcher/test/unit/detect_spec.ts, packages/launcher/test/unit/linux_spec.ts, packages/launcher/test/unit/windows_spec.ts, packages/server/lib/browsers/utils.ts, packages/server/lib/modes/run.js, packages/server/test/integration/cypress_spec.js, packages/server/test/unit/browsers/chrome_spec.coffee
- Closes #7020 
- Fixed a bug preventing Cypress from launching on systems where Chromium was installed via Snapcraft.
- in `cypress open`, project would never load and spinner would run forever. on `cypress run`, no output is printed to the console (browser detection runs before anything is printed)
- mysteriously, execa would hang on --version when used with the snap
- switched to using cp instead since execa is only really used for windows benefits and it works fine
- added a 5s timeout to getVersionString since it should never take that long
- instead of writing to the usual appdata dir, write to `$HOME/snap/chromium/current/Cypress` since that's the only place this chromium can write …
=> Fix using Chromium installed via snapcraft

packages/server/lib/plugins/resolve.js
- Closes #7036
Fixed typo that made user projects include bundled typescript.
This bug made `export default` and import object destruction impossible.
We won't import bundled typescript to user projects.
Because TypeScript uses duck typing, it cannot detect when an invalid field is added to an object. ([It's been discussed since 2014](https://github.com/microsoft/TypeScript/issues/202), but it seems that there's no clear answer yet.)
Because of that, I didn't notice that `baseDir` is wrong. (The right name is `basedir`.)
I fixed the typo.
Unfortunately, I guess there's no other way to test them except adding some test code to master branch tests.
The test passes.
- [NA] Have tests been added/updated?
- [NA] Has a PR for user-facing changes been opened in …
=> Fix typo that made user projects include bundled typescript.

scripts/cypress.js
- Closes #7052
- https://github.com/cypress-io/cypress/commit/abf4d858694e1be3ae6b93da42c6678ad22ba290#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R138 upgraded execa, from execa 2.0.0+ onwards, errors no longer have a `code` prop, only an `exitCode` prop
- affected `cypress` script used by `driver`'s `cypress:run`
- did not add a verify:mocha:results stage to driver tests …
=> Fix internal driver tests exiting with wrong exitCode

DEPLOY.md
The deploy doc is great, but could use some more details to help a new deployer release a new version of Cypress.
=> Improve deploy doc

packages/server/lib/util/specs.js
Use `stderr` for debugging information instead of `stdout`, otherwise `e2e` tests will always fail with `DEBUG` enabled because it causes the `stdout` snapshots to differ.
=> Use console.error for logging specs found in debug mode

packages/driver/src/cy/commands/task.js, packages/driver/test/cypress/integration/commands/task_spec.coffee, packages/server/__snapshots__/6_task_spec.coffee.js
- Closes #7263 
- N/A as long as this goes in next release with error improvements. It's just an extension of that and doesn't need to be called out explicitly.
Before:
After (default):
After (stack trace open):
- N/A Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?
=> Improve cy.task errors

packages/launcher/lib/linux/index.ts
- Fixed an issue where browsers would not be detected on macOS or Linux if they take longer than 5 seconds to exit from a `--version` command. Timeout has been bumped to 30 seconds.
Users have reported hitting this limit in GitHub Actions while detecting browsers.
=> fix(launcher): Increase getVersionString timeout to 30s

packages/server/lib/browsers/protocol.js, packages/server/test/unit/browsers/protocol_spec.ts
- Closes #6518 (provides a better error when there is some issue launching Chrome)
- Improved error handling when Cypress launches Chromium-family browsers.
Moving this .catch statement to clean up errors, for example, the error that occurs in #6518 will now be wrapped by this.
=> fix(server): handle more CDP connection errors

cli/types/index.d.ts, cli/types/tests/cypress-tests.ts
SinonStatic is a superset of SinonApi:
```ts
type SinonStatic = SinonSandbox & LegacySandbox & SinonApi;
```
- Changed type for `Cypress.sinon` to `SinonStatic`.
- makes sandbox methods like sinon.stub usable from Cy tests
=> fix(types): use SinonStatic for Cypress.sinon type

packages/driver/src/cypress/resolvers.ts, packages/driver/test/cypress/integration/cypress/resolvers_spec.ts, packages/driver/ts/internal-types.d.ts, packages/rewriter/test/unit/js-spec.ts, packages/server/__snapshots__/6_visit_spec.coffee.js, packages/server/test/support/fixtures/projects/e2e/cypress/integration/source_rewriting_spec.js, packages/server/test/support/fixtures/projects/e2e/static/settimeout_redirect_document_href.html, packages/server/test/support/fixtures/projects/e2e/static/settimeout_redirect_href_hash.html, packages/server/test/support/fixtures/projects/e2e/static/settimeout_redirect_set_document_location.html, packages/server/test/support/fixtures/projects/e2e/static/settimeout_redirect_set_document_location_hash.html, packages/server/test/support/fixtures/projects/e2e/static/settimeout_redirect_set_window_document_location.html, packages/server/test/support/fixtures/projects/e2e/static/settimeout_redirect_window_document_href.html
- Closes #7402 
- With experimentalSourceRewriting enabled, fixed unexpected behavior when using `document.location` to set the current URL.
* extended existing replacement for `window.location` to cover `document.location` as well
* added tests for this, a well as hash usage
=> fix(rewriter): rewrite accesses to document.location

cli/types/cypress.d.ts, packages/driver/src/cy/commands/request.js, packages/driver/src/cypress/error_messages.coffee, packages/driver/test/cypress/integration/commands/request_spec.coffee
- Closes #2029 
- Closes #3576 
Originally, the PR https://github.com/cypress-io/cypress/pull/7380 (which describes the issue throughly and includes case analysis) was the attempt to solve the issues in consideration, but it was thought that there might be a different, yet very simple (one-line) solution.
Add support for `encoding` option in `cy.request()`
Introduce/use/support `encoding` option to [`cy.request()`](https://docs.cypress.io/api/commands/request.html), which is already supported by `@cypress/request` package (see [request.js:1130](https://github.com/cypress-io/request/blob/8afbb25/request.js#L1130)).
By introducing this option, the user can specify the `encoding` of the `response.body`. Which means, for instance, that the user can set the `encoding` of request to grab a …
=> feat(driver): Add support for `encoding` option in cy.request()

packages/driver/src/cy/commands/navigation.js
`$utils.throwErrByPath` isn't a function anymore, but it doesn't matter because this error is already handled correctly above
- Closes 
n/a - not user-facing
- [na] Have API changes been updated in the [`type definitions`](cli/types/cypress.d.ts)?
=> chore(driver): remove dead code in cy.visit

packages/driver/src/cypress/xml_http_request.js, packages/driver/test/cypress/integration/cypress/xml_http_request_spec.js
- Closes #7518 
- Fixed a regression in 4.6.0 where an XHR response without a body would cause the error `Cannot read property '__error' of null`
- This was introduced from an error during decaffeination in https://github.com/cypress-io/cypress/pull/7227
- N/A Have API changes been updated in the [`type definitions`](cli/types/cypress.d.ts)?
=> Fix "Cannot read property '__error' of null" error

packages/driver/package.json, packages/server/test/e2e/3_issue_7481.ts, packages/web-config/package.json, packages/web-config/webpack.config.base.ts, yarn.lock
- Closes #7481
- Fixed an issue where authenticated URLs would error with `Request cannot be constructed from a URL that includes credentials: /__cypress/runner/./wasm/mappings.wasm`
For the sake of source maps and all their goodness, we use the [source-map](https://github.com/mozilla/source-map) package. It needs to load a `mappings.wasm` file in order to parse the source map. Previously, we provided a url to the `mappings.wasm` file and the `source-map` package loaded it asynchronously via `fetch`.
This worked fine in most cases but failed when the URL was authenticated, because the `fetch` needs to be authenticated too.
The fix is that, instead of having the `mappings.wasm` loaded asynchronously, we provide it to the `source-map` package synchronously as an `ArrayBuffer`. Therefore, no …
=> Fix loading mappings.wasm on authenticated URLs

packages/rewriter/lib/threads/index.ts, packages/rewriter/lib/threads/types.ts, packages/rewriter/lib/threads/worker.ts
- Fixed a bug in `experimentalSourceRewriting` where Cypress could exit with a SIGABRT instead of exiting normally.
- try to let the threads shut themselves down to avoid https://github.com/electron/electron/issues/23366
- users were still encountering the SIGABRT when simply using `worker.terminate` from the main thread, which was the original workaround: https://github.com/cypress-io/cypress/issues/7297#issuecomment-635849687
- [na] Have API changes been updated in the [`type definitions`](cli/types/cypress.d.ts)?
=> fix(rewriter): make workers self-exit to avoid SIGABRTs

packages/reporter/cypress/integration/test_errors_spec.js, packages/reporter/src/collapsible/collapsible.scss, packages/reporter/src/collapsible/collapsible.spec.tsx, packages/reporter/src/collapsible/collapsible.tsx, packages/reporter/src/commands/commands.scss, packages/reporter/src/errors/errors.scss, packages/reporter/src/errors/test-error.tsx, packages/reporter/src/runnables/runnables.scss
- Closes #7563
Moves the location of the stack trace and print to console button to below the code frame in an error message
Before:
After:
=> Move stack trace below code frame in runner

packages/driver/src/cypress/chai_jquery.js, packages/driver/src/dom/elements.ts, packages/driver/test/cypress/integration/commands/assertions_spec.js
- Closes #7603
`should('have.value')` works with `<progress>`, `<meter>`, `<li>`.
- Why was this change necessary? Regression
**Before:**
**After:**
- [N/A] Have API changes been updated in the [`type definitions`](cli/types/cypress.d.ts)?
- [N/A] Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?
=> Make should('have.value') work with <progress>, <meter>, <li>

cli/types/cypress.d.ts, packages/server/test/support/fixtures/projects/ts-proj-with-own-tsconfig/cypress/support/.eslintrc.json, packages/server/test/support/fixtures/projects/ts-proj-with-own-tsconfig/cypress/support/commands.ts
- Closes #7510
Fix the type signature of Cypress.Commands.add and overwrite.
- Why was this change necessary? Type failure for @typescript-eslint/no-misused-promises rule.
N/A
- [N/A] Have API changes been updated in the [`type definitions`](cli/types/cypress.d.ts)?
- [N/A] Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?
=> fix: Cypress.Commands.add Type Signature for @typescript-eslint/no-misused-promises rule

packages/driver/src/cy/errors.js, packages/driver/test/cypress/integration/e2e/uncaught_errors_spec.js
- Closes #7590
- Fixed an issue where errors thrown as strings would not display correctly.
If a user application threw an error as a string (`throw 'some error'` as opposed to `throw new Error('some error')`, an internal error `Cannot read property 'split' of undefined` would be displayed and the `uncaught:exception` event would be called with the error as a string instead of as an object with typical error properties.
If there is a string exception in an application, the test will now fail with the correct error. If the `uncaught:exception` event is being used, it will be called with an error object now, as it should.
- N/A Have API changes been updated …
=> Handle uncaught errors thrown as strings

cli/types/cypress.d.ts, cli/types/tests/cypress-tests.ts
- Updated type defitions for `cy.wait(ms)` to correctly yield the type of the previous Subject.
Updated types to match the docs:
=> fix(types): cy.wait yields previous subject

cli/schema/cypress.schema.json, cli/types/cypress.d.ts, cli/types/tests/cypress-tests.ts, packages/driver/cypress/integration/commands/actions/click_spec.js, packages/driver/src/dom/elements.ts, packages/server/lib/experiments.ts
- Closes #7679 
- Fixed an issue where a click would hang if the subject had a shadow root and shadow DOM support was not enabled.
Also fixed TypeScript types and descriptions that referenced the old option name `ignoreShadowBoundaries`.
Clicks no longer hang when the subject has a shadow root and shadow dom support is not enabled.
- N/A Have API changes been updated in the [`type definitions`](../cli/types/cypress.d.ts)?
- N/A Have new configuration options been added to the [`cypress.schema.json`](../cli/schema/cypress.schema.json)?
=> Fix issue where click hangs if subject has a shadow root and shadow dom support is not enabled

packages/server/lib/modes/record.js, packages/server/test/unit/api_spec.js
- Closes #7548
- Dashboard upload of `stdout` is deferred until after the video/image uploads complete
`stdout` does not need to be sent on both `PUT /instances/:id` and `PUT /instances/:id/stdout`. Sending in the first could cause the request to the dashboard to fail if the payload size is too large, which will prevent the run from completing, prevent any asset uploads, etc.
Stdout will be delayed from appearing in the dashboard until after any assets have uploaded
=> Fix: skip sending stdout on PUT /instances

packages/server/lib/util/node_options.ts
n/a - internal only
Now, the server will pass on `--inspect` or `--inspect-brk` arguments to the forked process if the NODE_OPTIONS check fails.
This fixes the behavior of the `yarn dev-debug` command in root.
- [na] Have API changes been updated in the [`type definitions`](../cli/types/cypress.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](../cli/schema/cypress.schema.json)?
=> chore: make NODE_OPTIONS fork with --inspect args

packages/driver/cypress/fixtures/shadow-dom.html, packages/driver/cypress/integration/commands/querying_spec.js, packages/driver/cypress/integration/commands/traversals_spec.js, packages/driver/src/cy/commands/navigation.js, packages/driver/src/cy/commands/querying.js
- Closes #7676
- Fixed a bug where querying shadow dom could cause the error `Cannot read property 'length' of undefined` in run mode
The root cause of this issue is that the framework Salesforce uses (_Aura_) wraps the native `document.querySelectorAll`. jQuery (via Sizzle) [determines that `document.querySelectorAll` is not available](https://github.com/jquery/sizzle/blob/af163873d7cdfc57f18b16c04b1915209533f0b1/src/sizzle.js#L796) in that case, because it doesn't think it's native (even though _Aura_ calls the native method within its wrapper). This causes jQuery to fall back to other methods of querying, which don't work well with shadow dom and result in the error at issue. 
Why does it only happen in run mode? Because there is no snapshotting. In interactive mode, an early XHR …
=> Fix issue with finding elements in shadow dom under specific conditions

packages/server/lib/util/node_options.ts, packages/server/test/scripts/run.js, packages/server/test/unit/node_options_spec.ts
- Closes #7722
- Fixed an issue where Cypress could exit successfully even with failing tests under certain conditions.
- if Cypress was spawned in global mode and was killed via a signal, the parent process would exit with a 0 exit code due to #7722
- also fixed an instance of this pattern in the server tests
- all other instances of exit signal handling are correct
- [na] Have API changes been updated in the [`type definitions`](../cli/types/cypress.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](../cli/schema/cypress.schema.json)?
=> fix: correct bad propagation of exit signals

packages/server/package.json, packages/server/patches/@benmalka+foxdriver+0.4.0.patch, packages/server/test/e2e/1_firefox_spec.ts, scripts/run-docker-local.sh
- Closes #7723 
- Fixed a bug where debug logs from the `@benmalka/foxdriver` module would always appear if any `DEBUG` environment variable was set.
- now `DEBUG=@benmalka/foxdriver` can be used to isolate this log stream
- [na] Have API changes been updated in the [`type definitions`](../cli/types/cypress.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](../cli/schema/cypress.schema.json)?
=> fix(server): fix excess debug logs from foxdriver

packages/driver/cypress/fixtures/generic.html, packages/driver/cypress/fixtures/global_parent_definition.html, packages/driver/cypress/integration/commands/actions/click_spec.js, packages/driver/cypress/integration/commands/actions/type_spec.js, packages/driver/cypress/integration/issues/6412_spec.ts, packages/driver/src/dom/coordinates.js
- Close #6412 
- Using Cypress commands to traverse the DOM on an application with a global `parent` variable will no longer throw `Illegal Invocation` errors.
- When the AUT has a global variable called `parent`, our calls to `win.parent` actually return this global variable instead of the window's parent as expected. 
- Honestly, I would love a better way to target the actual `window.parent` when it's overwritten, but I couldn't find a way to do this for the AUT window + any other nested iframes this could also be defined in.
- Doing the work for this actually highlighted another bug on calculating the highlight coordinates when clicking on an element within an iframe with global parent definition. I decided not to address this as part of this work as it seems very rare. …
=> Ensure that the window's parent is a window before checking for props of AutIframe

packages/server/lib/browsers/cri-client.ts, packages/server/test/unit/browsers/cri-client_spec.ts
- Closes #7180
- Fixed an issue where Cypress tests in Chromium-family browsers could randomly fail with the error "WebSocket is already in CLOSING or CLOSED state."
- we retry on certain connection errors, this was not one of them, now it is (since it represents a race condition, where a reconnect could still succeed)
=> fix: attempt reconnection if CDP websocket in closed/closing state

cli/types/cypress.d.ts, packages/driver/cypress/integration/commands/actions/scroll_spec.js, packages/driver/src/cy/commands/actions/scroll.js, packages/driver/src/cypress/error_messages.js
- Closes https://github.com/cypress-io/cypress/issues/1924
You can now pass the `ensureScrollability: false` option to `.scrollTo()` to skip the scroll ability check of an element. Addresses https://github.com/cypress-io/cypress/issues/1924.
- I've used `ensureScrollability`, but it seems quite a long name for an option. Suggestions are welcome.
- I'll open a PR to update the documentation once or if the PR is approved and we agree on the option naming.
Now users can use `scrollTo()` on an element that can have a variable height without getting an error.
Passing `ensureScrollable: false`
Passing incorrect arg to `ensureScrollable`
Trying to scroll unscrollable el without `ensureScrollable: false`
=> Add ensureScrollability option to scrollTo command

packages/server/lib/util/args.js, packages/server/test/unit/args_spec.js
- Closes https://github.com/cypress-io/cypress/issues/6891
We now handle values containing exponential operators passed to `--env` command line option. Fixes: https://github.com/cypress-io/cypress/issues/6891
Debugging and suggestions for fixing the issue are in the issue comments.
Logs:
```zsh
node $(yarn bin cypress) open --dev --global --env WSD_VERSION_HASH=769e98018
cypress:server:args argv array: [ '/Users/user/.npm/_npx/19508/lib/node_modules/node/bin/node', '/Users/username/cypress/scripts/start.js', '--env', 'WSD_VERSION_HASH=769e98018', '--cwd', '/Users/username/cypress' ] +0ms
...
cypress:server:args argv options: { _: [ '/Users/username/cypress/packages/electron/dist/Cypress/Cypress.app/Contents/MacOS/Cypress' ], 'max-http-header-size': '1048576 --http-parser=legacy', config: …
```
=> Handle env values containing exponential operators

packages/driver/cypress/integration/commands/fixtures_spec.js, packages/driver/cypress/integration/commands/xhr_spec.js, packages/driver/src/cy/commands/fixtures.js, packages/driver/src/cy/commands/xhr.js
- Closes #7818
- Closes #8010 
- cy.route throws an error when fixture cannot be found.
- In addition I've fixed the `fixture` command which raised an error for `null.json`. BTW. did you know that if the fixture contains following key in the returned object `__error` then `cy.fixture` throws an error :) ?
- Why was this change necessary?
To provide better error message in case of missing fixture or problem with parsing
- What is affected by this change?
`cy.route` calls `cy.fixture` if response meets criteria of fixture shortcut `fx:` | `fixture:`. With this additional check we can raise an error even before HTTP request is sent.
If fixture file doesn't exists, or there is a problem with fixture, `cy.route` will raise an error.
Before:
Now:
=> fix: cy.route swallows the error about missing fixture #7818

cli/schema/cypress.schema.json, cli/types/cypress.d.ts, packages/driver/cypress/integration/commands/screenshot_spec.js, packages/driver/src/cy/commands/screenshot.js, packages/server/lib/config.js, packages/server/test/unit/config_spec.js
- Closes https://github.com/cypress-io/cypress/issues/5029
Now you can disable screenshots by setting `screenshotOnRunFailure` to `false` in the configuration. 
- Any suggestions about the configuration option name?
- A PR for the documentation still needs to be opened (I will wait for this PR to be approved to do so)
It will be easier to disable screenshots.
=> feat: Add configuration option for disabling screenshots

cli/types/cypress.d.ts, cli/types/tests/chainer-examples.ts, cli/types/tests/kitchen-sink.ts
- Closes #5573
Add more `should` interface definitions.
- Why was this change necessary? Help users with more auto completion.
- Any implementation details to explain? 
To remove duplication in comments, I used union types. Without it, many functions have almost identical 4 different documentation comments.
Now, auto completions like `'have.lengthOf'` work.
It's because there are too many valid combination for chai.js. It's simply impossible to cover all of them. And we can block valid assertions in TS codes. 
It's not hard to find them. All we need to do is running the test once.
- [N/A] Have API changes been …
=> fix: add more should interface definitions.

cli/types/cypress-npm-api.d.ts, cli/types/tests/cypress-npm-api-test.ts
- Closes #7309 
Moved types inside `'cypress'` module to `CypressCmd` namespace to make them usable. 
- Why was this change necessary? Types defined in `cypress-npm-api.d.ts` weren't usable for users who want to create their own TypeScript commands.
N/A
=> fix: Introduce CypressCommandLine namespace to type NPM module api

cli/types/cypress.d.ts
- Closes #8144
Correct type for Cookie['expiry']
=> fix: Cookie interface expiry prop

packages/server/__snapshots__/5_screenshots_spec.js, packages/server/lib/screenshots.js, packages/server/test/support/helpers/e2e.ts, packages/server/test/unit/screenshots_spec.js
- Closes #2403
- Fixed an issue where screenshots could fail because of names that were too long for the filesystem to accept.
- now using bytes instead of characters to resize the string
- if an ENAMETOOLONG error is encountered, the string will be further downsized, down to a minimum of 64 bytes after which the error will still be thrown, like described in https://github.com/cypress-io/cypress/pull/2635#issuecomment-434839317 …
=> fix: truncate screenshot filenames using byteLength

packages/driver/cypress/integration/commands/xhr_spec.js, packages/driver/src/cy/commands/xhr.js
Fix for introduced regression from https://github.com/cypress-io/cypress/pull/7983 in cy.route  fixture inside the route command
First of all I'm sorry for introduced regression. I didn't mean to and I hope you will forgive me :) I've decided to revert some of my changes related to load fixture in `cy.route`. The only thing I left is a improved error message in case when fixture doesn't exist.
- Closes #8181 
Revert the code that tries to load a fixture inside a cy.route command.
We don't need to try load a fixture inside a cy.route. Error message has been improved, but it will show up only when user waits for a stubbed route or returns a rejected promise from custom command.
In every other case, test will be not marked as failed (even when fixture has not been found).
Previous behaviour …
=> fix: (driver) - Fix for introduced regression in cy.route 

packages/server/lib/controllers/spec.js, packages/server/package.json, packages/server/test/unit/spec_spec.js, yarn.lock
N/A - this only affects unreleased 5.0 branch
The issue:
- webpack preprocessor emits ‘rerun’ for every file once it’s done bundling it. It does this even when it’s the first time the file is bundled. 
- When running 'All Specs', this results in ‘rerun’ getting called over and over in the runner and it re-requesting iframe/_all over and over.
- This loads the iframe and multiple specs over and over, eventually leading to an EPIPE error thrown by express sendFile, because the socket open for the file is now closed by the new version of the file being sent. (This and the previous items occur outside of 'All Specs', but are unlikely to cause the next item because it just happens once instead of being multiplied by the number of specs).
- The EPIPE error is obscured by the …
=> fix: Fix crashing due to rerunning on initial bundle of specs

packages/desktop-gui/cypress/fixtures/browsers.json, packages/desktop-gui/cypress/fixtures/config.json, packages/desktop-gui/cypress/integration/project_nav_spec.js, packages/desktop-gui/src/project-nav/browsers.jsx, packages/desktop-gui/src/project/project-model.js
- Closes #8281 
- Fixed a bug where the "last used browser" would be incorrectly remembered in `cypress open` if a non-default-channel browser was selected.
=> fix(desktop-gui): remember last browser used w/ non-default channel

packages/driver/src/cy/jquery.js
TR-244
Should fix [this flaky failure](https://app.circleci.com/pipelines/github/cypress-io/cypress/12876/workflows/15a6e1bb-66b4-4aba-a59e-fc34d993a826/jobs/421794).
The error originates from [this `cy.readFile().then` call](https://github.com/cypress-io/cypress-documentation/blob/develop/cypress/support/defaults.js#L48). We try to look up the remote jQuery instance from  even though the subject is not a dom element. This causes it to _sometimes_ fail with a cross-origin error in Firefox.
This prevents attempting to look up the remote jQuery instance in cases where the subject is not a dom element.
=> fix: Avoid looking up remote jquery instance if subject is not an element

packages/example/package.json, yarn.lock
Branched it correctly this time.
=> chore: Upgrade cypress-example-kitchensink to 1.12.0

packages/https-proxy/package.json, packages/https-proxy/test/integration/proxy_spec.js, packages/network/package.json, packages/network/test/unit/agent_spec.ts, packages/server/lib/util/proxy.ts, yarn.lock
- Close #8287 
- Revert #7900 
- We fixed a regression in 4.11.0 where the `NO_PROXY` environment variable would no longer be respected over `npm_config_noproxy` environment variables. This could have potentially caused issue for proxied requests.
- It seems the original dep is not intending to change the behavior of the dep, so we'll have to do some further work if we want to update the dep. https://github.com/Rob--W/proxy-from-env/issues/13
=> fix: NO_PROXY env var no longer be respected over npm_config_noproxy env var

packages/driver/cypress/integration/commands/assertions_spec.js, packages/driver/src/cy/commands/asserting.js, packages/driver/src/cypress/error_messages.js
* Closes https://github.com/cypress-io/cypress/issues/883
An error is now thrown when incorrectly using a single language chainer instead of an actual assertion, which would previously lead to falsely passing assertions.
Previously false positives caused by the usage of one language chain as an assertion will now fail with message: 
>The chainer `be` is a language chainer provided to improve the readability of your assertions, not an actual assertion. Please provide a valid assertion.
>https://on.cypress.io/assertions
┆Issue is synchronized with this [Jira Bug](https://cypress-io.atlassian.net/browse/TR-171) by [Unito](https://www.unito.io/learn-more)
=> fix: Throw error when assertion contains only one language chainer

packages/launcher/__snapshots__/windows_spec.ts.js, packages/launcher/lib/windows/index.ts, packages/launcher/test/unit/windows_spec.ts
- Closes #8425 
- Fixed an issue where Cypress would not detect newer 64-bit installations of Chrome on Windows.
=> fix(launcher): detect new Chrome 64-bit path on Windows

packages/launcher/__snapshots__/windows_spec.ts.js, packages/launcher/lib/windows/index.ts, packages/launcher/test/unit/windows_spec.ts
- Closes #8432 
- Fixed an issue where Cypress would not detect per-user Firefox installations on Windows.
=> fix(launcher): detect Firefox installed in AppData on Windows

packages/driver/cypress/integration/commands/querying_spec.js, packages/driver/src/cy/commands/querying.js
- Closes #8478
- Fixed an issue where querying the shadow in a `cy.within()` callback would throw the error 'root.getRootNode is not a function'
=> fix: Fix querying shadow dom in cy.within

packages/driver/cypress/integration/commands/net_stubbing_spec.ts, packages/net-stubbing/lib/external-types.ts, packages/net-stubbing/lib/internal-types.ts, packages/proxy/lib/http/request-middleware.ts, packages/proxy/lib/types.ts
- Closes #7967 
Added a `followRedirect` option to request interception, to allow redirects to be followed before continuing to response interception.
- matches `followRedirect` option of `cy.request`
- may want to add a `redirects` array to `res` object
=> feat(net-stubbing): add `followRedirect` to request interception

packages/driver/cypress/integration/commands/net_stubbing_spec.ts, packages/net-stubbing/lib/external-types.ts, packages/net-stubbing/lib/internal-types.ts, packages/proxy/lib/http/request-middleware.ts, packages/proxy/lib/types.ts
- Cherry-pick of #8282 (was mistakenly merged into old network stubbing branch)
Added a `followRedirect` option to request interception, to allow redirects to be followed before continuing to response interception.
- matches `followRedirect` option of `cy.request`
- may want to add a `redirects` array to `res` object
=> feat(net-stubbing): add `followRedirect` to request interception (#8282)

packages/reporter/cypress/integration/tests_spec.ts, packages/reporter/src/commands/command.spec.tsx, packages/reporter/src/commands/command.tsx, packages/reporter/src/commands/commands.scss
- Closes #8012
- Fixed a performance issue which led to CPU bottlenecking during Cypress runs.
- `<Progress>` element added in #7646 has a performance issue, the CSS animation on `width` causes repetitive Layout updates which leads to a serious performance regression: 
* without Progress element:  
* with Progress element:  
* performance issues were noted in the original PR but it was merged anyways
- animating `transform` instead of `width` fixes it:
Commit SHA | Time to finish https://github.com/nphillipsworth/cypress-test-tiny/
--- | ---
public 4.8.0 build | 142066ms
3f3e860fc | 172671ms
f883590ef | 174939ms
f305f8b10 | 153007ms
dc075618b (from #7646) | 302152ms
dc075618b without Progress element | 157521ms
dc075618b using requestAnimationFrame | 182470ms
dc075618b with transform …
=> fix(perf): use JS to animate command progress bars

cli/types/cypress.d.ts, cli/types/tests/cypress-tests.ts
- Closes #7807
`Cypress.Commands.add` could only return `void` or `Chainable`. Now, `Promise` is added to the list.
- Why was this change necessary? TypeScript throws an error for valid code.
N/A
=> fix(typedefs): Cypress.Commands.add can return Promises.

packages/driver/cypress/fixtures/shadow-dom.html, packages/driver/cypress/integration/commands/querying_shadow_dom_spec.js, packages/driver/cypress/integration/commands/querying_spec.js, packages/driver/src/cy/commands/querying.js
- Closes #8494
- Fixed an issue where using `cy.contains()` within a shadow root would not yield the correct element
In addition to fixing the issue, this adds a couple more tests to ensure `cy.contains()` works correctly when the element being queried is in the shadow dom
=> fix: Fix issue with cy.contains when scoped inside shadow root

packages/net-stubbing/lib/external-types.ts
- Added missing type declarations for the `cy.route2` command.
=> fix(types): add tsdocs for cy.route2

cli/schema/cypress.schema.json, cli/types/cypress.d.ts, packages/driver/cypress.json, packages/driver/cypress/integration/commands/actions/click_spec.js, packages/driver/cypress/integration/cypress/shadow_dom_utils_spec.ts, packages/driver/cypress/integration/dom/elements_spec.ts, packages/driver/src/cy/commands/querying.js, packages/driver/src/cy/commands/traversals.js, packages/driver/src/cypress/shadow_dom_utils.ts, packages/driver/src/dom/elements.ts, packages/server/__snapshots__/7_record_spec.js, packages/server/lib/config_options.ts, packages/server/lib/errors.js, packages/server/lib/experiments.ts, packages/server/test/support/fixtures/projects/shadow-dom-global-inclusion/cypress.json, packages/server/test/unit/config_spec.js
- The `experimentalShadowDomSupport` flag is now deprecated and no longer necessary for testing the shadow DOM. Utilize the `includeShadowDom` option as needed to enable including shadow DOM elements in query results.
=> chore: Deprecate experimentalShadowDomSupport flag and remove its usage

packages/driver/cypress/integration/commands/net_stubbing_spec.ts, packages/driver/src/cy/net-stubbing/events/index.ts, packages/driver/src/cy/net-stubbing/static-response-utils.ts, packages/net-stubbing/lib/external-types.ts, packages/net-stubbing/lib/internal-types.ts, packages/net-stubbing/lib/server/intercept-response.ts, packages/net-stubbing/lib/server/util.ts
- Closes #7661
- Added the capability to specify `delayMs` and `throttleKbps` when stubbing static responses using `cy.route2`.
=> feat(net-stubbing): throttle/delay for StaticResponses

packages/server/lib/util/ts-node.js, packages/server/package.json, packages/server/test/e2e/1_typescript_spec_support_spec.ts, packages/server/test/support/fixtures/projects/ts-proj-with-paths/cypress.json, packages/server/test/support/fixtures/projects/ts-proj-with-paths/cypress/plugins/index.ts, packages/server/test/support/fixtures/projects/ts-proj-with-paths/cypress/support/index.ts, yarn.lock
- Closes #8555
- Fixed an issue where using TypeScript path aliases in the plugins file would error
Users can now use TypeScript path aliases or 3rd party code that relies on 3rd party path aliases in their plugins file without it erroring.
=> fix: Support path aliases in plugins file

packages/driver/cypress/fixtures/issue-7170.html, packages/driver/cypress/integration/issues/7170_spec.js, packages/driver/src/dom/selection.ts
- Closes #7170
When a number-type input field is manually focused, the number typed with `cy.type()` didn't append it but prepend it. This PR fixes this problem.
- Why was this change necessary? => Fix unexpected behavior.
- Any implementation details to explain? => When an input field is manually focused, `__Cypress_state__` is broken. So, we just return the length of the field as `pos`.
N/A
- [N/A] Have new configuration options been added to the …
=> fix: Append number to manually-focused number-type input.

packages/server/__snapshots__/6_visit_spec.js, packages/server/lib/request.js, packages/server/test/e2e/6_visit_spec.js, packages/server/test/support/fixtures/projects/e2e/cypress/integration/visit_spec.coffee
* Closes #8544
Fixed an issue where HTTP POST requests sent by `cy.visit` would fail if a HTTP redirect was received in the response.
* [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)?
* [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
* [na] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?
=> fix(server): correctly redirect cy.visit when using HTTP POST

packages/driver/cypress/integration/commands/net_stubbing_spec.ts, packages/driver/src/cy/net-stubbing/static-response-utils.ts
- Closes #8532
- Fixed an issue with `cy.route2` where stubbing a response with an empty array did not work as expected.
=> fix(route2): empty arrays are correctly JSONified in all circumstances

packages/driver/cypress/integration/commands/net_stubbing_spec.ts, packages/driver/src/cy/net-stubbing/events/response-received.ts, packages/net-stubbing/lib/server/intercept-error.ts, packages/net-stubbing/lib/server/intercept-request.ts, packages/net-stubbing/lib/server/intercept-response.ts, packages/net-stubbing/lib/server/types.ts
- Closes #8536
Fixed an issue where objects yielded by `cy.wait`ing on `cy.route2` aliases would not have the `response` property if the `response` was not intercepted.
=> fix(route2): always have .response present on cy.route2.wait

cli/types/cypress.d.ts, cli/types/tests/actions.ts, cli/types/tests/cypress-tests.ts
- Closes #5795
Replaces deprecated Mocha interfaces: `IRunnable` and `ITest`.
- Why was this change necessary? => Deprecated interfaces sometimes cause lint/ts compiler warning/errors.
N/A
=> fix: Replaced deprecated Mocha interfaces.

packages/driver/cypress/integration/commands/assertions_spec.js, packages/driver/src/cypress/chai_jquery.js
- Closes #5763
After Cypress 3.5.0, selector became `undefined` when no element is found. This error is fixed.
- Why was this change necessary? => Showing `undefined` is really unintuitive.
- Any implementation details to explain?
It happened because [`.selector` api is deprecated](https://api.jquery.com/selector/). That's why I cached the selector and used it instead.
**Before:**
**After:**
- [N/A] Have new configuration options been added to the …
=> fix: Reporter shows the selector when it cannot find elements.

packages/driver/cypress/integration/commands/task_spec.js, packages/driver/cypress/plugins/index.js, packages/server/lib/plugins/child/task.js, packages/server/lib/plugins/index.js
- Closes #5913
When we pass no argument to `cy.task`, it converted it to `null`, not `undefined`. This PR fixes this bug.
- Why was this change necessary? It's impossible to use default argument.
- Any implementation details to explain? IPC converts `undefined` to `null`. To prevent this, we now pass an object with a special property when args is `undefined`.
N/A
- [N/A] Have new configuration options been added to the …
=> fix: cy.task() can pass undefined as default argument.

cli/lib/cli.js, cli/test/lib/cypress_spec.js
- Closes #8632 
Fixes an issue preventing users from passing the config-file argument when starting cypress through the Node module API.
Passing the config-file argument when starting cypress through the Node module API now matches the behavior of starting cypress from the cli.
=> fix: corrected coercion of config-file argument

cli/lib/util.js, cli/test/lib/util_spec.js
- Closes #8488
Support to override env variables with empty value, such as "CYPRESS_INSTALL_BINARY=".
Before: Cannot override the env of CYPRESS_INSTALL_BINARY to a *unset* status.
After: Can override the env of CYPRESS_INSTALL_BINARY to a *unset* status.
=> fix(cli): support to unset an env variable with an empty value

packages/driver/cypress/integration/commands/net_stubbing_spec.ts, packages/driver/cypress/plugins/server.js, packages/net-stubbing/lib/server/index.ts, packages/net-stubbing/lib/server/is-host-interceptable.ts, packages/net-stubbing/test/unit/is-host-interceptable-spec.ts, packages/server/lib/server.js
- Closes #8487
Fixed an issue where routes defined with `cy.route2` would not match against HTTPS requests to a different origin.
- only affected HTTPS requests - all HTTP requests are proxied already
- makes an attempt to optimize which HTTPS requests are proxied. some will still be transparently proxied. only potentially-interceptable connections will be proxied through the Cy proxy layer, and thus through the net-stubbing code
- check `is-host-interceptable.ts` for implementation
Users can now use `cy.route2` to spy and stub on any URL, anywhere :smile:  …
=> fix(net-stubbing): route HTTPS traffic through net-stubbing interceptors

cli/types/cypress.d.ts, packages/desktop-gui/cypress/integration/project_nav_spec.js, packages/desktop-gui/src/app/nav.scss, packages/desktop-gui/src/project-nav/browsers.jsx, packages/driver/cypress/integration/util/firefox_forced_gc_spec.ts, packages/driver/src/util/firefox_forced_gc.ts, packages/launcher/__snapshots__/browsers_spec.ts.js, packages/launcher/__snapshots__/darwin_spec.ts.js, packages/launcher/__snapshots__/windows_spec.ts.js, packages/launcher/lib/browsers.ts, packages/launcher/lib/detect.ts, packages/launcher/test/unit/detect_spec.ts, packages/launcher/test/unit/linux_spec.ts, packages/server/__snapshots__/3_plugins_spec.js, packages/server/__snapshots__/7_record_spec.js, packages/server/__snapshots__/browsers_spec.js, packages/server/__snapshots__/chrome_spec.js, packages/server/__snapshots__/cri-client_spec.ts.js, packages/server/lib/errors.js
- Closes #8241
- Firefox support is now out of beta!
- Updated `firefoxGcInterval` workaround to only apply to versions of Firefox older than 80. A warning will be presented if an older version is used.
New warning:
(note, the BrowserIcon for Custom Firefox is wrong (?)... not related to these changes)
=> feat: take Firefox support out of beta

packages/driver/cypress/integration/cypress/location_spec.js, packages/driver/src/cypress/location.js
- Closes #5090
Thanks, @ryan-snyder!
Allows cy.visit() to visit the URLs with `..` like `https://google.com?q=..` 
- Why was this change necessary? => Perfectly fine URL was not allowed.
- Any implementation details to explain? => When there are consecutive dots, it is not a valid URL. But `$Location.isUrlLike()` treats it's fine. Fixed that issue.
N/A
- [N/A] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/ …
=> fix: cy.visit() allows the URLs with double dots.

packages/proxy/lib/http/response-middleware.ts, packages/server/test/integration/http_requests_spec.js
Since Cypress omits the blocking CSP header, it should also omit the
report-only CSP header. This fixes a lot of `unsafe-inline` script-src
warnings that I have seen when running cypress.
A test has been added to checked that this header is removed.
=> fix(proxy): omit CSP report only header

packages/driver/cypress/integration/cypress/location_spec.js, packages/driver/src/cypress/location.js
- Closes #2101
Thanks, @ryan-snyder!
Note: I don't usually solve first-timers-only issues. But it's related with #5175. So, I fixed it. 
/ is not added when `baseUrl` has param(s)
- Why was this change necessary? Some people defines `baseUrl` with params. But Cypress adds `/` by default. 
N/A
- [N/A] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/s …
=> fix: Don't add / when baseUrl has param(s).

packages/driver/cypress/integration/util/firefox_forced_gc_spec.ts, packages/driver/src/cypress.js, packages/driver/src/util/firefox_forced_gc.ts
- Closes 
Fixed an issue where the forced garbage collection timer would still display in Firefox, even when using a version of Firefox newer than 80.
- follow-up on #8586 
- needed the intervalGetter to also return undefined
=> fix(driver): hide forced GC warning if using FF >= 80

packages/driver/cypress/integration/commands/net_stubbing_spec.ts, packages/driver/src/cy/net-stubbing/events/request-received.ts, packages/driver/src/cy/net-stubbing/events/response-received.ts
- Closes 
- Fixed a bug in `cy.route2` where route handler timeouts could leak into other tests and cause random failures.
- this was a major source of flake in the net-stubbing tests - timeouts for the req/res callbacks could leak between tests, and not all of the tests were designed to resolve within `defaultCommandTimeout`
- this is why there were random clusters of tests that would be flakier than others!
- additionally addressed a few other flaky tests
- added retries to one flaky test which i am unable to reproduce locally despite running many many times …
=> fix: prevent cy.route2 callback timeouts from leaking into next test

packages/driver/cypress/integration/commands/connectors_spec.js, packages/driver/src/cy/commands/connectors.js, packages/driver/src/cypress/cy.js
* Closes #4921
When dual commands like `cy.contains()` is used `each()`, it didn't work properly. This PR solves this problem.
Unexpected behavior of `each()` and `contains()`.
Nothing
This problem happened because `each()` didn't care about whether the command is called first or not.
Because of that, the code A was interpreted like Code B.
```js
// code A
cy.contains('New York')
cy.get('span').each(() => {})
cy.contains('New York')
```
```js
// code B
cy.contains('New York')
cy.get('span').each(() => {}).contains('New York')
```
N/A
* [N/A] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
* [N/A] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/ty …
=> fix: each followed by contains correctly changes the scope.

packages/driver/cypress/integration/commands/querying_spec.js, packages/driver/src/cy/commands/querying.js
* Closes #2106
* Closes #4672
* Closes #4757
* Closes #5183
These all 4 issues cover the same problem and this PR solves that.
When a command is chained after `cy.within()` and `cy.get()` is called inside it, the scope was permanently changed. This PR solves this problem. 
The command didn't work as the documentation says.
Some codes that use this bug will be broken. Example below:
```html
<article class='post'>
<h1>My Blog Post</h1>
</article>
```
```js
cy.get(`article`).within(() => cy.get(`h1`)).should(`have.text`, `My Blog Post`);
```
This should fail because the `article` has text `\n My Blog Post \n`.
When running tests, Cypress queues commands and runs them later. 
```js
cy.get('article').within(() => {
cy.get('h1').should('contain.text', 'Blog')
})
.should('have.class', 'post') …
```
=> fix: within followed by should correctly changes the scope.

packages/launcher/lib/detect.ts, packages/launcher/test/unit/detect_spec.ts
* Closes 
N/A
* Why was this change necessary?
It's considered bad practice to modify the parameters of a function in that call. In order to purify the function call, we should create a new object instead.
* Any implementation details to explain?
Chose to create a new object instead of just returning the version and setting it due to some typing difficulties with FoundBrowser
N/A
=> chore: Update setMajorVersion to not modify browser on call

packages/server/test/e2e/6_video_compression_spec.js, packages/server/test/e2e/7_record_spec.js
This was breaking the build. Mocha doesn't have support for Cypress's test retries syntax. doh.
=> chore: fix mocha retries syntax in e2e test

packages/driver/cypress/integration/commands/net_stubbing_spec.ts, packages/driver/cypress/plugins/server.js, packages/proxy/lib/http/response-middleware.ts
- Closes #8497 
- Fixed an issue where, with `experimentalNetworkStubbing` enabled, `cy.visit`s to URLs that redirect and set `Transfer-Encoding: chunked` would fail in Cypress with a "Parse Error".
- Cypress was setting the erroneous transfer-encoding header
- Still doesn't fix the case where the user has actually set both Content-Length and Transfer-Encoding: chunked - we cannot fix this case without modifying the HTTP parser, see https://github.com/nodejs/llhttp/issues/69
- [na] Have new configuration options been …
=> fix: fix loading redirects with TE: chunked

packages/driver/cypress/integration/commands/net_stubbing_spec.ts, packages/driver/src/cy/net-stubbing/add-command.ts
- Closes #8921 
- Fixed an issue where `headers` field names passed to `cy.route2` would not case-insensitively match against the field names of incoming HTTP requests.
- see https://github.com/cypress-io/cypress/issues/8921#issuecomment-714525877
- also added test to ensure no duplicate field names are set
=> fix(route2): case-insensitively match headers

packages/driver/src/cy/net-stubbing/events/response-received.ts
- Closes #8858 
Fix the flaky "Cannot set property response of undefined".
- Why was this change necessary? => This causes flaky failures. 
- Any implementation details to explain? => This failure happened because `request` is sometimes `undefined`. But `sendContinueFrame` assumes that `request` is always non-`undefined`. Fixed this problem. 
N/A
- [N/A] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develo …
=> fix: Cannot set property response of undefined

npm/webpack-preprocessor/package.json
The binary build is broken in develop/master because the webpack-preprocessor dist folder isn't found... likely because it isn't being built.
=> chore: add prod build task for webpack-preprocessor to fix the binary build

.gitignore, npm/react/package.json, npm/vue/package.json, npm/webpack-preprocessor/package.json, scripts/npm-release.js
There was a bug in the release process where:
1. a change was made where the `build-prod` task was run instead of the `build` task, so nothing was building
2. also we weren't waiting for the builds to pass before releasing
- Closes #9037
=> fix: adding build-prod tasks to all of the npm dependencies that need artifacts

packages/driver/cypress/integration/commands/navigation_spec.js, packages/driver/cypress/plugins/server.js, packages/server/lib/server.js, packages/server/test/integration/server_spec.js
- close #8506 
- Using `cy.visit()` on sites with `content-type` of `text-html` followed by parameters will no longer throw an error about visiting a site with an invalid content-type.
- Is this enough tests around this?
- Is this a stringent enough content-type test?
=> fix: Expand logic for checking contentType when determining if content is HTML

packages/driver/cypress/integration/commands/net_stubbing_spec.ts, packages/net-stubbing/lib/server/intercept-request.ts
Fixed an issue with not being able to await a request body when providing static response stub and using the `experimentalNetworkStubbing`.
* Why was this change necessary?
It's a bug fix.
* What is affected by this change?
experimentalNetworkStubbing
N/A
=> fix(route2): fixed the issue with not being able to await a request body when providing static response stub

packages/desktop-gui/cypress/integration/release_notes_spec.js, packages/desktop-gui/src/update/updates.js
N/A - only an issue in `develop` 
I made a false assumption that `on.cypress.io` would return 404 for a non-supported path (e.g. `/release-notes/1.2.3`), which will happen if the in-app release notes feature is released before the new version of `on.cypress.io` is deployed (seems likely to happen). In reality, it tries to redirect to the docs and returns an empty object. In that case, the desktop gui would think there were release notes when there weren't and display a release notes modal with `undefined` instead of going straight to the update instructions.
Before:
After:
- N/A …
=> fix: Handle non-error empty objects from release notes service

.releaserc.js
Make a semantic release channel to publish prerelease version of webpack-preprocessor that supports webpack v5 #8929
=> chore: Create webpack5 release channel for webpack prepocessor

CONTRIBUTING.md
The Committing > Testing section was removed in https://github.com/cypress-io/cypress/commit/5842d1dffe32831dcfe2349b928f4386f47db980
Potential Contributors are now not confused anymore when nothing happens after clicking on "Testing" ;)
=> docs(contributing.md): remove "Testing" toc entry

packages/driver/cypress/integration/commands/actions/type_spec.js, packages/driver/src/cy/actionability.js, packages/driver/src/dom/elements.ts, packages/driver/src/dom/selection.ts
* Closes #2717 
* Closes #7721 
* It's the rework of #8529.
When `cy.type()` and `cy.click()` were used against an element inside `contenteditable`, it only worked with the root `contenteditable` element. With this PR, this behavior is fixed. Users can freely work with elements inside contenteditable. 
* Why was this change necessary? => To change things inside `contenteditable`, it is sometimes necessary to work with elements inside it. 
* What is affected by this change? => This is a breaking change. The behaviors of `type()` and `click()` changed slightly.
* Any implementation details to explain? => The change was a bit bigger than expected. I had to change the behavior of `runAllCheck` in `actionability.js` to ignore elements inside `contenteditable`. 
```html
<div id="a" …
```
=> feat: Allow type() and click() to select an element inside contenteditable.

packages/server/lib/config_options.ts, packages/server/lib/errors.js, packages/server/test/e2e/0_fetch_polyfill_spec.js, packages/server/test/support/helpers/e2e.ts, packages/server/test/unit/config_spec.js
* Closes 
* Deprecated the `experimentalFetchPolyfill` experimental option. Consider using `cy.http()` to stub `fetch` requests instead.
* [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
* [na] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?
=> feat: deprecate experimentalFetchPolyfill

cli/types/cypress.d.ts, cli/types/tests/kitchen-sink.ts
- Closes #9120 
Added the type of `redirects` and changed `redirectedToUrl` optional. 
- Why was this change necessary? => `redirects` was missing and `redirectedToUrl` was wrong.
- Any implementation details to explain?
The following code told me that the type of `redirects` is `string[]`.
https://github.com/cypress-io/cypress/blob/91b900958b4b97ff4cb67450c768fe8408acc370/packages/server/lib/request.js#L727
I checked the code below and learned that `redirectedToUrl` isn't removed. It was optional. 
https://github.com/cypress-io/cypress/blob/91b900958b4b97ff4cb67450c768fe8408acc370/packages/server/lib/request.js#L748-L761
N/A
=> chore: Fix Response type.

cli/types/cypress.d.ts, cli/types/tests/cypress-tests.ts, packages/desktop-gui/cypress/integration/release_notes_spec.js, packages/desktop-gui/cypress/support/index.js, packages/driver/cypress/integration/commands/net_stubbing_spec.ts, packages/driver/cypress/integration/commands/xhr_spec.js, packages/driver/cypress/integration/cy/snapshot_spec.js, packages/driver/src/cy/commands/waiting.js, packages/driver/src/cy/net-stubbing/add-command.ts, packages/driver/src/cy/net-stubbing/events/index.ts, packages/driver/src/cy/net-stubbing/events/request-received.ts, packages/driver/src/cy/net-stubbing/wait-for-route.ts, packages/driver/src/cypress/error_messages.js, packages/net-stubbing/lib/external-types.ts, packages/server/lib/errors.js
- Renamed the `cy.route2` command to `cy.intercept`.
- also updated types, tsdocs for "Interceptions"
=>  feat(net-stubbing): rename cy.http to cy.intercept 

circle.yml, npm/webpack-preprocessor/index.ts, npm/webpack-preprocessor/lib/typescript-overrides.ts, npm/webpack-preprocessor/test/unit/index.spec.js, npm/webpack-preprocessor/test/unit/typescript-overrides.spec.ts
- Closes #8477
- Addresses [TR-450](https://cypress-io.atlassian.net/browse/TR-450)
- Addresses [TR-398](https://cypress-io.atlassian.net/browse/TR-398)
- Webpack preprocessor now allows passing the path to TypeScript via the `typescript` option.
When we run the default preprocessor and require typescript, it ends up requiring cypress's own version of typescript and not the user's. This prevents us from monkey-patching the correct version of typescript for source maps compatibility. 
We already search out the path to the user's typescript and pass it to the preprocessor. This utilizes that path to require typescript.
- N/A Has a PR for user-facing changes been opened in …
=> feat(webpack-preprocessor): Allow specifying typescript path

packages/server/lib/browsers/chrome.ts, packages/server/lib/browsers/cri-client.ts, packages/server/lib/browsers/electron.js, packages/server/test/e2e/6_video_compression_spec.js, packages/server/test/unit/browsers/chrome_spec.js
* Closes #9265
fix recorded videos only show a static frames.
explained in https://github.com/cypress-io/cypress/issues/9265#issuecomment-732691175
chromium throttles frame rate with `Page.screencastFrameAck`
=> fix(server): CDP needs screencasts ack before sending more frames

packages/driver/cypress/integration/commands/net_stubbing_spec.ts, packages/driver/src/cy/net-stubbing/add-command.ts, packages/net-stubbing/lib/server/route-matching.ts
* Closes #9313 
Lower-cased HTTP methods can be used with cy.intercept. 
* Why was this change necessary? => `cy.intercept` only allowed upper-cased HTTP methods. 
* What is affected by this change? => N/A
* Any implementation details to explain? => N/A
N/A
=> fix: lower-cased HTTP methods can be used with cy.intercept.

packages/driver/cypress/integration/cypress/location_spec.js, packages/driver/src/cypress/location.js
* Closes #9360
Don't remove "/" at the end when user passed it.
* Why was this change necessary? => "/" at the end was removed even when user passed it.
* What is affected by this change? => N/A
* Any implementation details to explain? => N/A
N/A
=> fix: Don't remove the "/" at the end when user passed it.

packages/driver/cypress/fixtures/issue-8998.html, packages/driver/cypress/integration/issues/8998_spec.js, packages/driver/src/dom/visibility.js
* Closes #8998
* Closes #9031 
Fix Cypress.dom.isVisible() regression caused by "position: fixed"
* Why was this change necessary? => When Cypress.dom.isVisible() is used with an ancestor element with "position: fixed", it causes a regression.
* What is affected by this change? => N/A
* Any implementation details to explain? => I only check `pointer-events: none` for the element to be tested and its parent element because of the performance. Looping to the body can be bad for performance. 
Regression resolved.
=> fix: Fix Cypress.dom.isVisible() regression caused by "position: fixed"

circle.yml, packages/net-stubbing/lib/server/intercept-request.ts, packages/net-stubbing/lib/server/util.ts, packages/proxy/lib/http/index.ts, packages/proxy/package.json, packages/proxy/test/integration/net-stubbing.spec.ts, yarn.lock
- Closes #9264 
- Responses stubbed from `cy.intercept` will now automatically set `Access-Control-Allow-Origin` and `Access-Control-Allow-Credentials` to permissive values unless explicitly overridden.
=> feat: automatically set CORS headers on stubbed responses

packages/driver/cypress/integration/commands/net_stubbing_spec.ts, packages/driver/cypress/plugins/server.js, packages/net-stubbing/lib/server/intercept-request.ts, packages/net-stubbing/lib/server/intercept-response.ts, packages/net-stubbing/package.json, packages/network/lib/http-utils.ts, packages/network/lib/index.ts, packages/proxy/lib/http/response-middleware.ts
- Closes #8999
- Closes #8934 
- Fixed an issue where HTTP responses that cannot have a body (like HTTP 304 and HTTP 204) could not be awaited using `cy.intercept`.
- Fixed an issue where HTTP redirects could not be awaited using `cy.intercept` unless dynamically intercepted.
- tricky because internally, Node.js treats 304s differently from 204s
- also tricky because the fix for #4358 had to be maintained or else the 5 second timeout continues …
=> fix(net-stubbing): fix waiting on responses with no-body status codes

packages/driver/cypress/integration/commands/net_stubbing_spec.ts, packages/driver/src/cy/net-stubbing/events/request-received.ts
- Closes #9170 
- Fixed a race condition that could cause an unexpected "Cannot read property "fireChangeEvent" of undefined" error when using `cy.intercept`.
- if an intercepted request is received at the end of a test, it is possible for a race condition to occur where the server sends an `http:request:received` event that has no handler in the driver
- this was gracefully handled, but there were no tests around it, leading to this regression
- fixed, and also added tests for unexpected `http:response:received` and `http:request:complete`
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/c …
=> fix(net-stubbing): do not fireChangeEvent for non-existing routes

packages/driver/src/cypress/runner.js, packages/runner/cypress/fixtures/issues/issue-9162.js, packages/runner/cypress/integration/issues/issue-9162.js
- Closes #9162
Tests don't hang when there's an error in `before()` block.
- Why was this change necessary? => Test runner stopped when there's an error in `before()` block.
- Any implementation details to explain? => Revived the removed `getTest()` function and checks if the test is `pending`(skipped).
N/A
=> fix: tests don't hang when there's an error in before() block.

packages/server-ct/.eslintrc.json, packages/server-ct/example/src/components/HelloWorld.spec.js, packages/server-ct/example/src/components/Prettiest.spec.js, packages/server-ct/example/src/components/test/Pretty.spec.js
This targets spike/evergreen-bem: https://github.com/cypress-io/cypress/pull/9524.
I changed the component-testing example to use the Cypress testing API instead of using Vue Test Utils as per @JessicaSachs's recommendation as a good way to get my hands dirty.
Also the type definitions for `mount` in `@cypress/vue` appear to be incomplete, this can probably be fixed either here or in Vue Test Utils, but this doesn't seem like very important thing to do right now, so I left it as-is.
=> test(component-testing): use Cypress in Vue tests

cli/__snapshots__/cli_spec.js, cli/lib/cli.js, cli/lib/exec/open.js, cli/lib/util.js
In the main `bem` branch, only the `server` package understands the flag component-testing.
For end users to access it we add a flag to the cli, that will pass it down to the server package in production.
Use with `cypress open --component-testing` to open the window.
There is a shortcut `cypress open -ct`
=> feat(ct): Add the ct flag to the cypress cli and wire it to component testing

packages/driver/cypress/integration/commands/net_stubbing_spec.ts, packages/driver/src/cy/commands/querying.js, packages/driver/src/cy/commands/waiting.js, packages/driver/src/cy/net-stubbing/add-command.ts, packages/driver/src/cy/net-stubbing/aliasing.ts, packages/driver/src/cy/net-stubbing/events/request-received.ts, packages/driver/src/cy/net-stubbing/wait-for-route.ts, packages/net-stubbing/lib/external-types.ts
- Closes #9306 
- Fixed an issue where using `cy.get` for an alias of `cy.intercept` would always yield null.
- added explicit support for `cy.get('@alias')`, `@alias.all`, and `@alias.[index]`
=> fix(net-stubbing): fix cy.get(alias) with cy.intercept()

packages/driver/cypress/integration/commands/net_stubbing_spec.ts, packages/driver/src/cy/net-stubbing/events/request-complete.ts, packages/driver/src/cy/net-stubbing/wait-for-route.ts, packages/net-stubbing/lib/external-types.ts, packages/net-stubbing/lib/server/intercept-request.ts, packages/net-stubbing/lib/server/intercept-response.ts, packages/net-stubbing/lib/server/types.ts, packages/net-stubbing/lib/server/util.ts
- Closes #9062
- Response errors from `forceNetworkError` can now be awaited using `cy.intercept` and `cy.wait`.
- will yield `interception.error` instead of `interception.response` when `cy.wait`ed
=> feat(net-stubbing): allow waiting on network errors/forceNetworkError

packages/desktop-gui/cypress/fixtures/runs.json, packages/driver/cypress/integration/commands/actions/trigger_spec.js, packages/driver/cypress/integration/commands/assertions_spec.js, packages/driver/cypress/integration/commands/connectors_spec.js, packages/driver/cypress/integration/commands/files_spec.js, packages/driver/cypress/integration/commands/querying_shadow_dom_spec.js, packages/driver/src/cy/retries.js, packages/driver/src/cypress/error_messages.js, packages/runner/cypress/integration/reporter.errors.spec.js, packages/server/__snapshots__/1_caught_uncaught_hook_errors_spec.js, packages/server/__snapshots__/3_config_spec.js, packages/server/__snapshots__/3_issue_173_spec.ts.js, packages/server/__snapshots__/5_spec_isolation_spec.js, packages/server/__snapshots__/5_stdout_spec.js, packages/server/__snapshots__/6_web_security_spec.js, packages/server/test/support/helpers/e2e.ts
- Closes #5781
Retry timeout error message now contains timeout period.
- Why was this change necessary? => It wasn't clear how long the timeout was.
- Any implementation details to explain? => It simply shows the difference. 
**Before:**
**After:**
I intentionally stopped the CI because there are some problems to solve. 
* Is error message OK? Maybe there might be better copy.
* Should we should the timeout period number every time? If it's the default, should we hide it?
* Maybe it's not an important information and just closing the issue might be the solution. 
Without these questions cleared, editing error messages in the tests is meaningless.
=> feat: Add timeout period to retry error message

packages/driver/cypress/integration/commands/waiting_spec.js, packages/driver/cypress/integration/commands/xhr_spec.js, packages/driver/cypress/integration/issues/3890_spec.js, packages/driver/src/cy/commands/waiting.js
- Closes #3890
You can overwrite `cy.route` command and still wait on the alias
```js
Cypress.Commands.overwrite('route', (route, ...args) => {
return cy.log(`cy.route ${args.join(' ')}`)
.then(() => {
return route(...args)
})
})
cy.server()
.route(/foo/, 'my value').as('getFoo')
// make request
cy.wait('@getFoo').its('responseBody').should('equal', 'my value')
```
As described in https://glebbahmutov.com/blog/cypress-intercept-problems/#the-intercept-was-registered-too-late sometimes we might need to log when the `cy.route` is defined. For that we need to overwrite the `cy.route` command. Now we can wait for the `cy.route` interception.
=> fix: waiting on an alias when the cy.route command has been overwritten

npm/vue/src/index.ts
Hotfix for types
Previous error:
```
➜  vue git:(spike/evergreen-bem) ✗ yarn build
yarn run v1.22.10
$ tsc
src/index.ts:87:27 - error TS2349: This expression is not callable.
Type '{}' has no call signatures.
87     computed[key] = () => fn(store)
~~
Found 1 error.
```
=> fix: evergreen branch has broken types and isn't compiling

npm/react/README.md, npm/vue/README.md
This PR fixes a few broken links in the component testing docs. 
- Closes N/A
=> fix(Component Testing): Broken links in docs

npm/react/package.json
Allows to use `import { mount } from '@cypress/react';` in TypeScript projects. 
Currently `types` filed in the `package.json` targets missing `lib` directory, which makes imports from `@cypress/react` invalid.
=> fix(react): link types from the correct directory

packages/reporter/cypress/integration/commands_spec.ts, packages/reporter/cypress/integration/runnables_spec.ts, packages/reporter/cypress/support/index.ts, packages/runner/cypress/integration/retries.ui.spec.js
Add extra assertion to ensure page it loaded before taking Percy snapshot.
Percy flake: https://percy.io/cypress-io/cypress/builds-next/8146025/changed/463611682
=> test: fix percy flake for 'loading tests' display

packages/driver/cypress/integration/commands/net_stubbing_spec.ts, packages/driver/src/cy/net-stubbing/add-command.ts, packages/net-stubbing/lib/external-types.ts, packages/net-stubbing/lib/server/driver-events.ts, packages/net-stubbing/lib/server/route-matching.ts, packages/net-stubbing/test/unit/route-matching-spec.ts
- Closes #9379 
- Closes #14256
- adds a `matchUrlAgainstPath` property to RouteMatcher
- allows differentiating `cy.intercept(url)` from `cy.intercept({ url })` or `cy.intercept({ path })`
- also follows old `cy.route` behavior by applying a `/` prefix to un-prefixed `url` values that are being matched against a path - old behavior: https://github.com/cypress-io/cypress/blob/ad194de98ffbbcdf687aa7c6c64b1cc1f6690a94/packages/driver/src/cypress/server.js#L296-L301
now works as described in https://github.com/cypress-io/cypress/issues/9379#issuecomment-742004697
=> fix(net-stubbing): match cy.intercept(url) globs against url+path

npm/vue/cypress/component/advanced/i18n/spec.js, npm/vue/cypress/component/router-example/PizzaShop/router.js, npm/webpack-dev-server/src/startServer.ts
Was not using the correct webpack config, I stole the fix from here:
https://github.com/cypress-io/cypress/pull/14287/files#diff-09d40ce97f8a517d6564d565aa9cf53bcaefaf37c3e5db9c5502412bacbbc5e9
The i18n spec still fails (among others) due to missing functionality like `cy.stub`, but at least some of the basic Vue specs now pass (previously the bundle was completely broken).
Test:
1. build latest webpack-dev-server with `yarn build` in `npm/webpack-dev-server`.
2. `cd packages/server-ct`
3. `NODE_OPTIONS=--max-http-header-size=1048576 node ../../scripts/start.js --component-testing --project ../../npm/vue`
4. Click first spec - it should work fine.
=> fix: fix vue tests by using correct webpack config

npm/webpack-dev-server/src/aut-runner.ts, npm/webpack-dev-server/src/loader.ts, packages/driver/src/cypress.js, packages/runner-ct/src/main.jsx, packages/server-ct/crossword-example/cypress/component/RenderFn.spec.js, packages/server-ct/crossword-example/src/components/RenderFn.js
Testing:
1. make sure you build the latest webpack-dev-server by going to `npm/webpack-dev-server` and running `yarn build`.
2. Go to `packages/server-ct`
3. run `yarn cypress:open`
Currently `.vue` files do not trigger HMR for some reason - I need to look into this. But you can edit `RenderFn.js` and `RenderFn.spec.js` and watch the test re-run. Note is is entirely blowing away the AUT iframe by emitting a `restart` event, ensuring no state is preserved between tests.
=> fix: blow away AUT iframe when HMR triggers

packages/driver/cypress/integration/commands/querying_spec.js, packages/driver/src/dom/elements.ts
- Closes #8626
cy.contains() won't throw an error when single quote is used inside its argument regex.
- Why was this change necessary? => Let Cypress not throw an error when a regex is used with single quote in cy.contains.
- Any implementation details to explain? => Sizzle cannot parse it. So, I used double quotes when single quotes are used inside cy.contains regex.
N/A
=> fix: cy.contains() works with regexes that use single quotes.

packages/reporter/src/header/header.tsx, packages/reporter/src/main.tsx, packages/runner-ct/src/app/BottomPane.jsx, packages/runner-ct/src/app/ReporterHeader.tsx, packages/runner-ct/src/app/app.scss, packages/runner-ct/src/app/app.tsx, packages/runner-ct/src/header/header.jsx, packages/runner-ct/src/lib/state.ts, packages/runner-ct/src/lib/useWindowSize.ts, packages/runner-ct/src/specs/specs-list.scss, packages/runner-ct/src/specs/specs-list.tsx
This PR implements the layout design for runner-ct. 
How it looks now:
List of changes:
- Move command log to the vertical panel
- Read default size of iframe panel from `config.viewportHeight`
- Fix iframe focus interception when resizing
- Remove back to tests button from command log
- Change design for specs list and search field
I would love to write some tests and add percy snapshots, but e2e tests PR [is blocked](https://github.com/cypress-io/cypress/pull/14266)
=> feat(component-testing): MVP layout for component-testing runner

packages/driver/cypress/integration/dom/jquery_spec.ts, packages/driver/src/dom/jquery.js
- Closes #14278
`isJquery` returns only boolean results.
- Why was this change necessary? => `isJquery` sometimes returned `undefined`.
- Any implementation details to explain? => Simply added `!!`.
Users will not get `undefined` results.
=> fix: Cypress.dom.isJquery() returns only boolean results

packages/net-stubbing/lib/server/intercept-request.ts, packages/proxy/test/integration/net-stubbing.spec.ts
- Closes #9359 
We fixed an issue with `cy.intercept()` where multipart/form-data was wrongly encoded by the internal proxy, thus resulting in differences between the `content-length` header and the actual byte length of the request body buffer, which led to `Unexpected end of multipart data` errors on the backend service where the request was pointing to. Fixes #9359. 
This change is necessary because otherwise it is not possible to use `cy.intercept()` on multipart/form-data file upload requests. 
For a more technical answer please read my [comment](https://github.com/cypress-io/cypress/issues/9359#issuecomment-747354545) on the issue.
The `InterceptRequest` middleware and internal proxy are affected by these changes.
The usage of cypress for the user has not changed.
=> fix: (cy.intercept()) intercept-request body buffer encoding problem for multipart/form-data

npm/webpack-dev-server/src/startServer.ts
makes test re-run after every save of the spec file or any of the dependencies
closes CT-182 
1. `yarn install` on root
1. `yarn install` on `/packages/server-ct/crossword-examples`
1. move to `/packages/server-ct`
1. start `yarn cypress:open`
1. open Cell.spec.js in cypress
1. open Cell.vue in code and change something in the code of the component
1. save 
It should re-run the tests in cypress
[EDIT] This PR is a rebase of #14334 onto the branch with all tests passing.
=> fix(component-testing): hot replace of dependencies of specs in component testing mode

cli/package.json, packages/driver/cypress/integration/commands/assertions_spec.js, packages/driver/package.json, packages/proxy/package.json, packages/server/package.json, yarn.lock
- Closes #9644 
Added missing calledOnceWith & calledOnceWithExactly sinon matchers.
- Why was this change necessary? => `calledOnceWith` and `calledOnceWithExactly` exist in sinon-chai and Cypress types, but they're not supported.
- Any implementation details to explain? => The problem was fixed at cypress-io/sinon-chai#46. This PR updates the dependency and added some tests for the missing matchers.
```js
const foo = cy.spy().as("foo")
setTimeout(() => {
foo({ bar: "test" })
}, 500)
cy.get("@foo").should(
"be.calledOnceWith",
Cypress.sinon.match({
bar: "test",
})
);
```
The code above now works.
=> fix: Added missing calledOnceWith & calledOnceWithExactly sinon matchers.

packages/server/lib/browsers/firefox.ts, packages/server/lib/socket-base.ts, packages/socket/lib/socket.ts, packages/ts/tsconfig.json
=> types: fix types

packages/driver/cypress/integration/commands/assertions_spec.js, packages/driver/src/cypress/chai_jquery.js
- Closes #14359
`cy.wrap(undefined).should('have.value', 'somevalue')` didn't show correct error message caused by #7621.
- Why was this change necessary? => Because it didn't show the correct message.
- Any implementation details to explain? => I didn't handle the case when `$el[0]` is `undefined`. 
`cy.wrap(undefined).should('have.value', 'somevalue')` shows the error like before.
=> fix: should(`have.value`) regression

packages/server/test/support/fixtures/projects/e2e/cypress/integration/only_multiple_spec.js, packages/server/test/support/fixtures/projects/e2e/cypress/integration/only_spec.js
N/A - internal only
The `.only` rule change in https://github.com/cypress-io/cypress/pull/14422 followed by the decaffeination in https://github.com/cypress-io/cypress/pull/14399 caused a couple lint errors only caught in `develop`. 
N/A
=> chore: Fix lint error due to .only rule change

packages/server/lib/util/args.js, packages/server/lib/util/coerce.js, packages/server/test/unit/coerce_spec.js
- Closes #8818
After 5.0.0, JSON-string-typed args were split on every comma. This returns useless array like `['{a:b', 'c:d}', '{e:f', 'g:h}']`. This PR solves this issue. 
- Why was this change necessary? => To return useful value from args. 
N/A
=> fix: Parse JSON string arg properly.

packages/server-ct/src/project-ct.ts, packages/server-ct/test/unit/project-ct.spec.ts
Use 500/500 by default for the viewport in component testing.
This is a little dirty. Ideally we will have a separate set of defaults for component testing, extends from a set of base defaults. I tried to do this but it's quite a big change to the existing server code, so this will do for now. The nice thing about this way is it only touches the CT code.
=> fix: default component testing viewport

packages/runner-ct/src/app/app.tsx, packages/runner-ct/src/specs/spec-file.tsx
When we open compont testing we get the following warnings in the console:
```
@ The prop `runMode` is marked as required in `App`, but its value is `undefined`.
in App (created by Container)
in Container
@ Warning: Failed prop type: You provided a `checked` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultChecked`. Otherwise, set either `onChange` or `readOnly`.
in input (created by SpecFile)
in li (created by SpecFile)
in SpecFile (created by SpecItem)
in SpecItem (created by SpecsList)
in ul (created by SpecsList)
in div (created by SpecsList)
in div (created by SpecsList)
in SpecsList (created by App)
in div (created by Pane)
in Pane (created by SplitPane)
in div (created by SplitPane)
in SplitPane …
```
=> fix: remove two annoying react warnings

packages/server-ct/index.ts
In component-testing when quitting the chrome instance, the process needs to exit.
- Start component testing
- Type Ctrl-Q to quit chrome
The process should exit normally
=> fix: when quitting chrome exit the process

npm/webpack-dev-server/package.json, npm/webpack-dev-server/src/loader.ts, npm/webpack-dev-server/src/makeWebpackConfig.ts, npm/webpack-dev-server/src/plugin.ts, npm/webpack-dev-server/src/startServer.ts, packages/driver/cypress/integration/cypress/script_utils_spec.js, packages/driver/src/cypress/script_utils.js, yarn.lock
Made sure that support files are loaded in component testing mode.
Since we now accept to delegate the loading of the spec to a 3rd party we need to add the support script loading to this list of loads.
Run the `server-ct/crossword` example and look at the `App.spec.js`. 
It uses a custom command "fillCrossword" that now works.
Closes CT-181
=> fix(component-testing): bring back support for support files

packages/launcher/lib/browsers.ts, packages/server/__snapshots__/5_cdp_spec.ts.js, packages/server/lib/browsers/chrome.ts, packages/server/lib/browsers/cri-client.ts, packages/server/lib/errors.js, packages/server/package.json, packages/server/test/e2e/5_cdp_spec.ts, packages/server/test/support/fixtures/projects/remote-debugging-port-removed/cypress/plugins.js, packages/server/test/unit/browsers/cri-client_spec.ts, yarn.lock
- TR-594
- Closes #6540
- Closes #7450
- Closes #8674
- Closes #8986
- Updated the CDP connection to attempt to use the stdio transport first with Chrome 72 and above, before falling back to using TCP. This should remediate issues causing sporadic 'Cypress failed to make a connection to the Chrome DevTools Protocol after retrying' errors.
- forked chrome-remote-interface to enable sessionId and stdio, see: https://github.com/cypress-io/chrome-remote-interface
- upstream PRs: cyrus-and/chrome-remote-interface#440 cyrus-and/chrome-remote-interface#441
- using `CYPRESS_REMOTE_DEBUGGING_PORT` will force Cypress to use CDP in TCP mode
- warns and falls back to TCP if stdio cannot find a target after 60 seconds (default, can be configured with `CYPRESS_CDP_TARGET_TIMEOUT`)
- i expect that some …
=> fix: use stdio for CDP instead of TCP

packages/runner-ct/src/app/app.tsx, packages/runner-ct/src/iframe/iframes.jsx, packages/runner-ct/src/iframe/iframes.scss, packages/runner-ct/src/lib/state.ts
Update the coordinates in the AUT viewport when resizing.
Video: http://g.recordit.co/3lsJu7wb6i.gif
NOTE: This is only set up for width right now. We could do something similar for height but it feels a little weird - a static height of 500 (or whatever) feels "right", somehow. It's a little more messy to deal with height, too - for width we can use the callback on `<SplitPane>`, but this won't work for height. We might need something like MutationObserver, if we choose to go down that route.
closes CT-192
=> fix(component-testing): Update AUT coordinates when resizing

cli/types/cypress.d.ts
- Closes #14392
Added types for config properties appended at runtime.
- Why was this change necessary? => Some runtime config properties are not defined in the type file. 
I got the list of runtime config properties with the code below:
```js
it('t', () => {
console.log(Cypress.config())
})
```
And compared the list of options in `server/lib/config_options.ts`.
N/A
* I intentionally left some explanations for some properties as `???` because it's hard to guess or track the meaning of them.
* I intentionally grouped and left no explanation for internal or unlisted properties. 
I intentionally didn't add tests because config types are not tested in the `cli` tests.
=> fix: Added types for runtime config.

packages/driver/cypress/integration/commands/net_stubbing_spec.ts, packages/driver/src/cy/commands/waiting.js
TR-620
- Closes #14444
When there was a dot in `req.alias`, it failed. This PR fixes this problem. 
- Why was this change necessary? => adding dot for `req.alias` failed without reason. 
- Any implementation details to explain? => I only allowed the exception for `request` and `response`. 
N/A
`request` and `response` are reserved. But it is not documented in [`cy.wait`](https://docs.cypress.io/api/commands/wait.html),  [`cy.intercept`](https://docs.cypress.io/api/commands/intercept.html#Comparison-to-cy-route), [`cy.route`](https://docs.cypress.io/api/commands/route.html#Syntax) docs. 
Only documentation I could find was [0.5.10 changelog](https://docs.cypress.io/guides/references/changelog.html#0-5-10). I think it should be added to avoid …
=> fix: Alias name for `req.alias` containing a dot fail to intercept

npm/react/src/index.ts
Ensure the existing CT solutions is not broken by the new CT changes.
I tested it like this:
- in `npm/react` run `node ../../scripts/start.js --project ${PWD}` (e2e runner + CT plugin)
- in `npm/react` run `node ../../scripts/start.js --component-testing --project ${PWD}` (new CT runner)
I had to delete the export default, but this seems fine? It is marked for deprecation and this is basically a new major version (ideally CT goes out with 7.0).
=> fix(component-testing): remove default export

packages/driver/cypress/integration/commands/net_stubbing_spec.ts, packages/driver/src/cy/net-stubbing/events/response-received.ts, packages/driver/src/cy/net-stubbing/static-response-utils.ts, packages/net-stubbing/lib/external-types.ts, packages/net-stubbing/lib/internal-types.ts, packages/net-stubbing/lib/server/intercept-response.ts, packages/net-stubbing/lib/server/util.ts
- Closes #14446 (programmatic delay)
- Closes #14511 (static delay argument)
Fixed an issue where using `delayMs` with `cy.intercept` did not wait for the expected amount of time when used in a `StaticResponse`.
- continueResponseAt was an attempt to be more time-accurate, but let's KISS, this works well enough. it will never be ms-accurate anyways
=> fix: correctly wait for static delayMs w/ cy.intercept

packages/launcher/lib/browsers.ts, packages/server/__snapshots__/5_cdp_spec.ts.js, packages/server/lib/browsers/chrome.ts, packages/server/lib/browsers/cri-client.ts, packages/server/lib/errors.js, packages/server/package.json, packages/server/test/e2e/5_cdp_spec.ts, packages/server/test/support/fixtures/projects/remote-debugging-port-removed/cypress/plugins.js, packages/server/test/unit/browsers/cri-client_spec.ts, yarn.lock
Seems to be causing more issues than good so far - should probably still do this, but need to rethink the error messaging/potentially race TCP/stdio connection.
Reverts cypress-io/cypress#14348
=> fix: revert "fix: use stdio for CDP instead of TCP"

packages/driver/cypress/integration/commands/net_stubbing_spec.ts, packages/driver/src/cy/commands/querying.js, packages/driver/src/cy/commands/waiting.js, packages/driver/src/cy/net-stubbing/add-command.ts, packages/driver/src/cypress/error_messages.js, packages/net-stubbing/lib/external-types.ts
BREAKING CHANGE
- Closes 
`cy.route2` was previously aliased to `cy.intercept`. Now the alias `cy.route2` has been removed. Please update usage of `cy.route2` to `cy.intercept`.
- was renamed in 6.0.0 to make the experimentalNetworkStubbing migration easier for users
- has been warning for a major release now so time to remove
=> feat: remove deprecated cy.route2 command

npm/react/package.json, npm/react/plugins/cra-v3/file-preprocessor.js, npm/react/plugins/load-webpack/index.js, npm/react/plugins/utils/get-transpile-folders.js
- Closes #14601
Cypress folders are added to be transpiled by webpack for react/plugins/load-webpack by default
logic from `@cypress/react/plugins/cra-v3` reused
no need to customise webpack config with cypress folders
=> feat(component-testing): Make cypress's folders to be transpiled by default via webpack-preprocessors

packages/server/lib/plugins/dev-server.js
Fixes an issue if devserver not registered. 
> I tried to write a unit test for this, but project-ct is sooo complicated and it is required to mock dozens of functions to get to the state when `_initiPlugins` called.
=> chore: add comprehensive error message if dev-server is not registered

packages/server/lib/browsers/chrome.ts, packages/server/lib/browsers/cri-client.ts, packages/server/test/unit/browsers/chrome_spec.js
N/A - This fixes an issues that's only in `develop`
CDP has deprecated `Page.setDownloadBehavior` in favor of `Browser.setDownloaderBehavior`, but `Browser.setDownloadBehavior` isn't available in older versions of Chrome and will throw an error, whereas `Page.setDownloadBehavior` still works even in newer versions of Chrome.
=> fix: Revert Browser.setDownloadBehavior to Page.setDownloaderBehavior

packages/driver/cypress/integration/commands/net_stubbing_spec.ts, packages/driver/src/cy/net-stubbing/events/response-received.ts, packages/driver/src/cy/net-stubbing/static-response-utils.ts, packages/net-stubbing/lib/external-types.ts, packages/net-stubbing/lib/internal-types.ts, packages/net-stubbing/lib/server/intercept-response.ts, packages/net-stubbing/lib/server/util.ts
- Closes 
- The `delayMs` option for `StaticResponse`s used with `cy.intercept` has been renamed to `delay`.
=> feat: rename delayMs to delay, deprecate delay

cli/package.json, cli/types/cy-http.d.ts, cli/types/cypress.d.ts, npm/react/cypress/plugins/index.js, npm/react/package.json, npm/vue/cypress/plugins/index.js, npm/webpack-dev-server/src/index.ts, packages/runner-ct/cypress/plugins/index.js, yarn.lock
closes CT-252
Fixes and tightens the types of `dev-server:start`
I think it could use a bit of factoring to avoid repeating the type definitions.
This can be accomplished in a future PR.
=> fix(component-testing): start dev server event typings

cli/__snapshots__/errors_spec.js, cli/lib/errors.js, cli/lib/tasks/verify.js, cli/test/lib/tasks/verify_spec.js
- Closes #7640
Show better message when smoke test failed with cache permission error
Permission error is not catching when smoke test, so user see a weird error when install Cypress with insufficient permission.
User will see better message when install failed
=> feat: Add Cache folder error message on smoke test

npm/react/cypress/component/viewport-spec.js, npm/react/cypress/component/viewport-spec.jsx, packages/runner-ct/src/SpecList/spec-list.scss, packages/runner-ct/src/app/app.scss, packages/runner-ct/src/app/app.tsx, packages/runner-ct/src/header/header.jsx, packages/runner-ct/src/iframe/iframes.jsx, packages/runner-ct/src/iframe/iframes.scss, packages/runner-ct/src/lib/state.ts
Makes the AUT adjust to the containing window when resizing.
When common build ready open npm/react and run `yarn cy:open`
On the last spec, `viewport_spec.js` the last test forces the window to be 2000px wide.
Try resizing the window and you will see the content adapt.
When we adjust the layout, we will need to adjust the calculation of the container width and height.
closes CT-231
=> fix(component-testing): make content adjust to size of window

circle.yml
This is getting run as part of `unit-tests` anyways:
https://github.com/cypress-io/cypress/blob/2891a511a386b8e6d2bdc4a45c92156514b511f0/circle.yml#L689-L690
So let's just run it once.
=> chore(ci): only run build system unit tests once

cli/lib/cli.js, packages/runner-ct/cypress/component/RunnerCt.spec.tsx, packages/runner-ct/cypress/component/SpecList/SpecList.spec.tsx
closes CT-264
- open nom/react
- change the contents of cypress.json with 
```json
{
"viewportWidth": 400,
"viewportHeight": 400,
"video": false,
"projectId": "z9dxah",
"testFiles": "**/hello-world-spec.{js,jsx,ts,tsx}",
"env": {
"reactDevtools": true,
"cypress-react-selector": {
"root": "#cypress-root"
}
},
"ignoreTestFiles": [
"**/__snapshots__/*",
"**/__image_snapshots__/*"
],
"experimentalComponentTesting": true,
"experimentalFetchPolyfill": true
}
```
- run yarn cy:run
- the run should fail
=> fix: add exit management on run-ct cli comand

npm/vite-dev-server/.eslintrc, npm/vite-dev-server/README.md, npm/vite-dev-server/cypress.json, npm/vite-dev-server/cypress/components/large-third-party-dep-shaken.spec.ts, npm/vite-dev-server/cypress/components/large-third-party-dep.spec.ts, npm/vite-dev-server/cypress/components/smoke.spec.ts, npm/vite-dev-server/cypress/components/support.spec.ts, npm/vite-dev-server/cypress/plugins.js, npm/vite-dev-server/cypress/support/support.js, npm/vite-dev-server/index-template.html, npm/vite-dev-server/index.d.ts, npm/vite-dev-server/index.html, npm/vite-dev-server/index.js, npm/vite-dev-server/package.json, npm/vite-dev-server/src/index.ts, npm/vite-dev-server/src/makeCypressPlugin.ts, npm/vite-dev-server/src/makeHtmlPlugin.ts, npm/vite-dev-server/src/startServer.ts, npm/vite-dev-server/tsconfig.json, packages/server-ct/src/routes-ct.ts, yarn.lock
Identical to `@cypress/webpack-dev-server`
```js
// plugins.js file
import { startDevServer } from '@cypress/vite-dev-server'
module.exports = (on, config) => {
on('dev-server:start', async (options) => {
// viteConfig is optional -- we need tests for this in a playground
return startDevServer({ options }) 
})
return config
}
```
1. `yarn install`
2. `cd npm/vite-dev-server`
3. `yarn cy:open # or yarn cy:run`
**Re-running specs when the dependency graph changes**
Updating the watched specs or their dependencies does not restart the Cypress runner. Manually restarting the test _does_ trigger a re-run with the updated source in the dep graph. Need to figure out the right hooks inside of Vite to do manually do this.
**Compilation error handling**
We do not proxy up compile errors via the …
=> feat: adding vite-dev-server plugin

circle.yml
Before, darwin/linux download links for develop builds had the wrong version (check the URLs):
=> chore(ci): fix binary upload version

cli/types/cypress.d.ts
Sorry if not respecting the contribution guidelines, but this is an issue/PR as I noticed the autoEnd option isn't in the typescript definitions for Cypress, and it was referenced in the webcast on Youtube by the Cypress team: https://www.youtube.com/watch?v=V-o8WzlwKmM
Tried adding it here with a sensible comment, does it look good?
EDIT: Unlazied myself and searched the issues and see that there's #9590 and actually also already a PR for this at #14220 but it seems like this PR is inactive? So I'll keep this up?
closes #9590 (though it doesn't address the lack of documentation)
=> fix: Add autoEnd option to Cypress.Log Typescript definitions

packages/server/__snapshots__/spec_writer_spec.ts.js, packages/server/lib/modes/interactive-e2e.js, packages/server/lib/modes/run.js, packages/server/lib/util/electron-app.js, packages/server/test/integration/cypress_spec.js, packages/server/test/support/helpers/electron_stub.js, packages/server/test/unit/modes/interactive_spec.js
This change fixes an issue that caused the startup to be delayed by 500ms.
We used `app.on('ready')` without checking `app.isReady()`, however the
'ready' event may already have fired at this point and thus we never
resolved the Promise waiting for it.
Using `app.whenReady` fixes this and now that Promise resolves before
the delay expires.
Related links:
https://www.electronjs.org/docs/api/app#event-ready
https://www.electronjs.org/docs/api/app#appwhenready
- Closes 
* Improved the startup time of `cypress open` and `cypress run`.
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/c …
=> fix: use app.whenReady and remove delay race for electron startup

packages/runner-ct/cypress/component/RunnerCt.spec.tsx, packages/runner-ct/cypress/component/SpecList/SpecList.spec.tsx, packages/runner-ct/src/SpecList/SpecList.tsx, packages/runner-ct/src/SpecList/components/SearchSpec.tsx, packages/runner-ct/src/app/NoSpecSelected.scss, packages/runner-ct/src/app/NoSpecSelected.tsx, packages/runner-ct/src/app/ReporterHeader.tsx, packages/runner-ct/src/app/RunnerCt.scss, packages/runner-ct/src/app/RunnerCt.tsx, yarn.lock
Here what the user will see once component testing is open: 
This PR also includes a lot of small UI bugfixes that I found, you can review them one-by-one by following the commits:
=> feat(component-testing): Component testing  runner splash screen

npm/webpack-dev-server/src/index.ts
Hopefully this will trigger it and verify if there was indeed a bug in npm earlier, or our config is incorrect.
=> fix: add a trivial change to trigger semantic release

packages/server-ct/package.json, yarn.lock
chalk was missing from the dependencies
- run binary-build
- scaffold a component testing project
- run `yarn cypress open-ct` will fail
- add `CYPRESS_RUN_BINARY=<where-the-binary-has-built>` before the command to try the fixed binary
- it works !!!!
closes CT-277
=> fix: update dependencies of server-ct

npm/react/package.json
exclude the dist folder from rollup watch
=> build: avoid infininte rollup refresh on watch

npm/webpack-dev-server/index.js, npm/webpack-dev-server/package.json, npm/webpack-dev-server/src/errors.ts
Fixing a crasher in `@cypress/webpack-dev-server`:
1. index-template.html wasn't being published which caused a failure
2. webpack-dev-server was not listed as a peer dependency. Webpack does not include it (CRA + Vue CLI do)
3. Error stack traces didn't clearly explain that peer dependencies were missing.
Cypress stack trace is very, very long (2-3 full page scrolls) so it's important that we have good runtime error handling.
=> fix: add webpack-dev-server to peerDependencies, improve peerDependency error handling, fix index-template.html path

npm/webpack-dev-server/package.json
Missing index-template.html was failing the build.
=> fix: missing index-template.html from package.json deps for webpack-dev-server

packages/driver/cypress/fixtures/xhr-abort.html, packages/driver/cypress/integration/commands/net_stubbing_spec.ts, packages/driver/src/cy/net-stubbing/wait-for-route.ts
- Closes #9549
`cy.wait()` falsely returns timeout when user aborted XHR. This PR fixes this issue.
- Why was this change necessary? => Cypress should handle aborting XHR.
- Any implementation details to explain? => Current code only checks the first request that matches the condition. But when user aborted XHR, there are multiple requests that match it and sometimes 2nd+ item tells us that the request has been done. So, I changed the code to fix this problem. 
N/A
=> fix: cy.wait() works correctly when user aborted XHR.

packages/driver/cypress/integration/commands/net_stubbing_spec.ts, packages/driver/cypress/plugins/server.js, packages/driver/src/cy/net-stubbing/events/utils.ts
- Closes #14763
- BREAKING CHANGE: Updated cy.intercept to automatically parse more JSON MIME types, including 'application/vnd.api+json'.
- This may remove the need to `JSON.parse(req.body)` or `JSON.parse(res.body)` manually in tests.
=> fix: updated cy.intercept to automatically parse more JSON MIME types

packages/server/__snapshots__/1_busted_support_file_spec.js, packages/server/__snapshots__/1_es_modules_spec.js, packages/server/__snapshots__/1_typescript_spec_support_spec.ts.js, packages/server/__snapshots__/5_stdout_spec.js, packages/server/__snapshots__/7_record_spec.js, packages/server/lib/plugins/preprocessor.js, packages/server/test/unit/plugins/preprocessor_spec.js
- Addresses [TR-667](https://cypress-io.atlassian.net/browse/TR-667)
- Cypress now displays the stack from errors thrown in the preprocessor.
We used to remove the stack from where there was a preprocessor error. I don't remember why. It may have been that we thought the error was overly verbose when we displayed it. But removing the stack makes it very difficult to debug a preprocessor, so it's better if we keep it and err on the side of it being verbose.
Users now see the error stack when there's a preprocessor error.
**Before**
**After**
- N/A Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli …
=> fix: Remove truncation of preprocessor errors

npm/design-system/rollup.config.js, npm/design-system/tsconfig.json, yarn.lock
When adding specs to the src directory, they are incorrectly type checked. This throws warnings in the console when building.
=> chore: fixing warnings in build due to specs being untyped

packages/server/lib/util/settings.js, packages/server/test/e2e/6_visit_spec.js, packages/server/test/e2e/6_web_security_spec.js, packages/server/test/e2e/7_record_spec.js, packages/server/test/integration/cypress_spec.js, packages/server/test/specUtils.ts, packages/server/test/unit/settings_spec.js
- You may now write your config as `cypress.js` instead of `cypress.json`. `cypress.js` must confirm to the same API, for example:
```js
module.exports = {
video: false
}
```
The eventual goal is outlined [in this ticket](https://cypress-io.atlassian.net/browse/CT-305). We need to support runner specific config files; JS is more flexible than JSON for this. The first step to supporting JS as well as JSON for configuration is to load it via `require` instead of `fs.readJson`.
It is still the same.
N/A
=> feat: use require to support config via cypress.js

packages/driver/cypress/fixtures/dom.html
- Closes None
- Related to #14965
Fix the test failure caused by #14965.
- Why was this change necessary? N/A
- Any implementation details to explain? => It was happening because I placed the form outside the root `div` element.
N/A
test is not added because the goal of this PR is fixing the failing test.
=> fix: nextUntil failure caused by PR 14965

packages/driver/cypress/fixtures/dom.html, packages/driver/cypress/integration/commands/actions/clear_spec.js, packages/driver/src/cy/commands/actions/type.js
- Closes #8447
`clear()` and `type('{selectall}{del}')` behave differently when they were used against elements that contain text inputs.
- Why was this change necessary? => They didn't follow the documentation.
- What is affected by this change? => If an element is big and its center is outside the viewport, it would now return "center hidden" error, rather than "invalid element".
- Any implementation details to explain? => If the given element is not a text input, it now checks the actionability and uses the `$elToClick` just like `cy.type()`. 
N/A
=> fix: clear() and type('{selectall}{del}') behavior difference.

cli/schema/cypress.schema.json, cli/types/cypress.d.ts, packages/server/__snapshots__/3_plugins_spec.js, packages/server/__snapshots__/4_plugin_run_events_spec.ts.js, packages/server/lib/config_options.ts, packages/server/lib/errors.js, packages/server/lib/experiments.ts, packages/server/lib/plugins/child/validate_event.js, packages/server/lib/plugins/run_events.js, packages/server/test/e2e/4_plugin_run_events_spec.ts, packages/server/test/support/fixtures/projects/plugin-after-spec-deletes-video/cypress.json, packages/server/test/support/fixtures/projects/plugin-run-event-throws/cypress.json, packages/server/test/support/fixtures/projects/plugin-run-events/cypress.json, packages/server/test/unit/config_spec.js, packages/server/test/unit/plugins/child/validate_event_spec.js, packages/server/test/unit/plugins/run_events_spec.js, yarn.lock
- Addresses [TR-671](https://cypress-io.atlassian.net/browse/TR-671)
- The `experimentalRunEvents` configuration flag has been removed. It is no longer necessary to enable listening to run events in the plugins file.
=> feat: Remove experimentalRunEvents flag

packages/desktop-gui/cypress/integration/settings_spec.js, packages/reporter/cypress/integration/header_spec.ts, packages/reporter/src/header/header.scss
N/A - internal only
Fixes a few flaky percy snapshots I've noticed. The commits/comments have more details for each.
Here's an example of the flake in the desktop-gui ones: https://percy.io/cypress-io/cypress/builds/9022886/changed/511561142?browser=chrome&browser_ids=16&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=800&widths=400%2C800
=> chore: Fix some percy snapshot flakiness

packages/runner-ct/src/plugins/ReactDevtools.tsx, packages/runner-ct/src/plugins/ReactDevtoolsFallback.tsx, packages/runner-ct/src/plugins/devtools-fallback.scss
- Closes https://cypress-io.atlassian.net/browse/CT-315
Improve UI and UX around devtools in CT runner by:
- preventing crash when launching devtools without a spec selected
- add a useful message explaining why devtools may not be showing up
N/A
I added a fallback message if devtools cannot be displayed and some useful instructions on how to get them to show:
N/A
=> chore(component-testing): improve UX around devtools

packages/driver/cypress/fixtures/errors.html, packages/driver/cypress/integration/e2e/uncaught_errors_spec.js
None - or maybe just too detailed for it to be worthwhile documenting. Unless you think otherwise.
This test would not pass before https://github.com/cypress-io/cypress/pull/14826 and from the user's perspective this is the expected behavior so I think it's worth having a test for it if the issue got fixed.
It didn't
=> test: add test for async errors being caught by AUT error handlers

packages/driver/cypress/fixtures/dom.html, packages/driver/cypress/integration/commands/actions/submit_spec.js, packages/driver/src/cy/commands/actions/submit.js, packages/driver/src/cypress/error_messages.js
Reverts #14965 and #15266. 
Sorry @sainthkh, I merged the submit validation PR prematurely before we discussed it as a team. In case we decide it's not the desired behavior, we'd rather not implement it for the time being, because reverting it would be another breaking change. We're erring on the side of keeping it out of this release until we can prioritize and fully discuss how we'd like to handle this.
=> chore: Revert submit validation

packages/server/lib/video_capture.js
- Closes #3491
- Fixed an issue that could cause an `ffmpeg` error ("width not divisible by 2") during video recording in Chromium-family browsers, including Chrome, Electron, and Edge.
- apparently the h264 codec requires an even resolution: https://stackoverflow.com/a/20848224/3474615
- odd resolutions will error
- this fixes the issue by cropping the video by 1 pixel on the right or bottom, as needed, to reach an even resolution
- we already do this for Firefox
- [na] Have new …
=> fix(video): crop all odd resolutions to be even

npm/react/package.json
This is causing this warning on `yarn install`: 
```
warning nohoist config is ignored in "@cypress/react" because it is not a private package. If you think nohoist should be allowed in public packages, please submit an issue for your use case.
```
I'm assuming this is a mistake then?
=> chore: remove invalid nohoist

packages/runner-ct/src/lib/state.ts
Dev tools are not useful in run mode and they make some strange failures in CI
closes CT-326
=> fix: disable dev tools in run mode

npm/webpack-dev-server/src/index.ts, npm/webpack-dev-server/src/startServer.ts, npm/webpack-dev-server/test/e2e.spec.ts
If there is a compilation error in webpack there is no point in running any of the tests since none will pass anyway.
In `open` mode we still have the opportunity to fix the crash in hot mode.
closes CT-322
- open `npm/vue/cypress/plugins/index.js`
- modify `webpackConfig` so that it fail (for instance adding `delete webpackConfig.module`)
- run `yarn cy:run`
=> feat: webpack stop early when error in run mode

npm/react/releaserc.js
Add a release file to specify that we can release @cypress/react on the next channel on the next/npm/react branch
=> build: release react on next/npm/react with next

packages/runner-ct/cypress/component/RunnerCt.spec.tsx, packages/runner-ct/src/app/ReporterContainer.tsx, packages/runner-ct/src/app/RunnerCt.module.scss, packages/runner-ct/src/app/RunnerCt.tsx
Fixes [CT-342](https://cypress-io.atlassian.net/browse/CT-342).
There was a regression which caused the spec list placeholder to be shown when no spec was selected. This PR fixes that.
Before:
After:
=> chore: should hide reporter when theres no spec selected

circle.yml
In order to deliver vite-dev-server on master we have to test it beforehand.
This adds the tests to the ci
=> ci: run vite tests in ci

packages/runner-ct/src/app/RunnerCt.tsx, packages/runner-ct/src/lib/debounce.ts, packages/runner-ct/src/lib/state.ts
When calculating the scale for the AUT `<iframe>`, we should not subtract the width of the spec list if the spec list is closed.
=> fix(runner-ct): correctly scale runner-ct when spec list is hidden

packages/runner-ct/src/lib/state.ts
Fix scaling.
Notice the AUT does not rescale when hiding the spec list.
https://user-images.githubusercontent.com/19196536/110751677-eba00880-828f-11eb-97c1-6385a25f426b.mov
https://user-images.githubusercontent.com/19196536/110751738-ff4b6f00-828f-11eb-9b26-e585d0ece10b.mov
=> fix: default aut scale to 1

cli/schema/cypress.schema.json, cli/types/cypress.d.ts, npm/react/cypress/component/viewport-spec.jsx, npm/react/cypress/plugins/index.js, npm/vue/cypress/plugins/index.js, packages/server-ct/src/project-ct.ts, packages/server/lib/open_project.js, packages/server/lib/plugins/child/run_plugins.js, packages/server/lib/plugins/index.js, packages/server/lib/project-e2e.ts, packages/server/lib/util/settings.js, packages/server/test/integration/plugins_spec.js, packages/server/test/support/fixtures/projects/chrome-browser-preferences/cypress/plugins/index.js, packages/server/test/support/fixtures/projects/component-tests/cypress/plugins/index.js, packages/server/test/support/fixtures/projects/e2e/cypress/plugins/index.js, packages/server/test/support/fixtures/projects/firefox-memory/cypress/plugins/index.js, packages/server/test/support/fixtures/projects/plugin-before-browser-launch-deprecation/cypress/plugins/index.js, packages/server/test/support/fixtures/projects/plugin-config-version/cypress/plugins/index.js, packages/server/test/support/fixtures/projects/plugin-config/cypress/plugins/index.js, packages/server/test/support/fixtures/projects/plugin-event-deprecated/cypress/plugins/index.js, packages/server/test/support/fixtures/projects/read-only-project-root/cypress/plugins/index.js, packages/server/test/support/fixtures/projects/retries-2/cypress/plugins/index.js, packages/server/test/unit/settings_spec.js
- Closes https://cypress-io.atlassian.net/browse/CT-305?focusedCommentId=13398
Note: This behavior and API was discussed over the course of two meetings and validated with Brian, Zach, and Jess. 
```bash
// cypress.json
{
// defaults
video: true,
// added this e2e key
e2e: {
video: false // override!
},
// added component
component: { 
viewportWidth: 500 // video is true - inherited.
}
}
```
Note the third argument is `mode`. This is `component` or `e2e`. The user can have conditional plugins using this flag.
```js
module.exports = (on, config, mode) => {
if (mode === 'component') {
// start webpack-dev-server, etc.
}
if (mode === 'e2e') {
// e2e things
}
// You still need to return a config file.
// e2e or CT specific config can be done in `cypress.json` using `e2e` or `component` keys. …
```
=> feat: support ct/e2e specific overrides in cypress.json

packages/driver/cypress/integration/commands/actions/click_spec.js, packages/driver/src/cy/actionability.js
- Closes #3200
- Interacting with an element that requires scrolling within an element with `scroll-behavior: smooth` no longer fails Cypress's actionability check
The solution involves setting all `scroll-behavior` to `inherit` before scrolling and then resetting it after scrolling by injecting a style tag and then removing it.
Commands that require actionability (e.g. click) no longer fail to find the element when it's within another element with `scroll-behavior: smooth`.
- N/A Have new configuration options been …
=> fix: Fix actionability when element has scroll-behavior: smooth

cli/schema/cypress.schema.json, cli/types/cypress.d.ts, npm/react/cypress/plugins/index.js, npm/vue/cypress/plugins/index.js, packages/server-ct/src/project-ct.ts, packages/server/lib/config.js, packages/server/lib/open_project.js, packages/server/lib/plugins/child/run_plugins.js, packages/server/lib/plugins/index.js, packages/server/lib/project-e2e.ts, packages/server/lib/util/settings.js, packages/server/test/e2e/6_visit_spec.js, packages/server/test/e2e/6_web_security_spec.js, packages/server/test/e2e/7_record_spec.js, packages/server/test/integration/cypress_spec.js, packages/server/test/integration/plugins_spec.js, packages/server/test/specUtils.ts, packages/server/test/support/fixtures/projects/chrome-browser-preferences/cypress/plugins/index.js, packages/server/test/support/fixtures/projects/component-tests/cypress/plugins/index.js, packages/server/test/support/fixtures/projects/e2e/cypress/plugins/index.js, packages/server/test/support/fixtures/projects/firefox-memory/cypress/plugins/index.js, packages/server/test/support/fixtures/projects/plugin-before-browser-launch-deprecation/cypress/plugins/index.js, packages/server/test/support/fixtures/projects/plugin-config-version/cypress/plugins/index.js, packages/server/test/support/fixtures/projects/plugin-config/cypress/plugins/index.js, packages/server/test/support/fixtures/projects/plugin-event-deprecated/cypress/plugins/index.js, packages/server/test/support/fixtures/projects/read-only-project-root/cypress/plugins/index.js, packages/server/test/support/fixtures/projects/retries-2/cypress/plugins/index.js, packages/server/test/unit/config_spec.js, packages/server/test/unit/settings_spec.js
- Closes #15497
- Cypress no longer write extra config values to `cypress.json` when adding the project ID
This was caused by a combination of using `require` to obtain the contents of `cypress.json` and mutating the config object itself. Since node caches required modules, it mutated the in-memory cache of the `cypress.json`, so subsequent 'reads' had the mutated content with extra values, which then got written back to the file when writing the project ID.
This reverts PRs #15444 and #15263.
- N/A Have new …
=> fix: Revert cypress.json changes

npm/create-cypress-tests/package.json, package.json, yarn.lock
Added `shx` to fix building inside of `powershell` or `cmd`, which do not have `chmod`.
=> chore: fix create-cypress-tests building on windows

npm/create-cypress-tests/package.json, npm/react/README.md
As mentioned in #15450 we need to deliver the wizard again and probably update the Readme.md for `@cypress/react`.
=> fix: add missing script for building wizard

packages/driver/cypress/integration/commands/net_stubbing_spec.ts
- Closes #14522 
- Closes #14205
- Fixed an issue where only the first matching alias for a route would yield a response object on `cy.wait`.
- this was actually fixed in #15255 - which is going into 7.x
- sainthkh opened a PR to fix this for 6.x but closed since 7.x is around the corner
=> fix: add test for cy.intercept having response for multiple aliases

cli/types/cypress.d.ts, cli/types/tests/kitchen-sink.ts
- Closes #14842
`set-cookie` can be `string[]`. So, the `headers` type has been changed.
- Why was this change necessary? => Cypress type doesn't reflect the real code.
N/A
=> fix: Response.headers type.

packages/server/lib/gui/windows.ts, packages/server/lib/ipc/ipc.js
- Closes 
- This became the default with Electron 12, we should follow the defaults as closely as possible.
- Users can override using `before:browser:launch` API
- internal change: contextBridge.exposeInMainWorld must now be used to expose preload APIs, but this only affects the `ipc` object used by `desktop-gui`, so it should not affect users: https://www.electronjs.org/docs/tutorial/context-isolation …
=> fix: enable contextIsolation by default in Electron

scripts/get-next-version.js
By popular demand!
If defined, `NEXT_VERSION` acts the same as the old `NEXT_DEV_VERSION` environment variable. Otherwise, semantic commits are used.
Generally, if you want to build a higher version number, you can just add a commit with the correct semantic commit message. But there's no way to build a lower version number without using `NEXT_VERSION`.
=> chore: allow nextVersion to be overridden by NEXT_VERSION

npm/design-system/src/components/FileExplorer/FileExplorer.tsx, npm/design-system/src/components/Nav/LeftNav.tsx, npm/design-system/src/components/SpecList/SpecList.module.scss, packages/runner-ct/src/app/KeyboardHelper.scss, packages/runner-ct/src/app/RunnerCt.module.scss, packages/runner-ct/src/app/RunnerCt.scss, packages/runner-ct/src/app/RunnerCt.tsx, packages/runner-ct/src/variables.scss
This addresses the style changes when merging #15513
=> fix: addressing style regressions in the CT runner

npm/webpack-dev-server/src/aut-runner.ts
Something about changing `before` to `Cypress.on('test:before:run')` breaks one specific test, this one: https://app.circleci.com/pipelines/github/cypress-io/cypress/18194/workflows/92cfba01-a7cb-400e-9eca-f0b1afc0e113/jobs/657723/tests#failed-test-0
=> refactor: simplify vue mount

cli/types/cypress.d.ts, cli/types/tests/chainer-examples.ts
- Closes #15353
Add the type definition for `cy.writeFile` with 4 arguments. 
- Why was this change necessary? => 4 argument definition is valid, but it doesn't exist. 
N/A
=> fix: add the type definition for cy.writeFile with 4 arguments.

packages/driver/cypress/integration/commands/actions/click_spec.js, packages/driver/src/cy/actionability.js, packages/driver/src/cy/commands/actions/click.js, packages/driver/src/cypress/error_messages.js
- Closes #3738
- `cy.click()` will no longer fail with "coordsHistory must be at least 2 sets of coords" when specifying `{ multiple: true }`
There was a bug where using `cy.click({ multiple: true })` would time out because all clicks needed to be finished in the time we normally give one click (4000ms by default). If the system was slow, the timeout was lowered, and/or there were a lot of elements to click, this became more likely.
Now, each click when using `{ multiple: true }` gets a full timeout (4000ms).
Also, the error message "coordsHistory must be at least 2 sets of coords" was confusing and not useful to users. It appeared because it happened to be the error we use to trigger an initial retry in order to test that the element is not animating between ticks. I improved the error, …
=> fix: Fix "coordsHistory must be at least 2 sets of coords" error

packages/runner-ct/cypress/component/ResizeReporter.spec.tsx, packages/runner-ct/cypress/component/ResizeSpecList.spec.tsx, packages/runner-ct/cypress/component/RunnerCt.spec.tsx, packages/runner-ct/cypress/component/utils.ts, packages/runner-ct/cypress/fixtures/testSpecFile.ts, packages/runner-ct/src/app/RunnerCt.tsx, packages/runner-ct/src/app/SpecContent.tsx, packages/runner-ct/src/iframe/iframes.scss
- Closes https://cypress-io.atlassian.net/browse/CT-390
N/A - this product is not user facing yet.
In [this refactor](https://github.com/cypress-io/cypress/pull/15617) the AUT scaling was broken. I am not 100% clear on exactly why but [this does not work](https://github.com/cypress-io/cypress/pull/15617/files#diff-8503e32c6d767fd2ddb45768cb4514dad1a1c40940db86dfbf9fe5a71ea2d4f9R50) as you'd expect. When doing
```tsx
<SplitPane
onChange={debounce(props.state.updatePluginsHeight)}
/>
```
The `props.state.updatePluginsHeight` function will always receive the same width. I guess it is capturing the initial argument in the closure?
I fixed it by doing this:
```tsx
function onChange (width: number) {
props.state.updatePluginsHeight(width)
}
<SplitPane
onChange={debounce(onChange)}
/>
```
The …
=> fix(runner-ct): scale AUT correctly

npm/design-system/src/index.scss
The normalize and fontawesome css files were never succesfully imported.
Nobody complained, and the errors in the command prompts are triggering. 
If we want to load normalize in the future, I suggest to do it in a separate PR.
- Closes CT-381
Errors `Refused to apply style` are gone from the console in open-ct
The two file had `@import` statements that were left as is during compilation. At runtime, the server tried to reach those files but given the context could not find it.
If these files need to be in the stack it would be nice to inline them.
For now, there is no regression and the error is gone.
=> fix: remove failing imports

packages/driver/cypress/integration/commands/net_stubbing_spec.ts, packages/driver/src/cy/net-stubbing/add-command.ts, packages/driver/src/cy/net-stubbing/events/response.ts, packages/driver/src/cy/net-stubbing/static-response-utils.ts, packages/net-stubbing/lib/external-types.ts, packages/net-stubbing/lib/internal-types.ts, packages/net-stubbing/lib/server/middleware/response.ts, packages/net-stubbing/lib/server/util.ts
- Closes 
- BREAKING CHANGE: The `res.throttle` and `res.delay` functions on responses yielded to `cy.intercept()` response handlers have been renamed to `res.setThrottle` and `res.setDelay`.
- `delayMs` is renamed to `delay`, `delayMs` is backwards-compatible (original PR: #14822) 
- this was reverted, but the reversion was never released, so no new changelog item
=> feat: rename delayMs, res.throttle, res.delay

packages/server/lib/server-e2e.ts, packages/server/test/integration/server_spec.js
- Closes #15738
Allow cy.visit() to work with pages that return application/xhtml* content-type
See the description on the ticket
Before:
After:
=> feat: Support application/xhtml content type of cy.visit()

packages/driver/cypress/fixtures/sticky.html, packages/driver/cypress/integration/dom/visibility_spec.ts, packages/driver/src/dom/visibility.js
- Closes #14938
It checks the visibility correctly when an element has "position: sticky".
- Why was this change necessary? => visibility function doesn't handle "position: sticky" properly.
N/A
=> fix: position: sticky visibility.

packages/electron/lib/electron.js, packages/server/test/e2e/7_record_spec.js
Internal-only - CLI already catches this correctly.
=> chore: exit with non-zero exit code on signal exit
